### ISSUE TITLE
apex安装问题

### ISSUE THREAD

**Issue by perces** [Megvii-BaseDetection/YOLOX#100]
我的cuda=11.1 cudnn=8.2 pytho=3.7 pytorch=1.9 torch.version.cuda=11.1
![image](https://user-images.githubusercontent.com/67944897/126741076-6756aa33-92b0-47db-8eeb-6c1f937680c3.png)
![image](https://user-images.githubusercontent.com/67944897/126741098-6b6d1e67-2e76-4785-8005-b0a5f483a212.png)
![image](https://user-images.githubusercontent.com/67944897/126741113-791e28c3-f23a-44df-9c58-ad3d5e0d7874.png)

**Comment by zcswdt** [comment]
> 我的cuda=11.1 cudnn=8.2 pytho=3.7 pytorch=1.9 torch.version.cuda=11.1
> ![image](https://user-images.githubusercontent.com/67944897/126741076-6756aa33-92b0-47db-8eeb-6c1f937680c3.png)
> ![image](https://user-images.githubusercontent.com/67944897/126741098-6b6d1e67-2e76-4785-8005-b0a5f483a212.png)
> ![image](https://user-images.githubusercontent.com/67944897/126741113-791e28c3-f23a-44df-9c58-ad3d5e0d7874.png)

我也出现了和你一样的问题，请问解决了吗？

**Comment by perces** [comment]
> > 我的cuda=11.1 cudnn=8.2 pytho=3.7 pytorch=1.9 torch.version.cuda=11.1
> > ![image](https://user-images.githubusercontent.com/67944897/126741076-6756aa33-92b0-47db-8eeb-6c1f937680c3.png)
> > ![image](https://user-images.githubusercontent.com/67944897/126741098-6b6d1e67-2e76-4785-8005-b0a5f483a212.png)
> > ![image](https://user-images.githubusercontent.com/67944897/126741113-791e28c3-f23a-44df-9c58-ad3d5e0d7874.png)
> 
> 我也出现了和你一样的问题，请问解决了吗？

没有，直接使用是可以的，但是训练会报错

**Comment by XinPeiHou** [comment]
cd apex
不执行README的步骤，直接执行python setup.py install我的成功了

**Comment by yumendecc** [comment]
看看是不是这个原因
https://blog.csdn.net/weixin_44966641/article/details/118767856

**Comment by 1757525671** [comment]
> 看看是不是这个原因
> https://blog.csdn.net/weixin_44966641/article/details/118767856

解决了，感谢
