### ISSUE TITLE
How to train model with one class (COCO data)

### ISSUE THREAD

**Issue by Michelvl92** [Megvii-BaseDetection/YOLOX#1000]
Thank you for your contributions. I use yolox to train my own data in coco format, but I want to change the multi-category to single-category training. I want to ask how to train a single-category model without changing the multi-category)( label data?

**Comment by ily666666** [comment]
你训练集只有其中一个类别就行了吧

**Comment by FateScript** [comment]
change [annotation path](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/exp/yolox_base.py#L36-L37)  and [num_classes](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/exp/yolox_base.py#L20).
