### ISSUE TITLE
30类别VOC数据集训练报错

### ISSUE THREAD

**Issue by theDeep1nteresting** [Megvii-BaseDetection/YOLOX#1004]
hi，我在使用YOLOX训练自己数据集的时候，出现如下错误：
  File "E:\Python\Pytorch\GitHub\YOLOX-main\yolox\data\datasets\voc.py", line 71, in __call__
    label_idx = self.class_to_ind[name]
                       │    │                 └ '101'
                       │    └ {'稻纵卷叶螟': 0, '稻瘿蚊': 1, '稻飞虱': 2, '稻象虫': 3, '稻叶蝉': 4, '蛴螬虫': 5, '蝼蛄': 6, '金针虫': 7, '黄地老虎': 8, ...
                       └ <yolox.data.datasets.voc.AnnotationTransform object at 0x000001C7F4CC6160>

KeyError: '101'

1、我首先用15类进行训练，可以运行
2、稍后我用30类进行训练，就出现了上述的错误
3、将其中29类删除，也能运行
ps：无论标签是中文还是英文，都会出现这个错误
感觉像是超过20类就会报错一样，想请教一下，问题出在哪里？

**Comment by theDeep1nteresting** [comment]
已解决

**Comment by 0nethought** [comment]
请问怎么解决的

**Comment by improgress** [comment]
> 已解决

how to resovle it？  im confused...

**Comment by anqilin9** [comment]
咋解决的 大佬
