### ISSUE TITLE
Road signs detection

### ISSUE THREAD

**Issue by DanielDoe** [Megvii-BaseDetection/YOLOX#1007]
The code runs very well on detecting vehicles and persons but does not detect traffic signs. Please what should I do? Do I need to add a class somewhere? if I do what is it? Really appreciate your efforts!

**Comment by FateScript** [comment]
Sounds like a bug. I'm not sure what you writed.
Maybe you could try visualize you data during training or consider wheather your road signs are too small to detect.
Sorry that we could not offer more help for self defined dataset.
