### ISSUE TITLE
How to choose a gpu?

### ISSUE THREAD

**Issue by Petilia** [Megvii-BaseDetection/YOLOX#1009]
I have 3 gpu's available, but I only want to train the model on one. 

I can't find the argument I need to set for this.

I am interested in the gpu highlighted in red.

How do I do that?

![image](https://user-images.githubusercontent.com/94632457/146761864-bde7bdf9-105b-4db3-88be-74d5b2acda94.png)

**Comment by FateScript** [comment]
export CUDA_VISIBLE_DEVICES in your cli might help you.
