### ISSUE TITLE
How to control the number of processes?

### ISSUE THREAD

**Issue by cyh767** [Megvii-BaseDetection/YOLOX#1011]
Hi,

I am training YOLOX with `-d 4 -b 64` . I find it seems to spawn a lot of processes (16+). How can I control the number of process per device? Is there anything else I need to set besides `self.data_num_workers` in yolox/exp/yolox_base.py (which I already set to 2, but the number of process per device seem still larger than 2)?

Thanks for your help.

**Comment by FateScript** [comment]
Reduce `data_num_worker` could help you to reduce number of spawned process. 
NOTE that you are useing 4 devices, so number of your process should multiply 4.

**Comment by cyh767** [comment]
Thanks I'll have a look

**Comment by cyh767** [comment]
Setting `self.data_num_workers` works well. Thanks.
