### ISSUE TITLE
How can I get a model with weights to use in my project? 

### ISSUE THREAD

**Issue by ll2pakll** [Megvii-BaseDetection/YOLOX#1013]
How can I get a model with weights to use in my project? For example:

    import torchvision.models as models
    yolox = models.yolox(pretrained=True)

And how can I change the output layer? For example:

    yolox.lastlayer = nn.Conv2d(512, num_classes, kernel_size=(1,1), stride=(1,1))

**Comment by FateScript** [comment]
One possible way:
1. import your exp (e.g. : yolox-tiny exp)
2. call `exp.get_models()`

We will provide interface later.

**Comment by FateScript** [comment]
In the latest version, you could get model by the following code:
```python3
from yolox.exp import get_exp
model = get_exp(exp_name="yolox-tiny").get_model()
```

**Comment by FateScript** [comment]
I will close this issue. Feel free to reopen if you have any further question.
