### ISSUE TITLE
cannot reproduce results on coco

### ISSUE THREAD

**Issue by jeffreyking23** [Megvii-BaseDetection/YOLOX#1016]
I have trained yolox-s on coco2017dataset，cannot reproduce the results，ap always 0，How to reproduce the results？

**Comment by FateScript** [comment]
Did you modify any code? Or are you using image cache?

**Comment by jeffreyking23** [comment]
I pull the latest code from github and use  CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/train.py -n yolox-s -d 8 -b 64 --fp16 -o --cache to train the model

**Comment by FateScript** [comment]
Please check your cache carefully. You could remove it and regenerate to train your model.

**Comment by jeffreyking23** [comment]
thank you，really is the cache problem. The training process is correct now.
