### ISSUE TITLE
Accuracy results

### ISSUE THREAD

**Issue by kolesnevg** [Megvii-BaseDetection/YOLOX#1017]
Hi, I'm trying to use YOLOX and I got one problem - I do not see Accuracy results at all
About dataset - I converted my custom dataset to COCO format and use it

Then I trained model
`python tools/train.py -n yolox-tiny -d 1 -b 48 -o`

After I run eval by command
`python tools/eval.py -n  yolox-tiny -c /content/YOLOX/latest_ckpt.pth -b 64 -d 1 --conf 0.001`

and got results

> 2021-12-22 13:42:53 | INFO     | yolox.data.datasets.coco:45 - loading annotations into memory...
> 2021-12-22 13:42:53 | INFO     | yolox.data.datasets.coco:45 - Done (t=0.00s)
> 2021-12-22 13:42:53 | INFO     | pycocotools.coco:88 - creating index...
> 2021-12-22 13:42:53 | INFO     | pycocotools.coco:88 - index created!
> 2021-12-22 13:42:57 | INFO     | __main__:156 - loading checkpoint from /content/YOLOX/latest_ckpt.pth
> 2021-12-22 13:42:57 | INFO     | __main__:160 - loaded checkpoint done.
> 100%|##########| 12/12 [00:10<00:00,  1.12it/s]
> 2021-12-22 13:43:08 | INFO     | yolox.evaluators.coco_evaluator:171 - Evaluate in main process...
> 2021-12-22 13:43:08 | INFO     | __main__:187 - 
> Average forward time: 1.03 ms, Average NMS time: 0.17 ms, Average inference time: 1.20 ms

There is no accuracy :(

**Comment by FateScript** [comment]
The log show that your model detected nothing.

**Comment by kolesnevg** [comment]
Thank you, the problem was in my dataset annotations
