### ISSUE TITLE
how to solve the problem that git clone git@github.com:Megvii-BaseDetection/YOLOX.git?

### ISSUE THREAD

**Issue by zhuyiliulian** [Megvii-BaseDetection/YOLOX#102]
Cloning into 'YOLOX'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by yonomitt** [comment]
use this command instead:

```
git clone https://github.com/Megvii-BaseDetection/YOLOX.git
```
