### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox'

### ISSUE THREAD

**Issue by zcswdt** [Megvii-BaseDetection/YOLOX#1022]
您好，我在执行训练的代码时，无法找到yolox这个，我检查了一下，目录有这个文件夹啊。
![image](https://user-images.githubusercontent.com/43515926/147320789-86e2ec1c-e1b3-4637-876e-7032c5306373.png)

**Comment by FateScript** [comment]
Please  following README and install yolox
