### ISSUE TITLE
自定义模块中使用AdaptiveAvgPool2d((1, None))提示TypeError

### ISSUE THREAD

**Issue by CodingOfZero** [Megvii-BaseDetection/YOLOX#1027]
![7QF6BVC_0XE(()Y8J6O7Q6P](https://user-images.githubusercontent.com/26578444/147386153-9d91f714-7c98-48d8-982c-cd7d5ed0b68a.png)

**Comment by FateScript** [comment]
Your log shows your `output_size` is (None, 1) , which causes the exception.

**Comment by CodingOfZero** [comment]
在自定义模块中使用了nn.AdaptiveAvgPool2d((None, 1))，导致在basic_hook.py文件中发生错误。当我把logger.info注释掉时，貌似可以工作了
![image](https://user-images.githubusercontent.com/26578444/147433710-03a40cdf-d5ce-4a1b-adea-ed0c6c020970.png)

**Comment by CodingOfZero** [comment]
> Your log shows your `output_size` is (None, 1) , which causes the exception.

在模块中使用了nn.AdaptiveAvgPool2d((None, 1))，导致在basic_hook.py文件中发生错误。我暂时把logger.info注释掉了，不去计算模型的信息了😅
![image](https://user-images.githubusercontent.com/26578444/147477526-607b84ca-7295-49bf-9d4d-f47a0746b3b2.png)
