### ISSUE TITLE
运行eval.py时 用trt多batch推理时会报错 TensorRT model is not support model fusing and distributed inferencing！

### ISSUE THREAD

**Issue by frandoLin** [Megvii-BaseDetection/YOLOX#1031]
trt模型是用官方代码转化的，bs为1时 可以正常推理，但是大于1时，会报错。跟了下代码，发现程序中做了限制，请问是不是这意味着yolox-s不支持trt的多batch推理？谢谢！
![image](https://user-images.githubusercontent.com/41569547/147525977-f1a8db5d-1839-4444-af8e-6edbc9cc1f5d.png)

**Comment by FateScript** [comment]
Yep.

**Comment by frandoLin** [comment]
> Yep.

所以有其他方式使用多batch的trt吗？比如先转成onnx再转trt？

**Comment by frandoLin** [comment]
> Yep.

以及能否帮忙拉入官方交流群，申请了好几天一直没有通过

**Comment by FateScript** [comment]
建议你检查一下是不是扫了一群的码，很多人都加的是一群，issue里面说了请加二群....

**Comment by frandoLin** [comment]
> 建议你检查一下是不是扫了一群的码，很多人都加的是一群，issue里面说了请加二群....

我一直扫的是二群的码 现在加上了
