### ISSUE TITLE
4G显存跑1batch都out of memry

### ISSUE THREAD

**Issue by sq2012** [Megvii-BaseDetection/YOLOX#1039]
4G显存跑1batch都out of memry，显卡是GTX1650，换了3090，发现显存占用12G，想问下，yolox这么吃显存吗？以往yolo也就4G显存随便都能跑，是我操作问题还是yolox真的就吃显存，-o --fp16已经关掉了,用的是yolox_x

**Comment by sq2012** [comment]
-O --FP16关掉了，

**Comment by FateScript** [comment]
What if you use some some small model like nano, tiny or small ?  YOLOX-X is a large model and you need more GPU mem to  train such a model.

**Comment by sq2012** [comment]
谢谢
