### ISSUE TITLE
加群

### ISSUE THREAD

**Issue by qixitan** [Megvii-BaseDetection/YOLOX#1040]
二群是没人管理了吗？
一直申请加不进去

**Comment by FateScript** [comment]
请确认是不是扫的2群的码，我们在后台收到的很多都是一群的加群请求...基本上没看到几个申请2群的

**Comment by qixitan** [comment]
你好 感谢您的回复 早上已经通过了二群的申请 感谢🙏



发自我的iPad洋斯“＂


------------------ 原始邮件 ------------------
发件人: Feng Wang ***@***.***&gt;
发送时间: 2021年12月30日 11:13
收件人: Megvii-BaseDetection/YOLOX ***@***.***&gt;
抄送: qixitan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Megvii-BaseDetection/YOLOX] 加群 (Issue #1040)





 
请确认是不是扫的2群的码，我们在后台收到的很多都是一群的加群请求...基本上没看到几个申请2群的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
