### ISSUE TITLE
Predictions for evaluation in pycocotools format

### ISSUE THREAD

**Issue by Michelvl92** [Megvii-BaseDetection/YOLOX#1044]
Hi 

I have a modified evaluation based on [pycocotools](https://github.com/cocodataset/cocoapi). Just as pycocotools it it expects the predictions on a dataset as follows: 
```
[{'image_id': 793, 'category_id': 1, 'bbox': [0.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582}, 
{'image_id': 793, 'category_id': 1, 'bbox': [590.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582},
......
{'image_id': 795, 'category_id': 1, 'bbox': [1180.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582}]
```

Is there a possibility to the predictions in such a format (this is usually built in many frameworks), or how can I implement this easily en quickly by myself?

**Comment by FateScript** [comment]
I'm not  clear about your issue.  Are you talking about writing a new `Evaluator`?
If so, you might override [this function](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/exp/yolox_base.py#L269-L281) in your Exp class.
