### ISSUE TITLE
静态量化模型时报错

### ISSUE THREAD

**Issue by TD-wzw** [Megvii-BaseDetection/YOLOX#1045]
静态量化在torch.quantization.fuse_modules()这个函数报错
选择融合['conv','bn']

报错：torch.nn.modules.module.ModuleAttributeError: 'YOLOX' object has no attribute 'conv'

请问报这个YOLOX找不到conv是什么原因，是因为python setup.py develop的原因吗？

**Comment by FateScript** [comment]
`setup.py` only helps to install yolox.  YOLOX module doesn't have a module named 'conv' and 'bn', that's the true reason.
You might read docstring `fuse_modules` carefully and use string like ['focus.conv', 'focus.bn'] or something like this.

**Comment by TD-wzw** [comment]
> `setup.py` only helps to install yolox. YOLOX module doesn't have a module named 'conv' and 'bn', that's the true reason. You might read docstring `fuse_modules` carefully and use string like 'focus.conv', 'focus.bn' or something like this.

谢谢，解决了~
