### ISSUE TITLE
运行demo出错

### ISSUE THREAD

**Issue by Xiang99** [Megvii-BaseDetection/YOLOX#105]
ssh://xyx/home/td/anaconda3/envs/open-mmlab/bin/python -u /home/xyx/code/YOLOX-main/tools/demo.py image -n yolox-s -c weight/yolox_s.pth.tar --path assets/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result
Traceback (most recent call last):
  File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "/home/td/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yolox_s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyx/code/YOLOX-main/tools/demo.py", line 275, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 48, in get_exp
    return get_exp_by_file(exp_file)
  File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: exps/default/yolox_s.py doesn't contains class named 'Exp'

Process finished with exit code 1

**Comment by fanfan-hanyang** [comment]
Hello, there are still errors in changing yolox_s.pth.tar to my own path, YOLOX Demo!: error: unrecognized arguments: yolox_s.pth
how to solve it?
![000](https://user-images.githubusercontent.com/73423540/126751332-e9f7a92a-9d92-4207-90ce-0dba4affdf9b.png)

**Comment by Joker316701882** [comment]
@fanfan-hanyang you need **-c** to speicify your model path.

**Comment by chenxu93** [comment]
![image](https://user-images.githubusercontent.com/42310082/126786897-d0f95351-3df2-4c74-a507-ab0848b38169.png)
 same  bug

**Comment by chenxu93** [comment]
@Xiang99 I have  the same bug, do you resolve it ?

**Comment by Xiang99** [comment]
> @Xiang99 I have the same bug, do you resolve it ?
参考下这个(https://github.com/Megvii-BaseDetection/YOLOX/commit/8180c60664a0388af2e72577f8d67451c65309dd)

**Comment by fanfan-hanyang** [comment]
> @fanfan-hanyang you need **-c** to speicify your model path.

ok！I have solved it,thank you very much

**Comment by Joker316701882** [comment]
@Xiang99 Have you solved this problem?

> ssh://xyx/home/td/anaconda3/envs/open-mmlab/bin/python -u /home/xyx/code/YOLOX-main/tools/demo.py image -n yolox-s -c weight/yolox_s.pth.tar --path assets/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result
> Traceback (most recent call last):
> File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 13, in get_exp_by_file
> current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
> File "/home/td/anaconda3/envs/open-mmlab/lib/python3.7/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 965, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'yolox_s'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/xyx/code/YOLOX-main/tools/demo.py", line 275, in
> exp = get_exp(args.exp_file, args.name)
> File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 48, in get_exp
> return get_exp_by_file(exp_file)
> File "/home/xyx/code/YOLOX-main/yolox/exp/build.py", line 16, in get_exp_by_file
> raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
> ImportError: exps/default/yolox_s.py doesn't contains class named 'Exp'
> 
> Process finished with exit code 1

**Comment by FateScript** [comment]
Long time no update for this issue, close.

**Comment by pistachio0812** [comment]
> @fanfan-hanyang you need **-c** to speicify your model path.

can you make it clear?
