### ISSUE TITLE
Inference result differs from training

### ISSUE THREAD

**Issue by LLsmile** [Megvii-BaseDetection/YOLOX#1054]
I trained a yolos model in my datasets with given code and tested it with tools/demo.py. AP in training is 60% but nothing was detected when I run tools/demo.py. I don't know what's wrong.

**Comment by LLsmile** [comment]
test images come from the trainsets.

**Comment by FateScript** [comment]
Did your specify your weights? What's your command?

**Comment by LLsmile** [comment]
`python tools/demo.py image -f exps/default/yolox_s.py -c ./YOLOX_outputs/yolox_s/best_ckpt.pth.tar  --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu --path ./datasets/COCO/train2017`
The test command should be OK. The default yolo_s model provided in this repo achieves good results. But my model behaves strangely.

**Comment by FateScript** [comment]
Did `inference result differs from training` solved?  Did your best_ckpt get the same result with your training result?

**Comment by LLsmile** [comment]
Not yet. Besides, nothing changes, no matter I use the best_ckpt as pretrained model or not.
