### ISSUE TITLE
when i try to run tensorrt demo with yolox-tiny, i got a wrong result

### ISSUE THREAD

**Issue by ngsford** [Megvii-BaseDetection/YOLOX#107]
`./yolox ../model_trt.engine -i ../../../../assets/dog.jpg
blob image
3ms
num of boxes before nms: 67359`

**Comment by ruinmessi** [comment]
what's your converting command? 
Also notice that yolox-nano and yolox-tiny have a default size of 416, thus you may have to change the input size in the yolox.cpp

**Comment by ngsford** [comment]
@ruinmessi emm,i forgot to change the input size.
