### ISSUE TITLE
保存训练图像，会有概率出现多图重叠现象？

### ISSUE THREAD

**Issue by NarutoZhao** [Megvii-BaseDetection/YOLOX#1078]
在yolox/data/dataset/voc.py 的VOCSetection中的 pull_item 中，添加了保存图像的代码。
有一定概率会出现几个图像拼接，重叠现象

In yolox/data/the dataset/voc. Py VOCDetectionIn yolox/data/the dataset/voc. Py VOCDetection class of pull_item function, add the save image code.
There is a certain probability of several image splicing, overlapping phenomenon

**Comment by NarutoZhao** [comment]
import copy
img_draw = copy.deepcopy(img)
img_name = time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime()) + '.jpg'
path_ = 'datasets/mask_rect'
os.makedirs(path_, exist_ok=True)
for bob in target_o:
    cv2.rectangle(img_draw, (int(bob[0]), int(bob[1])), (int(bob[2]), int(bob[3])), (0, 0, 255), 1)
cv2.imwrite(os.path.join(path_, '%s' % img_name), img_draw)

**Comment by NarutoZhao** [comment]
![image](https://user-images.githubusercontent.com/32025355/149764862-b0845266-a168-4e5b-bd99-ec42eaa2462c.png)

**Comment by NarutoZhao** [comment]
![image](https://user-images.githubusercontent.com/32025355/149764910-85743ff5-91b5-4a02-b827-73805a4ed930.png)

**Comment by NarutoZhao** [comment]
@FateScript 
是因为，多线程时的问题吗？以及 数据增强？

**Comment by Joker316701882** [comment]
@NarutoZhao This is caused by using mosaic data augmentation.
