### ISSUE TITLE
coordinates calculate error [important]

### ISSUE THREAD

**Issue by ujsyehao** [Megvii-BaseDetection/YOLOX#1087]
Hello, we all know COCO box format is unnormalized (xmin, ymin, width, height), 
As we all know, for unnormalized coord, width = xmax - xmin + 1, ex: x1=3, x2=10 -> width = x2 - x1 + 1 = 8

but in coco.py, line 145 code below:
`            
x2 = np.min((width, x1 + np.max((0, obj["bbox"][2]))))
y2 = np.min((height, y1 + np.max((0, obj["bbox"][3]))))
`
the code is x2 = x1 + width, it is uncorrect, is should be x2  = x1 + width - 1.

Thank you in advance!

**Comment by ujsyehao** [comment]
Any response?

**Comment by FateScript** [comment]
Thanks @ujsyehao . It's how you interpert annotations of COCO and it doesn't really affect performance.
For example, detectron2 treat box anno the same way as we did, reference  [code](https://github.com/facebookresearch/detectron2/blob/main/detectron2/structures/boxes.py#L77-L98).

**Comment by ujsyehao** [comment]
hh, thank you for your reply,
1. interpert annotations of COCO -> x, y: the upper-left coordinates of the bounding box
width, height: the dimensions of your bounding box
2. it may  not affect performance
