### ISSUE TITLE
训练过程问题请教

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#1088]
![image](https://user-images.githubusercontent.com/78945582/150445327-1f38734a-4ebb-415d-98a9-553bccbe3a42.png)
为什么会出现-1这样的值？什么原因？

**Comment by scsolaris** [comment]
这是pycocotools的设定，如果某种指标(如small)没有检测出任何结果，输出值就是-1，详见[cocoeval.py](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L453)代码
