### ISSUE TITLE
yolox-x精度无法复现

### ISSUE THREAD

**Issue by Deng-yongbiao** [Megvii-BaseDetection/YOLOX#1091]
你好，我参考github上面的教程进行yolox-x的训练过程，启动命令为```python -m yolox.tools.train -n yolox-x -d 8 -b 64 --fp16 -o```但是最终得出最高的精度为50.28，比readme中的最高精度差了0.8，请问这种现象是正常的吗？还是说我有什么训练中的细节没有注意到。我的服务器是8张3090的显卡。希望得到您的回答，谢谢！

**Comment by GOATmessi7** [comment]
你可以测试一下test-dev上的精度。因为license的问题我们去掉了yolov5针对val集合精调的hsv aug的参数，所以在val上的performance会下降，但是test-dev上的AP应该不会有变化

**Comment by Deng-yongbiao** [comment]
好的谢谢
