### ISSUE TITLE
hello, i had found that how to print per_class map50-95，but i really want to know how to print per_class ap50

### ISSUE THREAD

**Issue by beauty-snowman** [Megvii-BaseDetection/YOLOX#1092]
hello, i had found that how to print per_class map50-95，but i really want to know how to print per_class ap50. thanks

**Comment by beauty-snowman** [comment]
i find bugs per_class map50-95.
per class AP:
| class   | AP    | class   | AP    | class     | AP    |
|:--------|:------|:--------|:------|:----------|:------|
| bicycle | 0.716 | car     | 1.327 | motorbike | 0.605 |
| bus     | 2.132 | train   | 0.895 | truck     | 0.384 |

**Comment by beauty-snowman** [comment]
what should i do.

**Comment by beauty-snowman** [comment]
我发现了，会了。（→。→）

**Comment by LucasVillarroelR** [comment]
Hello, how can I print per_class ap50?

**Comment by RyanZRH** [comment]
> 我发现了，会了。（→。→）

你好，能教教我吗，我也想实现显示每类的AP50
