### ISSUE TITLE
get_data_loader() got an unexpected keyword argument 'cache_img' : Issue persists with the new branch too

### ISSUE THREAD

**Issue by anshudaur** [Megvii-BaseDetection/YOLOX#1093]
Hi,

The issue for cache parameter still exits with the current main branch, whether I pass cache parameter or not
 "get_data_loader() got an unexpected keyword argument 'cache_img' " 

How can I fix it?

Thank you

**Comment by anshudaur** [comment]
Remove -o

**Comment by Xiaoyao-Zym** [comment]
I got this issue as well, Have you solved it yet? Now.
