### ISSUE TITLE
how can i do transfer learning yolox

### ISSUE THREAD

**Issue by vanmeruso** [Megvii-BaseDetection/YOLOX#1105]
Hello,
I want to train only yolox head with backbone freeze.
how can i do this?
yolox is able to do this with argument 'freeze'.
thank you.

**Comment by FateScript** [comment]
May be we should provide a function named `freeze`.

**Comment by FateScript** [comment]
You could detach output tensor to work around, We will provide a freeze function to do this.

**Comment by vanmeruso** [comment]
@FateScript Thank you so much!

**Comment by Moaaz-Abdelrahman** [comment]
@FateScript Any update about this feature. How can I train the head of the model only. 
Thanks

**Comment by FateScript** [comment]
@Moaaz-Abdelrahman @vanmeruso YOLOX supports freezing module  in #1156  now. Feel free to advise / raise issue.
