### ISSUE TITLE
feat request(cache data): Skip corrupted images

### ISSUE THREAD

**Issue by ankandrew** [Megvii-BaseDetection/YOLOX#1142]
### Problem/Request

Is it possible to add an option to skip corrupted images? If just one of the training images is corrupted when using cache acceleration, it stops training.

### Error origin

https://github.com/Megvii-BaseDetection/YOLOX/blob/d99bee009220e3c4878ab4b97ff20f14dd8281a9/yolox/data/datasets/coco.py#L192-L193

_Note: I'm not using COCO dataset but my own w/ COCO format._

**Comment by FateScript** [comment]
In my opinion, if your image is corrupt, one proper way is to remove the image from your dataset but not training it. If your image is normal but your cache is corrupt, it's a bug issue.

**Comment by ankandrew** [comment]
I agree, the dataset should be curated before training process. Outside YoloX Scope. Closing.
