### ISSUE TITLE
关于标签异常的问题

### ISSUE THREAD

**Issue by HuYo-OS** [Megvii-BaseDetection/YOLOX#1148]
请问为什么训练的时候标签还是正常的，用训练完后的权重测试视频的时候标签就不对了呀，打上的还是coco_classes原来的标签，voc_classes,coco_classes改成自己的了，问题依旧

**Comment by FateScript** [comment]
Did you modify any code in YOLOX?

**Comment by HuYo-OS** [comment]
> 您是否修改了 YOLOX 中的任何代码？

修改了yolox/exp/yolox_base.py里的num_classes，depth，width，num_workers，max_epoch

**Comment by FateScript** [comment]
Could you plz provide a minimum code to reimplemented your issue?

**Comment by HuYo-OS** [comment]
> 您能否提供最低代码来重新实施您的问题？

重新部署之后就好了，非常感谢！
