### ISSUE TITLE
推理错误咨询

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#1149]
在推理过程中，我把一张img张量[n,c,h,w]分成两个张量img_1和img_2，连续第二次调用self.model出错，请问是什么原因？要怎么改？多谢！
![image](https://user-images.githubusercontent.com/78945582/155669689-efa4d2d5-3788-499c-8e2d-44c5abd05cc4.png)
![image](https://user-images.githubusercontent.com/78945582/155669717-81259e67-6299-42b2-9dc1-d3322c623d70.png)

**Comment by FateScript** [comment]
Your log shows it's a shape mismatched error, plz double check your tensor shape.
