### ISSUE TITLE
Why the evaluation score so small?

### ISSUE THREAD

**Issue by AI-Passionner** [Megvii-BaseDetection/YOLOX#1158]
I ran the evaluation on the COCO dataset and got very small scores. I didn't change anything except for specifying the COCO data as 
./COCO
    /annotations/
       /instances_train2017.json
       /instances_val2017.json
   /train2017/*.jpg
   /val2017/*.jpg

Couldn't figure out why since I just wanted to reproduce the result first before I move to the next step. Any thoughts?
![image](https://user-images.githubusercontent.com/65562616/156857805-2c063be6-ab38-4422-98c8-fc086ffb8faf.png)

**Comment by AI-Passionner** [comment]
figured out./

**Comment by Kyle-fang** [comment]
Ask, what is the reason?
