### ISSUE TITLE
运行DEMO只给我返回了INFO信息，到底有没有运行成功呢？

### ISSUE THREAD

**Issue by lihui669** [Megvii-BaseDetection/YOLOX#118]
![image](https://user-images.githubusercontent.com/40649829/126789268-16e2cc1f-312c-4a38-a5a1-d11149846f8a.png)
并没有返回检测结果，只返回了INFO信息，也没有报错，这是什么情况呢？

**Comment by 18369674616** [comment]
我也是这样的   你的有结果了吗   我也不知道是对还是错了

**Comment by 18369674616** [comment]
我也是这样的 你的有结果了吗 我也不知道是对还是错了

**Comment by 18369674616** [comment]
我也是这样的 你的有结果了吗 我也不知道是对还是错了

**Comment by Joker316701882** [comment]
你们更新了吗？这个问题昨天应该修了

**Comment by 18369674616** [comment]
是的  刚刚下载了最新版   运行成功了  谢谢 @Joker316701882

**Comment by lihui669** [comment]
> 你们更新了吗？这个问题昨天应该修了
我也成功了，谢谢

**Comment by tkone2018** [comment]
我下最新版的还是出现这个问题了python demo.py image -n yolox-x -c ./pre_weights/yolox_x.pth.tar
