### ISSUE TITLE
About the reg_preds initializaition?

### ISSUE THREAD

**Issue by YTEP-ZHI** [Megvii-BaseDetection/YOLOX#1187]
https://github.com/Megvii-BaseDetection/YOLOX/blob/10a04c7cd2cfa68b91fd7efcbd6df5a20ca63114/yolox/models/yolo_head.py#L132-L141

I'm not sure why the bias of reg_preds are un-initialized while that of cls_preds and obj_preds are initialized? What is the reason to treat them differently? Looking forward to your reply.

**Comment by FateScript** [comment]
It's prior prob for background classes. Such code is very common in detection task.

**Comment by YTEP-ZHI** [comment]
Thanks for your reply.
