### ISSUE TITLE
训练voc数据集  ifa != nullptr. Unable to find address for: ib0

### ISSUE THREAD

**Issue by Xiang99** [Megvii-BaseDetection/YOLOX#119]
RuntimeError: [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: ib0

看之前的问题说是把all_reduce_norm(self.model)注释了，我注释了还是不行

**Comment by ruinmessi** [comment]
This is a bug of NCCL confugure. Plz pull the latest updates.
