### ISSUE TITLE
different device with different results

### ISSUE THREAD

**Issue by aidemHJC** [Megvii-BaseDetection/YOLOX#1194]
hi
i used the same model in PC and phone to infer the same images, but the results are very different, both in classification and location
Is it normal?
thanks

**Comment by FateScript** [comment]
Plz check your setting of nms threshold / box score threshold. BTW, what do they look like?

**Comment by aidemHJC** [comment]
thanks for your reply, i'll double check, 

i found the classification and location are both different, for example, 
in the same image, the ground truth is Class A, [x1,y1,x2,y2] is [1,1,2,2]
in PC the result is :Class A, [x1,y1,x2,y2] is [1.1, 0.9, 2.0, 1.9]
BUT in phone the result is:  Class B, [x1,y1,x2,y2] is [1.5, 0.6, 2.3, 1.9]

thnaks,
BR
