### ISSUE TITLE
Support for Non-Square Images

### ISSUE THREAD

**Issue by MadanMl** [Megvii-BaseDetection/YOLOX#1211]
I have trying to use the implementation for non-square Images and getting error : RuntimeError: Sizes of tensors must match except in dimension 3. Got 135 and 136 (The offending index is 0).

I had set:
input_size = (1920,1080)
random_size = 0
mscale = 0

**Comment by FateScript** [comment]
1080 is not multiple of 32, plz pad to 1088 to solve this issue.

**Comment by MadanMl** [comment]
> 1080 is not a multiple of 32, plz pad to 1088 to solve this issue.

Thank you for your reply. Do I have to manually change my input (adding the pad) or will the script handles it automatically? 
Is there as specific reason for 32?
