### ISSUE TITLE
训练自己数据集时map曲线不正常

### ISSUE THREAD

**Issue by SSTato** [Megvii-BaseDetection/YOLOX#1221]
请问我在训练自己的数据集的时候，使用s和m版本的YOLOX是map曲线都是正常的，但是l和x都出现了以下情况。
橙色曲线为YOLOX-m，蓝色曲线为YOLOX-l。

![image](https://user-images.githubusercontent.com/93987794/161795464-4157b1bd-3b0d-45f5-9590-172130572981.png)

**Comment by vaerdu** [comment]
> 据集

你好，你怎么把两条曲线弄到一张图上的？

**Comment by SSTato** [comment]
> > 据集
> 
> 你好，你怎么把曲线弄到一张图上？

使用tensorboard

**Comment by vaerdu** [comment]
> > > 据集
> > 
> > 
> > 你好，你怎么把曲线弄到一张图上？
> 
> 使用tensorboard

嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？

**Comment by SSTato** [comment]
> > > > 据集
> > > 
> > > 
> > > 你好，你怎么把曲线弄到一张图上？
> > 
> > 
> > 使用tensorboard
> 
> 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？

是的

**Comment by vaerdu** [comment]
> > > > > 据集
> > > > 
> > > > 
> > > > 你好，你怎么把曲线弄到一张图上？
> > > 
> > > 
> > > 使用tensorboard
> > 
> > 
> > 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？
>

> > > > > 据集
> > > > 
> > > > 
> > > > 你好，你怎么把曲线弄到一张图上？
> > > 
> > > 
> > > 使用tensorboard
> > 
> > 
> > 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？
> 
> 是的
[
![image](https://user-images.githubusercontent.com/78519509/161900616-fd3eae9e-f652-49c4-97de-ef2cf01d45b4.png)
](url)

**Comment by vaerdu** [comment]
> > > > > 据集
> > > > 
> > > > 
> > > > 你好，你怎么把曲线弄到一张图上？
> > > 
> > > 
> > > 使用tensorboard
> > 
> > 
> > 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？
> 
> 是的

[
![image](https://user-images.githubusercontent.com/78519509/161900665-293a04a6-c2c4-4a93-ab57-3bb074115068.png)
](url)
添加后曲线都混乱了是什么原因？

**Comment by SSTato** [comment]
> > > > > > 据集
> > > > > 
> > > > > 
> > > > > 你好，你怎么把曲线弄到一张图上？
> > > > 
> > > > 
> > > > 使用tensorboard
> > > 
> > > 
> > > 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？
> > 
> > 
> > 是的
> 
> [ ![image](https://user-images.githubusercontent.com/78519509/161900665-293a04a6-c2c4-4a93-ab57-3bb074115068.png) ](url) 添加后曲线都混乱了是什么原因？



> > > > > > 据集
> > > > > 
> > > > > 
> > > > > 你好，你怎么把曲线弄到一张图上？
> > > > 
> > > > 
> > > > 使用tensorboard
> > > 
> > > 
> > > 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？
> > 
> > 
> > 是的
> 
> [ ![image](https://user-images.githubusercontent.com/78519509/161900665-293a04a6-c2c4-4a93-ab57-3bb074115068.png) ](url) 添加后曲线都混乱了是什么原因？

![11](https://user-images.githubusercontent.com/93987794/161901113-5bae9531-08be-4198-939f-2101b4115489.PNG)
这样放

**Comment by vaerdu** [comment]
> 

可以了，非常感谢！

**Comment by vaerdu** [comment]
> > > > > > > 据集
> > > > > > 
> > > > > > 
> > > > > > 你好，你怎么把曲线弄到一张图上？
> > > > > 
> > > > > 
> > > > > 使用tensorboard
> > > > 
> > > > 
> > > > 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？
> > > 
> > > 
> > > 是的
> > 
> > 
> > [ ![image](https://user-images.githubusercontent.com/78519509/161900665-293a04a6-c2c4-4a93-ab57-3bb074115068.png) ](url) 添加后曲线都混乱了是什么原因？
> 
> > > > > > > 据集
> > > > > > 
> > > > > > 
> > > > > > 你好，你怎么把曲线弄到一张图上？
> > > > > 
> > > > > 
> > > > > 使用tensorboard
> > > > 
> > > > 
> > > > 嗯嗯，是把两次训练得到的evens文件放到一个文件夹里吗？
> > > 
> > > 
> > > 是的
> > 
> > 
> > [ ![image](https://user-images.githubusercontent.com/78519509/161900665-293a04a6-c2c4-4a93-ab57-3bb074115068.png) ](url) 添加后曲线都混乱了是什么原因？
> 
> ![11](https://user-images.githubusercontent.com/93987794/161901113-5bae9531-08be-4198-939f-2101b4115489.PNG) 这样放

可以了，非常感谢！

**Comment by wujihua628** [comment]
你们好，如何用tensorboard可视化loss曲线呢

**Comment by SSTato** [comment]
> 你们好，如何用tensorboard可视化loss曲线呢

tensorboard --logdir runs\train
