### ISSUE TITLE
Would it be better if changing the file opening mode to read-only when loading cached images?

### ISSUE THREAD

**Issue by npurson** [Megvii-BaseDetection/YOLOX#1225]
Since the cache operation is time-consuming on clusters, it would be ideal to let several training tasks use the same cached file (or its symbolic links). However, the **unnecessary writing mode when opening the cached file blocks other processes from concurrent loading**.
A simple is solution is to change the `mode="r+"` to `mode="r"` in the `yolox/data/datasets/coco.py` line 133 and `yolox/data/datasets/voc.py` line 188.

**Comment by FateScript** [comment]
Did you benchmark the time ? @npurson

**Comment by npurson** [comment]
> Did you benchmark the time ? @npurson

I haven't compare the total training time under exactly same settings, but AFAIC, there is no notable change observed in `data_time`, should it be?
