### ISSUE TITLE
ImportError: exps/example/yolox_voc/yolox_coco_s.py doesn't contains class named 'Exp'

### ISSUE THREAD

**Issue by haomayang1126** [Megvii-BaseDetection/YOLOX#123]

**Comment by haomayang1126** [comment]
i use coco dataset to train，this is my exp file，what happend

# encoding: utf-8
import os
import random
import torch
import torch.nn as nn
import torch.distributed as dist

from yolox.exp import Exp as MyExp
from yolox.data import get_yolox_datadir

class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.num_classes = 4
        self.depth = 0.33
        self.width = 0.50
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]


    def get_data_loader(self, batch_size, is_distributed, no_aug=False):
        from yolox.data import (
            COCODataset,
            TrainTransform,
            YoloBatchSampler,
            DataLoader,
            InfiniteSampler,
            MosaicDetection,
        )

        dataset = COCODataset(
            data_dir='data/COCO/',
            json_file=self.train_ann,
            img_size=self.input_size,
            preproc=TrainTransform(
                rgb_means=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225),
                max_labels=50,
            ),
        )

        dataset = MosaicDetection(
            dataset,
            mosaic=not no_aug,
            img_size=self.input_size,
            preproc=TrainTransform(
                rgb_means=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225),
                max_labels=120,
            ),
            degrees=self.degrees,
            translate=self.translate,
            scale=self.scale,
            shear=self.shear,
            perspective=self.perspective,
            enable_mixup=self.enable_mixup,
        )

        self.dataset = dataset

        if is_distributed:
            batch_size = batch_size // dist.get_world_size()

        sampler = InfiniteSampler(
            len(self.dataset), seed=self.seed if self.seed else 0
        )

        batch_sampler = YoloBatchSampler(
            sampler=sampler,
            batch_size=batch_size,
            drop_last=False,
            input_dimension=self.input_size,
            mosaic=not no_aug,
        )

        dataloader_kwargs = {"num_workers": self.data_num_workers, "pin_memory": True}
        dataloader_kwargs["batch_sampler"] = batch_sampler
        train_loader = DataLoader(self.dataset, **dataloader_kwargs)

        return train_loader

    def get_eval_loader(self, batch_size, is_distributed, testdev=False):
        from yolox.data import COCODataset, ValTransform

        valdataset = COCODataset(
            data_dir='data/COCO/',
            json_file=self.val_ann if not testdev else "image_info_test-dev2017.json",
            name="val2017" if not testdev else "test2017",
            img_size=self.test_size,
            preproc=ValTransform(
                rgb_means=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)
            ),
        )

        if is_distributed:
            batch_size = batch_size // dist.get_world_size()
            sampler = torch.utils.data.distributed.DistributedSampler(
                valdataset, shuffle=False
            )
        else:
            sampler = torch.utils.data.SequentialSampler(valdataset)

        dataloader_kwargs = {
            "num_workers": self.data_num_workers,
            "pin_memory": True,
            "sampler": sampler,
        }
        dataloader_kwargs["batch_size"] = batch_size
        val_loader = torch.utils.data.DataLoader(valdataset, **dataloader_kwargs)

        return val_loader

    def get_evaluator(self, batch_size, is_distributed, testdev=False):
        from yolox.evaluators import COCOEvaluator

        val_loader = self.get_eval_loader(batch_size, is_distributed, testdev=testdev)
        evaluator = COCOEvaluator(
            dataloader=val_loader,
            img_size=self.test_size,
            confthre=self.test_conf,
            nmsthre=self.nmsthre,
            num_classes=self.num_classes,
            testdev=testdev,
        )
        return evaluator

**Comment by haomayang1126** [comment]
(Swin) G:\Pythonproject\YOLOX-main>python tools/train.py -f exps/example/yolox_voc/yolox_coco_s.py -d 8 -b 7 --fp16 -o -c assets/yolox_s.pth.tar
exp_file is  exps/example/yolox_voc/yolox_coco_s.py
exp_name is None
Traceback (most recent call last):
  File "g:\pythonproject\yolox-main\yolox\exp\build.py", line 14, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "C:\Users\xiaoma\Anaconda3\envs\Swin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yolox_coco_s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 106, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "g:\pythonproject\yolox-main\yolox\exp\build.py", line 59, in get_exp
    return get_exp_by_file(exp_file)
  File "g:\pythonproject\yolox-main\yolox\exp\build.py", line 17, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: exps/example/yolox_voc/yolox_coco_s.py doesn't contains class named 'Exp'

(Swin) G:\Pythonproject\YOLOX-main>

**Comment by Zhang-ze-peng** [comment]
Hi, have you resolve this problem? I encounter the same problem.

**Comment by tucachmo2202** [comment]
Hi,
Could you tell me how do you fix that error? Thank.

**Comment by haomayang1126** [comment]
HI，please check the command carefully，that‘s&nbsp; because i write the wrong EXP file path in command。before：python tools/train.py -f g:\Pythonproject\YOLOX-main\exps\example\yolo_voc\yolox_voc_s.py -d 1 -b 7 --fp16 -c assets/yolox_s.pth.tar         now：python tools/train.py -f g:\Pythonproject\YOLOX-main\exps\example\yolox_voc\yolox_voc_s.py -d 1 -b 7 --fp16 -c assets/yolox_s.pth.tar 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月3日(星期二) 凌晨2:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Megvii-BaseDetection/YOLOX] ImportError: exps/example/yolox_voc/yolox_coco_s.py doesn&#39;t contains class named &#39;Exp&#39; (#123)





 
Hi,
 Could you tell me how do you fix that error? Thank.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
