### ISSUE TITLE
TypeError: preproc() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by EchoYGemini** [Megvii-BaseDetection/YOLOX#1244]
之前跑通过，最近跑demo都会报这个错误
Traceback (most recent call last):
  File "tools/demo.py", line 296, in <module>
    main(exp, args)
  File "tools/demo.py", line 287, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
  File "tools/demo.py", line 180, in image_demo
    outputs, img_info = predictor.inference(image_name)
  File "tools/demo.py", line 136, in inference
    img, ratio = preproc(img, self.test_size, self.rgb_means, self.std)
TypeError: preproc() takes from 2 to 3 positional arguments but 4 were given

**Comment by EchoYGemini** [comment]
> 之前跑通过，最近跑demo都会报这个错误 Traceback (most recent call last): File "tools/demo.py", line 296, in main(exp, args) File "tools/demo.py", line 287, in main image_demo(predictor, vis_folder, args.path, current_time, args.save_result) File "tools/demo.py", line 180, in image_demo outputs, img_info = predictor.inference(image_name) File "tools/demo.py", line 136, in inference img, ratio = preproc(img, self.test_size, self.rgb_means, self.std) TypeError: preproc() takes from 2 to 3 positional arguments but 4 were given

**Comment by Razamalik4497** [comment]
did you find solution I got the same problem
