### ISSUE TITLE
Predict result compare with yolov4-tiny-3l and yolox-s (Same input data)

### ISSUE THREAD

**Issue by er778899789** [Megvii-BaseDetection/YOLOX#1248]
I use same dataset training with yolov4-tiny-3l and yolox-s.
Both model mAP50 best score are the same about 95%.
But the confidence score in result image, yolov4-tiny-3l is almost better than yolox-s. 

But compare with confidence score why yolox-s worse than yolov4-tiny-3l?

Can anyone give me some advice? THX!!

**Comment by FateScript** [comment]
The score in yolox is not using sqrt function. If socre value is 0.81 in YOLOX, the true score value is 0.9 actually.

**Comment by er778899789** [comment]
@FateScript Thanks for reply.
How can I change the function that calculate confidence score like yolov4?
If it true score value is 0.9, I want to use these value to do other post-processing.

**Comment by er778899789** [comment]
@FateScript I find confidence score formula in this function. (like below image)

![image](https://user-images.githubusercontent.com/32409355/163523343-e211d4c6-f35d-453d-9ac7-dc6580a4a418.png)

I print two tensor's value find output[:, 4] get very high score, almost tensor([0.99 ~ 0.98]). And output[:, 5] get tensor([0.94 ~ 0.80]). 

Can you explain what the meanings about output[:, 4] and output[:, 5] ?

**Comment by FateScript** [comment]
centerness and pred_score
