### ISSUE TITLE
有个问题，yolo_head.py的get_in_boxes_info函数中，为什么is_in_boxes_anchor = is_in_boxes_all | is_in_centers_all使用or呢

### ISSUE THREAD

**Issue by treasureqqm** [Megvii-BaseDetection/YOLOX#1251]
不知道为什么要这样设计？这种方式好像和YOLOX的论文所述并不一致（论文中说，使用center的3x3区域），和FCOS的第一版（gt bounding box内的所有区域）和第二版（定义了一个center area，类似于yolox的is_in_centers_all）也不一致。不知自己是否有理解错的地方，希望作者或其他对这问题理解的人可以帮忙解答问题，谢谢大家

**Comment by mankasto** [comment]
get_in_boxes_info函数中除了is_in_boxes_anchor之外，还包含了is_in_boxes_and_center, 这个和论文是一致的。后续在标签分配部分的代码中是先用了is_in_boxes_anchor作为前景的mask初筛计算pair-wise cost, 但是最后在cost中还加了一项100000.0*(~is_in_boxes_and_center)，也就是说给不在中心3*3区域的cell对应的cost加了一个很大的值，之后肯定会被过滤掉。

**Comment by treasureqqm** [comment]
> get_in_boxes_info函数中除了is_in_boxes_anchor之外，还包含了is_in_boxes_and_center, 这个和论文是一致的。后续在标签分配部分的代码中是先用了is_in_boxes_anchor作为前景的mask初筛计算pair-wise cost, 但是最后在cost中还加了一项100000.0*(~is_in_boxes_and_center)，也就是说给不在中心3*3区域的cell对应的cost加了一个很大的值，之后肯定会被过滤掉。
谢谢回复，那这是否说明，直接改为&也可以？即
is_in_boxes_anchor = is_in_boxes_all & is_in_centers_all
还是说，改为&会有一些副作用？

**Comment by mankasto** [comment]
@treasureqqm 你好，在is_in_boxes_anchor 这里应该不能改成&（与），因为is_in_boxes_all和 is_in_centers_all 是一个维度为num_anchors (num_cells)的0-1二值（布尔） tensor, 表示的是各个cell落在是否任意一个（这里还可能有一个cell落在多个gt bbox区域内的情况）gt bbox内，所以只能是维度为[num_gt, num_anchors] 的 is_in_boxes_and_center再做&（与）运算，才能把gt bbox也对应上。
代码：
is_in_boxes_anchor = is_in_boxes_all | is_in_centers_all     
is_in_boxes_and_center = (
      is_in_boxes[:, is_in_boxes_anchor] & is_in_centers[:, is_in_boxes_anchor]         
 )

**Comment by treasureqqm** [comment]
@mankasto 感谢详细的回复，我自己再理解一下

**Comment by treasureqqm** [comment]
认真看代码后，已理解，感谢 @mankasto

**Comment by QSQSQSQS** [comment]
我还是不太理解，能麻烦细讲一下吗，为什么不能直接用is_in_boxes_anchor = is_in_boxes_all & is_in_centers_all呢，谢谢 @treasureqqm
