### ISSUE TITLE
 ERROR    | __main__:<module>:83 - An error has been caught in function '<module>', process 'MainProcess' (16268), thread 'MainThread' (13536):

### ISSUE THREAD

**Issue by gwq2018** [Megvii-BaseDetection/YOLOX#1268]
您好，请问可以为我解答一下吗？

![image](https://user-images.githubusercontent.com/37999134/164616226-6b5c6b2a-42e1-455a-83ca-236e5e043924.png)

**Comment by FateScript** [comment]
Are you using the model you trained or model we provided?

**Comment by gwq2018** [comment]
确实是模型的原因，我使用了其他地方的yolox 的模型，已经解决了，谢谢
