### ISSUE TITLE
Training of experiment is done and the best AP is 9.91

### ISSUE THREAD

**Issue by colsona** [Megvii-BaseDetection/YOLOX#127]
So has anyone trained after 20 epoches for COCO? I  used yolo_x but the results are so unbelivable.

![image](https://user-images.githubusercontent.com/49737402/126887644-89b80749-0cbc-4ab1-a03f-7530dd041ab7.png)
`2021-07-24 21:11:25 | INFO     | yolox.core.trainer:298 -
Average forward time: 2.48 ms, Average NMS time: 0.94 ms, Average inference time: 3.42 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.099
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.190
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.091
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.046
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.112
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.119
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.141
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.244
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.262
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.108
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.287
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.320

2021-07-24 21:11:25 | INFO     | yolox.core.trainer:307 - Save weights to ./YOLOX_outputs/yolox_s
2021-07-24 21:11:25 | INFO     | yolox.core.trainer:183 - Training of experiment is done and the best AP is 9.91
`

**Comment by Joker316701882** [comment]
@colsona What is your training command?

**Comment by colsona** [comment]
> @colsona What is your training command?

I say wrongly above. I used yolox_s. The training command:`CUDA_VISIBLE_DEVICES=2,3 python tools/train.py -n yolox-s -d 2 -b 16 --fp16 -o` By the way, can you tell me how you set the iteration for every epoch. I don't see it in the code.

**Comment by Joker316701882** [comment]
@colsona You should **download our pre-trained yolox_s.pth.tar** and then **finetune** your dataset on it.
Use the command
`CUDA_VISIBLE_DEVICES=2,3 python tools/train.py -n yolox-s -d 2 -b 16 --fp16 -o -c xxxxxx.pth.tar`

You are now training from scratch, so the mAP=9.91 is very normal.

**Comment by Joker316701882** [comment]
@colsona It's normal to get 9.9mAP at the 20th epoch. Why do you think this value is unbelivable.

Iteration for every epoch is automatically calculated by:
iterations per epoch = num_images / img_number_per_batch

**Comment by colsona** [comment]
I know it! Thank you very much for your answers. I was training from&nbsp;scratch! It's norm.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/YOLOX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月25日(星期天) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] Training of experiment is done and the best AP is 9.91 (#127)





 
@colsona It's normal to get 9.9mAP at the 20th epoch. Why do you think this value is unbelievable.
 
Iteration for every epoch is automatically calculated by:
 iterations per epoch = num_images / img_number_per_batch

**Comment by Joker316701882** [comment]
@colsona Yes. And if you want to train on your own dataset, remember to download the pre-trained model and finetune on it. It will converge much faster.

**Comment by colsona** [comment]
> @colsona Yes. And if you want to train on your own dataset, remember to download the pre-trained model and finetune on it. It will converge much faster.

OK! Thank you very much!! Your answers are really useful to me.
