### ISSUE TITLE
coco training:IndexError: list index out of range

### ISSUE THREAD

**Issue by jinbo8** [Megvii-BaseDetection/YOLOX#1273]
我训练coco格式数据时遇到了以下问题，查了很多博客, 没有找到解决方法，下载使用的是官网链接的coco128数据集，也修改了类别yolox_.py下的类别为80，这种问题有大佬知道怎么解决的吗？
![image](https://user-images.githubusercontent.com/54313512/165033232-18dfaf14-7b45-4aa6-88ab-fa045872d280.png)

![SEYXW6MM_`9RM2_ K$HZYWU](https://user-images.githubusercontent.com/54313512/165033158-85aeca96-3cd6-45c1-a336-d5fdc5de42fa.jpg)

**Comment by ninenox-dev** [comment]
`2022-04-29 08:09:38 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (613), thread 'MainThread' (140693641181056):
Traceback (most recent call last):

  File "tools/train.py", line 140, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=8, cache=False, ckpt='yolox_nano.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='nano.py'...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7ff5c6545cb0>

  File "tools/train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7ff4fc8b4ef0>
    └ <yolox.core.trainer.Trainer object at 0x7ff4f292aad0>

  File "/content/YOLOX/yolox/core/trainer.py", line 76, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7ff4f2860f80>
    └ <yolox.core.trainer.Trainer object at 0x7ff4f292aad0>

  File "/content/YOLOX/yolox/core/trainer.py", line 86, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7ff4f2864950>
    └ <yolox.core.trainer.Trainer object at 0x7ff4f292aad0>

  File "/content/YOLOX/yolox/core/trainer.py", line 222, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7ff4f2864c20>
    └ <yolox.core.trainer.Trainer object at 0x7ff4f292aad0>

  File "/content/YOLOX/yolox/core/trainer.py", line 326, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7ff4f292aad0>
    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff4ea678990>
    │          └ <yolox.core.trainer.Trainer object at 0x7ff4f292aad0>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/content/YOLOX/yolox/exp/yolox_base.py", line 322, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7ff4f284c290>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff4ea678990>

  File "/content/YOLOX/yolox/evaluators/coco_evaluator.py", line 187, in evaluate
    data_list.extend(self.convert_to_coco_format(outputs, info_imgs, ids))
    │         │      │    │                      │        │          └ tensor([[10000000],
    │         │      │    │                      │        │                    [10000001]])
    │         │      │    │                      │        └ [tensor([400, 400]), tensor([300, 300])]
    │         │      │    │                      └ [tensor([[5.9590e+01, 7.6316e+01, 2.3592e+02, 3.2472e+02, 3.0647e-01, 9.9889e-01,
    │         │      │    │                                 2.0000e+00],
    │         │      │    │                                [6.0957e+01, ...
    │         │      │    └ <function COCOEvaluator.convert_to_coco_format at 0x7ff4f284c320>
    │         │      └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff4ea678990>
    │         └ <method 'extend' of 'list' objects>
    └ []

  File "/content/YOLOX/yolox/evaluators/coco_evaluator.py", line 220, in convert_to_coco_format
    label = self.dataloader.dataset.class_ids[int(cls[ind])]
            │    │          │       │             │   └ 0
            │    │          │       │             └ tensor([2., 5., 7.])
            │    │          │       └ [1, 2]
            │    │          └ <yolox.data.datasets.coco.COCODataset object at 0x7ff4eaf23950>
            │    └ <torch.utils.data.dataloader.DataLoader object at 0x7ff4eaeed6d0>
            └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff4ea678990>

IndexError: list index out of range`

I had error same, How to fix it?

**Comment by doctorchoco** [comment]
Your annotation files are not fit to your image files. Check it!

**Comment by Finorita** [comment]
修改的类别是在yolox_base.py文件下的吗？然后你训练的时候，加载的配置文件对应的numclasses有没有修改成71？例子中，配置文件是yolox_vox_x.py，可以直接使用exps/co(用户-英文不记得了）/yolox_s.py，直接运行就OK了，要修改一下数据集路径哦！coco128类别是71

**Comment by Finorita** [comment]
> 

我的意思是，看看官方文件的例子来做，但是配置文件用exps/co(用户-英文不记得了）/yolox_s.py这个就好啦

**Comment by Finorita** [comment]
有个不情之请，你做完以后可以告诉我预测结果标签和框对应得上吗？还有可以告诉我coco128的json文件中的category(最后一项)对应的是1-80还是1-71呀？
