### ISSUE TITLE
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'

### ISSUE THREAD

**Issue by fushh** [Megvii-BaseDetection/YOLOX#1274]
![image](https://user-images.githubusercontent.com/71886569/165107921-3dcc45e1-3137-4978-81f3-074079c22dd1.png)
There is a error when initializing `DataPrefetcher`. I don't know what's wrong.

**Comment by FateScript** [comment]
What if you didn't use DataPrefetcher? Guess it's a dataloader error, not dataloader.

**Comment by fushh** [comment]
![image](https://user-images.githubusercontent.com/71886569/165214812-466dcf3a-b922-4048-b2e5-aa8f9343d6dc.png)
![image](https://user-images.githubusercontent.com/71886569/165214986-619a1989-b3d6-4b36-aa5c-bfe3171adeb5.png)

Yes, it is a dataloader error. Could you provide some tips to fix the bug?

**Comment by fushh** [comment]
Oh, I have found the bug. I made some mistakes when processing labels and thus an error at data augmentation raised. Thanks.
