### ISSUE TITLE
KeyError:错误的类名

### ISSUE THREAD

**Issue by AIgsl** [Megvii-BaseDetection/YOLOX#1275]
File "/media/gzzn/Data/YOLOX-main/yolox/data/datasets/voc.py", line 71, in __call__
    label_idx = self.class_to_ind[name]
                │    │            └ 'insulated_gloves'
                │    └ {'person': 0, 'head': 1, 'helmet': 2, 'insulated_clothing': 3, 'insulating_gloves': 4, 'hand': 5}
                └ <yolox.data.datasets.voc.AnnotationTransform object at 0x7fac7a9f2050>

KeyError: 'insulated_gloves'

为什么会出现不是我设定的类的名称呢？数据集统一标注的，应该没有问题啊

**Comment by caoyunzhu123** [comment]
我也有同样的问题，请问解决了吗？

**Comment by FateScript** [comment]
`insulating_gloves` doesn't match `insulated_gloves `,  plz read the error log carefully.

**Comment by FateScript** [comment]
I will close thie issue, feel free to reopen it if you have any further question.

**Comment by AIgsl** [comment]
这个问题关闭了，我就在邮箱回你吧。yolox做得很不错了，你只要环境配好，数据集没问题就基本上没问题了，我出现的一堆问题都是由于我数据集打标签标错了，你可以去看看你的数据集



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月29日(周五) 上午9:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Megvii-BaseDetection/YOLOX] KeyError:错误的类名 (Issue #1275)




 
我也有同样的问题，请问解决了吗？

**Comment by szgy66** [comment]
> 这个问题关闭了，我就在邮箱回你吧。yolox做得很不错了，你只要环境配好，数据集没问题就基本上没问题了，我出现的一堆问题都是由于我数据集打标签标错了，你可以去看看你的数据集
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月29日(周五) 上午9:10 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Megvii-BaseDetection/YOLOX] KeyError:错误的类名 (Issue #1275) 我也有同样的问题，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，请问怎么解决的嘛？我也遇到这个问题，纠结好久了，不胜感激

**Comment by AIgsl** [comment]
将数据集标注的错误的类名改成正确的，即可。网上有代码，如果找不到代码，你就加我QQ吧，我转你，QQ号就是邮箱号



---原始邮件---
发件人: "Yang ***@***.***&gt;
发送时间: 2022年5月8日(周日) 中午12:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Megvii-BaseDetection/YOLOX] KeyError:错误的类名 (Issue #1275)




  
这个问题关闭了，我就在邮箱回你吧。yolox做得很不错了，你只要环境配好，数据集没问题就基本上没问题了，我出现的一堆问题都是由于我数据集打标签标错了，你可以去看看你的数据集
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年4月29日(周五) 上午9:10 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Megvii-BaseDetection/YOLOX] KeyError:错误的类名 (Issue #1275) 我也有同样的问题，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
您好，请问怎么解决的嘛？我也遇到这个问题，纠结好久了，不胜感激

**Comment by szgy66** [comment]
非常谢谢的回复。我刚试了一下，VOC2012可以训练，但是自己数据集就不行，而且我发现你把VOC2012只选择两三类训练也会报错，不知道问题在哪

**Comment by szgy66** [comment]
> 
您好，看不到您的邮箱号呀，加不了您的扣扣
