### ISSUE TITLE
yolox_voc_s is only for yolox_s model or we can use other models by setting --ckpt

### ISSUE THREAD

**Issue by Ccantmaker** [Megvii-BaseDetection/YOLOX#1278]
when I use 
python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 0 -b 4 --fp16 -o -c weights/yolox_m.pth -e 66
start training
I get a latest_ckpt.pth after training, this .pth file is as big as yolox_s that I download from this net , rather than as big as yolox_m
and the warning
yolox.utils.checkpoint:26 - Shape of backbone.backbone.stem.conv.conv.weight in checkpoint is torch.Size([48, 12, 3, 3]), while shape of backbone.backbone
.stem.conv.conv.weight in model is torch.Size([32, 12, 3, 3]).
and so on

**Comment by FateScript** [comment]
This error caused by mismatch of  ckpt  and model, plz double check it.

**Comment by Ccantmaker** [comment]
I've saved it by modify the parameters in yolox_voc_s.py.
if we want to train other model ,should change the parameters in
def __init__(self):
    self.depth
    self.width
for some model we must modify other parameters, we can refer to exps/default , this folder have the standard model parameters
