### ISSUE TITLE
关于ONNX错误的问题

### ISSUE THREAD

**Issue by Simoyuan** [Megvii-BaseDetection/YOLOX#1286]
我在运行的时候出现了以下情况：
yolox_s.pth是官方下载的。
命令是：python3 tools/export_onnx.py --output-name yolox_s.onnx -f exps/default/yolox_s.py -c ckpt/yolox_s.pth

显示如下：
2022-04-29 10:30:44.222 | INFO     | __main__:main:64 - args value: Namespace(batch_size=1, ckpt='ckpt/yolox_s.pth', decode_in_inference=False, dynamic=False, exp_file='exps/default/yolox_s.py', experiment_name=None, input='images', name=None, no_onnxsim=False, opset=11, opts=[], output='output', output_name='yolox_s.onnx')
2022-04-29 10:30:44.516 | INFO     | __main__:main:88 - loading checkpoint done.
2022-04-29 10:30:50.764 | INFO     | __main__:main:99 - generated onnx model named yolox_s.onnx

Segmentation fault

然后运行python3 onnx_inference.py -m ../../yolox_s.onnx -i 000000000139.jpg  -s 0.3 --input_shape 416,416
Segmentation fault

**Comment by FateScript** [comment]
Did you export onnx correctly?

**Comment by Simoyuan** [comment]
> Did you export onnx correctly?

No, If I don't use --no-onnxsim, there will cause a fault "Segmentation fault. But if I use --no-onnxsim,  it will be export onnx with no message.

**Comment by FateScript** [comment]
It's impossible.You may refer code [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/tools/export_onnx.py#L91-L101)

**Comment by Simoyuan** [comment]
I follow this code, however there always is a issue.
![image](https://user-images.githubusercontent.com/104345049/165916423-c9ce213c-2499-4d22-9a3e-375e09960935.png)

**Comment by FateScript** [comment]
> I follow this code, however there always is a issue. ![image](https://user-images.githubusercontent.com/104345049/165916423-c9ce213c-2499-4d22-9a3e-375e09960935.png)

Seg Fault is caused by onnx-simplify, pytorch generate the onnx model. Try add `--no-onnxsim` in your cli.
BTW, is `onnx-simplifier==0.3.5` on you machine?

**Comment by Simoyuan** [comment]
yes, I have onnx-simplifier==0.3.5. add --no-onnxsim will be fine. thank you.
