### ISSUE TITLE
Adaptivepool2d

### ISSUE THREAD

**Issue by aisuta** [Megvii-BaseDetection/YOLOX#1292]
我尝试向网络加入 Adaptivepool2d(1,None), 
得到如下报错
TypeError: must be real number, not NoneType
尝试将None换成具体数值可通，
我不知道是不是因为python 版本问题还是yolox自身检测机制问题。

**Comment by FateScript** [comment]
You might use the api in the wrong way. It should be `Adaptivepool2d((1,None))`, but not `Adaptivepool2d(1,None)`

**Comment by FateScript** [comment]
I will close this issue, feel free  to reopen it if you have any further questions.
