### ISSUE TITLE
AssertionError while training

### ISSUE THREAD

**Issue by nahidalam** [Megvii-BaseDetection/YOLOX#1293]
I am following your documentation from [here](https://yolox.readthedocs.io/en/latest/quick_run.html#installation)

When I try to train using this command
```
python tools/train.py -n yolox-s -d 8 -b 64 --fp16 -o [--cache]
```
I get below error

```
Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    exp.merge(args.opts)
  File "/home/ec2-user/SageMaker/YOLOX/yolox/exp/base_exp.py", line 64, in merge
    assert len(cfg_list) % 2 == 0
AssertionError
```

After some debugging, I see that only `[--cache]` is considered as `ards.opts`. Since that is a odd number, it causes this error.

Please suggest.

**Comment by FateScript** [comment]
[--cache] means option, not input in your cli.

**Comment by nahidalam** [comment]
@FateScript so what should be the command in CLI?

**Comment by FateScript** [comment]
Plz use `python tools/train.py -n yolox-s -d 8 -b 64 --fp16 -o` or `python tools/train.py -n yolox-s -d 8 -b 64 --fp16 -o --cache` . If you want to use cache, just add `--cache`.

**Comment by nahidalam** [comment]
Thanks. I have another issue but that is separate from this one.
