### ISSUE TITLE
Does YOLOX filter out large H/W or W/H bounding boxes during the training?

### ISSUE THREAD

**Issue by AI-Passionner** [Megvii-BaseDetection/YOLOX#1295]
Thank all contributors for making the wonderful YOLOX available. 
I am benchmarking YOLOX and trying to find out if YOLOX could outperform YOLO5 in my own dataset. The reason is that all object detection models seem to be over 'customized' for the COCO dataset, especially in the data augmentation. 

YOLO5 code has a parameter, the aspect ratio of W/H (or H/W), used for filtering large ratio bounding boxes during training. With that parameter to be set large, YOLO5 can dramatically improve the performance. 
I am wondering if YOLOX has such a similar functionality? Does YOLOX load all bounding boxes, no matter how large the bounding box aspect ratio? 

This is very important. It seems that YOLO5 outperforms YOLOX a lot in my case, trying to figure out why
Thanks.

**Comment by FateScript** [comment]
YOLOX will resize your image to a fix size( also keep image ratio) and load all annotations.

**Comment by AI-Passionner** [comment]
That means YOLOX keeps all labels (bounding boxes), right? 
YOLOv5 originally throws any bounding boxes with the aspect ratio > 20 during the training,  since most COCO objects are usually less than this value. Then we found this bug and change this to 100 for our use case. Basically, we should include all bounding boxes during the training.  I am wondering if YOLOX filters any bounding boxes with a large aspect ratio. The benchmarking result shows that YOLOX is 2~3% lower than YOLOV5, comparing the small architecture. 
1. I went through the code and found that `max_labels` was set as 50. But when I increased to 200, it didn't improve at all.
2. I turn off the fp16, it didn't show the improvement, either. 

I am still testing other hyper-parameters,

**Comment by AI-Passionner** [comment]
1. by the way, the coco128 didn't work. The AP is always 0. However, the YOLO2COCO works. It might be worth figuring out why coco128 dataset won't work. 
2. in `voc.py`, `annopath=os.path.join(roopath, "Annotations", "{:s}.xml")`, ":s" should be deleted, othewise, it didn't work for the voc dataset. 

These are minor issues. It might prevent people from trying YOLOX. 
Of course, the new features introduced by YOLOX are very impressive. Hopefully, it actually outperforms the YOLOv5.

**Comment by FateScript** [comment]
Thanks for your kindly advice @AI-Passionner , I will fix issues you menationed later. Hopo you find the reason of worse perfomance.

**Comment by AI-Passionner** [comment]
@FateScript 
Good news. It seems YOLOX-s is very promising in my case when turning off the mosiac augmentation in the last 10 epochs (max=100). The AP seems to still have potential if keeps training. Compared to YOLOV5-s, the AP(0.5:0.95) has an almost 6% jump, very sweet.  I am very excited to run further experiments to see how far it can go. I will keep you posted. 
 Model       AP-0.50:0.95   Ap-0.5
YOLOX-s              0.830    0.942
YOLOV5-s           0.7597   0.936

However, I do need your input:
1. The maximum batch size is only 8 (GPU 11G 1080i), while YOLOV5-s can go up to 17. I tried 16, 12, and 10.  All show the error message,
"RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 11.00 GiB total capacity; 9.48 GiB already allocated; 0 bytes free; 9.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_
split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"
I googled and couldn't figure it out. YOLOV5 will have a similar message if the batch size is set too large. Any suggestions?
2. Are there any scripts to convert your pytorch (.pth)model to the TensorFlow model? Our model inferencing framework is Tensorflow and we have our own evaluation metrics (APs are just referencing).  I tried the YOLOV5 export and it didn't work.
3. Why did turning off the mosiac in the last few epochs result in the big jump? I started a new training by turning off the mosaic completely to check the difference. Did the mosiac help in COCO, for example, a solid increase in the AP? 

So many questions. Thank you.

**Comment by FateScript** [comment]
1. Larger batch size requires more GPU memory to train, if you really need to train YOLOX with larger batchsize, maybe `torch.utils.checkpoint`  could help you
2. We haven't provided such script. 
3. Mosaic might cause your data distribution away from the ground truth distribution (e. g. : an in-house scene and a scence outside might concat in one image). So turning off mosaic augmentation at the end of training might help to get a better performance.

**Comment by Joker316701882** [comment]
@AI-Passionner Hi, thank you for your interesting report. It seems your issues have been solved. Re-open this issue when necessary.
