### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt'

### ISSUE THREAD

**Issue by ryotaro137** [Megvii-BaseDetection/YOLOX#1302]
I would like to turn my trained nano model into a TensorRT using trt.py.

However, when I run tools/trt.py, I get the following error.
```python
# To TensorRT
! python tools/trt.py -f exps/example/custom/nano.py -n 13_nano  -b 1 -c ./YOLOX_outputs/nano/best_ckpt.pth
```
```python
Traceback (most recent call last):
  File "tools/trt.py", line 10, in <module>
    import tensorrt as trt
ModuleNotFoundError: No module named 'tensorrt'
```
For this reason, I executed the following code, which was also an error.
```python
!pip install nvidia-pyindex  
!pip install nvidia-tensorrt  
```
```python
ERROR: Could not find a version that satisfies the requirement nvidia-tensorrt (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-tensorrt
```
Please let me know if there is any solution to this problem.
Thank you in advance.

・My environment is Google Colab.

**Comment by FateScript** [comment]
Could `python3 -m pip install nvidia-pyindex` install the whl on your Colab?

Check https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing for more details.

**Comment by ryotaro137** [comment]
I tried your tips `python3 -m pip install nvidia-pyindex`
But, same error message appears.

**Comment by ryotaro137** [comment]
TensorRT was installed by `!pip install nvidia-tensorrt==8.0.3.4 --index-url https://pypi.ngc.nvidia.com`

But, next error messages  appears
```python
Traceback (most recent call last):
  File "tools/trt.py", line 12, in <module>
    from torch2trt import torch2trt
ModuleNotFoundError: No module named 'torch2trt'
```
