### ISSUE TITLE
运行pip3 install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./报错

### ISSUE THREAD

**Issue by TD-wzw** [Megvii-BaseDetection/YOLOX#131]
<img width="723" alt="捕获" src="https://user-images.githubusercontent.com/57340568/126890702-8743cb28-fe5f-44f2-9f6a-83540dad39d1.PNG">

**Comment by TD-wzw** [comment]
是因为cuda版本不对吗？

**Comment by Joker316701882** [comment]
@TD-wzw Hi, this is an apex installation issue, so you might try to open this issue at https://github.com/NVIDIA/apex.

**Comment by TD-wzw** [comment]
谢谢您！

**Comment by zwenyuan1** [comment]
你可以尝试命令nvcc -V，出来的结果应该是cuda 10.1。和虚环境里安装的cuda 10.2版本不匹配。所以你可以把系统里的cuda升级成10.2，或者把虚拟环境里的cuda 版本降级成10.1。我就是这么解决这个问题的。
