### ISSUE TITLE
运行demo出现ModuleNotFoundError: No module named 'yolox'

### ISSUE THREAD

**Issue by Astroooh** [Megvii-BaseDetection/YOLOX#1310]
安装完成后，打算运行demo试试，输入 python tools/demo.py image -n yolox-s -c weights/yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu
出现如下
Traceback (most recent call last):
  File "/home/dell/projects/Megvii_YOLOX/YOLOX-main/tools/demo.py", line 14, in <module>
    from yolox.data.data_augment import ValTransform
ModuleNotFoundError: No module named 'yolox'
求助解决，先行感谢啦

**Comment by Saucerman7** [comment]
请问这个问题最后是怎么解决的啊
