### ISSUE TITLE
Turn off Anchor Free in Training

### ISSUE THREAD

**Issue by AI-Passionner** [Megvii-BaseDetection/YOLOX#1319]
@FateScript 
I have a quick question. Is there an option to turn off the anchor-free?
I looked at the prediction on my document (image) data. Usually, objects are well separated but paired. It shows some patterns for the poor performance 
1. used to miss the object inside the big object
2. used to miss empty objects (no content inside the bounding box)

I am wondering if the anchor-free approach might not help in my case. 

Thanks.

**Comment by FateScript** [comment]
YOLOX is anchor free model, so it's impossisble to use anchor-based model(unless you write a new model in `get_model`).
