### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by LiJinrun** [Megvii-BaseDetection/YOLOX#132]
demo.py  
![image](https://user-images.githubusercontent.com/49092533/126896844-99b8fec0-c9e5-445d-a40e-6abdb44f1628.png)
这里应该改成self.conf_vis=conf_vis吧

**Comment by Joker316701882** [comment]
@LiJinrun please pull our latest branch and try it again.

**Comment by FateScript** [comment]
This typo is fixed now.
