### ISSUE TITLE
AttributeError: module 'yolox.layers.fast_cocoeval' has no attribute 'InstanceAnnotation'

### ISSUE THREAD

**Issue by Finorita** [Megvii-BaseDetection/YOLOX#1327]
I run under the windows 
![image](https://user-images.githubusercontent.com/105027890/169032850-709fae11-1ac2-4ca0-998a-f4a653718c11.png)

**Comment by zoufangyu1987** [comment]
我也遇到同樣的问题，怎么解决 ？

**Comment by Finorita** [comment]
我可以确定的是在ubuntu环境下跑就没问题，在windows下我也不知道，唉。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 下午3:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Megvii-BaseDetection/YOLOX] AttributeError: module &#39;yolox.layers.fast_cocoeval&#39; has no attribute &#39;InstanceAnnotation&#39; (Issue #1327)





 
我也遇到同樣的问题，怎么解决 ？

**Comment by zoufangyu1987** [comment]
是不是缺库，python转cpp相关的

**Comment by Finorita** [comment]
是的！！！！！但是不知道怎么处理！也不知道下载什么对应的才合适。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月19日(星期四) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Megvii-BaseDetection/YOLOX] AttributeError: module &#39;yolox.layers.fast_cocoeval&#39; has no attribute &#39;InstanceAnnotation&#39; (Issue #1327)





 
是不是缺库，python转cpp相关的

**Comment by zoufangyu1987** [comment]
我把代码强制改为用coco库，不去搞了，如下：
coco_evaluator.py文件的276行改为如下
            try:
                #from yolox.layers import COCOeval_opt as COCOeval    ######
                from pycocotools.cocoeval import COCOeval
            except ImportError:
                from pycocotools.cocoeval import COCOeval
