### ISSUE TITLE
A problem about IOU threshold 

### ISSUE THREAD

**Issue by TANKCHENG** [Megvii-BaseDetection/YOLOX#1340]
In NMS filtering algorithm, IOU threshold is usually set, but in `demo_utils.py/multiclass_nms` . Is there have some optimized?
In addition, what about  trying soft NMS?
-- Loyal fans from yolox

**Comment by FateScript** [comment]
In my opinion, which nms method your are using is not that matters, it only brings a slightly improvements. 
However, if you tune the threshold in nms, your output demo might be better(it's not really exciting to me).

**Comment by TANKCHENG** [comment]
>

**Comment by TANKCHENG** [comment]
Thanks for your reply !
