### ISSUE TITLE
请教一下PR曲线这样波动会是什么原因

### ISSUE THREAD

**Issue by wanyne-yyds** [Megvii-BaseDetection/YOLOX#1344]
![{20{KJDTRYA4A){AQSZ XS7](https://user-images.githubusercontent.com/43132407/170200006-75e5f777-1e23-4a72-b6b9-48eb1a4a0dac.png)

**Comment by Msunshineboy** [comment]
你好这个图你是怎么画的

**Comment by wanyne-yyds** [comment]
> 你好这个图你是怎么画的

Object-Detection-Metrics
