### ISSUE TITLE
issue about writing to tensorborad

### ISSUE THREAD

**Issue by xxa783** [Megvii-BaseDetection/YOLOX#1354]
> > > > > 是的，可以写到里面，写的时候注明一下mAP增长是因为关闭了mosaic。 ![image](https://user-images.githubusercontent.com/43342212/161971627-5a850ca0-5007-43cd-85cc-7f1e6f3a13fb.png) 另外这个图，蓝色和橙色的mAP在关闭mosaic还在持续增长阶段，你这缩短epoch实验似乎有点不严谨，你这个模型的epoch设置大概在100到120之间
> > > > 
> > > > 
> > > > 噢噢好的，能看看取出loss那边的代码吗，做了怎么样的修改拿到的 ![image](https://user-images.githubusercontent.com/79397109/161972359-0c27b1ff-e76f-4471-80d4-238c38276fc1.png)
> > > 
> > > 
> > > 用字典写，返回值从字典里取出来 `loss_dict = {} for k, v in loss_meter.items(): loss_dict.update({k: v.latest}) return loss_dict["字典的key"],loss_dict["字典的key"]` 应该是这么写，我还没测试
> > 
> > 
> > 好的谢谢哈，我学习下
> 
> 我今天看了一下 关于取出loss的东西，不用看我之前的那个没测试的版本，我今天测试了下发现并不好用，我写了个测试过的，loss在train_one_iter方法中的outputs中。这里是个粗略的测试过的 在train_one_iter方法结尾写上： ![image](https://user-images.githubusercontent.com/43342212/162204243-9edd0c09-a5ab-40f2-b84e-5ef6603f3ff4.png) 然后在train_in_iter中这么写： ![image](https://user-images.githubusercontent.com/43342212/162204367-0c1c5ddc-b1a1-4e91-87a4-90c207360d23.png) 最终tensorboard中显示为： ![image](https://user-images.githubusercontent.com/43342212/162204081-ad2dd191-00cd-48ed-9a06-7ad23c468766.png)

噢噢，昨天试了下还是没有学会哈哈哈哈哈，今天你发的这个我再试试，万分感谢

_Originally posted by @xmayyy in https://github.com/Megvii-BaseDetection/YOLOX/issues/1213#issuecomment-1091867532_

**Comment by FateScript** [comment]
Yes, you could use tensorboard to monitor your loss.
