### ISSUE TITLE
learning rate setting

### ISSUE THREAD

**Issue by deep-practice** [Megvii-BaseDetection/YOLOX#138]
If batchsize is 16 for one gpu,should I change the base lr?

**Comment by Joker316701882** [comment]
@deep-practice We have taken care of the LR for you. No need to modify the learning rate at any batch size. Please refer to 

https://github.com/Megvii-BaseDetection/YOLOX/blob/ce7d75497956c6c2544e352eda36f0173a917989/yolox/exp/yolox_base.py#L46

and

https://github.com/Megvii-BaseDetection/YOLOX/blob/96b74a504f183801dc4831931930b821fbe9d95d/yolox/core/trainer.py#L155

**Comment by deep-practice** [comment]
I see.Thx.

**Comment by FateScript** [comment]
> @Joker316701882 Should the 64 stay hardcoded or be adjusted?

You could adjust it. It's just per image learning rate.

**Comment by vionwinnie** [comment]
@FateScript Thanks for answering the previous questions. Is there a max_lr in the config? I tried looking around but didn't see anything.
