### ISSUE TITLE
Does all_reduce_norm before validation impact training?

### ISSUE THREAD

**Issue by gathierry** [Megvii-BaseDetection/YOLOX#1381]
I see `all_reduce_norm` is performed before evaluating (every 10 epochs) in which all BNs are synced by reduce_mean.
So when the training resumes after evaluation, are the `running_mean` and `running_var` starts to update from the synced value?

**Comment by FateScript** [comment]
Yes, the status will be broadcasted if you resume training after evaluation.

**Comment by gathierry** [comment]
So evaluation frequency difference (10 epochs vs 2 epochs for example) might change the final training result?

**Comment by FateScript** [comment]
In my opinion, shorten the frequency of applying all reduce norm could make your model converge faster, but it might not effect(or slightly effet) the final result .

**Comment by gathierry** [comment]
Thanks for the explanation.
I just feel that evaluation frequency should be a hyperparameter independent of the training process. But technically, I agree that it won't have a significant effect on the result.
