### ISSUE TITLE
未来有可能加入在预训练模型上finetune的训练方式吗

### ISSUE THREAD

**Issue by kisaragychihaya** [Megvii-BaseDetection/YOLOX#1386]
在RTX3080上面训练6000张图得8个小时。。。在yolov5上通过finetune预训练模型 半小时就能得到一个可以用的模型了，如果能加入finetune训练的话应该训练也能快不少吧

**Comment by Finorita** [comment]
这个是可以fine tuning，可以看freeze部分的内容（在code那里提供了模块），但是它的fine tuning是指重新训练decoder的。

**Comment by Finorita** [comment]
这个是可以fine tuning，可以看freeze部分的内容（在code那里提供了模块），但是它的fine tuning是指重新训练decoder的。
