### ISSUE TITLE
torchscript problem

### ISSUE THREAD

**Issue by sweatyl** [Megvii-BaseDetection/YOLOX#1387]
当我使用c++部署yolo x时，出现what :istuple();expecrted tuple but got tensor

**Comment by xxr11** [comment]
> 当我使用c++部署yolo x时，出现what :istuple();expecrted tuple but got tensor

你好，请问你有部署成功吗 我可以成功运行检测结果却不正确 保存为torchscript重新load是可以的 请问是有什么不支持的op吗
