### ISSUE TITLE
是否有加入旋转目标检测的计划

### ISSUE THREAD

**Issue by zgsxwsdxg** [Megvii-BaseDetection/YOLOX#1389]
首先，感谢cv同仁的辛苦工作与无私奉献，我觉得在实际场景中旋转目标也偏多，是否后续有基于yolox实现旋转目标检测的计划，谢谢

**Comment by FateScript** [comment]
Sorry that we don't have such a plan for detecting rotate object in official yolox. However, we encourage users to try it themselves and share code with the community.
