### ISSUE TITLE
RuntimeError: [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: ib0

### ISSUE THREAD

**Issue by oliverwxg** [Megvii-BaseDetection/YOLOX#139]
i ran the project with two v100 gpu.and error happened.

  File "/hdd2/wangxg/YOLOX-main/yolox/core/trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fe4f79e99e0>
    └ <yolox.core.trainer.Trainer object at 0x7fe5075e7790>

  File "/hdd2/wangxg/YOLOX-main/yolox/core/trainer.py", line 80, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7fe4f61803b0>
    └ <yolox.core.trainer.Trainer object at 0x7fe5075e7790>

  File "/hdd2/wangxg/YOLOX-main/yolox/core/trainer.py", line 209, in after_epoch
    all_reduce_norm(self.model)
    │               │    └ DistributedDataParallel(
    │               │        (module): YOLOX(
    │               │          (backbone): YOLOPAFPN(
    │               │            (backbone): CSPDarknet(
    │               │              (stem): Focus(
    │               │       ...
    │               └ <yolox.core.trainer.Trainer object at 0x7fe5075e7790>
    └ <function all_reduce_norm at 0x7fe50707d680>

  File "/hdd2/wangxg/YOLOX-main/yolox/utils/allreduce_norm.py", line 99, in all_reduce_norm
    states = all_reduce(states, op="mean")
             │          └ OrderedDict([('module.backbone.backbone.stem.conv.bn.weight', tensor([1.0018, 0.9815, 1.0007, 1.1823, 0.9813, 0.9801, 1.0103,...
             └ <function all_reduce at 0x7fe50707d5f0>

  File "/hdd2/wangxg/YOLOX-main/yolox/utils/allreduce_norm.py", line 68, in all_reduce
    group = _get_global_gloo_group()
            └ <functools._lru_cache_wrapper object at 0x7fe50706c730>

  File "/hdd2/wangxg/YOLOX-main/yolox/utils/dist.py", line 103, in _get_global_gloo_group
    return dist.new_group(backend="gloo")
           │    └ <function new_group at 0x7fe5078b2ef0>
           └ <module 'torch.distributed' from '/hdd2/wangxg/anaconda3/envs/py37-torch18/lib/python3.7/site-packages/torch/distributed/__in...

  File "/hdd2/wangxg/anaconda3/envs/py37-torch18/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2508, in new_group
    timeout=timeout)
            └ datetime.timedelta(seconds=1800)
  File "/hdd2/wangxg/anaconda3/envs/py37-torch18/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 592, in _new_process_group_helper
    timeout=timeout)
            └ datetime.timedelta(seconds=1800)

RuntimeError: [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: ib0

anybody has idea?

**Comment by shaoming20798** [comment]
I meet the same error! Is it a bug?

**Comment by oliverwxg** [comment]
the code is well when running with one gpu.i think the gloo has wrong config .it wanted to find the interface "ibo"

**Comment by daibin88** [comment]
This is a bug for the code,you can change 'yolox/utils/setup_env.py' def 
def configure_nccl():
  os.environ[]='lo'
  os.environ[]='lo'

the new yolox project code is change https://github1s.com/Megvii-BaseDetection/YOLOX/blob/HEAD/yolox/utils/setup_env.py#L15-L19

**Comment by oliverwxg** [comment]
excellent! i have changed my code as 👍 
     os.environ["NCCL_SOCKET_IFNAME"]='lo'
     os.environ["GLOO_SOCKET_IFNAME"]='lo'
waiting for the result...

**Comment by oliverwxg** [comment]
the bug is fixed .thanks a lot !!!!
