### ISSUE TITLE
How to detect only a subset of COCO Classes?

### ISSUE THREAD

**Issue by kevinvlowell** [Megvii-BaseDetection/YOLOX#1391]
Hi everyone,

I’m a bit new to computer vision, but is there a way to get the model to only detect the ‘person’ and ‘boat’ classes from the COCO dataset instead of all 80 classes? 

Would this also improve the speed of detection? Thanks!

**Comment by Leopold80** [comment]
I think you can delete other classifications you don't want.
so you can try by this way:

# add behind the output detections
keep = [outputs[:, 6] == c for c in [0, 1, 2,]]  # [0, 1, 2,]: classifications you want to detect
outputs = outputs[functools.reduce(lambda a, b: a | b, keep, True)]

it is equivalent to:
keep = (outputs[:, 6] == 0) | (outputs[:, 6] == 1) | (outputs[:, 6] == 2)
outputs = outputs[keep]

大概就是这个意思，筛选分类的索引，只保留你想要的

**Comment by zoldaten** [comment]
put in demo.py here:
```
from functools import reduce
...
def visual(self, output, img_info, cls_conf=0.35):
        ratio = img_info["ratio"]
        img = img_info["raw_img"]
        if output is None:
            return img
        output = output.cpu()        
        #keep = (output[:, 6] == 0) | (output[:, 6] == 1) | (output[:, 6] == 16)
        #output = output[keep]
        keep = [output[:, 6] == c for c in [1,2,16]] # [1, 2, 16]: classifications you want to detect        
        output = output[reduce(lambda a, b: a | b, keep, False)]

```
and reduce should have (False)

**Comment by Leopold80** [comment]
> 

Thanks, a little mistake on reduce

**Comment by kevinvlowell** [comment]
Thank you both for the suggestions! I wound up doing something similar by adding "cls_id not in [0, 8]" to the conditional in the vis function called within the demo (function found in visualize.py):

`def vis(img, boxes, scores, cls_ids, conf=0.5, class_names=None):

    for i in range(len(boxes)):
        box = boxes[i]
        cls_id = int(cls_ids[i])
        score = scores[i]
        if score < conf or cls_id not in [0, 8]:
            continue
        x0 = int(box[0])
        y0 = int(box[1])
        x1 = int(box[2])
        y1 = int(box[3])`

**Comment by rahuja23** [comment]
Hi I have a similar issue. I am trying to detect only 3 classes (which are not in coco at all) but it is detecting stuff with tag "Person" (which is not one of the classes). So I wanted to know how and where we can give class names?

**Comment by zoldaten** [comment]
check YOLOX-main\yolox\data\datasets\coco_classes.py

**Comment by rahuja23** [comment]
Thanks a lot! Can you also tell me how to make the model print avg_precision and avg_recall after each step of evaluation?
