### ISSUE TITLE
Variable names in Focus Layer

### ISSUE THREAD

**Issue by developer0hye** [Megvii-BaseDetection/YOLOX#14]
Thanks for sharing your work!

https://github.com/Megvii-BaseDetection/YOLOX/blob/f281865af2f0cdf5ff113304f804bf430c4485ca/yolox/models/network_blocks.py#L167-L170

I think that these variable names can cause misunderstanding. The results of indexing tensors are not top-left, top-right, bot-left, and bot-right patches. Its indexing method is related to indexing values whose index(x or y) is **odd or even number**.

It's hard to name these values... I tried to think about best name for these variables, but I failed.

```python
 tensor_even_y_even_x = x[..., ::2, ::2] 
 tensor_even_y_odd_x = x[..., ::2, 1::2] 
 tensor_odd_y_even_x = x[..., 1::2, ::2] 
 tensor_odd_y_odd_x = x[..., 1::2, 1::2] 
```

**Comment by FateScript** [comment]
Hello, consider a 4x4 matrix:
```shell
1, 2, 1, 2,
3, 4, 3, 4,
1, 2, 1, 2,
3, 4, 3, 4,
```
All 1 value are top left if you treat 2x2 area as a small patch, and it's easier for readers to understand what it means.
Maybe we should add this to document?

**Comment by developer0hye** [comment]
Good example! But if we just think about the meaning of variable name, I think someone can think like the below example.

x is
```
1, 1, 2, 2,
1, 1, 2, 2,
3, 3, 4, 4,
3, 3, 4, 4,
```
.
patch_top_left is

```
1, 1
1, 1
```
.
But actually patch_top_left is

```
1, 2
3, 4
```

**Comment by Joker316701882** [comment]
@developer0hye Hi, thank you for your suggestion. I think one can figure out what do the variables mean by reading the code. Hence this issue is closed.
