### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Xwmiss** [Megvii-BaseDetection/YOLOX#140]
When I set YOLOX in a new computer and start train, get the issue:

2021-07-26 09:44:07.773 | ERROR    | yolox.core.launch:launch:68 - An error has been caught in function 'launch', process 'MainProcess' (8165), thread 'MainThread' (140713275706240):
Traceback (most recent call last):

  File "/project/YOLOX/tools/train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
             │               │    └ Namespace(batch_size=16, ckpt='/project/YOLOX/yolox_s.pth.tar', devices=1, dist_backend='nccl', dist_url=None, exp_file=None,...
             │               └ 
             └ 'auto'

> File "/project/YOLOX/yolox/core/launch.py", line 68, in launch
    main_func(*args)
    │          └ 
    └ <function main at 0x7ff9f60527b8>

  File "/project/YOLOX/tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7ff9e8a550d0>
    └ <yolox.core.trainer.Trainer object at 0x7ff9f60557f0>

  File "/project/YOLOX/yolox/core/trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7ffa0864f2f0>
    └ <yolox.core.trainer.Trainer object at 0x7ff9f60557f0>

  File "/project/YOLOX/yolox/core/trainer.py", line 80, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7ffa0865c950>
    └ <yolox.core.trainer.Trainer object at 0x7ff9f60557f0>

  File "/project/YOLOX/yolox/core/trainer.py", line 210, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7ffa0865cbf8>
    └ <yolox.core.trainer.Trainer object at 0x7ff9f60557f0>

  File "/project/YOLOX/yolox/core/trainer.py", line 293, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(evalmodel, self.evaluator, self.is_distributed)
                             │    │   │    │          │    │          │    └ False
                             │    │   │    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7ff9f60557f0>
                             │    │   │    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff9e0158d68>
                             │    │   │    │          └ <yolox.core.trainer.Trainer object at 0x7ff9f60557f0>
                             │    │   │    └ YOLOX(
                             │    │   │        (backbone): YOLOPAFPN(
                             │    │   │          (backbone): CSPDarknet(
                             │    │   │            (stem): Focus(
                             │    │   │              (conv): BaseConv(
                             │    │   │                (conv): ...
                             │    │   └ <function Exp.eval at 0x7ff9f6052d08>
                             │    └ 
                             └ <yolox.core.trainer.Trainer object at 0x7ff9f60557f0>

  File "/project/YOLOX/yolox/exp/yolox_base.py", line 250, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7ffa0864f9d8>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff9e0158d68>

  File "/project/YOLOX/yolox/evaluators/coco_evaluator.py", line 131, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([0., 0., 0.], device='cuda:0')
                   │    │                   └ [{'image_id': 92, 'category_id': 1, 'bbox': [864.0, 318.1875, 700.5, 419.8125], 'score': 0.9176738262176514, 'segmentation': ...
                   │    └ <function COCOEvaluator.evaluate_prediction at 0x7ffa0864fae8>
                   └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff9e0158d68>

  File "/project/YOLOX/yolox/evaluators/coco_evaluator.py", line 179, in evaluate_prediction
    a_infer_time = 1000 * inference_time / (n_samples * self.dataloader.batch_size)
                          │                 │           │    │          └ 16
                          │                 │           │    └ <torch.utils.data.dataloader.DataLoader object at 0x7ff9e01584e0>
                          │                 │           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7ff9e0158d68>
                          │                 └ 0.0
                          └ 0.0

ZeroDivisionError: float division by zero

maybe my val dataset is too small?

**Comment by ruinmessi** [comment]
I think so.... you may change "1000 * inference_time / (n_samples * self.dataloader.batch_size)" to "1000 * inference_time / max(1, n_samples * self.dataloader.batch_size)"

**Comment by ShuShuai163** [comment]
I ran into the same problem, I solved it because my xml file wight and height are 0, this is because there was a problem when converting png images into jpg files, two solutions, one is to pick out the problem xml file, the other is to resize when converting
