### ISSUE TITLE
怎么在自有数据集上评估？

### ISSUE THREAD

**Issue by raymondchu-z** [Megvii-BaseDetection/YOLOX#141]
命令`python tools/eval.py -n  yolox-s -c yolox_s.pth.tar -b 64 -d 8 --conf 0.001 [--fp16] [--fuse]`是默认在coco数据集上评估，怎么在自有数据集上评估？

**Comment by ruinmessi** [comment]
可以参看exps/example里对VOC数据集的实现。新建一个yolox_s_myown.py的实验文件，继承原来的yolox_s.py，然后重写你的数据部分，包括读取和评估

**Comment by Xiang99** [comment]
> 命令`python tools/eval.py -n yolox-s -c yolox_s.pth.tar -b 64 -d 8 --conf 0.001 [--fp16] [--fuse]`是默认在coco数据集上评估，怎么在自有数据集上评估？
请问你训练好的权重文件在哪儿，我没看到我训练好的权重文件

**Comment by Xiang99** [comment]
> 可以参看exps/example里对VOC数据集的实现。新建一个yolox_s_myown.py的实验文件，继承原来的yolox_s.py，然后重写你的数据部分，包括读取和评估

你好，可以参考一下你的吗

**Comment by raymondchu-z** [comment]
> 可以参看exps/example里对VOC数据集的实现。新建一个yolox_s_myown.py的实验文件，继承原来的yolox_s.py，然后重写你的数据部分，包括读取和评估

现在在写评估的部分，实验文件里的`get_evaluator()`明明写的是自己的evaluator，为什么还会
