### ISSUE TITLE
TypeError: evaluate() got an unexpected keyword argument 'return_outputs'

### ISSUE THREAD

**Issue by realkris** [Megvii-BaseDetection/YOLOX#1412]
if you meet this problem while training on your own dataset, this is due to PR #1181, the simplest way to solve it is to modify the code in YOLOX/yolox/exp/yolox_base.py, change the function eval() at the end of the script to:

    def eval(self, model, evaluator, is_distributed, half=False):
        return evaluator.evaluate(model, is_distributed, half)

it will works.

----------------------------------------------------------------------------
raw log:

2022-06-30 17:32:19 | INFO     | yolox.core.trainer:356 - Save weights to ./YOLOX_outputs/yolox_voc_s
2022-06-30 17:32:22 | INFO     | yolox.core.trainer:196 - Training of experiment is done and the best AP is 0.00
2022-06-30 17:32:22 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (31336), thread 'MainThread' (139816351606592):
Traceback (most recent call last):

  File "tools/train.py", line 141, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=4, cache=False, ckpt='pretrained/yolox_x.pth', devices=None, dist_backend='nccl', dist_url=None, exp_fil...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/media/realkris/WD_NVME_DATA/VIVA/3D/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f27f9e07e18>

  File "tools/train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f2897a11e18>
    └ <yolox.core.trainer.Trainer object at 0x7f289798eef0>

  File "/media/realkris/WD_NVME_DATA/VIVA/3D/YOLOX/yolox/core/trainer.py", line 76, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f2897a156a8>
    └ <yolox.core.trainer.Trainer object at 0x7f289798eef0>

  File "/media/realkris/WD_NVME_DATA/VIVA/3D/YOLOX/yolox/core/trainer.py", line 86, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7f2897a159d8>
    └ <yolox.core.trainer.Trainer object at 0x7f289798eef0>

  File "/media/realkris/WD_NVME_DATA/VIVA/3D/YOLOX/yolox/core/trainer.py", line 222, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7f2897a15c80>
    └ <yolox.core.trainer.Trainer object at 0x7f289798eef0>

  File "/media/realkris/WD_NVME_DATA/VIVA/3D/YOLOX/yolox/core/trainer.py", line 329, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed, return_outputs=True
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7f289798eef0>
    │          │    └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x7f27aed47128>
    │          └ <yolox.core.trainer.Trainer object at 0x7f289798eef0>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/media/realkris/WD_NVME_DATA/VIVA/3D/YOLOX/yolox/exp/yolox_base.py", line 322, in eval
    return evaluator.evaluate(model, is_distributed, half, return_outputs=return_outputs)
           │         │        │      │               │                    └ True
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x7f2897a0b7b8>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x7f27aed47128>

TypeError: evaluate() got an unexpected keyword argument 'return_outputs'

**Comment by tan90du-sx** [comment]
Hello, I also encountered this problem, and it has been solved by your method, thank you very much. But after thinking about it carefully, it is still unclear why the problem is encountered, whether the parameter format is different due to the replacement of the data set, or other reasons that prevent him from generating the wandb graph. Looking forward to your reply.

**Comment by manangoel99** [comment]
@realkris @tan90du-sx this issue has been fixed in #1525
