### ISSUE TITLE
Why using swap=(2, 0, 1) in preproc??? 

### ISSUE THREAD

**Issue by ZXYFrank** [Megvii-BaseDetection/YOLOX#1425]
[this line](https://github.com/Megvii-BaseDetection/YOLOX/blob/ce4b996917b6f6983247c90c933759896c04091c/yolox/data/data_augment.py#L142)

😱 I really cannot figure out why we should swap the channels here. It has incurred some 
 deeply-hidden mistakes in the main program which use dataloader defined by YOLOX.

![image](https://user-images.githubusercontent.com/49837632/177565965-eebdeafd-29a5-4e62-aa92-3836d2f7abdc.png)

```python
padded_img = padded_img.transpose(swap)
```

I want to know why. 🤔 The necessity or purpose of doing this. A lot of thanks.

**Comment by ZXYFrank** [comment]
Someone told me that there are some other project also swapping dimensions.

**Comment by FateScript** [comment]
It's channel first format(C, H, w).
