### ISSUE TITLE
about custom dataset 

### ISSUE THREAD

**Issue by cena001plus** [Megvii-BaseDetection/YOLOX#143]
I have run the training of the voc data set, and now I want to train my own data, the data annotation format is xml, I want to know, how many places need to be changed in the program? thanks.

**Comment by cena001plus** [comment]
> I have run the training of the voc data set, and now I want to train my own data, the data annotation format is xml, I want to know, how many places need to be changed in the program? thanks.

That is how to train on your own data set

**Comment by daibin88** [comment]
> I have run the training of the voc data set, and now I want to train my own data, the data annotation format is xml, I want to know, how many places need to be changed in the program? thanks.

Hi You can read https://blog.csdn.net/happyday_d/article/details/119105851

**Comment by cena001plus** [comment]
> > I have run the training of the voc data set, and now I want to train my own data, the data annotation format is xml, I want to know, how many places need to be changed in the program? thanks.
> 
> Hi You can read https://blog.csdn.net/happyday_d/article/details/119105851

This method is a little bit weird, but thank you

**Comment by cena001plus** [comment]
> > I have run the training of the voc data set, and now I want to train my own data, the data annotation format is xml, I want to know, how many places need to be changed in the program? thanks.
> 
> Hi You can read https://blog.csdn.net/happyday_d/article/details/119105851



Is there something wrong? The folder should contain: trainval.txt, train.txt test.txt

**Comment by wawaa** [comment]
I have the same problem.

**Comment by ImSuMyatNoe** [comment]
@cena001plus Have you found out how to train ur custom dataset? If so, please let me know. I have also faced difficulties in this.

**Comment by cena001plus** [comment]
> @cena001plus Have you found out how to train ur custom dataset? If so, please let me know. I have also faced difficulties in this.

[https://blog.csdn.net/weixin_42166222/article/details/119637797](url)
