### ISSUE TITLE
关于git不能使用问题

### ISSUE THREAD

**Issue by zcswdt** [Megvii-BaseDetection/YOLOX#144]
您好，我的电脑不能使用git这个命令，请问您的如下安装命令可以换一种安装方法吗？这个git+的命令我不会修改，谢谢。pip3 install cython; pip3 install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

**Comment by FAFUzxf** [comment]
l have this problem,too.l want use YOLOX to train myown dataset.  So l can uninstall pycocotools?

**Comment by lyyiangang** [comment]
@zcswdt 可以尝试先下载后安装。
```bash
pip3 install cython
git clone https://github.com/cocodataset/cocoapi.git
cd PythonAPI && python3 setup install
```

**Comment by lyyiangang** [comment]
@zcswdt @FAFUzxf  我做了个dockerfile， 里面直接包含了推理使用的cocoapi, tensorrt啥的， 你可以尝试下。
[链接](https://github.com/lyyiangang/yolox-dockerfile.git)

**Comment by wangg12** [comment]
pip install pycocotools

**Comment by zcswdt** [comment]
> @zcswdt @FAFUzxf 我做了个dockerfile， 里面直接包含了推理使用的cocoapi, tensorrt啥的， 你可以尝试下。
> [链接](https://github.com/lyyiangang/yolox-dockerfile.git)

非常感谢，非常感谢。

**Comment by zcswdt** [comment]
> @zcswdt 可以尝试先下载后安装。
> 
> ```shell
> pip3 install cython
> git clone https://github.com/cocodataset/cocoapi.git
> cd PythonAPI && python3 setup install
> ```

您好，我的这个cpython也安装不了，可以帮忙看看么？
![image](https://user-images.githubusercontent.com/43515926/126949636-d8b794fd-3561-49af-a405-2367eec709de.png)

**Comment by lyyiangang** [comment]
这个提示表示已经安装好了
