### ISSUE TITLE
怎么在保留原有的yolox_s的类基础上叠加训练自己的类呢？

### ISSUE THREAD

**Issue by bennett-doris** [Megvii-BaseDetection/YOLOX#1444]
yolox_s 模型默认会有80个类，我怎么在保留这80个类的基础上，再额外训练自己的类呢？我现在每次训练完自己的数据，就无法使用原来的类去进行检测？请问yolox在这方面有支持吗？

**Comment by Zephyr69** [comment]
No DL detector supports this; it's just not how deep learning works on a single model.

The best you can do is: 1) download COCO dataset, 2) mix it up with your own dataset (while making sure it is not overwhelmed by COCO), 3) find and label the missing labels for the whole mixed dataset according to your new [80 + n] classes, 4) train from scratch.

**Comment by bennett-doris** [comment]
> No DL detector supports this; it's just not how deep learning works on a single model.
> 
> The best you can do is: 1) download COCO dataset, 2) mix it up with your own dataset (while making sure it is not overwhelmed by COCO), 3) find and label the missing labels for the whole mixed dataset according to your new [80 + n] classes, 4) train from scratch.

Thanks for your answer. I will try what you said.
