### ISSUE TITLE
cv2.waitKey(0) error

### ISSUE THREAD

**Issue by ikeijo** [Megvii-BaseDetection/YOLOX#1447]
While testing my model in some images, after it writes the first output image and json the code breaks due to this error:

2022-07-22 13:39:57.428 | INFO     | __main__:image_demo:191 - Saving detection result in /content/gdrive/MyDrive/hub/checkpoints/yolox_voc_s/vis_res/2022_07_22_13_39_54/1157.jpg
Traceback (most recent call last):
  File "tools/demo.py", line 304, in <module>
    main(exp, args)
  File "tools/demo.py", line 295, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
  File "tools/demo.py", line 198, in image_demo
    ch = cv2.waitKey(0)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/highgui/src/window.cpp:717: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'

How can I solve this? I'm trying to look for a solution but with no success for now

**Comment by ikeijo** [comment]
I tried downgrading it to a bunch of different versions, the one that worked for me was opencv-python==4.5.1,48

**Comment by dstkibrom** [comment]
> I tried downgrading it to a bunch of different versions, the one that worked for me was opencv-python==4.5.1,48

This worked for me as well. 
pip install opencv-python==4.5.1.48
