### ISSUE TITLE
About Positive Sample Matching？

### ISSUE THREAD

**Issue by KangGrandesty** [Megvii-BaseDetection/YOLOX#145]
I read your code, in `yolo_head.py` [line 508](https://github.com/Megvii-BaseDetection/YOLOX/blob/96b74a504f183801dc4831931930b821fbe9d95d/yolox/models/yolo_head.py#L508)
```python
        n_candidate_k = 10
        topk_ious, _ = torch.topk(ious_in_boxes_matrix, n_candidate_k, dim=1)
        dynamic_ks = torch.clamp(topk_ious.sum(1).int(), min=1)
        for gt_idx in range(num_gt):
            _, pos_idx = torch.topk(
                cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False
            )
            matching_matrix[gt_idx][pos_idx] = 1.0
```
In this code, if `cost[gt_idx, pos_idx[-1]] > 100000.0`, the anchor was assigned as a positive sample.

What I mean is that if `cost[gt_idx, pos_idx[-1]] > 100000.0`, the anchor must be either not in box or not in center, or both.

Is this try to assign a positive sample for all gt boxes?

**Comment by Joker316701882** [comment]
@KangGrandesty I think you misunderstand our code.  Any anchor-gt pair whose `cost[gt_idx, pos_idx[-1]] > 100000.0`, its anchor is a negative sample.

**Comment by KangGrandesty** [comment]
In code [line 404](https://github.com/Megvii-BaseDetection/YOLOX/blob/96b74a504f183801dc4831931930b821fbe9d95d/yolox/models/yolo_head.py#L404):
```python
        cost = (
            pair_wise_cls_loss
            + 3.0 * pair_wise_ious_loss
            + 100000.0 * (~is_in_boxes_and_center)
        )
```
If `cost < 100000.0`, the center of anchor must be in box and in center of box.

But, `dynamic_ks[i]` is the sum of the top-n-iou in all iou between ith gt boxes and predictions.

If `dynamic_ks[i] > is_in_boxes_and_center.sum(1)[i]`, it must exist the positive anchor with `cost > 100000.0`.

It is not a rigorous inference `all(dynamic_ks >= is_in_boxes_and_center.sum(1)) is True`.
