### ISSUE TITLE
How can i use pip version?

### ISSUE THREAD

**Issue by kadirnar** [Megvii-BaseDetection/YOLOX#1452]
Hi @FateScript ,

I want to write prediction code using yolox-pip. Can you share documentation about it?

**Comment by FateScript** [comment]
Sorry, I couldn't catch your meaning of `using yolox-pip`? If you write code in yolox, and it's merged by main branch, your prediction code will be included automaticlly after a new release.

**Comment by kadirnar** [comment]
I want to do "pip install yolox" instead of "git clone" to use the Yolox library. When I do "pip install yolox", I need to know which functions are imported.

Example(Yolov5-Pip):
```
import yolov5

# load custom model
model = yolov5.load('train/best.pt')
  
# set model parameters
model.conf = 0.25  # NMS confidence threshold
model.iou = 0.45  # NMS IoU threshold
model.agnostic = False  # NMS class-agnostic
model.multi_label = False  # NMS multiple labels per box
model.max_det = 1000  # maximum number of detections per image

# set image
img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'

# perform inference
results = model(img)
```
Repo Link: https://github.com/fcakyon/yolov5-pip

**Comment by kadirnar** [comment]
Hi @FateScript ,

Error Message:
```
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects      
```
This library does not have windows support.
https://github.com/cocodataset/cocoapi/issues/9

Can you add this for windows users?
https://pypi.org/project/pycocotools-windows/

**Comment by FateScript** [comment]
@kadirnar All method could be found in [`__init__.py`](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/__init__.py), for YOLOX, no method is imported when `import yolox`; For yolov5 that you metioned, it could be found [here](https://github.com/fcakyon/yolov5-pip/blob/main/yolov5/__init__.py). 

As for cocoapi, did you check the windows version?
