### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kwonseungsang** [Megvii-BaseDetection/YOLOX#1463]
![image](https://user-images.githubusercontent.com/65503324/182544137-5000b117-e9d9-4aff-b4f3-74a427d11cfc.png)

**Comment by happyhoo97** [comment]
I had same problem. Did you  solve the problem?

**Comment by OValery16** [comment]
I have seen this problem many times of this repo, and I spent a lot of time to figure it out what is wrong. 

The solution is very simple. The number of output classes has not been defined correctly, which results in an out of range list index.

https://github.com/Megvii-BaseDetection/YOLOX/blob/f0de34d54b5c5ca331e9bc975ef3787063c477fe/exps/example/custom/nano.py#L29

I hope this post will help you.
