### ISSUE TITLE
Evaluation returns all -1

### ISSUE THREAD

**Issue by masc-it** [Megvii-BaseDetection/YOLOX#1465]
Hi, during evaluation I get all -1s as you can see in the screenshot below. Training seems fine, all loss are below 0.9. What am I missing?

![image](https://user-images.githubusercontent.com/40116397/183248285-9018a2aa-9b9a-4a42-9be0-335732d12a89.png)

**Comment by Kangzf1996** [comment]
I met the same problem, do you know how to solve it?

**Comment by masc-it** [comment]
> I met the same problem, do you know how to solve it?

In my case I just had to double check and fix annotations in my validation set, since they were screwed up.

**Comment by Kangzf1996** [comment]
> > I met the same problem, do you know how to solve it?
> 
> In my case I just had to double check and fix annotations in my validation set, since they were screwed up.

Thank you for your reply. Actually, the problem in my case was also annotations.
