### ISSUE TITLE
How to output a graph of the training process?

### ISSUE THREAD

**Issue by kiterano** [Megvii-BaseDetection/YOLOX#1470]
I ran the training with the following commands:
```
python tools/train.py -f yolox_s.py -d 1 -b 8 --fp16 -o -c yolox_s.pth --cache
```
However, it does not output a graph of the training process as shown in the following image.
![image](https://user-images.githubusercontent.com/88527218/183555066-49b125aa-6feb-472e-bd0c-1f42bd07af83.png)

This image was taken from the following URL.
https://github.com/Megvii-BaseDetection/YOLOX/issues/892
https://github.com/Megvii-BaseDetection/YOLOX/issues/1006

How to output such an image?

**Comment by FateScript** [comment]
Such graph is output in Tensorboard. The summary is in your output dir by default.

**Comment by kiterano** [comment]
Thank you for your reply. I was able to get TensorBoard up and running and display the graph!

![image](https://user-images.githubusercontent.com/88527218/183562728-d2bf312b-8289-480e-b815-e998691f60c8.png)
