### ISSUE TITLE
Problem with MegEngine

### ISSUE THREAD

**Issue by LamnouarMohamed** [Megvii-BaseDetection/YOLOX#1488]
hi everyone,

Thank you so much for sharing this repository 
anyone solved this problem before

when we run the demo after prepare the megengine environment 
WRN NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current MegEngine installation. The current MegEngine install supports CUDA capabilities sm_52 sm_60 sm_61 sm_70 sm_75. If you want to use the NVIDIA GeForce RTX 3080 Ti with MegEngine, please check the instructions at https://github.com/MegEngine/MegEngine/blob/master/scripts/cmake-build/BUILD_README.md

**Comment by LamnouarMohamed** [comment]
I have followed all step in github link above but not yet solved the problem

**Comment by xxr3376** [comment]
@LamnouarMohamed Please provide more detail about the problem of buliding your own MegEngine package.
