### ISSUE TITLE
YOLOX input images are RGB or BGR?

### ISSUE THREAD

**Issue by nahidalam** [Megvii-BaseDetection/YOLOX#1492]
I am a bit confused whether YOLOX input images are RGB or BGR for training. Can you point me to the code? The [TrainTransform](https://github.com/Megvii-BaseDetection/YOLOX/blob/48fd2a95837a92e0583492210b5ebeb02a4e7d7d/yolox/data/data_augment.py#L161) class seems to indicate that the input images are converted to hsv which is a rearrangement of RGB?

Can you please clarify?

**Comment by FateScript** [comment]
@nahidalam  Thank you for pointing out the bug in `augment_hsv` function.
`cv2` is used in YOLOX, and `cv2.imread` return an BGR image by default.

I think this bug might not affect the performance of YOLOX and I will try to rerun my experiments of YOLOX after fixing it.

**Comment by nahidalam** [comment]
@FateScript so you are saying YOLOX is trained on `BGR` images? I was looking into [OpenVino](https://docs.openvino.ai/latest/omz_models_model_yolox_tiny.html) and they say that the original YOLOX expects `RGB` input. I guess they are wrong then.

**Comment by FateScript** [comment]
@korkland  YOLOX requires `BGR` input image, and I also try `RGB` image, it doesn't effect the final performance too much. 
@nahidalam I double check the `augment_hsv` function, it's correct and bug free. OpenVino doc is mistaken if they said that origin YOLOX expects `RBG` image.

**Comment by FateScript** [comment]
Maybe we should add more docstring for our code related to data augmentation @Joker316701882 .

**Comment by bartlomiejgadzicki-digica** [comment]
Digging up this issue, because I noticed that for detecting objects that heavily correlated with colors (in my case brown cardboard boxes), switching channels order makes a **huuge** difference. Pointing this our for posterity 📦

**Comment by Fleyderer** [comment]
I find this one thing funny:

https://github.com/Megvii-BaseDetection/YOLOX/blob/f00a798c8bf59f43ab557a2f3d566afa831c8887/yolox/data/data_augment.py#L142

By default, we read cv2 image, which is BGR, then pass it either to `ValTransform` or `TrainTransform` instance, where it uses `swap=(2, 0, 1)` to transform image from BGR to GRB :exclamation: 

So answer is: it is neither RGB or BGR, it is **GRB.**
