### ISSUE TITLE
How to train YOLOX with RGB images

### ISSUE THREAD

**Issue by nahidalam** [Megvii-BaseDetection/YOLOX#1495]
Since YOLOX is trained on `BGR` images (`cv2.imread` returns a `BGR` by default), what would it take if I want to train it on `RGB` images?

I am thinking below steps:

- Since my dataset is COCO format, change the dataset read [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/48fd2a95837a92e0583492210b5ebeb02a4e7d7d/yolox/data/datasets/coco.py#L193)
- Replace `BGR` with `RGB` in `augment_hsv` function [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/48fd2a95837a92e0583492210b5ebeb02a4e7d7d/yolox/data/data_augment.py#L25) and [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/48fd2a95837a92e0583492210b5ebeb02a4e7d7d/yolox/data/data_augment.py#L31)

Anything else? @FateScript

**Comment by FateScript** [comment]
@nahidalam For a long time training, RGB and BGR doesn't matter too much. I think fix bug in `augment_hsv` could help, but fixing this might not make the result better.
