### ISSUE TITLE
How can I check whether a model is overfitting or not?

### ISSUE THREAD

**Issue by minkichunm** [Megvii-BaseDetection/YOLOX#1496]
Mean AP, map_50, map_5095 are slightly decreased after a certain epoch.
I think it happens by overfitting.
Is there any way to stop training when a model starts to overfit?

Also, does "apex.amp.handle:140 - Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0" mean overfitting?

**Comment by Joker316701882** [comment]
> Is there any way to stop training when a model starts to overfit 
Just stop the training process.

> Also, does "apex.amp.handle:140 - Gradient overflow. Skipping step, loss scaler 0 reducing loss scale to 16384.0" mean overfitting?
No.
