### ISSUE TITLE
Do I need to change max_labels?

### ISSUE THREAD

**Issue by minkichunm** [Megvii-BaseDetection/YOLOX#1497]
Let's say I'm using 200 objects.

I changed a class information in voc_classes.py or coco_classes.py

In yolo_base.py and yolo_voc_s.py

        with wait_for_the_master():
            dataset = COCODataset(
                data_dir=self.data_dir,
                json_file=self.train_ann,
                img_size=self.input_size,
                preproc=TrainTransform(
                    max_labels=50,
                    flip_prob=self.flip_prob,
                    hsv_prob=self.hsv_prob),
                cache=cache_img,
            )

        dataset = MosaicDetection(
            dataset,
            mosaic=not no_aug,
            img_size=self.input_size,
            preproc=TrainTransform(
                max_labels=120,
                flip_prob=self.flip_prob,
                hsv_prob=self.hsv_prob),
            degrees=self.degrees,
            translate=self.translate,
            mosaic_scale=self.mosaic_scale,
            mixup_scale=self.mixup_scale,
            shear=self.shear,
            enable_mixup=self.enable_mixup,
            mosaic_prob=self.mosaic_prob,
            mixup_prob=self.mixup_prob,
        )

should I need to change also max_labels in COCODataset or MosaicDetection?

**Comment by Superyanzhuang** [comment]
I also encountered this problem, I reduced amx_labels=50, but return an error

**Comment by FateScript** [comment]
It depends on the max annoation number of a single image in your dataset. If it's greater than config in YOLOX, plz set the value.
