### ISSUE TITLE
Time complexity of SimOTA (dynamic top-k)

### ISSUE THREAD

**Issue by imadr** [Megvii-BaseDetection/YOLOX#1499]
Hello,
Is it possible to know the time complexity of the SimOTA (dynamic top-k) algorithm relative to the number of boxes in the output of the model. Because the training is relatively slow and gets way faster by reducing the max_labels parameter, and it seems like the slowest part of the learning is in top-k algorithm.

Thanks in advance for your answer.

**Comment by Joker316701882** [comment]
It is probably slow because of the dataloader, not label assignment. We have greatly sped up the training process in our recent PR #1584 . Feel free to try it!
