### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox-s'

### ISSUE THREAD

**Issue by zcl912** [Megvii-BaseDetection/YOLOX#15]

**Comment by Joker316701882** [comment]
@ Hi, did you successfully install yolox?
Please open a python console and try:
`import yolox`

**Comment by zcl912** [comment]
> Hi, did you successfully install yolox?
> Please open a python console and try:
> `import yolox`

thx, i installed yolox successfully

**Comment by Joker316701882** [comment]
Can you show us a screenshot of your bug?

**Comment by zcl912** [comment]
> Can you show us a screenshot of your bug?

the error is as follow:
![914182119](https://user-images.githubusercontent.com/35416036/126293950-bf8f9654-a2fb-4318-9d81-ef112ee35d5e.jpg)

**Comment by Joker316701882** [comment]
@zcl912 Can you try to pull the latest main branch? Seems we have fixed this issue.

**Comment by zcl912** [comment]
> @zcl912 Can you try to pull the latest main branch? Seems we have fixed this issue.

yeah, i just git clone the latest project, but it doesn't work

**Comment by Joker316701882** [comment]
@zcl912 the exp file is yolox_s.py, not yolox-s.py
by the way, the total batch size suggested equals to 8 * num_gpu, you use 1 gpu, so -b 8 is better.

please try:
`python tools/train.py -f exps/default/yolox_s.py -d 1 -b 8 --fp16 -o`

**Comment by zcl912** [comment]
> on tools/train.py -f exps/default/yolox_s.py -d 1 -b 8 --fp16 -o

em, but bs is irrevelent with the error

**Comment by zcl912** [comment]
> on tools/train.py -f exps/default/yolox_s.py -d 1 -b 8 --fp16 -o

em, but bs is irrevelent with the error

**Comment by Joker316701882** [comment]
the important thing is:
yolox_s.py, but you used yolox-s.py

**Comment by Joker316701882** [comment]
And if you don't change batch-size, you will meet OOM error.

**Comment by zcl912** [comment]
> the important thing is:
> yolox_s.py, but you used yolox-s.py

yeah, thx,  i just copy the command from the readme,  and ignore the detail.
