### ISSUE TITLE
RuntimeError: Trying to resize storage that is not resizable

### ISSUE THREAD

**Issue by lzh2333** [Megvii-BaseDetection/YOLOX#1502]
The traceback info
![issue](https://user-images.githubusercontent.com/54696957/187127355-f1c2567f-d47f-4712-84de-6e60eeb8be99.png)

The root cause of this bug is the "next" function in "data_prefetcher,py"
![issue2](https://user-images.githubusercontent.com/54696957/187127482-ccf12ca8-a0fc-4a54-ad1b-13e3852928eb.png)

After training for some time, the bug occurs.

**Comment by FateScript** [comment]
[This issue](https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/237) might help.

**Comment by lzh2333** [comment]
The problem has been solved, thank you!

**Comment by ajtao** [comment]
@lzh2333 can you share how you fixed the issue? Did you find some empty label files?

**Comment by StrugglingForBetter** [comment]
> The problem has been solved, thank you!

@lzh2333  Can you show use how to solve this problem? Thanks
