### ISSUE TITLE
I cannot reproduce the 40.5 AP on yolox-s

### ISSUE THREAD

**Issue by slacklife** [Megvii-BaseDetection/YOLOX#1511]
I cannot reproduce the 40.5 AP with the command below
```
python -m yolox.tools.train -n yolox-s -d 8 -b 128 --fp16 -o --cache
```
I already use the batchsize=128 as shown above.
There are no other modifications

I got the best AP is 37.34.

Can anyone reproduce it? What needs to be modified.

**Comment by FateScript** [comment]
what if you remove the cache and rerun the code?

**Comment by slacklife** [comment]
Can you specify the location of the cache file?
It is in `YOLOX_outputs/yolox_s` ?

**Comment by Joker316701882** [comment]
@slacklife any update?
