### ISSUE TITLE
How to resume training from last checkpoint?

### ISSUE THREAD

**Issue by jmtrutna** [Megvii-BaseDetection/YOLOX#1518]
I'm training my yolox-nano model in google colab:

!python tools/train.py \
    -f nano.py \
    -d 1 \
    -b 16 \
    --fp16 \
    -o \
    -c yolox_nano.pth

With an estimated run time of 2 and a half days for 300 epochs and google colab only allowing 24 hrs of continuous gpu usage...

How do I resume training?

**Comment by FateScript** [comment]
Plz just add `--resume` in your command.

**Comment by jmtrutna** [comment]
Thanks!
