### ISSUE TITLE
在哪里可以更改初始学习率的值呢？

### ISSUE THREAD

**Issue by lunaWU628** [Megvii-BaseDetection/YOLOX#1532]

**Comment by flyingfish7777** [comment]
他是一个自调整的学习率，是动态的，如果要改
yolox_base.py 下这里
self.warmup_lr = 0
self.min_lr_ratio = 0.05

**Comment by wujihua628** [comment]
感谢，但是我看很多教程上有写初始学习率=0.01的，但是不知道在哪个文件中能找到这个值

**Comment by vionwinnie** [comment]
@flyingfish7777  where can I modify the max lr?

**Comment by Joker316701882** [comment]
@lunaWU628 
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/exp/yolox_base.py#L77

Modifying 0.01 to your desired learning_rate to change the init lr.

@vionwinnie There isn't any definition about max lr.
