### ISSUE TITLE
训练出的置信度很低

### ISSUE THREAD

**Issue by TingFeng-7** [Megvii-BaseDetection/YOLOX#1550]
只有把score_thresh 调的很低 0.001 才能看到大部分目标，请问是训练不充分吗。单卡 bs=8 imgsz1920

**Comment by Joker316701882** [comment]
@TingFeng-7 用默认分辨率训练结果如何？

**Comment by TingFeng-7** [comment]
谢谢您的回复 问题已经解决 原因在于我的目标很多，但我的默认max_label没有改动导致的
