### ISSUE TITLE
why the conf_loss is like this?

### ISSUE THREAD

**Issue by kenny39** [Megvii-BaseDetection/YOLOX#1554]
loss_iou = (
            self.iou_loss(bbox_preds.view(-1, 4)[fg_masks], reg_targets)
        ).sum() / num_fg
        loss_obj = (
            self.bcewithlog_loss(obj_preds.view(-1, 1), obj_targets)
        ).sum() / num_fg
        loss_cls = (
            self.bcewithlog_loss(
                cls_preds.view(-1, self.num_classes)[fg_masks], cls_targets
            )
        ).sum() / num_fg

why the conf_loss is divided by num_fg instead of the whole amount of anchors of this batch(8400*batch_size)

**Comment by kenny39** [comment]
or like this 
nn.BCEWithLogitsLoss(reduction="mean")(obj_preds.view(-1, 1)[fg_mask], obj_targets[fg_mask])

**Comment by Joker316701882** [comment]
@kenny39 
This is a common practice in one-stage object detectors (e.g., FCOS). You can understand this as a balancing trick between the classification/confidence and regression losses.
