### ISSUE TITLE
Very low detection confidence

### ISSUE THREAD

**Issue by deepakcrk** [Megvii-BaseDetection/YOLOX#1561]
I have taken yolox(s) pretrained model, and finetuned again for 200 epochs by adding another 50K images to the COCO dataset,

Currently I am parsing only person images from COCO, I was able to get 5% improvement in AP@50 on the COCO validation dataset for person class. But I am seeing bad results visually compared to pretrained model, Also the cofidence of detecting person is also very low value.

On the same image pretrained model detects person with double the confidence than the finetuned model.

On some of my test sample image, the pretrained model is detecting person with confidence above 60-90%, whereas the finetuned model is detecting persons with less than 40%.

What could be the reason for the same?, eventhough finetuned models AP score is better?

**Comment by zhaolongjiao** [comment]
hi, did you solve the problem?  since I met seem problem with you described. If you can share the solution that can help me a lot, thank you!

**Comment by frigiddragon** [comment]
what is your answer?
