### ISSUE TITLE
Bug in AP evaluation? wrong bbox scaling 

### ISSUE THREAD

**Issue by deepakcrk** [Megvii-BaseDetection/YOLOX#1569]
In evaluation, the scaling of bounding box is happening w.r.t to the padded image.

For AP evaluation the bbox has to be scaled by taking the ratio of non-padded image right?

https://github.com/Megvii-BaseDetection/YOLOX/blob/f44fcdd2690b94c7bede47a89aa8763882297462/yolox/evaluators/coco_evaluator.py#L217-L220

Ideally the the box values needs to be scaled by taking the padding information as done in the demo script right?

**Comment by Joker316701882** [comment]
@deepakcrk ''Scale'' has nothing to do with padding operation, since we pad images on right and bottom sides.
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/data/data_augment.py#L154
