### ISSUE TITLE
local variable 'vis_folder' referenced before assignment  ??

### ISSUE THREAD

**Issue by jcyhcs** [Megvii-BaseDetection/YOLOX#157]
hi,professor:
i test use cmd like this:
python3 tools/demo.py image -n yolox-tiny -c /home/**/yolox/YOLOX/weights/yolox_tiny.pth --path /home/**/yolox/YOLOX/asset/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --device gpu

but i got error:
Traceback (most recent call last):
  File "tools/demo.py", line 275, in <module>
    main(exp, args)
  File "tools/demo.py", line 266, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
UnboundLocalError: local variable 'vis_folder' referenced before assignment

why?? please help me!

**Comment by ppt-gethub** [comment]
I met the same problem. Have you solved that?

**Comment by ppt-gethub** [comment]
> I met the same problem. Have you solved that?

I have solved the problem.
In the demo.py 33 line, in " def make_parser()" we have to change something:
parser.add_argument(
        '--save_result', default="true", help='whether to save the inference result of image/video' }
The original is :
--save_result", action="store_true", help="whether to save the inference result of image/video" 
and this code caused the problem.

**Comment by fat-kid** [comment]
thanks!!!
