### ISSUE TITLE
About the Pre-trained ！

### ISSUE THREAD

**Issue by baowenshuwh** [Megvii-BaseDetection/YOLOX#1571]
Were the pre-training weights in YOLOX trained on the coco dataset? I would like to use Convnext as the backbone of yolox, do I also need to get the pre-training weights by training  on the coco dataset?

**Comment by Joker316701882** [comment]
@baowenshuwh Yes, it is better to train ConvNeXt on COCO using YOLOX first.

**Comment by baowenshuwh** [comment]
> @baowenshuwh Yes, it is better to train ConvNeXt on COCO using YOLOX first.

Ok, thank you for your reply
