### ISSUE TITLE
mem: 91.5Gb

### ISSUE THREAD

**Issue by whiterAutumn** [Megvii-BaseDetection/YOLOX#1587]
During training，whether the memory usage is too large is reasonable
`2023-01-04 16:38:40 | INFO     | yolox.core.trainer:256 - epoch: 4/300, iter: 270/662, gpu mem: 11272Mb, ### mem: 91.5Gb, iter_time: 0.793s, data_time: 0.002s, total_loss: 6.4, iou_loss: 2.4, l1_loss: 0.0, conf_loss: 2.7, cls_loss: 1.3, lr: 2.500e-03, size: 640, ETA: 1 day, 22:48:10`

datasets: VOC
env: Ubuntu 16.04.7 LTS，torch1.8.0+cu111，python3.8.5，3090Ti

**Comment by FateScript** [comment]
You could reduce your memory usage by reduce the value of  [`data_num_workers`](https://github.com/Megvii-BaseDetection/YOLOX/blob/b861b22d3f8c78bfab129b8bbfbe2875822941e0/exps/example/custom/yolox_s.py#L24)` of your Exp object. 

And we are trying to support memory cache of VOC dataset these days.
