### ISSUE TITLE
modify n_anchors will wrong, how to solve?

### ISSUE THREAD

**Issue by zcq0860** [Megvii-BaseDetection/YOLOX#1588]
您好，最近在深入研究这项工作，也很感谢您的巨大贡献。
请问head.py中的n_anchors是不是每个grid预测多少anchors呢？修改后报错应该如何解决呀？

**Comment by Joker316701882** [comment]
n_anchors最好不要modify，因为yolox是anchor-free的，这个数只能是1

**Comment by Joker316701882** [comment]
我们会在某个pr把这个变量删除掉
