### ISSUE TITLE
module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by yangjunjie52** [Megvii-BaseDetection/YOLOX#1595]
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
Eval IoU : 0.50
/home/PM/YOLOX-main/yolox/evaluators/voc_eval.py:110: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  difficult = np.array([x["difficult"] for x in R]).astype(np.bool)
2023-01-19 17:28:52 | INFO     | yolox.core.trainer:196 - Training of experiment is done and the best AP is 0.00
2023-01-19 17:28:52 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (5014), thread 'MainThread' (139778397378368):
Traceback (most recent call last):

  File "tools/train.py", line 140, in <module>
    launch(
    └ <function launch at 0x7f1f9bb94160>

> File "/home/PM/YOLOX-main/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f1f8d626c10>

  File "tools/train.py", line 120, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7f1f8c9be5e0>
    └ <yolox.core.trainer.Trainer object at 0x7f1f8c9c8c70>

  File "/home/PM/YOLOX-main/yolox/core/trainer.py", line 77, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7f1f8c9bed30>
    └ <yolox.core.trainer.Trainer object at 0x7f1f8c9c8c70>

  File "/home/PM/YOLOX-main/yolox/core/trainer.py", line 87, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7f1f8c9c50d0>
    └ <yolox.core.trainer.Trainer object at 0x7f1f8c9c8c70>

  File "/home/PM/YOLOX-main/yolox/core/trainer.py", line 223, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7f1f8c9c53a0>
    └ <yolox.core.trainer.Trainer object at 0x7f1f8c9c8c70>

  File "/home/PM/YOLOX-main/yolox/core/trainer.py", line 331, in evaluate_and_save_model
    (ap50_95, ap50, summary), predictions = self.exp.eval(
                                            │    │   └ <function Exp.eval at 0x7f1f8c9beca0>
                                            │    └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
                                            └ <yolox.core.trainer.Trainer object at 0x7f1f8c9c8c70>

  File "/home/PM/YOLOX-main/yolox/exp/yolox_base.py", line 351, in eval
    return evaluator.evaluate(model, is_distributed, half, return_outputs=return_outputs)
           │         │        │      │               │                    └ True
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x7f1f8ca37310>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x7f1f8c11f790>

  File "/home/PM/YOLOX-main/yolox/evaluators/voc_evaluator.py", line 114, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([0., 0., 1.], device='cuda:0')
                   │    │                   └ {0: (tensor([[ 1.4744e+02,  2.8725e+01,  4.9979e+02,  1.5791e+02],
                   │    │                             [-8.2455e-01,  7.0921e+01,  1.4976e+02,  1.0143e+0...
                   │    └ <function VOCEvaluator.evaluate_prediction at 0x7f1f8ca37430>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x7f1f8c11f790>

  File "/home/PM/YOLOX-main/yolox/evaluators/voc_evaluator.py", line 186, in evaluate_prediction
    mAP50, mAP70 = self.dataloader.dataset.evaluate_detections(all_boxes, tempdir)
                   │    │          │       │                   │          └ '/tmp/tmpgcnornjl'
                   │    │          │       │                   └ [[array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), arr...
                   │    │          │       └ <function VOCDetection.evaluate_detections at 0x7f1f8ca37ca0>
                   │    │          └ <yolox.data.datasets.voc.VOCDetection object at 0x7f1fa8db01c0>
                   │    └ <torch.utils.data.dataloader.DataLoader object at 0x7f1f8c11ff10>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x7f1f8c11f790>

  File "/home/PM/YOLOX-main/yolox/data/datasets/voc.py", line 275, in evaluate_detections
    mAP = self._do_python_eval(output_dir, iou)
          │    │               │           └ 0.5
          │    │               └ '/tmp/tmpgcnornjl'
          │    └ <function VOCDetection._do_python_eval at 0x7f1f8ca37e50>
          └ <yolox.data.datasets.voc.VOCDetection object at 0x7f1fa8db01c0>

  File "/home/PM/YOLOX-main/yolox/data/datasets/voc.py", line 339, in _do_python_eval
    rec, prec, ap = voc_eval(
                    └ <function voc_eval at 0x7f1f8ca374c0>

  File "/home/PM/YOLOX-main/yolox/evaluators/voc_eval.py", line 110, in voc_eval
    difficult = np.array([x["difficult"] for x in R]).astype(np.bool)
                │  │                              │          └ <module 'numpy' from '/root/anaconda3/envs/yolox/lib/python3.8/site-packages/numpy/__init__.py'>
                │  │                              └ []
                │  └ <built-in function array>
                └ <module 'numpy' from '/root/anaconda3/envs/yolox/lib/python3.8/site-packages/numpy/__init__.py'>

  File "/root/anaconda3/envs/yolox/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "

AttributeError: module 'numpy' has no attribute 'bool'
(yolox) [root@VM-0-7-centos YOLOX-main]#

这是什么原因呀？
这是我的执行脚本： python tools/train.py -f /home/PM/YOLOX-main/exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 16 -c exps/weights/yolox_s.pth

**Comment by FateScript** [comment]
This bug is fixed in our latest version. Plz pull and update or downgrade your numpy version.
