### ISSUE TITLE
ValueError: current limit exceeds maximum limit

### ISSUE THREAD

**Issue by wangzhiming68** [Megvii-BaseDetection/YOLOX#16]
when I run demo, I have this error：
ValueError: current limit exceeds maximum limit

**Comment by Joker316701882** [comment]
@wangzhiming68 Could you show more information about this error? You can put your log here.

**Comment by Jike-u** [comment]
Hi, Thanks for your work!
i have the same errors, such as   :
c@xycxy:~/YOLOX$ python tools/demo.py video -n yolox-s -c  yolox_s.pth.tar --path  video --conf 0.3 --nms 0.65 --tsize 640 --save_result
Traceback (most recent call last):
  File "tools/demo.py", line 15, in <module>
    from yolox.data.data_augment import preproc
  File "/home/cxy/YOLOX/yolox/__init__.py", line 6, in <module>
    configure_module()
  File "/home/cxy/YOLOX/yolox/utils/setup_env.py", line 39, in configure_module
    resource.setrlimit(resource.RLIMIT_NOFILE, (ulimit_value, rlimit[1]))
ValueError: current limit exceeds maximum limit

**Comment by Jike-u** [comment]
> @wangzhiming68 Could you show more information about this error? You can put your log here.

Hi, Thanks for your work!
i have the same errors, such as :
c@xycxy:~/YOLOX$ python tools/demo.py video -n yolox-s -c yolox_s.pth.tar --path video --conf 0.3 --nms 0.65 --tsize 640 --save_result
Traceback (most recent call last):
File "tools/demo.py", line 15, in
from yolox.data.data_augment import preproc
File "/home/cxy/YOLOX/yolox/init.py", line 6, in
configure_module()
File "/home/cxy/YOLOX/yolox/utils/setup_env.py", line 39, in configure_module
resource.setrlimit(resource.RLIMIT_NOFILE, (ulimit_value, rlimit[1]))
ValueError: current limit exceeds maximum limit

**Comment by FateScript** [comment]
code [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/utils/setup_env.py#L30) set ulimit value and you can get such value from
```shell
ulimit -n
```
command.
You could comment such code if not needed.

**Comment by JensenGao** [comment]
> code [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/utils/setup_env.py#L30) set ulimit value and you can get such value from
> 
> ```shell
> ulimit -n
> ```
> 
> command.
> You could comment such code if not needed.

you can use following command to get your value , and modify "8192" to your value. 
```
ulimit -n
```

**Comment by HHaa-gif** [comment]
> code [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/utils/setup_env.py#L30) set ulimit value and you can get such value from
> 
> ```shell
> ulimit -n
> ```
> 
> command.
> You could comment such code if not needed.

I'm sorry, using the method you said didn't solve it

**Comment by LVkunfeng** [comment]
> [此处的](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/utils/setup_env.py#L30)代码设置 ulimit 值，您可以从
> 
> ```shell
> ulimit -n
> ```
> 
> 命令。
> 如果不需要，您可以注释此类代码。

I'd appreciate it if you could be more specific

**Comment by FateScript** [comment]
We have fixed this issue in this [commit](https://github.com/Megvii-BaseDetection/YOLOX/commit/a026133849b724b64fc4794224ee2a2b1c3b8600), you could pull the update and try again.
Thanks for reporting,  close this issue.
