### ISSUE TITLE
if i want to use yolox-tiny on nvidia jetson board, use tensorRT with C++, how can i do it?

### ISSUE THREAD

**Issue by jcyhcs** [Megvii-BaseDetection/YOLOX#160]
hi,professro!:

i work on nvidia jetson platform, i write infer program with c++, i want to use yolox-tiny to just infer, but i don't konw how to do it , please help me!

**Comment by ruinmessi** [comment]
Plz see the tensor C++ demo

**Comment by batrlatom** [comment]
You can use deepstream app together with this network. Take a look at https://github.com/nanmi/YOLOX-deepstream

**Comment by tulbureandreit** [comment]
@FateScript @jcyhcs Have you managed to run yolox-nano or tiny?

I cannot run them, only yolox-s
