### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sunfei007** [Megvii-BaseDetection/YOLOX#162]

**Comment by sunfei007** [comment]
我在训练自己的数据时出现了
AttributeError: Caught AttributeError in DataLoader worker process 0.
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by 1VeniVediVeci1** [comment]
也许是标签没写对？比如voc_classes里面改了吗？另外目标类别数量修改了吗？

**Comment by FateScript** [comment]
plz provide more information, you are most likely get a invalid image object.

**Comment by haileykwak** [comment]
check _imgpath in voc.py

**Comment by sunfei007** [comment]
> 检查 voc.py 中的 _imgpath

![image](https://user-images.githubusercontent.com/80185344/127125287-3a7b2213-7103-46c3-b7ce-50aeea21b4d2.png)

**Comment by sunfei007** [comment]
![image](https://user-images.githubusercontent.com/80185344/127125393-55ba0197-2a51-4d90-9d16-8d6be9735873.png)
z这些路径是对的，只是打印了四个就报错了

**Comment by jokesound** [comment]
> ![image](https://user-images.githubusercontent.com/80185344/127125393-55ba0197-2a51-4d90-9d16-8d6be9735873.png)
> z这些路径是对的，只是打印了四个就报错了

老哥你解决了吗？

**Comment by sunfei007** [comment]
> > ![image](https://user-images.githubusercontent.com/80185344/127125393-55ba0197-2a51-4d90-9d16-8d6be9735873.png)
> > z这些路径是对的，只是打印了四个就报错了
> 
> 老哥你解决了吗？

没有解决呀，你也是这个问题吗

**Comment by jokesound** [comment]
> > > ![image](https://user-images.githubusercontent.com/80185344/127125393-55ba0197-2a51-4d90-9d16-8d6be9735873.png)
> > > z这些路径是对的，只是打印了四个就报错了
> > 
> > 
> > 老哥你解决了吗？
> 
> 没有解决呀，你也是这个问题吗

是啊！我也一样。我开始以为可能是单个图像出问题，但是不断地删除不断地出现。不知道加载哪里出了问题。

**Comment by sunfei007** [comment]
> > > > ![image](https://user-images.githubusercontent.com/80185344/127125393-55ba0197-2a51-4d90-9d16-8d6be9735873.png)
> > > > z这些路径是对的，只是打印了四个就报错了
> > > 
> > > 
> > > 老哥你解决了吗？
> > 
> > 
> > 没有解决呀，你也是这个问题吗
> 
> 是啊！我也一样。我开始以为可能是单个图像出问题，但是不断地删除不断地出现。不知道加载哪里出了问题。

你的该不会也是检测人头的数据集吧

**Comment by jokesound** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/80185344/127125393-55ba0197-2a51-4d90-9d16-8d6be9735873.png)
> > > > > z这些路径是对的，只是打印了四个就报错了
> > > > 
> > > > 
> > > > 老哥你解决了吗？
> > > 
> > > 
> > > 没有解决呀，你也是这个问题吗
> > 
> > 
> > 是啊！我也一样。我开始以为可能是单个图像出问题，但是不断地删除不断地出现。不知道加载哪里出了问题。
> 
> 你的该不会也是检测人头的数据集吧

不是的。 @FateScript 能麻烦看一下是什么问题吗，并不是标签或者路径的问题。

**Comment by jokesound** [comment]
跑voc2007数据集是可以读取的。但是自己的数据集就会出现上述情况。

**Comment by ruinmessi** [comment]
pull the latest updates. We have fixed some serious bugs.

**Comment by lzqcumtb** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/80185344/127125393-55ba0197-2a51-4d90-9d16-8d6be9735873.png)
> > > > > z这些路径是对的，只是打印了四个就报错了
> > > > 
> > > > 
> > > > 老哥你解决了吗？
> > > 
> > > 
> > > 没有解决呀，你也是这个问题吗
> > 
> > 
> > 是啊！我也一样。我开始以为可能是单个图像出问题，但是不断地删除不断地出现。不知道加载哪里出了问题。
> 
> 你的该不会也是检测人头的数据集吧

遇到了同样的问题，但我是在第一个epoch计算完，第二个epoch开始时报这个错。
![1627549044(1)](https://user-images.githubusercontent.com/50006846/127463222-736ae497-596c-4f77-938f-6b392ab12c97.png)

**Comment by haileykwak** [comment]
what is the last line in error code?

**Comment by lzqcumtb** [comment]
> what is the last line in error code?

AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by 1098708658** [comment]
报这个错应该是num-workers 设置的太多 和显存不够使用导致线程直接崩了

**Comment by haileykwak** [comment]
> > what is the last line in error code?
> 
> AttributeError: 'NoneType' object has no attribute 'shape'

I think trainer cant get your image in imagepath.

**Comment by haomayang1126** [comment]
层主还没解决吗？我也是这个

**Comment by haomayang1126** [comment]
重新制作一下数据集，数据集有问题

**Comment by Rocknroll194** [comment]
好巧不巧 我也是这个问题 我把txt转成了 xml 训练就出问题了
