### ISSUE TITLE
How to change inference labels

### ISSUE THREAD

**Issue by mahnehsilla** [Megvii-BaseDetection/YOLOX#1625]
Which "classes file" does the program use for inference?

So I get this result for example:

![12---Copy--2-_jpg rf 53e32283385b4f43c9acac04e0ce7fff(2)](https://user-images.githubusercontent.com/125615505/222314504-c1929e82-75d4-4eac-8b55-34d22fd81e6c.jpg)

It is not taking the files with the annotations for some reason.

Should we change some configuration for the inference step @FateScript ?

**Comment by FateScript** [comment]
Labels is provided [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/4f8f1d79c8/tools/demo.py#L306) named `COCO_CLASSES`, plz check if it fits your self defined dataset.
