### ISSUE TITLE
Is it possible to train using CPU?

### ISSUE THREAD

**Issue by mahnehsilla** [Megvii-BaseDetection/YOLOX#1626]
The script `demo.py` uses **--devices** to specify either gpu or cpu.

The script `train.py` uses **--devices** to specify number of gpus.

I have looked at the code, and there isnt any flag for this. I wonder why it is not possible.

Is it possible to train using CPU-only @FateScript?

**Comment by FateScript** [comment]
CPU-only training cost too much time and we could afford this.

**Comment by mahnehsilla** [comment]
Thanks for your reply. But what do you mean?

**Comment by FateScript** [comment]
Yes, if you want to train a deep learning model on cpu, it's fine. But it will cost you a lot of time to get the final model and no one really train models with cpu. So it's not supported in YOLOX.

**Comment by mahnehsilla** [comment]
Thanks for the explanation!! 
I am new to this and didnt know that there was so much difference. May I ask you how do you personally train? Do you prepare your own hardware or is there any good cloud service?

**Comment by kv1830** [comment]
> If you want to train a deep learning model on cpu, it's fine and possible. But it will cost you a lot of time to get the final model and no one really train models with cpu. So it's not supported in YOLOX.

确实基本不会有人用CPU训练，但是有的公司的人员工电脑上是没有N卡的（比如我的。。），训练的时候是用服务器来训练，调试起来很不方便，如果能支持CPU训练的话，本地调试就会很方便啦。
