### ISSUE TITLE
模型在国产加速卡上的运行情况？

### ISSUE THREAD

**Issue by jingruhou** [Megvii-BaseDetection/YOLOX#163]
请问YOLOX模型有没有移植到寒武纪mlu270上面？有没有卡上的性能参数？有没有移植到华为Atlas上面？性能参数如何？

**Comment by ruinmessi** [comment]
可以参考第三方资源 https://github.com/OAID/Tengine/blob/tengine-lite/examples/tm_yolox.cpp 和知乎 https://zhuanlan.zhihu.com/p/392387835
