### ISSUE TITLE
a problem about distribute train on multi machine

### ISSUE THREAD

**Issue by yankai317** [Megvii-BaseDetection/YOLOX#164]
when i train coco dataset by using multi machine , but the the rank of the second machine is the same as the first machine. 
this is my script,
![image](https://user-images.githubusercontent.com/20473498/126965402-d1b78e0e-b3a0-439b-910b-a23e5404879d.png)
then i find the issue of code. the param "machine_rank" is not used by launch
![image](https://user-images.githubusercontent.com/20473498/126965277-12f47dfb-5ff9-4ce3-b9fb-180c562dc2aa.png)

**Comment by ruinmessi** [comment]
Thx, we will fix the bug soon
