### ISSUE TITLE
preproc() in data_augment.py is slow 

### ISSUE THREAD

**Issue by reihig** [Megvii-BaseDetection/YOLOX#1640]
Due to the time consuming execution of the preproc function in data_augment.py, we could not reduce inference time much by ONNXing the model.

Is there a good way to speed this up?

**Comment by FateScript** [comment]
Could you show me any benchmark data that indicate `preproc` function is the main bottleneck here?

**Comment by reihig** [comment]
I only observed that the preproc of data_augment.py was slow in a certain application of YOLOX, and didn't measure the processing time of YOLOX by itself.

In response to your request, I tested YOLOX by itself and found that the preproc processing time is indeed not dominant. (I should have done this before creating this issue.)

So I will close this issue.
