### ISSUE TITLE
Don't save ckpt.pth from every epoch

### ISSUE THREAD

**Issue by SamHosico** [Megvii-BaseDetection/YOLOX#1641]
Hi everyone, I don't want to save all the "xxx.pth" from every epoch, such as
"epoch_1_ckpt.pth"
"epoch_2_ckpt.pth"
...
and so on,
How can I set my param to solve this problem?

**Comment by menggui1993** [comment]
In your exp file, set `self.save_history_ckpt = False`

**Comment by SamHosico** [comment]
> In your exp file, set `self.save_history_ckpt = False`

Thanks, your suggestion is very usefull!
