### ISSUE TITLE
RuntimeError: FIND was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by Fyw1988** [Megvii-BaseDetection/YOLOX#1642]
Hi, I'm running python tools/train.py after configuring the environment following these steps：
`pip install -r requirements.txt
python3 setup.py develop`

Then I ran into the following problem:

`2023-03-22 12:38:45 | INFO     | yolox.core.trainer:203 - ---> start train epoch1
2023-03-22 12:38:46 | INFO     | yolox.core.trainer:195 - Training of experiment is done and the best AP is 0.00
2023-03-22 12:38:46 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (22906), thread 'MainThread' (139625041457280):
Traceback (most recent call last):

  File "tools/train.py", line 137, in <module>
    launch(
    └ <function launch at 0x7efc2ede65e0>

> File "/home/ding/fyw/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7efc20e4ee50>

  File "tools/train.py", line 118, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7efc1fcad0d0>
    └ <yolox.core.trainer.Trainer object at 0x7efc1fcae1c0>

  File "/home/ding/fyw/YOLOX/yolox/core/trainer.py", line 76, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7efc1fcad8b0>
    └ <yolox.core.trainer.Trainer object at 0x7efc1fcae1c0>

  File "/home/ding/fyw/YOLOX/yolox/core/trainer.py", line 85, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x7efc1fcad940>
    └ <yolox.core.trainer.Trainer object at 0x7efc1fcae1c0>

  File "/home/ding/fyw/YOLOX/yolox/core/trainer.py", line 91, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x7efc1fcad9d0>
    └ <yolox.core.trainer.Trainer object at 0x7efc1fcae1c0>

  File "/home/ding/fyw/YOLOX/yolox/core/trainer.py", line 110, in train_one_iter
    self.scaler.scale(loss).backward()
    │    │      │     └ tensor(25.0141, device='cuda:0', grad_fn=<AddBackward0>)
    │    │      └ <function GradScaler.scale at 0x7efc319b9b80>
    │    └ <torch.cuda.amp.grad_scaler.GradScaler object at 0x7efc1fcae2b0>
    └ <yolox.core.trainer.Trainer object at 0x7efc1fcae1c0>

  File "/home/ding/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
    │     │        └ <function backward at 0x7efc31629160>
    │     └ <module 'torch.autograd' from '/home/ding/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/autograd/__init__.py'>
    └ <module 'torch' from '/home/ding/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/__init__.py'>
  File "/home/ding/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    │        │                 └ <method 'run_backward' of 'torch._C._EngineBase' objects>
    │        └ <torch._C._EngineBase object at 0x7efc3a354d20>
    └ <class 'torch.autograd.variable.Variable'>

RuntimeError: FIND was unable to find an engine to execute this computation
`

Does this mean I failed to compile successfully?

**Comment by Fyw1988** [comment]
I reinstalled pytorch and the problem was fixed. I think it was caused by the wrong cuda version of pytorch

**Comment by tyler-tan** [comment]
我也是重新安装了pytorch，是少安装了一些pytorch附加库，重新安装pytorch即可解决

**Comment by Jessica-hub** [comment]
can anyone let me know what version of pytorch and cuda you are using?

**Comment by harshap-ai** [comment]
> can anyone let me know what version of pytorch and cuda you are using?

Yep same. Did you reinstall the same torch version? (in my case, it's 2.2.1).
