### ISSUE TITLE
YOLOX/yolox/layers/cocoeval/cocoeval.h:4:10: fatal error: pybind11/numpy.h: No such file or directory

### ISSUE THREAD

**Issue by sahamitul** [Megvii-BaseDetection/YOLOX#1648]
I get this crash while building:
YOLOX/yolox/layers/cocoeval/cocoeval.h:4:10: fatal error: pybind11/numpy.h: No such file or directory

Any ideas?

**Comment by FateScript** [comment]
Plz provide python3 version and numpy version here.

**Comment by sahamitul** [comment]
@FateScript I am using conda environment. Python 3.8 and numpy 1.22.3

I installed some conda libs using:
conda install pycocotools -c conda-forge
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install -c conda-forge gxx
conda install -c conda-forge ninja
conda install -c conda-forge pybind11

Thanks for any help.

**Comment by FateScript** [comment]
I'm using venv and everything works for me.
I search your error and find the following issue: [link](https://github.com/pybind/pybind11/issues/698), hope it could help you.

**Comment by sahamitul** [comment]
I did try that link without success. I will try now penv instead of conda. What python version did you use? @FateScript

**Comment by sahamitul** [comment]
Thanks worked. I also did "pip install -r requirements.txt", which you may put in README.
