### ISSUE TITLE
执行demo预测时，报错AttributeError: module 'torchvision.ops' has no attribute 'batched_nms'

### ISSUE THREAD

**Issue by zcswdt** [Megvii-BaseDetection/YOLOX#165]
![image](https://user-images.githubusercontent.com/43515926/126966416-21204792-5b1e-4366-a42f-ae1a395733d7.png)

**Comment by ruinmessi** [comment]
你torchvision的版本应该要升级了。。

**Comment by zcswdt** [comment]
> 你torchvision的版本应该要升级了。。
我安装的时候是按照readme中的运行的，
pip3 install -r requirements.txt

我看了一下我的torchvision版本，如下：
![image](https://user-images.githubusercontent.com/43515926/126970546-a2303fd0-d639-413a-859f-12bd24939189.png)
应该是最新的啊

**Comment by zcswdt** [comment]
> > 你torchvision的版本应该要升级了。。
> 
> 我安装的时候是按照readme中的运行的，
> pip3 install -r requirements.txt
> 
> 我看了一下我的torchvision版本，如下：
> ![image](https://user-images.githubusercontent.com/43515926/126970546-a2303fd0-d639-413a-859f-12bd24939189.png)
> 应该是最新的啊

好了，已经解决，谢谢了。
