### ISSUE TITLE
CUDA error: out of memory CUDA. kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrec

### ISSUE THREAD

**Issue by anonymoussss** [Megvii-BaseDetection/YOLOX#1653]
I am using the latest version of yolox via docker, using 8 T4 GPU for training, but even if I set the batch size to 1, I still get an error as follows: 
``` RuntimeError: CUDA error: out of memory 
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. 
```
Note that the error log is not
 ``` RuntimeError: CUDA out of memory. Tried to allocate xxx MiB (GPU 0; xxx GiB total capacity; xxx MiB already allocated...```
 So it's not that the GPU memory is not enough.

my training script as follows：
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/train.py -f exps/my_data/yolox_m -b 1 --fp16 -d 8 --cache ram`

However, When I use yolox 0.1.1 through docker on the same machine, it can run normally even if the batch size is set to 512.
my training script for 0.1.1 version  as follows:
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/train.py -f exps/my_data/yolox_m -b 1 --fp16 -d 8 --cache`

So , is there a memory problem in the latest version of yolox during multi-GPU training？

**Comment by anonymoussss** [comment]
@FateScript @Joker316701882

**Comment by FateScript** [comment]
@anonymoussss  Could you  please provide more info ? For example: your torch version, more exception log.

**Comment by anonymoussss** [comment]
@FateScript 
###  Local Environment
- 8*T4
- Nvidia Driver 460.73.01
- CUDA  version:11.2, 
- Docker

### The running environment in the docker container
- Python 3.8.5
- Torch 2.0.0+cu117
- The training dataset is a subset of coco 

### Exception log
![image](https://user-images.githubusercontent.com/12672787/231401257-ef59cd6a-6cd7-4412-b042-c2a9757889a7.png)

### The running environment in the yolox 0.1.1 docker container
- Python 3.7.7 
- Torch 1.7.0+cu101
- Can run smoothly

**Comment by anonymoussss** [comment]
Emmm...It seems to be a hardware problem of my machine. . I will close this issue .

**Comment by BobTheHunted** [comment]
> Emmm...It seems to be a hardware problem of my machine. . I will close this issue .

And what was the hardware issue?

**Comment by anonymoussss** [comment]
Actually, I don't know what's going on... My machine with 8 T4 GPU（gpu 0,1,2...6,7） has no problem when using gpu0~gpu5 or gpu1~gpu7 for training, but it will report 'cuda error' when using all 8 GPUs... When I use other versions of yolox, I can use all 8 GPUs. What's more, I can also run any other pytorch-based task to use all 8 GPUs.

**Comment by zehranrgi** [comment]
I also lived this problem when I used the colab machine. However, there are no problems w/ other Yolo versions.
