### ISSUE TITLE
There is a problem was generated before training

### ISSUE THREAD

**Issue by mingshan3** [Megvii-BaseDetection/YOLOX#1656]
如何关闭YOLOX训练之前的网络调试或者改变网络调试的数据维度
How to turn off network debugging before YOLOX training or change the data dimension of network debugging

**Comment by FateScript** [comment]
What's YOLOX network debugging? Do you mean `thop profile` info here?

**Comment by mingshan3** [comment]
> What's YOLOX network debugging? Do you mean `thop profile` info here?

I have been solved this problem,thank you
