### ISSUE TITLE
Is there any way to remove the Int64 and use Int32?

### ISSUE THREAD

**Issue by mahnehsilla** [Megvii-BaseDetection/YOLOX#1659]
When I try to use the onnx exported model on the web (where there are 2 choices wasm or webgl for running the inference). The wasm version is fine, but the webgl version complains about Int64 not being supported. Is this something that should be taken care of in the `onnx_export.py`? I think only the webgl version runs on JS, so the error is related to this export having int64 type not supported by javascript I presume. 

Any ideas?

**Comment by jheanelestrada** [comment]
Hi, were you able to solve this?

**Comment by mahnehsilla** [comment]
Use `wasm` as default, and in some browsers it may use webgl I think (so you can put it as fallback.)
