### ISSUE TITLE
Could not run 'torchvision::nms' with arguments from the 'CUDA' backend

### ISSUE THREAD

**Issue by qrzeffort** [Megvii-BaseDetection/YOLOX#166]
当我按照命令 ：

python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 8 --fp16 -o -c weight/yolox_x.pth

训练了10个epoch之后，出现了报错：
| ERROR    | yolox.core.launch:68 - An error has been caught in function 'launch', process 'MainProcess' (26366), thread 'MainThread' (140370027357952):
...
RuntimeError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 'torchvision::nms' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].

BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
AutogradCPU: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
AutogradCUDA: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
AutogradXLA: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
Tracer: fallthrough registered at /pytorch/torch/csrc/jit/frontend/tracer.cpp:967 [backend fallback]
Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

环境：
torch1.7 torchvision0.8.0 cuda10.2 cudnn7.6.5

显卡：
RTX2060 6GB

想问是我的环境安装不匹配还是硬件不支持，感谢回复！

**Comment by 1VeniVediVeci1** [comment]
是不是pytorch没有安装gpu版本

**Comment by qrzeffort** [comment]
> 是不是pytorch没有安装gpu版本

我是按照readme里安装的，应该没问题
后来又看了一遍
**_yolox_voc_s.py_** -d 1 -b 8 --fp16 -o -c weight/**_yolox_x.pth_**
yolox_voc_s对应的一定是yolox_s.pth吗

**Comment by 1VeniVediVeci1** [comment]
> > 是不是pytorch没有安装gpu版本
> 
> 我是按照readme里安装的，应该没问题
> 后来又看了一遍
> **_yolox_voc_s.py_** -d 1 -b 8 --fp16 -o -c weight/**_yolox_x.pth_**
> yolox_voc_s对应的一定是yolox_s.pth吗

事实上会有问题……它requirement里面装的pytorch是cpu版本，建议自己手动装gpu的pytorch

**Comment by ancybeibei** [comment]
我在测试demo的时候出现了这个问题，当时环境和你一样，我pull 了个docker ，环境为torch1.8.1 torchvision0.9.1 cuda10.2 cudnn8.2.0，demo没问题，暂时没有train

**Comment by qrzeffort** [comment]
问题解决了，还是因为环境问题，一开始我用的torch1.6版本在跑demo的时候报错，后来按照提示换了torch1.7版本但没有重新编译，demo是过了，但是train就出现这个问题（也是很奇怪），后来意识到这个问题之后想重新编译，发现又有报错，于是就按照requirement重新安装conda环境，就好了，现在我的环境是：
torch1.9 torchvision0.10.0 cuda10.2 cudnn7.6.5

**Comment by gsx1378** [comment]
天...torch1.7 torchvision0.8.0 cuda10.2 cudnn7.6.5,这套环境也不行吗...
