### ISSUE TITLE
ImportError: cannot import name 'container_abcs' from 'torch._six'

### ISSUE THREAD

**Issue by zhishao** [Megvii-BaseDetection/YOLOX#167]
env: win10, torch 1.9, cuda10.2

**Comment by 1VeniVediVeci1** [comment]
Try: open apex/amp/_initialize.py and replace the command from torch._six import container_abcs with import collections.abc as container_abcs

**Comment by zhishao** [comment]
@1VeniVediVeci1 Thx, it works, but i changed modified in apex\amp\_amp_state.py
