### ISSUE TITLE
openvino_inference.py   'Namespace' object has no attribute 'image_path'

### ISSUE THREAD

**Issue by BigPandaCPU** [Megvii-BaseDetection/YOLOX#168]
there is no image_path  arg in namespace,it should be args.input

![QQ截图20210726175225](https://user-images.githubusercontent.com/25834151/126970327-a4550f72-f774-41de-8620-0c3d9b2ef5ec.png)

**Comment by Joker316701882** [comment]
Fix. Thank you very much.
