### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by rzy87** [Megvii-BaseDetection/YOLOX#17]
Unfortunately, there is no substitute for 'resource' in Win10. 
![image](https://user-images.githubusercontent.com/56183944/126291860-bf325259-8160-49db-a754-d4df9a9431fc.png)

**Comment by FateScript** [comment]
resource is python3 standard library, you might check its [docs](https://docs.python.org/3/library/resource.html). Maybe you should update your python version.

**Comment by rzy87** [comment]
My python version is 3.7.6, and reinstalling the resource is helpless...

**Comment by rzy87** [comment]
OK, I just commented the resource code. hhh

**Comment by FateScript** [comment]
It seems that resources module is not on python build of Win. Just comment the code, I will fix this later.

**Comment by Hezhexi2002** [comment]
I meet the same error, so dose it be fixed now?

**Comment by Hezhexi2002** [comment]
OK,I comment the code too,and I found the solution have be submitted here:https://github.com/apache/spark/pull/23055,hope it will help you

**Comment by FateScript** [comment]
We have fixed this issue in this [commit](https://github.com/Megvii-BaseDetection/YOLOX/commit/a026133849b724b64fc4794224ee2a2b1c3b8600), you could pull the update.
Thanks for help @Hezhexi2002 ,  close this issue.
