### ISSUE TITLE
请问支持训练数据的标签是txt加载么？

### ISSUE THREAD

**Issue by zcswdt** [Megvii-BaseDetection/YOLOX#171]
我的训练数据标签是txt，请问有接口能支持吗？

**Comment by matankley** [comment]
I believe you mean darknet txt file format. At the moment I don't see there is an interface for it.
Easiest for you would be to write txt to COCO format converter. It will require less changes than implementing TxtDataLoader + Evaluator.

**Comment by zcswdt** [comment]
> e you mean darknet txt file



> I believe you mean darknet txt file format. At the moment I don't see there is an interface for it.
> Easiest for you would be to write txt to COCO format converter. It will require less changes than implementing TxtDataLoader + Evaluator.

Thank you very much for your reply. I will try to change the data into coco format, but I suggest that you can open an interface to support the reading of txt tags.

**Comment by zhangming8** [comment]
You can modify this script https://github.com/zhangming8/yolox-pytorch/blob/main/tools/voc_to_cooc.py
 Its function is to convert VOC data into coco. You only need to replace the code for parsing XML with parsing your TXT
