### ISSUE TITLE
torch是否是需要下载GPU版本

### ISSUE THREAD

**Issue by FAFUzxf** [Megvii-BaseDetection/YOLOX#172]
![image](https://user-images.githubusercontent.com/69864549/126985689-2b57a009-54b8-494e-ac36-51914f46e89d.png)
您好，我在训练时报了这个错误，网上查阅好可能是torch根据requirement.txt下载时，自动下载了cpu版本，是否可以在接下来的更新中，对于配置文件给予更好的说明？

**Comment by wwzh2015** [comment]
我好像启动不了GPU demo，只能跑CPU

**Comment by FAFUzxf** [comment]
重新去下一个gpu版本的torch，好像就可以了

**Comment by 1VeniVediVeci1** [comment]
先装好gpu pytorch，然后在装requirement

**Comment by wwzh2015** [comment]
> 先装好gpu pytorch，然后在装requirement

我就是这样的，还是启动不了gpu

**Comment by Joker316701882** [comment]
@FAFUzxf pull一下最新分支，demo支持cpu和gpu推理了，默认cpu

**Comment by wwzh2015** [comment]
> @FAFUzxf pull一下最新分支，demo支持cpu和gpu推理了，默认cpu

 parser.add_argument("--device", default="gpu", type=str, help="device to run our model, can either be cpu or gpu")
我改了默认为gpu，但还是cpu推理

**Comment by zhangming8** [comment]
你确认下载的是gpu版的pytorch吗

**Comment by wwzh2015** [comment]
> 你确认下载的是gpu版的pytorch吗

pytorch                   1.7.1           py3.8_cuda102_cudnn7_0    pytorch

**Comment by zhangming8** [comment]
先确认一下你的gpu版能不能用。
torch.rand([2]).cuda()有没有报错

**Comment by wwzh2015** [comment]
> 先确认一下你的gpu版能不能用。
> torch.rand([2]).cuda()有没有报错

>>> torch.cuda.is_available()
True
>>>
