### ISSUE TITLE
When running the Core ML model converted with coremltools in Swift, the objectness score behaves oddly only on the actual device

### ISSUE THREAD

**Issue by hiroalchem** [Megvii-BaseDetection/YOLOX#1780]
I wanted to use YOLOX for iOS, so I created a yolox.mlpackage using coremltools and developed a Swift app. Although there were no issues in the simulator, when I tested it on an actual device (iPhone 15 Pro), I noticed that the objectness score was abnormally high. Here is the code for loading the model and using it in the app. When I run this code, the objectness score exceeds 1, although other values do not show any abnormalities. Could anyone provide some advice?

```
    private func loadModel() {
        do {
            let model = try yolox()
            self.model = try VNCoreMLModel(for: model.model)
        } catch {
            errorMessage = "Failed to load model: \(error.localizedDescription)"
            print(errorMessage!)
        }
    }
    
    private func classifyImage() {
        print("classifyImage called")
        guard let uiImage = image, let ciImage = CIImage(image: uiImage) else {
            print("Image is not available for classification")
            return
        }
        
        guard let validModel = model else {
            print("Model is not loaded or available for classification")
            return
        }
        
        let request = VNCoreMLRequest(model: validModel) { request, error in
            if let error = error {
                print("Classification failed with error: \(error.localizedDescription)")
                return
            }
            
            guard let results = request.results as? [VNCoreMLFeatureValueObservation] else {
                print("Classification returned no results or wrong results type.")
                return
            }
            
            print("Total results returned: \(results.count)")
            if results.isEmpty {
                print("No results were returned.")
            } else {
                let boxes = self.postProcessFeatureValueObservations(results)
                DispatchQueue.main.async {
                    self.displayResults(boxes: boxes, on: uiImage)
                }
                print(boxes)
            }
        }
    
        
        let handler = VNImageRequestHandler(ciImage: ciImage)
        do {
            try handler.perform([request])
            print("Classification request performed")
        } catch {
            print("Failed to perform classification: \(error.localizedDescription)")
        }
    }
    
    func postProcessFeatureValueObservations(_ observations: [VNCoreMLFeatureValueObservation]) -> [BoundingBox] {
        var boxes: [BoundingBox] = []
        
        for observation in observations {
            guard let multiArray = observation.featureValue.multiArrayValue else { continue }
            let count = multiArray.count / 6  
            for i in 0..<count {
                let index = i * 6
                // セーフに各要素の値を取得
                let centerX = CGFloat(multiArray[index].floatValue)
                let centerY = CGFloat(multiArray[index + 1].floatValue)
                let width = CGFloat(multiArray[index + 2].floatValue)
                let height = CGFloat(multiArray[index + 3].floatValue)
                let score = Float(multiArray[index + 4].floatValue)
                let classScore = Float(multiArray[index + 5].floatValue)
                
                let x1 = centerX - width / 2.0
                let y1 = centerY - height / 2.0
                let x2 = centerX + width / 2.0
                let y2 = centerY + height / 2.0
                
                let rect = CGRect(x: x1, y: y1, width: x2 - x1, height: y2 - y1)
                if score * classScore > 0.1 { 
                    print(score)
                    boxes.append(BoundingBox(classScore: classScore, score: score, rect: rect))
                    if score > 1{
                        print("over1")
                    }
                }
            }
        }
```

**Comment by hiroalchem** [comment]
I passed "compute_precision=coremltools.precision.FLOAT32" when I convert model, then problem solved.

**Comment by ghost** [comment]
Hello @hiroalchem ,

I’m currently working on building an iOS application for object detection using YOLOX. I was wondering if you could kindly share the Core ML conversion code.

Also, if you have any information or tips regarding inference time on iOS, I’d really appreciate it.

Thank you so much for your time and support!

**Comment by hiroalchem** [comment]
@ProfessorHT 
I don’t remember exactly where the code was, but I believe it was probably this one.

`from yolox.exp import Exp as MyExp

class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.depth = 0.33
        self.width = 0.375
        self.input_size = (416, 416)
        self.mosaic_scale = (0.5, 1.5)
        self.random_size = (10, 20)
        self.test_size = (416, 416)
        self.exp_name = "fish"
        self.enable_mixup = False
        self.degrees = 10.0
        self.translate = 0.1

        # Define yourself dataset path
        self.data_dir = "./dataset_coco"
        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"

        self.num_classes = 1
        self.max_epoch = 300
        self.data_num_workers = 4
        self.eval_interval = 1

exp = Exp()

model = exp.get_model()
checkpoint = torch.load('./YOLOX/YOLOX_outputs/yolo_tiny/best_ckpt.pth', map_location='cpu')
model.load_state_dict(checkpoint['model'])
model.eval()

# ダミー入力
dummy_input = torch.randn(1, 3, 416, 416)  # 例えば、416x416の入力サイズ

# モデルのトレース
traced_model = torch.jit.trace(model, dummy_input)

# Core ML モデルへの変換
image_scale = 1/255.0  # 画像のピクセル値を0-1の範囲にスケール
red_bias = -0.485 / 0.229  # 正規化のための赤チャネルバイアス (ImageNetの平均と標準偏差)
green_bias = -0.456 / 0.224  # 緑
blue_bias = -0.406 / 0.225  # 青

# CoreMLモデルへの変換。入力型を明示的に指定。
model = ct.convert(
    traced_model,
    inputs=[ct.ImageType(scale=image_scale, bias=(blue_bias, green_bias, red_bias), color_layout='RGB', shape=dummy_input.shape)],
    convert_to="mlprogram"
)

model.save('yolox.mlpackage')`
