### ISSUE TITLE
用自己的数据集训练，训练10个epcho后，进行验证报错，请问是为什么？

### ISSUE THREAD

**Issue by lihui669** [Megvii-BaseDetection/YOLOX#179]
![image](https://user-images.githubusercontent.com/40649829/127007866-472b9a80-b46c-4989-baa6-71f1dfd633b2.png)
![image](https://user-images.githubusercontent.com/40649829/127008072-cfee0b45-322f-462e-9a6b-f46792eea5a4.png)
用自己的数据集，需要修改验证部分的代码吗？若调通程序后，在终端怎么让他从第10个迭代开始训练呢？

**Comment by ruinmessi** [comment]
直接加上--resume就可以了
