### ISSUE TITLE
When try to install requirments.txt

### ISSUE THREAD

**Issue by mhdsiyad** [Megvii-BaseDetection/YOLOX#1801]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /private/var/folders/vy/99vy6g_j707b_bz33fck_cfh0000gn/T/pip-install-zgi_deuf/onnx-simplifier_cf6eaf8827134fbab45518d42fc5ab94/setup.py:26: DeprecationWarning: Use shutil.which instead of find_executable
        CMAKE = find_executable('cmake')
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      /Users/siyad/Documents/python/webiwo/src/webiwo/YOLOX/yolox-env/lib/python3.12/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/vy/99vy6g_j707b_bz33fck_cfh0000gn/T/pip-install-zgi_deuf/onnx-simplifier_cf6eaf8827134fbab45518d42fc5ab94/setup.py", line 271, in <module>
          setuptools.setup(
        File "/Users/siyad/Documents/python/webiwo/src/webiwo/YOLOX/yolox-env/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/siyad/Documents/python/webiwo/src/webiwo/YOLOX/yolox-env/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 145, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/Users/siyad/Documents/python/webiwo/src/webiwo/YOLOX/yolox-env/lib/python3.12/site-packages/setuptools/dist.py", line 294, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/siyad/Documents/python/webiwo/src/webiwo/YOLOX/yolox-env/lib/python3.12/site-packages/setuptools/dist.py", line 330, in _normalize_version
          normalized = str(Version(version))
                           ^^^^^^^^^^^^^^^^
        File "/Users/siyad/Documents/python/webiwo/src/webiwo/YOLOX/yolox-env/lib/python3.12/site-packages/packaging/version.py", line 202, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      packaging.version.InvalidVersion: Invalid version: 'unknown'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mm0806son** [comment]
I fixed this by changing `onnx-simplifier` version to `0.3.10` in the `requirement.txt`.
See this [reply](https://github.com/Megvii-BaseDetection/YOLOX/issues/1781#issuecomment-2243360660).

**Comment by maja1001** [comment]
I had the same problem!

What version of Python do you have? For me it occurred with **Python 3.12.4**. With a conda environment and **Python 3.10**. everything works fine.

I think it also works with **Python 3.11**. (see the available / supported versions: https://pypi.org/project/onnx-simplifier/).

**Comment by mhdsiyad** [comment]
> I had the same problem!
> 
> What version of Python do you have? For me it occurred with **Python 3.12.4**. With a conda environment and **Python 3.10**. everything works fine.
> 
> I think it also works with **Python 3.11**. (see the available / supported versions: https://pypi.org/project/onnx-simplifier/).

i have python 3.12, after this issue downgraded to 3.9, also changed the version of  `onnx-simplifier` to 0.3.10 after all this its worked
