### ISSUE TITLE
Wrong default value for fp16

### ISSUE THREAD

**Issue by jasonkhadka** [Megvii-BaseDetection/YOLOX#181]
https://github.com/Megvii-BaseDetection/YOLOX/blob/8ba73adbad0415f56378eb77f8d28ea7969fb87c/tools/train.py#L60

**Comment by ruinmessi** [comment]
Thx. We actually set fp16 at true by default, as it saves GPU memory and has no influence on the accuracy.

**Comment by jasonkhadka** [comment]
then perhaps the action should be `store_false` ?

**Comment by wangg12** [comment]
> then perhaps the action should be `store_false` ?

then the name might be `--no_fp16` or `--no_amp`
