### ISSUE TITLE
希望能够得到对parser的相关参数的解释和作用？

### ISSUE THREAD

**Issue by FAFUzxf** [Megvii-BaseDetection/YOLOX#182]
在阅读源码时，小白对内部参数有一些不了解，希望可以得到一些回答。比如相关参数的作用？
![image](https://user-images.githubusercontent.com/69864549/127075174-a85b5d46-51e7-4bef-a31b-8128730220ec.png)
![image](https://user-images.githubusercontent.com/69864549/127075194-206a6864-1f7b-4cda-9321-2bc14b844357.png)
![image](https://user-images.githubusercontent.com/69864549/127075211-38a65f3a-efe3-4bbc-b0a8-7170b270aefa.png)
![image](https://user-images.githubusercontent.com/69864549/127075229-719b085e-1b30-4174-855b-31a4afe59663.png)
![image](https://user-images.githubusercontent.com/69864549/127075250-a1edc378-37f3-4bfd-8171-80189f5f96ee.png)
![image](https://user-images.githubusercontent.com/69864549/127075253-182908ef-1ef9-46a9-8af0-51531b6c8d5b.png)

**Comment by QWERDF007** [comment]
可以参考pytorch的分布式训练相关文档

**Comment by FAFUzxf** [comment]
好的，谢谢
