### ISSUE TITLE
国内的算法也不出一个中文的readme， 哎。看看人家百度。

### ISSUE THREAD

**Issue by Yaoxingtian** [Megvii-BaseDetection/YOLOX#187]
as titled

**Comment by Joker316701882** [comment]
@Yaoxingtian We have no time and have some more urgent issues now. If you are free, please help us and submit a pull request.

**Comment by FateScript** [comment]
抱歉带来了不好的体验，我们本身除了开源之外还有其他的工作要做，因为时间上不是很充分。我们只能选择受众量最大的英文。如果您有意愿，可以帮忙contribute，谢谢！

**Comment by BowieHsu** [comment]
@Yaoxingtian  兄弟，连readme都看不懂，就别乱搞了，找个外卖送吧。

**Comment by zcswdt** [comment]
> ，找个外卖送吧

看来你心里的辫子还在啊，这种东西是根深蒂固的。别人的意思不是看不懂，是觉得国内的算法，应该要有文化输出，算了，辫子这种东西是改变不了的，国外的月亮对你来说还是圆。

**Comment by 1VeniVediVeci1** [comment]
建议用中文写代码呢
一个新项目赶时间发出来当然是写个英文的所有人都能看，先学术，再政治

**Comment by zcswdt** [comment]
> 文写代



> 建议用中文写代码呢
> 一个新项目赶时间发出来当然是写个英文的所有人都能看，先学术，再政治

你不会到现在还觉得科学无界限吧？？？

**Comment by BowieHsu** [comment]
@zcswdt 加油。

**Comment by 1VeniVediVeci1** [comment]
> > 文写代
> 
> > 建议用中文写代码呢
> > 一个新项目赶时间发出来当然是写个英文的所有人都能看，先学术，再政治
> 
> 你不会到现在还觉得科学无界限吧？？？

okk，祝你当下一个李森科

**Comment by zcswdt** [comment]
> > > 文写代
> > 
> > 
> > > 建议用中文写代码呢
> > > 一个新项目赶时间发出来当然是写个英文的所有人都能看，先学术，再政治
> > 
> > 
> > 你不会到现在还觉得科学无界限吧？？？
> 
> okk，祝你当下一个李森科

不会吧，又开始扣帽子了，各种典故秀儿啊。哈哈哈，，，你要是生在古代估计是秀才，哦，也可能是秦桧，亦可能是赵高，指鹿为马。我在家经常教育我儿子要好好做人，希望你也一样哈。

**Comment by zcswdt** [comment]
> > 限吧？？？
> 
> okk，祝

fw

**Comment by zhangming8** [comment]
英文版看习惯了还好吧，大家都是中国人也不会写出太复杂的英语句子

**Comment by Yaoxingtian** [comment]
> @Yaoxingtian 兄弟，连readme都看不懂，就别乱搞了，找个外卖送吧。

哈哈哈， readme 几句话，英文你第一！

**Comment by Yaoxingtian** [comment]
> 建议用中文写代码呢
> 一个新项目赶时间发出来当然是写个英文的所有人都能看，先学术，再政治



> > @Yaoxingtian 兄弟，连readme都看不懂，就别乱搞了，找个外卖送吧。
> 
> 哈哈哈， readme 几句话，英文你第一！



> @Yaoxingtian 兄弟，连readme都看不懂，就别乱搞了，找个外卖送吧。

哈哈哈，我写的是中文你都看不懂我说的意思吗？

**Comment by Yaoxingtian** [comment]
> 建议用中文写代码呢
> 一个新项目赶时间发出来当然是写个英文的所有人都能看，先学术，再政治

哪来的政治？

**Comment by Yaoxingtian** [comment]
> 抱歉带来了不好的体验，我们本身除了开源之外还有其他的工作要做。因为时间上不是很充分，我们只能选择受众量最大的英文。如果您有意愿，可以帮忙contribute，谢谢！
没事，可以理解。我只是觉得中文在GitHub上出现太少，有能力者也是国内开源贡献者能写个中文说明作为国内读者看起来都会亲切。谢谢~

**Comment by Yaoxingtian** [comment]
> @Yaoxingtian We have no time and have some more urgent issues now. If you are free, please help us and submit a pull request.

If so , I can understand. 
But I think it's better to do it by yourself once you have time as you know the point more. 
Thanks~
