### ISSUE TITLE
如何在pycharm上运行

### ISSUE THREAD

**Issue by MangoloD** [Megvii-BaseDetection/YOLOX#190]
![image](https://user-images.githubusercontent.com/52820275/127100391-bf6c597e-5fcf-4625-8334-45b932bcf275.png)
在pycharm上运行会显示这种错误(已设置各个参数的值)

**Comment by jing2523** [comment]
`parser.add_argument('--demo', default='image', help='demo type, eg. image, video and webcam')`，demo前面加--

**Comment by MangoloD** [comment]
> `parser.add_argument('--demo', default='image', help='demo type, eg. image, video and webcam')`，demo前面加--

对，我也发现是这个问题了，还是感谢你
