### ISSUE TITLE
部署工具的Video檢測版本

### ISSUE THREAD

**Issue by hsulin0806** [Megvii-BaseDetection/YOLOX#194]
不知道會不會有OpenVINO、tensorRT、ONNXRuntime的Video影像辨識的python程式，謝謝。

**Comment by F0xZz** [comment]
自己手写啊~读入即可 
cap.open();
,,,,

**Comment by Joker316701882** [comment]
@hsulin0806 We have no plan to provide deploying demos for video. However, we welcome any contribution.

**Comment by hsulin0806** [comment]
好的，感谢。
