### ISSUE TITLE
小试了一把训练，发现不少问题

### ISSUE THREAD

**Issue by znsoftm** [Megvii-BaseDetection/YOLOX#199]
1. 安装不易 （这个可能是使用者的水平原因）
2. 对coco规范的理解有问题 ，比如文件名的约束太多 （这个可以由使用者转换解决）
3. bug 太多，基本上很难跑起来

总结 ： 曲高调高，但是实际拉稀，希望改进。 如果实在不好搞，可以弄nvidia-docker的方式，让大家可以一站搞定。

作为一个20多年经验的老工程师，感觉是这东东的工程化之路还长，训练代码稳定性比较差，有很大进步空间。

**Comment by 1VeniVediVeci1** [comment]
最难受的是好不容易跑起来，结果没有旧模型性能好。当然也有可能是我训练的参数没调好。

**Comment by zhangming8** [comment]
我这里实现了个简单版本的 yolox，代码比较容易读，后面会增加跟踪，可以看下https://github.com/zhangming8/yolox-pytorch

**Comment by ruinmessi** [comment]
> 1. 安装不易 （这个可能是使用者的水平原因）
> 2. 对coco规范的理解有问题 ，比如文件名的约束太多 （这个可以由使用者转换解决）
> 3. bug 太多，基本上很难跑起来
> 
> 总结 ： 曲高调高，但是实际拉稀，希望改进。 如果实在不好搞，可以弄nvidia-docker的方式，让大家可以一站搞定。
> 
> 作为一个20多年经验的老工程师，感觉是这东东的工程化之路还长，训练代码稳定性比较差，有很大进步空间。

感谢你的关注和建议。关于bug，现在的版本已经修复了内存泄漏和关闭mosaic的问题，可以正常跑起来并且复现coco的点了，coco的文件名约束也做了修改。至于docker，有人已经做了，可以在issue里搜索， 但是因为一些XX的因素，我们不能公开放了。
也希望你能继续帮助这个项目一起进步

**Comment by ruinmessi** [comment]
> 最难受的是好不容易跑起来，结果没有旧模型性能好。当然也有可能是我训练的参数没调好。

拉一下最新的updates试试，之前因为代码refactor的问题出了些bug
