### ISSUE TITLE
no module named yolox

### ISSUE THREAD

**Issue by zjnyly** [Megvii-BaseDetection/YOLOX#20]
```
Traceback (most recent call last):
  File "./tools/demo.py", line 15, in <module>
    from yolox.data.data_augment import preproc
ModuleNotFoundError: No module named 'yolox'
```
how can I import yolox?

**Comment by zjnyly** [comment]
I can import yolox in python interpreter, but can't successfully run the code

**Comment by FateScript** [comment]
I believe ```import yolox``` also not working for you, maybe you don't install yolox in the right way, please follow what  [README](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/README.md) says.

**Comment by pengtougu** [comment]
应该不止你遇到这个问题，我今天也遇到了，不管在win还是linux都出现了这个bug，设置sources root也不行

**Comment by pengtougu** [comment]
把demo.py从tools单独拎出来，让他直接从根目录去加载yolox里面的模块，应该可以解决你的问题

**Comment by Avnsx** [comment]
https://github.com/Megvii-BaseDetection/YOLOX/issues/154#issuecomment-971730170
