### ISSUE TITLE
How to evaluate voc data?

### ISSUE THREAD

**Issue by SophiaMonster** [Megvii-BaseDetection/YOLOX#206]
How to evaluate voc data, since the python tools/eval.py -n  yolox-s -c yolox_s.pth.tar -b 64 -d 8 --conf 0.001 [--fp16] [--fuse] is defaulted to evaluate in coco data format.

**Comment by ruinmessi** [comment]
Plz see https://github.com/Megvii-BaseDetection/YOLOX/blob/main/exps/example/yolox_voc/yolox_voc_s.py for an example

**Comment by jayphone17** [comment]
This might be working:
`
python tools/eval.py -c YOLOX_outputs/yolox_voc_s/best_ckpt.pth -f exps/example/yolox_voc/yolox_voc_s.py --conf 0.01 --nms 0.65 --test
`
