### ISSUE TITLE
Running in detectron2

### ISSUE THREAD

**Issue by Shanyaodedanshen** [Megvii-BaseDetection/YOLOX#213]
I want use it in detectron2. I don't know what is "targets". Could you tell me?  for example, in line 28, 'yolox.py'.
Thank you for you awesome work.

**Comment by zhangming8** [comment]
'targets' is the groundtruth generated by dataloader/dataset. When doing inference(model.eval()) we needn't 'target'( is None)

**Comment by Shanyaodedanshen** [comment]
> 'targets' is the groundtruth generated by dataloader/dataset. When doing inference(model.eval()) we needn't 'target'( is None)

Thx very much.

**Comment by Shanyaodedanshen** [comment]
By the way.
The shape of "targets" is [2,120,5]. So what's the meaning of them, respectively? Thx.
