### ISSUE TITLE
【已解决】训练过程中map50和map5095都为0

### ISSUE THREAD

**Issue by MangoloD** [Megvii-BaseDetection/YOLOX#218]

**Comment by MangoloD** [comment]
yolox.core.trainer:307 - Save weights to ./YOLOX_outputs\yolox_voc_s
0it [00:02, ?it/s]
Writing panda VOC results file
Writing tiger VOC results file
Eval IoU : 0.50
AP for panda = 0.0000
AP for tiger = 0.0000
Mean AP = 0.0000


yolox.evaluators.voc_evaluator:142 - Evaluate in main process...
Eval IoU : 0.80
Eval IoU : 0.85
Eval IoU : 0.90
Eval IoU : 0.95
--------------------------------------------------------------
map_5095: 0.0
map_50: 0.0
--------------------------------------------------------------

**Comment by ruinmessi** [comment]
看看你的training loss

**Comment by MangoloD** [comment]
> 看看你的training loss

total_loss: 58.7, iou_loss: 5.0, l1_loss: 0.0, conf_loss: 53.5, cls_loss: 0.2, lr: 4.335e-04, size: 768, ETA: 0:16:38
好像还都挺大的

**Comment by ruinmessi** [comment]
太大了。。。建议你可视化gt看看是不是有问题。。。

**Comment by MangoloD** [comment]
> 太大了。。。建议你可视化gt看看是不是有问题。。。

我检查了一下，应该是没有问题的
![image](https://user-images.githubusercontent.com/52820275/127283726-d733a90c-3aed-432d-b553-19e837066b47.png)

**Comment by zhangming8** [comment]
你这还没收敛，多跑几个epoch在看

**Comment by ruinmessi** [comment]
不是没收敛的问题。就是scratch训练coco，一开始最大loss也就20不到，再检查检查GT的格式吧，还有确认model的初始化是对的（在yolox_base.py里），看起来conf的loss很诡异

**Comment by MangoloD** [comment]
> 不是没收敛的问题。就是scratch训练coco，一开始最大loss也就20不到，再检查检查GT的格式吧，还有确认model的初始化是对的（在yolox_base.py里），看起来conf的loss很诡异

好的，我瞅瞅

**Comment by MangoloD** [comment]
有点懵，不知道问题到底出在哪里了

**Comment by MangoloD** [comment]
> 不是没收敛的问题。就是scratch训练coco，一开始最大loss也就20不到，再检查检查GT的格式吧，还有确认model的初始化是对的（在yolox_base.py里），看起来conf的loss很诡异

![image](https://user-images.githubusercontent.com/52820275/127291609-6cec87a8-d48c-4e10-8351-e9285f106630.png)
我查看了img.shape, target, index，应该是没有错的
我查看了数据，应该是这样，也没问题

**Comment by ruinmessi** [comment]
你pull一下最新的update？  好像我们之前有个时刻的commit确实有问题。。。

**Comment by MangoloD** [comment]
> 你pull一下最新的update？ 好像我们之前有个时刻的commit确实有问题。。。

好的，我发现了一个问题，就数据似乎没有经过 __getitem__ 方法

**Comment by myh12138** [comment]
> > 你pull一下最新的update？ 好像我们之前有个时刻的commit确实有问题。。。
> 
> 好的，我发现了一个问题，就数据似乎没有经过 **getitem** 方法

应该不会没经过geitem吧，它是经过了MosaicDetection 的 gititem，因为yolox_base后面又有一个dataset = MosaicDetection.
我的map算出来也是0很奇怪，而且有时候都没有box。有没有建议这可能是什么原因。

**Comment by APeiZou** [comment]
@MangoloD 遇到了同样的评估map为0的问题，你是怎么解决的啊？

**Comment by qingshanjiu** [comment]
遇到了同样的问题，甚至在我评估之前，试着跑了十个epoch，结束的时候提示保存的best模型ap为0。请问各位有没有解决办法

**Comment by MangoloD** [comment]
> @MangoloD 遇到了同样的评估map为0的问题，你是怎么解决的啊？

暂时没找到原因，我尝试关闭mix-up，结果也是一样的，貌似很多人都遇到了相同的问题

**Comment by sunlinlin-aragon** [comment]
trainer.py 中 这行代码  if self.epoch + 1 == self.max_epoch - self.exp.no_aug_epochs or self.no_aug:   会控制 l1_loss 加入计算，
只有 l1_loss 加入计算了 AP才不会为0   ，大家看看是不这个问题引起的

**Comment by MangoloD** [comment]
我已经解决这个问题了，现在训练ap正常了

**Comment by MangoloD** [comment]
> 遇到了同样的问题，甚至在我评估之前，试着跑了十个epoch，结束的时候提示保存的best模型ap为0。请问各位有没有解决办法

我已经发现问题的原因了，解决了，现在正常了

**Comment by MangoloD** [comment]
> @MangoloD 遇到了同样的评估map为0的问题，你是怎么解决的啊？

我发现问题原因了，已经解决了

**Comment by pistachio0812** [comment]
> 我已经解决这个问题了，现在训练ap正常了

说啊，怎么解决的

**Comment by MangoloD** [comment]
> > 我已经解决这个问题了，现在训练ap正常了
> 
> 说啊，怎么解决的

[解决YOLOX训练时AP为0](https://blog.csdn.net/weixin_42166222/article/details/119637797?spm=1001.2014.3001.5502)

**Comment by 18789447455** [comment]
> 我已经解决了这个问题了，现在训练好了

请问你怎么解决的

**Comment by 18789447455** [comment]
请问怎么解决的
