### ISSUE TITLE
What happen to the data_time?

### ISSUE THREAD

**Issue by Xwmiss** [Megvii-BaseDetection/YOLOX#219]
![image](https://user-images.githubusercontent.com/59326436/127276407-fd1d4c36-7979-4286-960a-0f7c37f6c937.png)
I have trained YOLOX in other computer which is ok, while in this computer I find the data read waste so much time! What happen😢

**Comment by Xwmiss** [comment]
I notice the #72 
But I made my dataset to coco-style and get normal performance while with the same setting in this computer get bad performance. (Maybe the code get updated? )

**Comment by ruinmessi** [comment]
you may update to the latest version, see #216 and #224 for reference.

**Comment by Xwmiss** [comment]
> you may update to the latest version, see #216 and #224 for reference.

OK，I will take a look,
THX!
