### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 233-234: ordinal not in range(128)

### ISSUE THREAD

**Issue by zhishao** [Megvii-BaseDetection/YOLOX#220]
![image](https://user-images.githubusercontent.com/18610954/127277443-f817a951-f707-48a0-aa00-a33147154768.png)

**Comment by moured** [comment]
The demo worked well, all setup was done successfully. But, I get the same exact error for training.

**Comment by MrSuen** [comment]
你是在docker容器里运行的吗，我的之前出现此情况是因为配置Dockerfile时的ascii环境出现问题了
先
locale-gen en_US.UTF-8
vim /etc/default/locale
删除全部,添加如下
LC_ALL="en_US.UTF-8"
source /etc/default/locale
或者
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
或者
vim .profile
加入
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
source .profile
转载自https://blog.csdn.net/amcsc/article/details/84598581
如果出现每次退出容器再进入时修改被重置的情况，可以试试~/.bashrc或者vi /root/.bashrc 在末尾添加 source /etc/profile，保存退出

**Comment by zhishao** [comment]
@MrSuen 我尝试了你的方法 但是没有任何效果。

**Comment by moured** [comment]
> 你是在docker容器里运行的吗，我的之前出现此情况是因为配置Dockerfile时的ascii环境出现问题了
> 先
> locale-gen en_US.UTF-8
> vim /etc/default/locale
> 删除全部,添加如下
> LC_ALL="en_US.UTF-8"
> source /etc/default/locale
> 或者
> export LANGUAGE=en_US.UTF-8
> export LANG=en_US.UTF-8
> export LC_ALL=en_US.UTF-8
> 或者
> vim .profile
> 加入
> export LANGUAGE=en_US.UTF-8
> export LANG=en_US.UTF-8
> export LC_ALL=en_US.UTF-8
> source .profile
> 转载自https://blog.csdn.net/amcsc/article/details/84598581
> 如果出现每次退出容器再进入时修改被重置的情况，可以试试~/.bashrc或者vi /root/.bashrc 在末尾添加 source /etc/profile，保存退出

Worked for me ! Thanks.

**Comment by Pony23333** [comment]
OK, I met the same problem while I have no right to modify any files under /etc. The solution I found is to use export to change system environment [temperily[](https://www.cnblogs.com/lsdb/p/12470739.html)])

**Comment by litingsjj** [comment]
@zhishao 你好，请问链接里的步骤你是在docker里面操作的吗？我尝试：vi /etc/environment，但是还是：bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)，还是需要在外面设置好之后，再起docker？这样我这边还是没解决

**Comment by a-beginner-debug** [comment]
把yolox/core/trainer.py中的第127行，注释掉就行了，只是打印信息，对模型性能没有影响的
def before_train(self):
        logger.info("args: {}".format(self.args))
#         logger.info("exp value:\n{}".format(self.exp))

        # model related init
        torch.cuda.set_device(self.local_rank)
        model = self.exp.get_model()
        logger.info(
            "Model Summary: {}".format(get_model_info(model, self.exp.test_size))
        )
        model.to(self.device)
