### ISSUE TITLE
Multi positives use center 5×5 area in code

### ISSUE THREAD

**Issue by BokyLiu** [Megvii-BaseDetection/YOLOX#221]
https://github.com/Megvii-BaseDetection/YOLOX/blob/5945f9ca98bd8c41b50f6d683732254886faf128/yolox/models/yolo_head.py#L471
文章中说的是 "We simply assigns the center 3×3 area as positives"，代码中实际用的是5x5？

**Comment by ruinmessi** [comment]
SimOTA和最初的multi positive策略并不一样。3x3是不使用SimOTA时的区域
