### ISSUE TITLE
python3 tools/eval.py执行评估代码时出现错误 ：CUDA error: initialization error

### ISSUE THREAD

**Issue by ahong007007** [Megvii-BaseDetection/YOLOX#222]
执行评估代码python3 tools/eval.py -n yolox-x -c ../pth/yolox_x.pth.tar -b 16 -d 2 --conf 0.001

![image](https://user-images.githubusercontent.com/22077027/127286270-d84c0f89-f13b-4e61-9cc2-af7f1c7715a6.png)

**Comment by ahong007007** [comment]
train.py代码可以正常运行，eval.py代码不正常

python tools/train.py -n yolox-s -d 8 -b 64 --fp16 -o 
![image](https://user-images.githubusercontent.com/22077027/127289027-ea3b9329-649b-46d6-a10b-541feab4d8f2.png)

![image](https://user-images.githubusercontent.com/22077027/127289107-edf9b88b-c822-4e8e-b36b-497063ab83aa.png)

**Comment by ruinmessi** [comment]
Plz pull the latest updates
