### ISSUE TITLE
可以详细解释下yolo_head.py里面的get_in_boxes_info和dynamic_k_matching两个函数吗？

### ISSUE THREAD

**Issue by xiaowenhe** [Megvii-BaseDetection/YOLOX#223]
可以详细解释下yolo_head.py里面的get_in_boxes_info和dynamic_k_matching两个函数吗？，谢谢！
特别是get_in_boxes_info函数中第473-492行，is_in_center的具体含义？

谢谢！

**Comment by Joker316701882** [comment]
Please check [OTA](https://github.com/Megvii-BaseDetection/OTA) and our [Chinese blog ](
https://www.zhihu.com/question/473350307/answer/2021031747).
