### ISSUE TITLE
训练时的问题（类型转换的bug）

### ISSUE THREAD

**Issue by zqjnyr** [Megvii-BaseDetection/YOLOX#225]
![QQ截图20210728170720](https://user-images.githubusercontent.com/69241941/127295993-28af9aeb-e2d4-46bc-aac8-b405d0e804cc.jpg)

**Comment by ruinmessi** [comment]
Did it happen on your own dataset? We checked our VOC example and did not encounter this error.

**Comment by zqjnyr** [comment]
> 它发生在你自己的数据集上吗？我们检查了我们的 VOC 示例并没有遇到此错误。

对，自己的训练集上

**Comment by ruinmessi** [comment]
you have to first convert your annos from str to float. 
like:  
``` python
cur_pt = int(float(bbox.find(pt).text)) - 1
```

**Comment by WANGCHAO1996** [comment]
> ```python
> cur_pt = int(float(bbox.find(pt).text)) - 1
> ```
how to convert?

**Comment by maziyi234** [comment]
File "/home/maziyi/python/yolox4/YOLOX/yolox/data/datasets/voc.py", line 326, in _do_python_eval
    use_07_metric = True if float(self._year) < 2010 else False
                                  │    └ 'orange'
                                  └ <yolox.data.datasets.voc.VOCDetection object at 0x7f7214862790>

ValueError: could not convert string to float: 'orange'
目前这个问题我也遇到了 求大佬解答
