### ISSUE TITLE
用自己的数据集训练好的权重进行测试报错，参数不匹配，怎么解决？

### ISSUE THREAD

**Issue by lihui669** [Megvii-BaseDetection/YOLOX#231]
测试时，我用指令>python tools/eval.py -n  yolox-x -c YOLOX_outputs/yolox_base/best_ckpt.pth.tar -b 1 -d 1 --conf 0.001 --fp16 --test，报错，意思大概是模型需要的参数和权重里的参数大小不匹配，请问是什么原因呢？
![SU I}}6V9VL{Z7A {RHGK7](https://user-images.githubusercontent.com/40649829/127335169-a6ba3972-6e70-4413-bb5f-30b2741dd764.png)
![P)JUP()~}Y%9QU{R48~R4YP](https://user-images.githubusercontent.com/40649829/127335199-c01c3ea2-e753-4084-ba1a-c5b729cb79a0.png)

**Comment by ruinmessi** [comment]
You load a yolox-L weights to a yolox-X model

**Comment by lihui669** [comment]
> You load a yolox-L weights to a yolox-X model

为什么会这样，我明明是用yolox-x的预训练权重训练的网路，这是我训练时用的命令python tools/train.py -f yolox/exp/yolox_base.py -d 1 -b 4 --fp16 -o -c models/yolox_x.pth.tar

**Comment by ruinmessi** [comment]
You should use `-n yolox-x' or `-f exps/default/yolox_x.py' to specify the yolox-x model. For yolox_base.py, it just adopts the default width=1.0, depth=1.0, generating a yolox-l model. So your pre-trained yolox-x weight is also not correctly loaded.
