### ISSUE TITLE
WARNING:Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 96, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([2, 96, 1, 1]).

### ISSUE THREAD

**Issue by haileykwak** [Megvii-BaseDetection/YOLOX#233]
Hi Im training my custom datasets in voc format.
training well now but have warning at start.

could this warning have bad result? or just ignore it?

my command and waning below,
$ python3 tools/train.py -f exps/example/yolox_voc/yolox_voc_tiny.py -d 1 -b 64 --fp16 -o -c yolox_tiny.pth.tar 

![image](https://user-images.githubusercontent.com/69446169/127415847-d43f9cd6-c254-472b-8eea-2a79436aa1e1.png)

**Comment by F0xZz** [comment]
you use the custom datasets you should change the code in the 
yolox/data/datasets/voc.py
data/datasets/voc_classes.py
yolox/exp/yolox_base.py

**Comment by haileykwak** [comment]
I changed the code in voc_classes.py , yolox_base.py.
which portion of the code should be changed in voc.py?

**Comment by ruinmessi** [comment]
> Hi Im training my custom datasets in voc format.
> training well now but have warning at start.
> 
> could this warning have bad result? or just ignore it?
> 
> my command and waning below,
> $ python3 tools/train.py -f exps/example/yolox_voc/yolox_voc_tiny.py -d 1 -b 64 --fp16 -o -c yolox_tiny.pth.tar
> 
> ![image](https://user-images.githubusercontent.com/69446169/127415847-d43f9cd6-c254-472b-8eea-2a79436aa1e1.png)

It's normal, as the coco pretrained weight has 80 classes but voc only has 20
