### ISSUE TITLE
About TensorRT C++ issues (关于TensorRT C++ 版本的问题)

### ISSUE THREAD

**Issue by F0xZz** [Megvii-BaseDetection/YOLOX#234]
I just use YOLOX  ,but i have some question about the TensorRT c++ version
1.I used the offical the method to convert the pth.tar weights to engine ,Use the torch2trt tool and install this packages with this command "python setup.py install --plugins" , i use the my custom path to point the TensorRT ,then i convert this pth.tar there were no error shows ,but when i wanna use this engine in your demo code ,there was an error happened shows that 
**getPluginCreator could not find plugin interpolatetorch2trt version 1**. 
2.When i use my custom datasets to train data , i convert to engine by onnx is right and can predict shows no error ,but the result the shows the obj.prob >1 . I have no idea about this
我使用了YOLOX，有以下几个问题:
1.我使用官方权重，尝试使用torch2trt并且使用 "python setup.py install --plugins" 该命令显示成功安装，且转换engine成功后显示如下问题**getPluginCreator could not find plugin interpolatetorch2trt version 1**. 
2.我使用自定义数据集和种类进行训练，得到的权重，使用Onnx再转engine过程正常，且导入engine模型可进行前向推理，但是结果中会出现obj.prob>1的结果，请问以下是什么原因导致的。

**Comment by F0xZz** [comment]
i would like to add a point that i train the 1classes ,and test the weights **pth.tar** and **onnx** show the right result in the pic .
but when i use the onnx to convert trt when i use the **engine** file is show the a lot of result box and some box obj.prob >1 and inf will show. so have any one has this problem 
我测试过单类训练，对pth.tar 和 Onnx权重进行过训练，全部结果正常，但是一旦用onnx to trt 的engine文件就显示出有部分置信度出现超过1和inf的现象

**Comment by F0xZz** [comment]
ok , i got know the reason about the c++ code my fault ,there was a set anchor varible just like yolo serial

**Comment by liangbaqiang** [comment]
我修改之后还是出现了prob > 1得情况，请问还需要改哪边
