### ISSUE TITLE
当我fix bug of multi-machine training之后，出现这个问题！

### ISSUE THREAD

**Issue by sunmooncode** [Megvii-BaseDetection/YOLOX#246]
UnboundLocalError: local variable 'port' referenced before assignment

**Comment by ruinmessi** [comment]
#240  Do you modify the code as this PR?

**Comment by sunmooncode** [comment]
使用单卡没问题 多卡报这个错！

**Comment by sunmooncode** [comment]
@ruinmessi yes

**Comment by ruinmessi** [comment]
I check and run the code without any problem. The PR is merged now, you can pull the updates and try again.

**Comment by sunmooncode** [comment]
@ruinmessi thanks, I have solved it.
