### ISSUE TITLE
Windows10  部署

### ISSUE THREAD

**Issue by Dandelion111** [Megvii-BaseDetection/YOLOX#25]
请问有没有win10部署教程？

**Comment by FateScript** [comment]
code本身没有考虑跨平台的内容，在我们的理解中部署平台的内容可能比较相似。以及像是ncnn的部署的内容已经提供了param和bin，很多流程无需再走，你可以尝试后遇到问题再发issue.

**Comment by Dandelion111** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2021年7月21日(星期三) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Megvii-BaseDetection/YOLOX] Windows10  部署 (#25)





 
code本身没有考虑跨平台的内容，在我们的理解中部署平台的内容可能比较相似。以及像是ncnn的部署的内容已经提供了param和bin，很多流程无需再走，你可以尝试后遇到问题再发issue.

**Comment by zlszhonglongshen** [comment]
![image](https://user-images.githubusercontent.com/9023908/126473112-02e58f0c-b40c-41b3-87f4-a91593aa64cc.png)

**Comment by YaphetS-X** [comment]
Running on windows10 will meet the error "ModuleNotFoundError: No module named 'resource'"
resource is a Unix specific package and will raise an error when trying to use it in Windows. according to [stackoverflow](https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource)
After i deleted line 6,34,35 in setup_env.py, it run successfully on my Windows.

**Comment by Hezhexi2002** [comment]
> Running on windows10 will meet the error "ModuleNotFoundError: No module named 'resource'"
> resource is a Unix specific package and will raise an error when trying to use it in Windows. according to [stackoverflow](https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource)
> After i deleted line 6,34,35 in setup_env.py, it run successfully on my Windows.

I just commented it and it works too

**Comment by haolongzhangm** [comment]
可以用megengine 部署， megengine 原生支持windows等各种OS

**Comment by jimmytyt** [comment]
> Running on windows10 will meet the error "ModuleNotFoundError: No module named 'resource'"
> resource is a Unix specific package and will raise an error when trying to use it in Windows. according to [stackoverflow](https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource)
> After i deleted line 6,34,35 in setup_env.py, it run successfully on my Windows.

![image](https://user-images.githubusercontent.com/18440163/126610372-07adebdd-cf1e-4f0b-8951-9da82b89bb72.png)
it does't work on my WIN10

**Comment by Hezhexi2002** [comment]
> > Running on windows10 will meet the error "ModuleNotFoundError: No module named 'resource'"
> > resource is a Unix specific package and will raise an error when trying to use it in Windows. according to [stackoverflow](https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource)
> > After i deleted line 6,34,35 in setup_env.py, it run successfully on my Windows.
> 
> ![image](https://user-images.githubusercontent.com/18440163/126610372-07adebdd-cf1e-4f0b-8951-9da82b89bb72.png)
> it does't work on my WIN10
Are you using train.py to train your custom datasets?If it is ,you must create your own exp_file,just follow the step in the link:https://github.com/Megvii-BaseDetection/YOLOX/blob/main/docs/train_custom_data.md and then try it again.

**Comment by cmFighting** [comment]
windows10，显卡rtx2070ti，cuda10.2可以编译通过
我在`setup.py`第50行修改成了
`with open("README.md", "r", encoding="utf-8") as f:`
效果如下，非常nice！：
![image](https://user-images.githubusercontent.com/42832508/126985679-121cd2d5-eec3-46b1-984f-efc944f9ea74.png)

![dog](https://user-images.githubusercontent.com/42832508/126985700-9a7e576d-dd7a-42c1-9413-5094dab5d611.jpg)

**Comment by Hezhexi2002** [comment]
> windows10，显卡rtx2070ti，cuda10.2可以编译通过
> **我在`setup.py`第50行修改成了**
> `with open("README.md", "r", encoding="utf-8") as f:`
> 效果如下，非常nice！：
> ![image](https://user-images.githubusercontent.com/42832508/126985679-121cd2d5-eec3-46b1-984f-efc944f9ea74.png)
> 
> ![dog](https://user-images.githubusercontent.com/42832508/126985700-9a7e576d-dd7a-42c1-9413-5094dab5d611.jpg)

I used to have the problem with you and I solve it in the same way with you

**Comment by Joker316701882** [comment]
Related Chinese blog:
https://blog.csdn.net/weixin_43218120/article/details/119170073
https://blog.csdn.net/Dora_blank/article/details/119087239
