### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by liuwei3612** [Megvii-BaseDetection/YOLOX#250]
按照训练步骤操作，出现下面的问题：
![图片](https://user-images.githubusercontent.com/12774651/127453776-7a7b29da-6123-4aa9-960c-2b26f615ec22.png)

**Comment by verages** [comment]
git clone https://github.com/NVIDIA/apex
cd apex
pip3 install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

**Comment by liuwei3612** [comment]
一个新的问题：
![图片](https://user-images.githubusercontent.com/12774651/127471218-21e1935a-c61b-40a0-a2fc-dbd1543f7ec6.png)

**Comment by 759401524** [comment]
你的数据集中有 `bk002` 这个类别，但你的训练目标里没有 `bk002`

**Comment by liuwei3612** [comment]
> 你的数据集中有 `bk002` 这个类别，但你的训练目标里没有 `bk002`

![图片](https://user-images.githubusercontent.com/12774651/127472552-69c90d76-954b-4ea0-a5c5-0d97e5f171a3.png)
有这个类别啊

**Comment by liuwei3612** [comment]
这个数据集在darknet下训练是好的

**Comment by liuwei3612** [comment]
![图片](https://user-images.githubusercontent.com/12774651/127622212-866c5ebd-2f85-43ec-b4de-970f0f1168f8.png)
训练时这个错误，大家遇到过吗？怎么解决？

**Comment by zhangming8** [comment]
> ![图片](https://user-images.githubusercontent.com/12774651/127622212-866c5ebd-2f85-43ec-b4de-970f0f1168f8.png)
> 训练时这个错误，大家遇到过吗？怎么解决？

每日鲜语牛奶？这是你自己数据，在VOC_CLASSES里面没有设置这个标签吧

**Comment by FateScript** [comment]
Close due to no update.
