### ISSUE TITLE
对于simota 的一个疑问

### ISSUE THREAD

**Issue by yankai317** [Megvii-BaseDetection/YOLOX#257]
![image](https://user-images.githubusercontent.com/20473498/127495968-bdd1b2e3-09b1-457a-8ac7-640b261a528f.png)
这部分代码将部分重复anchor的gt框取消匹配，最后会导致 部分gt框没有对应的anchor，相当于这部分gt框没有计算loss ,这样做是否会影响精度？

**Comment by ruinmessi** [comment]
For any question about our paper, plz discuss it via email. Thx!

**Comment by DDGRCF** [comment]
您好，我也有这样的疑惑
