### ISSUE TITLE
ImportError: /home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/exps/default/yolox_s.py doesn't contains class named 'Exp'

### ISSUE THREAD

**Issue by Abandon-ht** [Megvii-BaseDetection/YOLOX#26]
(YOLOX) ncy@Lenovo:~/PycharmProjects/YOLOX$ python tools/trt.py -n yolox-s -c yolox_s.pth.tar
2021-07-20 20:34:44.442 | ERROR    | __main__:<module>:77 - An error has been caught in function '<module>', process 'MainProcess' (180525), thread 'MainThread' (140272824201600):
Traceback (most recent call last):

  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/yolox/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
                  │         │             │  │    │        └ '/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/exps/default/yolox_s.py'
                  │         │             │  │    └ <function basename at 0x7f93ceec7e50>
                  │         │             │  └ <module 'posixpath' from '/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/posixpath.py'>
                  │         │             └ <module 'os' from '/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/os.py'>
                  │         └ <function import_module at 0x7f93cee564c0>
                  └ <module 'importlib' from '/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/importlib/__init__.py'>
  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'yolox_s'
           │          └ <function _gcd_import at 0x7f93cef8c310>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'yolox_s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

> File "/home/ncy/PycharmProjects/YOLOX/tools/trt.py", line 77, in <module>
    main()
    └ <function main at 0x7f93045813a0>

  File "/home/ncy/PycharmProjects/YOLOX/tools/trt.py", line 36, in main
    exp = get_exp(args.exp_file, args.name)
          │       │    │         │    └ 'yolox-s'
          │       │    │         └ Namespace(experiment_name=None, name='yolox-s', exp_file=None, ckpt='yolox_s.pth.tar')
          │       │    └ None
          │       └ Namespace(experiment_name=None, name='yolox-s', exp_file=None, ckpt='yolox_s.pth.tar')
          └ <function get_exp at 0x7f9304581310>

  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/yolox/exp/build.py", line 50, in get_exp
    return get_exp_by_name(exp_name)
           │               └ 'yolox-s'
           └ <function get_exp_by_name at 0x7f9304581280>
  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/yolox/exp/build.py", line 34, in get_exp_by_name
    return get_exp_by_file(exp_path)
           │               └ '/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/exps/default/yolox_s.py'
           └ <function get_exp_by_file at 0x7f93045811f0>
  File "/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/yolox/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
                                                                     └ '/home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/exps/default/yolox_s.py'

ImportError: /home/ncy/anaconda3/envs/YOLOX/lib/python3.9/site-packages/yolox-0.1.0-py3.9-linux-x86_64.egg/exps/default/yolox_s.py doesn't contains class named 'Exp'

**Comment by ruinmessi** [comment]
Have you correctly installed [tensorrt](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar) and [torch2trt](https://github.com/NVIDIA-AI-IOT/torch2trt)? I run the same command as 
```bash
python tools/trt.py -n yolox-s -c yolox_s.pth.tar
```
and it works well.

**Comment by Abandon-ht** [comment]
> Have you correctly installed [tensorrt](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-tar) and [torch2trt](https://github.com/NVIDIA-AI-IOT/torch2trt)? I run the same command as 
> ```bash
> python tools/trt.py -n yolox-s -c yolox_s.pth.tar
> ```
> and it works well. 

think you！Maybe it’s a problem with my Tensorrt or torch2trt installation. I will try to use the docker container tomorrow.

**Comment by pistachio0812** [comment]
have you solved it?
