### ISSUE TITLE
Faster than Yolo series？

### ISSUE THREAD

**Issue by lliming2006** [Megvii-BaseDetection/YOLOX#266]
Acceleration yoloX with tensorRT，then  compareded reasoning speed with Yolo series models without tensorrt acceleration？

**Comment by ruinmessi** [comment]
If you read our paper carefully, you would find that we compare the inference speed with the same setting: fp16, batch=1, v100. 
We provide the tensorRT demo for convenient deployment, not for an insane sarcasm like yours.

**Comment by lliming2006** [comment]
BUT  The reproduced results are quite different from those described in the paper, why?
Have you tested on other data sets？There are too many “water” papers！




----- 原始邮件 -----
发件人：Songtao Liu ***@***.***>
收件人：Megvii-BaseDetection/YOLOX ***@***.***>
抄送人：lliming2006 ***@***.***>,  Author ***@***.***>
主题：Re:_[Megvii-BaseDetection/YOLOX]_Faster_than_Yolo_series？_(#266)
日期：2021年07月30日 11点58分


If you read our paper carefully, you would find that we compare the inference speed with the same setting: fp16, batch=1, v100.

We provide the tensorRT demo for convenient deployment, not for an insane sarcasm like yours.

**Comment by lliming2006** [comment]
BUT  The reproduced results are quite different from those described in the paper, why?
Have you tested on other data sets？

**Comment by Joker316701882** [comment]
“BUT The reproduced results are quite different from those described in the paper, why?”
Pull our latest branch then try. We have fixed some fatal issues. The results are reproducible, even better than reported in our paper. This is our fault.

"Have you tested on other data sets"
Please, read our paper carefully then ask some useful question.
