### ISSUE TITLE
OOM at 10th epoch when training on VOC

### ISSUE THREAD

**Issue by scuizhibin** [Megvii-BaseDetection/YOLOX#270]

**Comment by Joker316701882** [comment]
@scuizhibin Please pull our latest branch. We have fixed the memory leak issue.

**Comment by liuwei3612** [comment]
![图片](https://user-images.githubusercontent.com/12774651/127622395-7a3988a0-52d8-49f6-8730-63399de6f6e4.png)
我训练时遇到这个问题，帮忙看下，谢谢

**Comment by scuizhibin** [comment]
使用最新的版本试一试。


---Original---
From: ***@***.***&gt;
Date: Fri, Jul 30, 2021 16:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Megvii-BaseDetection/YOLOX] OOM at 10th epoch when training on VOC (#270)




 

 我训练时遇到这个问题，帮忙看下，谢谢
 
&mdash;

**Comment by Joker316701882** [comment]
@liuwei3612 This is not the same issue. Reopen another if necessary.
