### ISSUE TITLE
How should I look  the weight file ?

### ISSUE THREAD

**Issue by sunmooncode** [Megvii-BaseDetection/YOLOX#271]
![Screenshot from 2021-07-30 15-07-12](https://user-images.githubusercontent.com/86471590/127615467-7d3f6491-ba6f-41ab-bebc-3b3f068d50bd.png)
What is the meaning of these digital files ？

**Comment by 1VeniVediVeci1** [comment]
the whole tar file is the weight

**Comment by Joker316701882** [comment]
@sunmooncode Do not untar/unzip it. For example, yolox_s.pth.tar. You can directly change its name to yolox_s.pth first. Then use [netron](https://netron.app/) to explore the model details.
