### ISSUE TITLE
how to close eval while training？

### ISSUE THREAD

**Issue by raymondchu-z** [Megvii-BaseDetection/YOLOX#272]
`self.eval_interval = 500，self.max_epoch = 30，self.no_aug_epochs = 10` has been set in exp, but still eval after epoch20.I think it is related to `self.no_aug_epochs = 10`.
So how to close eval while training？

**Comment by ruinmessi** [comment]
We set eval_interval to 1 after close mosaic: https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/core/trainer.py#L203
So you can modify this line to close all eval

**Comment by raymondchu-z** [comment]
thx!
