### ISSUE TITLE
mask_b = np.minimum(boxes[:, 2], boxes[:, 3]) > 8

### ISSUE THREAD

**Issue by ziyeZzz** [Megvii-BaseDetection/YOLOX#273]
Hi, 请问在yolox/data/data_augment.py中的TrainTransform中mask_b = np.minimum(boxes[:, 2], boxes[:, 3]) > 8这一行代码中的8代表什么意思？
另外我正在尝试修改yolox源码用于检测不规则四边形，您认为是否合适呢？

谢谢解答。

**Comment by hhaAndroid** [comment]
@Joker316701882  Have you investigated the impact of this setting on the final performance?

**Comment by Joker316701882** [comment]
@Joker316701882 No. It's just some weird code from the [original codebase](https://github.com/ruinmessi/ASFF) we used.

**Comment by ruinmessi** [comment]
> @Joker316701882 No. It's just some weird code from the [original codebase](https://github.com/ruinmessi/ASFF) we used.

Hey, not weird ok?  I set the number just because the minimal stride of FPN is 8. But I did not investigate the impact.

**Comment by hhaAndroid** [comment]
@ruinmessi OK,Thank you!

**Comment by jovialio** [comment]
@hhaAndroid Have you investigated this impact of this on mmdet's version of YoloX? Trained my custom dataset using Megvii and mmdet but was not able to hit Megvii's performance. 

This portion of the code is interesting in filtering out boxes <1 width and height and using all the boxes if all boxes were filtered by the mask.

`mask_b = np.minimum(boxes[:, 2], boxes[:, 3]) > 1
        boxes_t = boxes[mask_b]
        labels_t = labels[mask_b]

        if len(boxes_t) == 0:
            image_t, r_o = preproc(image_o, input_dim)
            boxes_o *= r_o
            boxes_t = boxes_o
            labels_t = labels_o`
