### ISSUE TITLE
error in training

### ISSUE THREAD

**Issue by fxt960803** [Megvii-BaseDetection/YOLOX#277]
2021-07-30 17:15:40 | INFO     | yolox.core.trainer:246 - epoch: 185/200, iter: 10/44, mem: 3298Mb, iter_time: 0.245s, data_time: 0.001s, total_loss: inf, iou_loss: 5.0, l1_loss: inf, conf_loss:
9.3, cls_loss: 0.4, lr: 3.128e-05, size: 768, ETA: 0:03:17
------------CPU Mode for This Batch-------------
2021-07-30 17:15:41 | ERROR    | yolox.models.yolo_head:332 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in thi
s batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2021-07-30 17:15:41 | INFO     | yolox.core.trainer:186 - Training of experiment is done and the best AP is 0.07
2021-07-30 17:15:41 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (7928), thread 'MainThread' (14816):
Traceback (most recent call last):

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 315, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x00000179DC97C3A0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(128, 128, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x00000179DC97C310>

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False], device='cuda:0')
        │    │                  │     │               │           └ 1
        │    │                  │     │               └ tensor([0.], device='cuda:0', dtype=torch.float16)
        │    │                  │     └ tensor([], device='cuda:0', size=(1, 0))
        │    │                  └ tensor([], device='cuda:0', size=(1, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x00000179DC97C4C0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 620, in dynamic_k_matching
    topk_ious, _ = torch.topk(ious_in_boxes_matrix, n_candidate_k, dim=1)
                   │     │    │                     └ 10
                   │     │    └ tensor([], device='cuda:0', size=(1, 0))
                   │     └ <built-in method topk of type object at 0x00007FFA428C6620>
                   └ <module 'torch' from 'D:\\anaconda\\envs\\pytorch1.8\\lib\\site-packages\\torch\\__init__.py'>

RuntimeError: invalid argument 5: k not in range for dimension at C:/w/b/windows/pytorch/aten/src\THC/generic/THCTensorTopK.cu:24

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "train.py", line 113, in <module>
    launch(
    └ <function launch at 0x00000179DA271040>

> File "D:\YOLOX-main\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x00000179DC8ADCA0>

  File "train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x00000179DBABFC10>
    └ <yolox.core.trainer.Trainer object at 0x00000179DC8AEF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x00000179DC86DE50>
    └ <yolox.core.trainer.Trainer object at 0x00000179DC8AEF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 80, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x00000179DC88B3A0>
    └ <yolox.core.trainer.Trainer object at 0x00000179DC8AEF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 86, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x00000179DC88B430>
    └ <yolox.core.trainer.Trainer object at 0x00000179DC8AEF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 98, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ tensor([[[   0.0000, 1140.0000,    4.4219,    4.4219,    7.7734],
              │    │     │                [   0.0000,    0.0000,    0.0000,    0.0000,    0....
              │    │     └ tensor([[[[-0.8164, -0.8335, -0.8335,  ..., -0.1656, -0.1656, -0.1656],
              │    │                 [-0.7822, -0.7993, -0.7993,  ..., -0.1656, ...
              │    └ YOLOX(
              │        (backbone): YOLOPAFPN(
              │          (backbone): CSPDarknet(
              │            (stem): Focus(
              │              (conv): BaseConv(
              │                (conv): ...
              └ <yolox.core.trainer.Trainer object at 0x00000179DC8AEF40>

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[-0.8164, -0.8335, -0.8335,  ..., -0.1656, -0.1656, -0.1656],
             │    │                    [-0.7822, -0.7993, -0.7993,  ..., -0.1656,...
             │    └ <function YOLOX.forward at 0x00000179DC97C820>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "D:\YOLOX-main\yolox\models\yolox.py", line 34, in forward
    loss, iou_loss, conf_loss, cls_loss, l1_loss, num_fg = self.head(
                                                           └ YOLOX(
                                                               (backbone): YOLOPAFPN(
                                                                 (backbone): CSPDarknet(
                                                                   (stem): Focus(
                                                                     (conv): BaseConv(
                                                                       (conv): ...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ ((tensor([[[[-7.0618e-02, -1.7688e-01, -1.7676e-01,  ..., -2.0218e-02,
             │    │                      4.5258e-02,  1.2323e-01],
             │    │                    [-2.71...
             │    └ <function YOLOXHead.forward at 0x00000179DC97C040>
             └ YOLOXHead(
                 (cls_convs): ModuleList(
                   (0): Sequential(
                     (0): BaseConv(
                       (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 197, in forward
    return self.get_losses(
           │    └ <function YOLOXHead.get_losses at 0x00000179DC97C1F0>
           └ YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 344, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x00000179DC97C3A0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(128, 128, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x00000179DC97C310>

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False])
        │    │                  │     │               │           └ 1
        │    │                  │     │               └ tensor([0.])
        │    │                  │     └ tensor([], size=(1, 0))
        │    │                  └ tensor([], size=(1, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x00000179DC97C4C0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 620, in dynamic_k_matching
    topk_ious, _ = torch.topk(ious_in_boxes_matrix, n_candidate_k, dim=1)
                   │     │    │                     └ 10
                   │     │    └ tensor([], size=(1, 0))
                   │     └ <built-in method topk of type object at 0x00007FFA428C6620>
                   └ <module 'torch' from 'D:\\anaconda\\envs\\pytorch1.8\\lib\\site-packages\\torch\\__init__.py'>

RuntimeError: selected index k out of range

**Comment by ruinmessi** [comment]
seems your location candidate is even smaller than 10. 
you can modify  [this line](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L619) to
```python
n_candidate_k = min(10, ious_in_boxes_matrix.size(1))
```

**Comment by fxt960803** [comment]
> seems your location candidate is even smaller than 10.
> you can modify [this line](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L619) to
> 
> ```python
> n_candidate_k = min(10, ious_in_boxes_matrix.size(1))
> ```

谢谢您的回答，我再去进行尝试

**Comment by fxt960803** [comment]
> seems your location candidate is even smaller than 10.
> you can modify [this line](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L619) to
> 
> ```python
> n_candidate_k = min(10, ious_in_boxes_matrix.size(1))
> ```

2021-07-30 18:17:50 | ERROR    | yolox.models.yolo_head:332 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in thi
s batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2021-07-30 18:17:50 | INFO     | yolox.core.trainer:186 - Training of experiment is done and the best AP is 0.00
2021-07-30 18:17:50 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (4548), thread 'MainThread' (8516):
Traceback (most recent call last):

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 315, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x000001FA32D4C430>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(128, 128, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x000001FA32D4C3A0>

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False], device='cuda:0')
        │    │                  │     │               │           └ 4
        │    │                  │     │               └ tensor([0., 0., 0., 0.], device='cuda:0', dtype=torch.float16)
        │    │                  │     └ tensor([], device='cuda:0', size=(4, 0))
        │    │                  └ tensor([], device='cuda:0', size=(4, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x000001FA32D4C550>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 623, in dynamic_k_matching
    _, pos_idx = torch.topk(
    │            │     └ <built-in method topk of type object at 0x00007FF9F22A6620>
    │            └ <module 'torch' from 'D:\\anaconda\\envs\\pytorch1.8\\lib\\site-packages\\torch\\__init__.py'>
    └ tensor([], device='cuda:0', size=(4, 0), dtype=torch.int64)

RuntimeError: invalid argument 5: k not in range for dimension at C:/w/b/windows/pytorch/aten/src\THC/generic/THCTensorTopK.cu:24


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "train.py", line 113, in <module>
    launch(
    └ <function launch at 0x000001FA306D1040>

> File "D:\YOLOX-main\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001FA32CBDCA0>

  File "train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001FA31ECFC10>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000001FA32C7CE50>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 80, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x000001FA32C9B3A0>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 86, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x000001FA32C9B430>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 98, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ tensor([[[   0.0000,  172.3750,  341.0000,  157.2500,  330.5000],
              │    │     │                [   0.0000,  259.2500,  355.5000,   58.5625,  301....
              │    │     └ tensor([[[[ 0.4165,  0.9131,  1.0156,  ..., -0.1656, -0.1656, -0.1656],
              │    │                 [-0.0629, -0.5938, -0.0116,  ..., -0.1656, ...
              │    └ YOLOX(
              │        (backbone): YOLOPAFPN(
              │          (backbone): CSPDarknet(
              │            (stem): Focus(
              │              (conv): BaseConv(
              │                (conv): ...
              └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[ 0.4165,  0.9131,  1.0156,  ..., -0.1656, -0.1656, -0.1656],
             │    │                    [-0.0629, -0.5938, -0.0116,  ..., -0.1656,...
             │    └ <function YOLOX.forward at 0x000001FA32D4C8B0>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "D:\YOLOX-main\yolox\models\yolox.py", line 34, in forward
    loss, iou_loss, conf_loss, cls_loss, l1_loss, num_fg = self.head(
                                                           └ YOLOX(
                                                               (backbone): YOLOPAFPN(
                                                                 (backbone): CSPDarknet(
                                                                   (stem): Focus(
                                                                     (conv): BaseConv(
                                                                       (conv): ...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ ((tensor([[[[-2.7441e-01, -2.7808e-01,  5.4541e-01,  ..., -2.3694e-01,
             │    │                     -2.4548e-01, -2.2803e-01],
             │    │                    [-2.66...
             │    └ <function YOLOXHead.forward at 0x000001FA32D4C0D0>
             └ YOLOXHead(
                 (cls_convs): ModuleList(
                   (0): Sequential(
                     (0): BaseConv(
                       (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 197, in forward
    return self.get_losses(
           │    └ <function YOLOXHead.get_losses at 0x000001FA32D4C280>
           └ YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 344, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x000001FA32D4C430>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(128, 128, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x000001FA32D4C3A0>

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False])
        │    │                  │     │               │           └ 4
        │    │                  │     │               └ tensor([0., 0., 0., 0.])
        │    │                  │     └ tensor([], size=(4, 0))
        │    │                  └ tensor([], size=(4, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x000001FA32D4C550>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 623, in dynamic_k_matching
    _, pos_idx = torch.topk(
    │            │     └ <built-in method topk of type object at 0x00007FF9F22A6620>
    │            └ <module 'torch' from 'D:\\anaconda\\envs\\pytorch1.8\\lib\\site-packages\\torch\\__init__.py'>
    └ tensor([], size=(4, 0), dtype=torch.int64)

RuntimeError: selected index k out of range

又出现了这样的问题

**Comment by fxt960803** [comment]
> seems your location candidate is even smaller than 10.
> you can modify [this line](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L619) to
> 
> ```python
> n_candidate_k = min(10, ious_in_boxes_matrix.size(1))
> ```

2021-07-30 18:17:50 | ERROR    | yolox.models.yolo_head:332 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in thi
s batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2021-07-30 18:17:50 | INFO     | yolox.core.trainer:186 - Training of experiment is done and the best AP is 0.00
2021-07-30 18:17:50 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (4548), thread 'MainThread' (8516):
Traceback (most recent call last):

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 315, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x000001FA32D4C430>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(128, 128, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x000001FA32D4C3A0>

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False], device='cuda:0')
        │    │                  │     │               │           └ 4
        │    │                  │     │               └ tensor([0., 0., 0., 0.], device='cuda:0', dtype=torch.float16)
        │    │                  │     └ tensor([], device='cuda:0', size=(4, 0))
        │    │                  └ tensor([], device='cuda:0', size=(4, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x000001FA32D4C550>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 623, in dynamic_k_matching
    _, pos_idx = torch.topk(
    │            │     └ <built-in method topk of type object at 0x00007FF9F22A6620>
    │            └ <module 'torch' from 'D:\\anaconda\\envs\\pytorch1.8\\lib\\site-packages\\torch\\__init__.py'>
    └ tensor([], device='cuda:0', size=(4, 0), dtype=torch.int64)

RuntimeError: invalid argument 5: k not in range for dimension at C:/w/b/windows/pytorch/aten/src\THC/generic/THCTensorTopK.cu:24


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "train.py", line 113, in <module>
    launch(
    └ <function launch at 0x000001FA306D1040>

> File "D:\YOLOX-main\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001FA32CBDCA0>

  File "train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001FA31ECFC10>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000001FA32C7CE50>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 80, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x000001FA32C9B3A0>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 86, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x000001FA32C9B430>
    └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 98, in train_one_iter
    outputs = self.model(inps, targets)
              │    │     │     └ tensor([[[   0.0000,  172.3750,  341.0000,  157.2500,  330.5000],
              │    │     │                [   0.0000,  259.2500,  355.5000,   58.5625,  301....
              │    │     └ tensor([[[[ 0.4165,  0.9131,  1.0156,  ..., -0.1656, -0.1656, -0.1656],
              │    │                 [-0.0629, -0.5938, -0.0116,  ..., -0.1656, ...
              │    └ YOLOX(
              │        (backbone): YOLOPAFPN(
              │          (backbone): CSPDarknet(
              │            (stem): Focus(
              │              (conv): BaseConv(
              │                (conv): ...
              └ <yolox.core.trainer.Trainer object at 0x000001FA32CBFF40>

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[ 0.4165,  0.9131,  1.0156,  ..., -0.1656, -0.1656, -0.1656],
             │    │                    [-0.0629, -0.5938, -0.0116,  ..., -0.1656,...
             │    └ <function YOLOX.forward at 0x000001FA32D4C8B0>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "D:\YOLOX-main\yolox\models\yolox.py", line 34, in forward
    loss, iou_loss, conf_loss, cls_loss, l1_loss, num_fg = self.head(
                                                           └ YOLOX(
                                                               (backbone): YOLOPAFPN(
                                                                 (backbone): CSPDarknet(
                                                                   (stem): Focus(
                                                                     (conv): BaseConv(
                                                                       (conv): ...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ ((tensor([[[[-2.7441e-01, -2.7808e-01,  5.4541e-01,  ..., -2.3694e-01,
             │    │                     -2.4548e-01, -2.2803e-01],
             │    │                    [-2.66...
             │    └ <function YOLOXHead.forward at 0x000001FA32D4C0D0>
             └ YOLOXHead(
                 (cls_convs): ModuleList(
                   (0): Sequential(
                     (0): BaseConv(
                       (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 197, in forward
    return self.get_losses(
           │    └ <function YOLOXHead.get_losses at 0x000001FA32D4C280>
           └ YOLOXHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 344, in get_losses
    ) = self.get_assignments(  # noqa
        │    └ <function YOLOXHead.get_assignments at 0x000001FA32D4C430>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\anaconda\envs\pytorch1.8\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (YOLOXHead(
           │         (cls_convs): ModuleList(
           │           (0): Sequential(
           │             (0): BaseConv(
           │               (conv): Conv2d(128, 128, kernel_size...
           └ <function YOLOXHead.get_assignments at 0x000001FA32D4C3A0>

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 511, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ tensor([False, False, False,  ..., False, False, False])
        │    │                  │     │               │           └ 4
        │    │                  │     │               └ tensor([0., 0., 0., 0.])
        │    │                  │     └ tensor([], size=(4, 0))
        │    │                  └ tensor([], size=(4, 0))
        │    └ <function YOLOXHead.dynamic_k_matching at 0x000001FA32D4C550>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "D:\YOLOX-main\yolox\models\yolo_head.py", line 623, in dynamic_k_matching
    _, pos_idx = torch.topk(
    │            │     └ <built-in method topk of type object at 0x00007FF9F22A6620>
    │            └ <module 'torch' from 'D:\\anaconda\\envs\\pytorch1.8\\lib\\site-packages\\torch\\__init__.py'>
    └ tensor([], size=(4, 0), dtype=torch.int64)

RuntimeError: selected index k out of range

修改后还是报错

**Comment by ratcat1232** [comment]
您好，我也遇到了和您一样的问题#267。也是在倒数第15个epoch，即close_mosaic这块提示OOM和CPU mode is applied然后训练中断。我修改了self.no_aug_epochs的参数，每次也都是该epoch中断。
如果您解决了此问题，可否在楼中说明一下解决方法，谢谢！

**Comment by fxt960803** [comment]
> seems your location candidate is even smaller than 10.
> you can modify [this line](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L619) to
> 
> ```python
> n_candidate_k = min(10, ious_in_boxes_matrix.size(1))
> ```

Thank you for your reply. The problem has been solved after the update

**Comment by Shanyaodedanshen** [comment]
我的n_candidate_k 打印出来会是0，然后就报错了。。训练前已经把自动忽略没有标签的图像了，有大佬知道原因吗，谢谢。

**Comment by Shanyaodedanshen** [comment]
> 我的n_candidate_k 打印出来会是0，然后就报错了。。训练前已经把自动忽略没有标签的图像了，有大佬知道原因吗，谢谢。

并且一出现这样的错误，就会进入CPU模式，但这似乎不是由于显存不够引起的，所以似乎不需要进入CPU模式。。

**Comment by ratcat1232** [comment]
> 
> 
> 我的n_candidate_k 打印出来会是0，然后就报错了。。训练前已经把自动忽略没有标签的图像了，有大佬知道原因吗，谢谢。

不知道您遇到的是否和我们当时是一样的问题。我们当时下载最新的代码，setup.py develop后就没再出现过这个报错。您可以另开一楼贴上具体报错，作者回复很快！

**Comment by Shanyaodedanshen** [comment]
> > 我的n_candidate_k 打印出来会是0，然后就报错了。。训练前已经把自动忽略没有标签的图像了，有大佬知道原因吗，谢谢。
> 
> 不知道您遇到的是否和我们当时是一样的问题。我们当时下载最新的代码，setup.py develop后就没再出现过这个报错。您可以另开一楼贴上具体报错，作者回复很快！

谢谢。我后来已经setup过了。我再开一楼吧。
