### ISSUE TITLE
can "nn.silu" convert to openvino layer?

### ISSUE THREAD

**Issue by aboy2018** [Megvii-BaseDetection/YOLOX#28]
Do I need to replace nn.silu to nn.relu? for work on openvino

**Comment by Joker316701882** [comment]
@aboy2018 Before converting the model to ONNX, we have replaced nn.SiLU to a version that able to deploy:
https://github.com/Megvii-BaseDetection/YOLOX/blob/ce7d75497956c6c2544e352eda36f0173a917989/tools/export_onnx.py#L71

where this deploy-friendly SiLU is defined here:

https://github.com/Megvii-BaseDetection/YOLOX/blob/ce7d75497956c6c2544e352eda36f0173a917989/yolox/models/network_blocks.py#L9

So it should be fine.

**Comment by aboy2018** [comment]
> @aboy2018 Before converting the model to ONNX, we have replaced nn.SiLU to a version that is able to deploy:
> 
> https://github.com/Megvii-BaseDetection/YOLOX/blob/ce7d75497956c6c2544e352eda36f0173a917989/tools/export_onnx.py#L71
> 
> where this deploy-friendly SiLU is defined here:
> 
> https://github.com/Megvii-BaseDetection/YOLOX/blob/ce7d75497956c6c2544e352eda36f0173a917989/yolox/models/network_blocks.py#L9
> 
> So it should be fine.

So good.Thank you.
