### ISSUE TITLE
mAP on val dataset

### ISSUE THREAD

**Issue by zhangming8** [Megvii-BaseDetection/YOLOX#281]
Hi, I find you provide mAP of yolox-s/m/l/x/darnket53 on 'test2017' in README. Can you provide the mAP of them on COCO 'val2017' dataset? Thanks.

**Comment by ruinmessi** [comment]
I didn't record them. But I remember that for small and medium models, val mAP are nearly the same with test-dev, for yolox-l, we get 49.5 or 49.6 on val. For yolox-x, the gap is large, we get 50.5 or 50.7 on val but 51.2 on test-dev.

**Comment by zhangming8** [comment]
> I didn't record them. But I remember that for small and medium models, val mAP are nearly the same with test-dev, for yolox-l, we get 49.5 or 49.6 on val. For yolox-x, the gap is large, we get 50.5 or 50.7 on val but 51.2 on test-dev.
> You can also test on your own to get the exact number.

I reevaluated all the results:
                 size    mAP(val2017)    mAP(test2017)
|yolox-s    |640        |39.2                    |39.5                 
|yolox-m   |640        |46.2                    |46.4                 
|yolox-l     |640        |49.5                    |50.0                 
|yolox-x    |640        |50.5                    |51.1                 

val2017 was evaluate by COCO api, test2017 was evaluate by COCO website.
For yolox-s and yolox-x, my results are slightly different from yours(just 0.01). Can you re-check them?

**Comment by ruinmessi** [comment]
Thx. I will re-check the original weights.

**Comment by Joker316701882** [comment]
@zhangming8 When you evaluate the mAP on val2017, did you set the score threshold to 0.001?

**Comment by zhangming8** [comment]
> @zhangming8 When you evaluate the mAP on val2017, did you set the score threshold to 0.001?

I evaluted on val2017, test2017 today, and I also set conf to 0.001.
The evaluation commands were from readme.
such as:
python tools/eval.py -n  yolox-s -c yolox_s.pth.tar -b 64 -d 1 --conf 0.001
and weights were donwnloaded from your shared onedrive link.

**Comment by Joker316701882** [comment]
@zhangming8  0.01 difference is acceptable. Hence I close this issue for now.
