### ISSUE TITLE
mAP curve of training on COCO dataset is unexpected

### ISSUE THREAD

**Issue by superaha** [Megvii-BaseDetection/YOLOX#282]
Hi there,

Thanks for this project. We have been trying to reproduce the results on our cluster. Currently, we use two nodes, each node is configured with 8 X 32GB V100 GPUs. Below is the current mAP curve of our training process:

![image](https://user-images.githubusercontent.com/76199834/127690320-09f5d2b3-e8ab-4257-8276-a73e41d69b6c.png)

The **blue** line is the version with known memory leak issue and the **orange** line is the version after "fix memory leak" commit. mAP is evaluated every 10 epochs. As expected, we also see the blue experiment is restarted due to unknown error at around 110-th epoch. This is probably due to the memory leak bug. 

The orange line seems not as expected. It does not show any performance gain after 50-th epoch. 

It seems even the **blue** comes with memory leak bug, it still achieves an mAP of 0.426 after 110 epochs of training. Does anyone see similar training results?

Thanks.

**Comment by superaha** [comment]
Just realized there are some commits after the memory leak. We will pull the latest version and report the results later.

**Comment by ruinmessi** [comment]
Sorry for the 'mixup bug' in the "fix memory leak" commit, as we only test the yolox-tiny model without mixup at that time. Now the training curve is normal.

**Comment by hhaAndroid** [comment]
> Just realized there are some commits after "fix memory leak". We will pull the latest version and report the results later.

Hi @superaha Have you finished your training? What is the accuracy after training? I am very interested.

**Comment by Joker316701882** [comment]
@hhaAndroid Use the latest branch to train yolox-tiny, you can get 32.3mAP.

**Comment by zhangming8** [comment]
> @hhaAndroid Use the latest branch to train yolox-tiny, you can get 32.3mAP.

awesome

**Comment by superaha** [comment]
Hi there, 

Now I finished training. The mAP curve is as following:

![image](https://user-images.githubusercontent.com/76199834/127760440-f32817ce-138e-409f-aae3-605ef6e4aaf7.png)

The deep blue curve is the one with the latest branch. It achieve 48.5 mAP.

Hope this helps.

**Comment by Joker316701882** [comment]
@superaha Thank you for your information. This is a bit lower than in our report. We will check it in next week. Hence the main problem in this issue is solved, I close it now. Reopen if necessary.

**Comment by hhaAndroid** [comment]
> @hhaAndroid Use the latest branch to train yolox-tiny, you can get 32.3mAP.

OK.Thank you very much.

**Comment by hhaAndroid** [comment]
> @hhaAndroid Use the latest branch to train yolox-tiny, you can get 32.3mAP.

OK.Thank you very much.

**Comment by noelp2500** [comment]
May I ask, how you obtained the curve

**Comment by ajtvsv07** [comment]
@superaha what is time taken to train each epoch ?

**Comment by PurvangL** [comment]
@superaha I am trying to run on two nodes but training just hangs after initialization and doesn't make any progress. could you let me know if you faced issue similar to this?

python3 tools/train.py -n yolox-s -b 64 --dist-url tcp://master_node_ip:12312  --num_machines 2 --machine_rank 1
