### ISSUE TITLE
训练voc数据集，模型训练好的标志是查看 total_loss吗？还是查看其他指标？

### ISSUE THREAD

**Issue by scuizhibin** [Megvii-BaseDetection/YOLOX#283]
epoch: 71/300, iter: 100/2069, mem: 5643Mb, iter_time: 0.598s, data_time: 0.287s, total_loss: 5.1, iou_loss: 1.9, l1_loss: 0.0, conf_loss: 2.3, cls_loss: 1.0,

**Comment by Joker316701882** [comment]
@scuizhibin Evaluated mAP on the validation set is a better criterion.

**Comment by scuizhibin** [comment]
谢谢


---原始邮件---
发件人: &quot;Ge ***@***.***&gt;
发送时间: 2021年7月31日(周六) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Megvii-BaseDetection/YOLOX] 训练voc数据集，模型训练好的标志是查看 total_loss吗？还是查看其他指标？ (#283)




 
@scuizhibin Evaluated mAP on the validation set is a better criterion.
 
&mdash;

**Comment by scuizhibin** [comment]
map&nbsp;有两个，一个是map_5095一个是map50&nbsp;&nbsp;分别代表什么意思？


---原始邮件---
发件人: &quot;Ge ***@***.***&gt;
发送时间: 2021年7月31日(周六) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Megvii-BaseDetection/YOLOX] 训练voc数据集，模型训练好的标志是查看 total_loss吗？还是查看其他指标？ (#283)




 
@scuizhibin Evaluated mAP on the validation set is a better criterion.
 
&mdash;

**Comment by Joker316701882** [comment]
@scuizhibin 
mAP5095 is used by COCO. mAP50 is used more in VOC.
Please refer to coco style mAP and VOC style mAP for more details.

**Comment by scuizhibin** [comment]
voc&nbsp;&nbsp;map50&nbsp;&nbsp;0.829


---原始邮件---
发件人: &quot;Ge ***@***.***&gt;
发送时间: 2021年7月31日(周六) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Megvii-BaseDetection/YOLOX] 训练voc数据集，模型训练好的标志是查看 total_loss吗？还是查看其他指标？ (#283)




 
@scuizhibin
 mAP5095 is used by COCO. mAP50 is used more in VOC.
 Please refer to coco style mAP and VOC style mAP for more details.
 
&mdash;
