### ISSUE TITLE
Slow training speed

### ISSUE THREAD

**Issue by Tim5Tang** [Megvii-BaseDetection/YOLOX#285]
能不能优化一下训练速度啊，这和yolov5的训练速度差的不是一点点，看gpu使用率太低了。

**Comment by ruinmessi** [comment]
As our internal version has some data accelerating tools, we didn't notice the memory leak, the data preprocessing and I\O bottleneck at the beginning. Now we have fixed some fatal issues and have a plan for the data acceleration. We also welcome your contributions, thx.

**Comment by Tim5Tang** [comment]
i have test the newest version, very good thx
