### ISSUE TITLE
apex always reports errors, can I not use apex?

### ISSUE THREAD

**Issue by AustinKuture** [Megvii-BaseDetection/YOLOX#289]
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

Even if I use https://www.github.com/nvidia/apex to install, it will still get an error.

**Comment by zhangming8** [comment]
Maybe, you can try this one? Its an easy re-implement. https://github.com/zhangming8/yolox-pytorch

**Comment by FateScript** [comment]
Apex is already removed now. Feel free to reopen issue.
