### ISSUE TITLE
imbalanced training classes

### ISSUE THREAD

**Issue by xiaomujiang** [Megvii-BaseDetection/YOLOX#292]
训练的数据中比例10：1， 有哪些参数可以loss权重调整吗？ 或者在哪里加入focal ？

**Comment by Joker316701882** [comment]
@xiaomujiang You can modify this loss to whatever loss you want, or manipulate the loss weights for different classes.

https://github.com/Megvii-BaseDetection/YOLOX/blob/3640b242bdd752715ea6e38dfb7ad7c2fbe9adf4/yolox/models/yolo_head.py#L400-L403
