### ISSUE TITLE
How to change the eval threshold in training

### ISSUE THREAD

**Issue by raymondchu-z** [Megvii-BaseDetection/YOLOX#299]
怎么修改训练过程中评估的阈值？没有找到代码在哪，谢谢
因为观察到训练过程评估的精度和训练结束后用eval.py评估的结果有较大差别：
训练时最后一个epoch评估结果：

> Eval IoU : 0.50
> AP for pedestrain = 0.6718, gt_Num = 2953
> AP for rider = 0.8295, gt_Num = 8530
> AP for tricycle = 0.6603, gt_Num = 1104
> AP for car = 0.9628, gt_Num = 56715
> AP for van = 0.8495, gt_Num = 8110
> AP for bus = 0.9003, gt_Num = 2677
> AP for van_truck = 0.8365, gt_Num = 4591
> AP for tank_truck = 0.7335, gt_Num = 328
> Mean AP = 0.8055

> 

使用eval评估的结果
~~~
python tools/eval.py -f yolox_s_30epoch_0730.py -c ./YOLOX_outputs/best_ckpt.pth.tar -b 64 -d 1 --conf 0.3
~~~

> Eval IoU : 0.50
> AP for pedestrain = 0.4896, gt_Num = 2953
> AP for rider = 0.6922, gt_Num = 8530
> AP for tricycle = 0.3389, gt_Num = 1104
> AP for car = 0.9164, gt_Num = 56715
> AP for van = 0.5277, gt_Num = 8110
> AP for bus = 0.7371, gt_Num = 2677
> AP for van_truck = 0.5236, gt_Num = 4591
> AP for tank_truck = 0.3455, gt_Num = 328
> Mean AP = 0.5714

**Comment by zhangming8** [comment]
Here. https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/exp/yolox_base.py#L59

**Comment by raymondchu-z** [comment]
意思是训练时评估的阈值参数都是从exp中取的？那就奇怪了，我用和exp同样的参数，无法重新得到最后一个epoch评估的结果。
