### ISSUE TITLE
如何弱化数据增强 ？ 对应代码怎么改 求大佬指点

### ISSUE THREAD

**Issue by lgf821793883** [Megvii-BaseDetection/YOLOX#302]

**Comment by lgf821793883** [comment]
# --------------- transform config ----------------- #
    self.degrees = 10.0
    self.translate = 0.1
    self.scale = (0.1, 2)
    self.mscale = (0.8, 1.6)
    self.shear = 2.0
    self.perspective = 0.0
    self.enable_mixup = True

**Comment by LeopoldLin** [comment]
Refer to _exps/default/nano.py_ and _exps/default/yolox_tiny.py_:

self.scale = (0.5, 1.5)
self.enable_mixup = False

Overwrite above two parameters in your exp file.

**Comment by liminghu** [comment]
I do not think mosaic augmentation can be turned off, I have tried self.enable_mosaic = False, I save the images after the augmentation, I still can see mosaic images.
