### ISSUE TITLE
训练后测试出现 size mismatch for backbone

### ISSUE THREAD

**Issue by EdwardVincentMa** [Megvii-BaseDetection/YOLOX#303]
E:\PyProject\yolox>python tools/demo.py image --conf 0.25 --nms 0.45 --tsize 640 --save_result --device [gpu]
2021-08-02 11:08:40.983 | INFO     | __main__:main:247 - Args: Namespace(camid=0, ckpt='./weights/nano_latest_ckpt_0801.pth.tar', conf=0.25, demo='image', device='[gpu]', exp_file=None, experiment_name='yolox_tiny', fp16=False, fuse=False, name='yolox-tiny', nms=0.45, path='./datasets/VOCdevkit/VOC2007/JPEGImages', save_result=True, trt=False, tsize=640)
2021-08-02 11:08:41.115 | INFO     | __main__:main:257 - Model Summary: Params: 5.04M, Gflops: 15.20
2021-08-02 11:08:41.117 | INFO     | __main__:main:268 - loading checkpoint
Traceback (most recent call last):
  File "tools/demo.py", line 303, in <module>
    main(exp, args)
  File "tools/demo.py", line 271, in main
    model.load_state_dict(ckpt["model"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for backbone.backbone.stem.conv.conv.weight: copying a param with shape torch.Size([32, 12, 3, 3]) from checkpoint, the shape in current model is torch.Size([24, 12, 3, 3]).
        size mismatch for backbone.backbone.stem.conv.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.stem.conv.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.stem.conv.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.stem.conv.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.0.conv.weight: copying a param with shape torch.Size([64, 32, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 24, 3, 3]).
        size mismatch for backbone.backbone.dark2.0.bn.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for backbone.backbone.dark2.0.bn.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for backbone.backbone.dark2.0.bn.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for backbone.backbone.dark2.0.bn.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for backbone.backbone.dark2.1.conv1.conv.weight: copying a param with shape torch.Size([32, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 48, 1, 1]).
        size mismatch for backbone.backbone.dark2.1.conv1.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv1.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv1.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv1.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv2.conv.weight: copying a param with shape torch.Size([32, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([24, 48, 1, 1]).
        size mismatch for backbone.backbone.dark2.1.conv2.bn.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv2.bn.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv2.bn.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv2.bn.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for backbone.backbone.dark2.1.conv3.conv.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([48, 48, 1, 1]).
        size mismatch for backbone.backbone.dark2.1.conv3.bn.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for backbone.backbone.dark2.1.conv3.bn.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for backbone.backbone.dark2.1.conv3.bn.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).
        size mismatch for backbone.backbone.dark2.1.conv3.bn.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([48]).

后面还有很多 mismatch 的信息，就不打印了，不知道这是什么错误，求大神指教

**Comment by zhangming8** [comment]
Args: Namespace(camid=0, ckpt='./weights/nano_latest_ckpt_0801.pth.tar', conf=0.25, demo='image', device='[gpu]', exp_file=None, experiment_name='yolox_tiny', fp16=False, fuse=False, name='yolox-tiny', nms=0.45, path='./datasets/VOCdevkit/VOC2007/JPEGImages', save_result=True, trt=False, tsize=640)

your network is yolox-tiny, but you load yolox-nano's weight
