### ISSUE TITLE
finished 213/300 epochs，the best AP is 0.017，Average inference time: 154.67 ms

### ISSUE THREAD

**Issue by ahong007007** [Megvii-BaseDetection/YOLOX#306]
使用7月30日官方的代码，训练集是COCO，
训练和测试代码没有任何改动（v100八卡训练，一直被占用，所以P40测试）
训练:
python tools/train.py -n yolox-x -d 8 -b 64 --fp16 -o
loss一直降低，l1_loss一直为0
评估：python tools/eval.py -n  yolox-x -c yolox_x.pth.tar -b 64 -d 8 --conf 0.001

**评估过程持续卡机，大约持续5分钟。**
![image](https://user-images.githubusercontent.com/22077027/127816794-263b7f80-d1d2-45c7-b031-f84adbc5a857.png)

**Comment by ruinmessi** [comment]
Have you pulled this update: #275 ?

**Comment by ahong007007** [comment]
请问是训练代码更新，还是测试评估代码更新？我理解7月30日pull的master分支，不是最新的？

**Comment by ahong007007** [comment]
@ruinmessi 更新到8月2日最新代码开始训练，l1_loss: 0.0，一直为0.
如果这个loss不使用，为什么不从训练中去除？谢谢，^_^

**Comment by ruinmessi** [comment]
See #74

**Comment by ahong007007** [comment]
v100八卡机训练，预期需求5天，时间太长了，训练时遇到1个bug，一周没了，o(╥﹏╥)o
![image](https://user-images.githubusercontent.com/22077027/127820001-9d30c255-d7f8-4ee8-afe8-8e6cca166ada.png)

**Comment by ruinmessi** [comment]
Actually, the training speed is mainly bounded by the data preprocessing, as the training time for yolox-s to yolox-l is almost the same. We didn't notice this issue as our internal tools efficiently handled it. I suggest you adopt multi-node training or use DALI to accelerating the process.

**Comment by APeiZou** [comment]
@ruinmessi 你好,现在解决了训练精度的问题吗？

**Comment by Joker316701882** [comment]
@APeiZou It's been fixed days ago. Please try out latest branch
