### ISSUE TITLE
multi gpu stuck at "launch_by_subprocess"

### ISSUE THREAD

**Issue by weyoung0** [Megvii-BaseDetection/YOLOX#309]
Thanks for your excellent work!
感谢作者的工作，又把yolo带到了新的高度！
多卡训练时遇到问题：
单卡训练正常，多卡训练时卡在这里：
2021-08-02 16:36:33 | INFO     | yolox.core.trainer:193 - ---> start train epoch1
输出上面的信息之后就停住了，手动停掉程序显示如下信息：
^CTraceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    launch(
  File "/home/zlw/PycharmProjects/YOLOX-main/yolox/core/launch.py", line 80, in launch
    launch_by_subprocess(
  File "/home/zlw/PycharmProjects/YOLOX-main/yolox/core/launch.py", line 163, in launch_by_subprocess
    process.wait()
  File "/home/zlw/miniconda3/envs/yolox/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/home/zlw/miniconda3/envs/yolox/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/zlw/miniconda3/envs/yolox/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

可能是多线程的问题？

**Comment by ruinmessi** [comment]
You may reduce your num of workers and try again.

**Comment by weyoung0** [comment]
> You may reduce your num of workers and try again.

I set exp.data_num_workers=0, and problem still exists.

**Comment by ruinmessi** [comment]
What's your training command? And plz report your env details like GPU, RAM.

**Comment by weyoung0** [comment]
> What's your training command? And plz report your env details like GPU, RAM.

training command:
CUDA_VISIBLE_DEVICES=2,3 python tools/train.py -f exps/example/yolox_mydataset/mydataset_exp.py -d 2 -b 64 --fp16 -o -c weights/yolox_s.pth
env details:
Ubuntu 16.04.6
TITAN Xp x 4 (I used 2 of them)
pytorch version: 1.8.0
RAM: 125G

The problem is similar to #252 , he stuck at epoch3 while i stuck at epoch1.
But my system is ubuntu. Thank you again!

**Comment by sunfei007** [comment]
> > 你的训练指令是什么？并请报告您的环境详细信息，例如 GPU、RAM。
> 
> 训练命令：
> CUDA_VISIBLE_DEVICES=2,3 python tools/train.py -f exps/example/yolox_mydataset/mydataset_exp.py -d 2 -b 64 --fp16 -o -c weights/yolox_s.pth 环境
> 细节：
> Ubuntu 16.04.6
> TITAN Xp x 4（我使用了其中的 2 个）
> pytorch 版本：1.8.0
> RAM：125G
> 
> 问题类似于#252，他卡在 epoch3 而我卡在 epoch1。
> 但是我的系统是ubuntu。再次感谢你！

我也遇到了这样的问题，请问有方法解决了吗

**Comment by StephenStorm** [comment]
> You may reduce your num of workers and try again.

I also encountered the same problem on Linux, The training will always be stuck and unable to train. The gpu memory is not released, I need to kill the process manually. And regardless of the batch size, the gpu memory is full.

**Comment by FieldRen** [comment]
我遇到了同样的问题，4卡训练会卡住，2卡，3卡没问题
