### ISSUE TITLE
ZeroDivisionError occured when training

### ISSUE THREAD

**Issue by LingyvKong** [Megvii-BaseDetection/YOLOX#313]
用一个自己的数据集（VOC格式）训练到第11个epoch时出现ZeroDivisionError，日志如下：
```
2021-08-02 17:27:35 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (108050), thread 'MainThread' (47444391041152):
Traceback (most recent call last):

  File "train.py", line 125, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=64, ckpt='weights/yolox_nano.pth.tar', devices=None, dist_backend='nccl', dist_url=None, exp_file='exps/...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/xxxx/YOLOX/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x2b272f61bc80>

  File "train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x2b2874b170d0>
    └ <yolox.core.trainer.Trainer object at 0x2b27275b7198>

  File "/xxxx/YOLOX/yolox/core/trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x2b27275e7ae8>
    └ <yolox.core.trainer.Trainer object at 0x2b27275b7198>

  File "/xxxx/YOLOX/yolox/core/trainer.py", line 81, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x2b27275f4378>
    └ <yolox.core.trainer.Trainer object at 0x2b27275b7198>

  File "/xxxx/YOLOX/yolox/core/trainer.py", line 215, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x2b27275f4620>
    └ <yolox.core.trainer.Trainer object at 0x2b27275b7198>

  File "/xxxx/YOLOX/yolox/core/trainer.py", line 307, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x2b27275b7198>
    │          │    └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x2b273f8bf7b8>
    │          └ <yolox.core.trainer.Trainer object at 0x2b27275b7198>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/xxxx/YOLOX/yolox/exp/yolox_base.py", line 248, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x2b27275eb598>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x2b273f8bf7b8>

  File "/xxxx/YOLOX/yolox/evaluators/voc_evaluator.py", line 129, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([0., 0., 0.], device='cuda:0')
                   │    │                   └ {0: (tensor([[ 468.4615,  728.8462,  516.1539,  773.4615],
                   │    │                             [ 440.3846,  719.2308,  743.4615,  966.9231],
                   │    │                             [ 47...
                   │    └ <function VOCEvaluator.evaluate_prediction at 0x2b27275eb6a8>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x2b273f8bf7b8>

  File "/xxxx/YOLOX/yolox/evaluators/voc_evaluator.py", line 167, in evaluate_prediction
    a_infer_time = 1000 * inference_time / (n_samples * self.dataloader.batch_size)
                          │                 │           │    │          └ 64
                          │                 │           │    └ <torch.utils.data.dataloader.DataLoader object at 0x2b27b1395128>
                          │                 │           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x2b273f8bf7b8>
                          │                 └ 0.0
                          └ 0.0

ZeroDivisionError: float division by zero
```
我简单的将voc_evaluator.py文件对应代码改为了如下以保证代码正常运行
```python
  if n_samples:
      a_infer_time = 1000 * inference_time / (n_samples * self.dataloader.batch_size)
      a_nms_time = 1000 * nms_time / (n_samples * self.dataloader.batch_size)
  else:
      a_infer_time = 0
      a_nms_time = 0
```

请问这样改是否可以，以及出现这个error的本质原因是什么呢？
感谢

**Comment by ruinmessi** [comment]
Plz see #256

**Comment by Orazer** [comment]
我也同样出现了这个问题

`2021-08-05 18:53:59 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (14548), thread 'MainThread' (14544):
Traceback (most recent call last):

  File "tools\train.py", line 123, in <module>
    launch(
    └ <function launch at 0x0000028690206C10>

> File "d:\yolox-main\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000002869273F790>

  File "tools\train.py", line 109, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000028691A7D280>
    └ <yolox.core.trainer.Trainer object at 0x000002868AB57C70>

  File "d:\yolox-main\yolox\core\trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x00000286926D7430>
    └ <yolox.core.trainer.Trainer object at 0x000002868AB57C70>

  File "d:\yolox-main\yolox\core\trainer.py", line 81, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x00000286926E3B80>
    └ <yolox.core.trainer.Trainer object at 0x000002868AB57C70>

  File "d:\yolox-main\yolox\core\trainer.py", line 215, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x00000286926E3E50>
    └ <yolox.core.trainer.Trainer object at 0x000002868AB57C70>

  File "d:\yolox-main\yolox\core\trainer.py", line 306, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(
                             │    │   └ <function Exp.eval at 0x000002869273FE50>
                             │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x000002868AB57C70>

  File "d:\yolox-main\yolox\exp\yolox_base.py", line 251, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x00000286926D7EE0>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x0000028692BC6670>

  File "d:\yolox-main\yolox\evaluators\voc_evaluator.py", line 129, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([0., 0., 0.], device='cuda:0')
                   │    │                   └ {0: (None, None, None), 1: (None, None, None), 2: (None, None, None)}
                   │    └ <function VOCEvaluator.evaluate_prediction at 0x00000286926E3040>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x0000028692BC6670>

  File "d:\yolox-main\yolox\evaluators\voc_evaluator.py", line 167, in evaluate_prediction
    a_infer_time = 1000 * inference_time / (n_samples * self.dataloader.batch_size)
                          │                 │           │    │          └ 8
                          │                 │           │    └ <torch.utils.data.dataloader.DataLoader object at 0x0000028692BC6460>
                          │                 │           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x0000028692BC6670>
                          │                 └ 0.0
                          └ 0.0

ZeroDivisionError: float division by zero
`

**Comment by MehmetZahidGenc** [comment]
if you get error (divison by zero) upgrade   "/content/YOLOX/yolox/evaluators/voc_evaluator.py"

line 167 =>    a_infer_time = 1000 * inference_time / (n_samples+1 * self.dataloader.batch_size)

line 168 =>    a_nms_time = 1000 * nms_time / (n_samples+1 * self.dataloader.batch_size)
