### ISSUE TITLE
AttributeError: module 'nano' has no attribute 'Exp'

### ISSUE THREAD

**Issue by tucachmo2202** [Megvii-BaseDetection/YOLOX#319]
I retrain yolo-nano with this script `python3 tools/train.py -n yolox-n
ano -d 1 -b 64 --fp16 -o`. However it raised this error 
`AttributeError: module 'nano' has no attribute 'Exp'
ImportError:exps/default/nano.py doesn't contains class named 'Exp'`
Could you help me to fix?
Thanks very much!

**Comment by ruinmessi** [comment]
hi, we test our code and it runs well. So I suggest you to pull the updates and reinstall yolox with:
```
pip install -e -v .
```

**Comment by tucachmo2202** [comment]
@ruinmessi , Thank for reply soon,
I found that I have a package name nano too so I modify the file name and it run well.
