### ISSUE TITLE
Training time too long

### ISSUE THREAD

**Issue by cryboykevin** [Megvii-BaseDetection/YOLOX#32]
I train yolox-s with batch size 128 + 8 x V100, and the task takes about 2 days 6 hours for 300 epoch. Is the training time normal ?

**Comment by FateScript** [comment]
Please provide your data_time and train_time in log, Thanks

**Comment by cryboykevin** [comment]
> Please provide your data_time and train_time in log, Thanks

Here are some of training logs:

2021-07-21 02:58:47 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 640/925, mem: 7751Mb, iter_time: 0.666s, data_time: 0.047s, total_loss: 11.2, iou_loss: 3.8, l1_loss: 0.0, conf_loss: 4.8, cls_loss: 2.7, lr: 3.830e-04, size: 672, ETA: 2 days, 18:48:57
671 2021-07-21 02:58:54 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 650/925, mem: 7751Mb, iter_time: 0.700s, data_time: 0.043s, total_loss: 11.3, iou_loss: 3.6, l1_loss: 0.0, conf_loss: 4.9, cls_loss: 2.8, lr: 3.950e-04, size: 576, ETA: 2 days, 18:36:51
672 2021-07-21 02:59:02 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 660/925, mem: 7751Mb, iter_time: 0.792s, data_time: 0.030s, total_loss: 11.5, iou_loss: 3.7, l1_loss: 0.0, conf_loss: 5.1, cls_loss: 2.7, lr: 4.073e-04, size: 672, ETA: 2 days, 18:31:30
673 2021-07-21 02:59:09 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 670/925, mem: 7751Mb, iter_time: 0.776s, data_time: 0.033s, total_loss: 11.6, iou_loss: 3.7, l1_loss: 0.0, conf_loss: 5.3, cls_loss: 2.7, lr: 4.197e-04, size: 736, ETA: 2 days, 18:25:14
674 2021-07-21 02:59:18 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 680/925, mem: 7751Mb, iter_time: 0.865s, data_time: 0.012s, total_loss: 11.7, iou_loss: 3.7, l1_loss: 0.0, conf_loss: 5.3, cls_loss: 2.6, lr: 4.323e-04, size: 704, ETA: 2 days, 18:25:11
675 2021-07-21 02:59:25 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 690/925, mem: 7751Mb, iter_time: 0.660s, data_time: 0.051s, total_loss: 11.8, iou_loss: 3.5, l1_loss: 0.0, conf_loss: 5.6, cls_loss: 2.6, lr: 4.451e-04, size: 512, ETA: 2 days, 18:11:24
676 2021-07-21 02:59:32 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 700/925, mem: 7751Mb, iter_time: 0.754s, data_time: 0.022s, total_loss: 11.2, iou_loss: 3.7, l1_loss: 0.0, conf_loss: 5.1, cls_loss: 2.4, lr: 4.581e-04, size: 608, ETA: 2 days, 18:04:14
677 2021-07-21 02:59:40 | INFO     | yolox.core.trainer:250 - epoch: 1/300, iter: 710/925, mem: 7751Mb, iter_time: 0.792s, data_time: 0.031s, total_loss: 11.2, iou_loss: 3.7, l1_loss: 0.0, conf_loss: 4.9, cls_loss: 2.5, lr: 4.713e-04, size: 736, ETA: 2 days, 17:59:42

**Comment by ruinmessi** [comment]
Hi, we reproduce the training setting and your training time seems normal. Actually, if you change yolox-s to yolox-l, the total training time is almost the **same**! We suppose the major time consuming comes from our data augment operation, and we also have a plan to accelerate it.

**Comment by RaymondByc** [comment]
@ruinmessi Hello, do you know what causes the difference in training time between iters? Like the record shown, the max consuming time is 0.940ms, and the min consuming time is 0.544ms.
