### ISSUE TITLE
How to remove Slice op of ONNX model

### ISSUE THREAD

**Issue by raymondchu-z** [Megvii-BaseDetection/YOLOX#321]
![image](https://user-images.githubusercontent.com/28563129/127946321-812a9bb5-47cc-45cc-8f3e-097a22a07ea5.png)
我以为这些slice节点是配合多尺度训练用的，然后我设置`self.random_size = None`关掉了多尺度训练。但是导出的模型还是有这些slice。
请问怎么去掉这些节点？

**Comment by raymondchu-z** [comment]
搜了下在ncnn的文档里提到了这是focus模块。怎么关掉这个模块？

**Comment by zhiqwang** [comment]
- https://zhuanlan.zhihu.com/p/391788686
- https://zhuanlan.zhihu.com/p/275989233

这两篇文章里有比较详细的介绍。

**Comment by raymondchu-z** [comment]
@zhiqwang 感谢回复！我想做的是去掉这个focus模块，请问该怎么做？

**Comment by ruinmessi** [comment]
You can just replace it with a 3x3 conv with stride 2 and finetune the model.

**Comment by raymondchu-z** [comment]
> You can just replace it with a 3x3 conv with stride 2 and finetune the model.

 谢谢！
