### ISSUE TITLE
报错信息提示很人性化，请教下用的是什么包？

### ISSUE THREAD

**Issue by kevinchow1993** [Megvii-BaseDetection/YOLOX#322]
![image](https://user-images.githubusercontent.com/23069943/127950609-9bd5bd4e-c1cf-4855-a29b-4ef8b6a1a465.png)

**Comment by FateScript** [comment]
It's  logger.catch in [loguru](https://github.com/Delgan/loguru), acttually it's  [better-exception](https://github.com/Qix-/better-exceptions).
