### ISSUE TITLE
Stuck at training on custom dataset

### ISSUE THREAD

**Issue by HIT-ShuWei** [Megvii-BaseDetection/YOLOX#325]
![图片](https://user-images.githubusercontent.com/65894349/127955929-4947499f-0c33-4833-8626-8acd6af1d0ed.png)

重复实验了几次，都会在train到epoch=10左右卡住不动，也没有其他报错
其中Invalid sos parameter for sequential JPEG 在其他框架中（Detectron2,mmdetection）中均不会影响训练，可以忽略

**Comment by ruinmessi** [comment]
Have you pulled the latest updates? We fixed some sticking issues at #216 and #275

**Comment by HIT-ShuWei** [comment]
> Have you pulled the latest updates? We fixed some sticking issues at #216 and #275

thx, problem solved

**Comment by luckyluliu** [comment]
Invalid sos parameter for sequential JPEG，请问这个是什么问题呀？我训练的时候也报这个东西 @HIT-ShuWei
