### ISSUE TITLE
colab demo

### ISSUE THREAD

**Issue by AK391** [Megvii-BaseDetection/YOLOX#33]
Hi, can you please add a google colab demo for inference

**Comment by yancie-yjr** [comment]
This is my inference demo for YOLOX, but free GPU will be released at any time in colab platform. I can not provide a ready-to-use colab demo.
https://colab.research.google.com/drive/1ssNIezTKnuVk34B_PkhF3vxKFIWoq2bs?usp=sharing

**Comment by AK391** [comment]
@yancie-yjr thanks is it possible to due inference on cpu in colab?
