### ISSUE TITLE
Unexpected interruption of training

### ISSUE THREAD

**Issue by ahong007007** [Megvii-BaseDetection/YOLOX#334]
使用官方代码，COCO数据集，复现YOLOX-X模型
python tools/train.py -n yolox-x -d 8 -b 64 --fp16 -o
训练到72 个epoch意外中断。
1. 从原因上看是COCO图片造成的，也许某个图片异常。训练过程是否可以跳过这个？因为1个图片，训练过程重新训练，太太可惜了。

![image](https://user-images.githubusercontent.com/22077027/127983543-af7fb9da-b30c-4c11-9963-29c761962833.png)

![image](https://user-images.githubusercontent.com/22077027/127983419-d9250f3f-7711-4c48-ae52-d43138955b3b.png)

**Comment by ruinmessi** [comment]
You can add --resume to resume the training.

**Comment by Joker316701882** [comment]
@ahong007007 You can use ''--resume'' to continue your training. Don't worry.
