### ISSUE TITLE
第十轮结束后，验证时出现了FileNotFoundError: [Errno 2] No such file or directory: '20190522030_0549.xml'

### ISSUE THREAD

**Issue by haomayang1126** [Megvii-BaseDetection/YOLOX#335]
验证的时候出错，但是我的Annotations文件夹里有20190522030_0549.xml ，为什么找不到呢

100%|#########################################################################################################################################################################| 9/9 [00:06<00:00,  1.38it/s]
2021-08-03 16:37:20 | INFO     | yolox.evaluators.voc_evaluator:161 - Evaluate in main process...
Writing nangzhong VOC results file
Writing xiantizengzi VOC results file
Writing biantaotifeida VOC results file
Eval IoU : 0.50
2021-08-03 16:37:20 | INFO     | yolox.core.trainer:186 - Training of experiment is done and the best AP is 0.00
2021-08-03 16:37:20 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (12408), thread 'MainThread' (6628):
Traceback (most recent call last):

  File "tools\train.py", line 120, in <module>
    launch(
    └ <function launch at 0x000001C15E74A820>

> File "g:\pythonproject\yolox-main\yolox\core\launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000001C160D38310>

  File "tools\train.py", line 104, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000001C160075280>
    └ <yolox.core.trainer.Trainer object at 0x000001C1590390D0>

  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 71, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000001C160CEE790>
    └ <yolox.core.trainer.Trainer object at 0x000001C1590390D0>

  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 81, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x000001C160CF1D30>
    └ <yolox.core.trainer.Trainer object at 0x000001C1590390D0>

  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 215, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x000001C160CF6040>
    └ <yolox.core.trainer.Trainer object at 0x000001C1590390D0>

  File "g:\pythonproject\yolox-main\yolox\core\trainer.py", line 306, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(
                             │    │   └ <function Exp.eval at 0x000001C160D389D0>
                             │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x000001C1590390D0>

  File "g:\pythonproject\yolox-main\yolox\exp\yolox_base.py", line 251, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x000001C160CEEF70>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001C16B023280>

  File "g:\pythonproject\yolox-main\yolox\evaluators\voc_evaluator.py", line 129, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([0.6822, 0.0844, 8.0000], device='cuda:0')
                   │    │                   └ {0: (tensor([[ 3.0820e+02,  2.2344e+02,  4.6562e+02,  4.1016e+02],
                   │    │                             [ 4.0742e+02,  4.5273e+02,  6.5195e+02,  6.0586e+0...
                   │    └ <function VOCEvaluator.evaluate_prediction at 0x000001C160CF10D0>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001C16B023280>

  File "g:\pythonproject\yolox-main\yolox\evaluators\voc_evaluator.py", line 206, in evaluate_prediction
    mAP50, mAP70 = self.dataloader.dataset.evaluate_detections(
                   │    │          │       └ <function VOCDetection.evaluate_detections at 0x000001C160CF1820>
                   │    │          └ <yolox.data.datasets.voc.VOCDetection object at 0x000001C16B0230A0>
                   │    └ <torch.utils.data.dataloader.DataLoader object at 0x000001C16B023250>
                   └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000001C16B023280>

  File "g:\pythonproject\yolox-main\yolox\data\datasets\voc.py", line 175, in evaluate_detections
    mAP = self._do_python_eval(output_dir, iou)
          │    │               │           └ 0.5
          │    │               └ 'C:\\Users\\xiaoma\\AppData\\Local\\Temp\\tmpy5bql4hj'
          │    └ <function VOCDetection._do_python_eval at 0x000001C160CF19D0>
          └ <yolox.data.datasets.voc.VOCDetection object at 0x000001C16B0230A0>

  File "g:\pythonproject\yolox-main\yolox\data\datasets\voc.py", line 239, in _do_python_eval
    rec, prec, ap = voc_eval(
                    └ <function voc_eval at 0x000001C160CF1280>

  File "g:\pythonproject\yolox-main\yolox\evaluators\voc_eval.py", line 93, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
    │    │            │         │        │      └ '20190522030_0549'
    │    │            │         │        └ <method 'format' of 'str' objects>
    │    │            │         └ '{:s}.xml'
    │    │            └ <function parse_rec at 0x000001C160CEE940>
    │    └ '20190522030_0549'
    └ {}

  File "g:\pythonproject\yolox-main\yolox\evaluators\voc_eval.py", line 17, in parse_rec
    tree = ET.parse(filename)
           │  │     └ '20190522030_0549.xml'
           │  └ <function parse at 0x000001C15EB0E940>
           └ <module 'xml.etree.ElementTree' from 'C:\\Users\\xiaoma\\Anaconda3\\envs\\Swin\\lib\\xml\\etree\\ElementTree.py'>

  File "C:\Users\xiaoma\Anaconda3\envs\Swin\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
    │    │     │       └ None
    │    │     └ '20190522030_0549.xml'
    │    └ <function ElementTree.parse at 0x000001C15EB029D0>
    └ <xml.etree.ElementTree.ElementTree object at 0x000001C160FDC8E0>

  File "C:\Users\xiaoma\Anaconda3\envs\Swin\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
                  └ '20190522030_0549.xml'

FileNotFoundError: [Errno 2] No such file or directory: '20190522030_0549.xml'

**Comment by haomayang1126** [comment]
手撕代码之后，终于发现问题所在，就是路径问题，读取不到anno的路径，源yolox文件有一点问题大家都没发现吗？
打开voc_eval.py,添加以下代码
    path1=filename
    path2='G:\Pythonproject\YOLOX-main\datasets\VOCdevkit\VOC2007\Annotations'
    path3=os.path.join(path2,path1)

将tree = ET.parse(filename)改为    tree = ET.parse(path3)

**Comment by haomayang1126** [comment]
> 手撕代码之后，终于发现问题所在，就是路径问题，读取不到anno的路径，源yolox文件有一点问题大家都没发现吗？
> 打开voc_eval.py,添加以下代码
> path1=filename
> path2='G:\Pythonproject\YOLOX-main\datasets\VOCdevkit\VOC2007\Annotations'
> path3=os.path.join(path2,path1)
> 
> 将tree = ET.parse(filename)改为 tree = ET.parse(path3)

path2路径自行修改成自己的

**Comment by ruinmessi** [comment]
You can change your evaldata dir in this line: https://github.com/Megvii-BaseDetection/YOLOX/blob/main/exps/example/yolox_voc/yolox_voc_s.py#L84

**Comment by pistachio0812** [comment]
> @haomayang1126 你好，我也遇到了这个问题，但是按照你的方法修改了还是不行，初步判断是yolox/data/datasets/voc.py里面对anno的读取有问题： annopath = os.path.join(rootpath, "Annotations", "{:s}.xml")
> 
> 但接下来的我就不会改了，能麻烦看下吗，谢谢

改成：annopath=os.path.join(rootpath,'Annotations','{}.xml')

**Comment by FlyingRR** [comment]
> > @haomayang1126 你好，我也遇到了这个问题，但是按照你的方法修改了还是不行，初步判断是yolox/data/datasets/voc.py里面对anno的读取有问题： annopath = os.path.join(rootpath, "Annotations", "{:s}.xml")
> > 但接下来的我就不会改了，能麻烦看下吗，谢谢
> 
> 改成：annopath=os.path.join(rootpath,'Annotations','{}.xml')

多谢！

**Comment by xbbkok** [comment]
https://github.com/jwyang/faster-rcnn.pytorch/issues/654#issuecomment-581989987
