### ISSUE TITLE
大佬您好，请问这个网络是anchor free的，是不是不能修改anchor尺寸？

### ISSUE THREAD

**Issue by EdwardVincentMa** [Megvii-BaseDetection/YOLOX#338]
如果不能修改anchor尺寸，那么对长宽比比较大的物体，nano识别的不太好哦。有什么办法解决吗？

**Comment by Joker316701882** [comment]
@EdwardVincentMa In my point of view, your problem is not relevant to anchor/anchor size. You may need a larger/deeper model. By the way, did you finetune our model on your dataset? Or you just directly tested our models.

**Comment by EdwardVincentMa** [comment]
> @EdwardVincentMa In my point of view, your problem is not relevant to anchor/anchor size. You may need a larger/deeper model. By the way, did you finetune our model on your dataset? Or you just directly tested our models.

我训练了自己的数据集，发现 Aspect ratio 较大的，confidence 低，也会出现较多错误的 bounding box

**Comment by Joker316701882** [comment]
@EdwardVincentMa Try larger models. For example, yolox-s, yolox-m.
