### ISSUE TITLE
How to designate device of GPU

### ISSUE THREAD

**Issue by 1757525671** [Megvii-BaseDetection/YOLOX#339]
Such as title. Always occupy 0 device if not set device of GPU.

**Comment by Joker316701882** [comment]
add "CUDA_VISIBLE_DEVICES=<YOU_GPU_ID>" at the beginning of your training command.

**Comment by 1757525671** [comment]
> add "CUDA_VISIBLE_DEVICES=<YOUR_GPU_ID>" at the beginning of your training command.

Ok, thanks.
