### ISSUE TITLE
Why do we need to put the data to our pytorch model before saving model_trt to self.model in demo.py?

### ISSUE THREAD

**Issue by developer0hye** [Megvii-BaseDetection/YOLOX#342]
https://github.com/Megvii-BaseDetection/YOLOX/blob/1660f0c285eb7c914b96dff82c76e415618e5371/tools/demo.py#L117-L120

Thanks for sharing great work!

I can't understand why we need to put the data to our pytorch model before saving `model_trt` to `self.model`.

Is the purpose of this code block to warm up the GPU before the inference stage?

**Comment by ruinmessi** [comment]
For trt model, we put the bbox decoder outside of the model forward. 
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/tools/demo.py#L147

So you have to warm up the decoder to initial the "self.hw":
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L207

**Comment by developer0hye** [comment]
@ruinmessi Thanks!
