### ISSUE TITLE
 Trying to create tensor with negative dimension 

### ISSUE THREAD

**Issue by 15162162323** [Megvii-BaseDetection/YOLOX#346]
File "/project/train/src_repo/YOLOX/yolox/core/trainer.py", line 158, in before_train
    occupy_mem(self.local_rank)
    │          │    └ 0
    │          └ <yolox.core.trainer.Trainer object at 0x7f52788cb2e8>
    └ <function occupy_mem at 0x7f522cde9d90>

  File "/project/train/src_repo/YOLOX/yolox/utils/metric.py", line 38, in occupy_mem
    x = torch.cuda.FloatTensor(256, 1024, block_mem)
        │     │    │                      └ -106
        │     │    └ <class 'torch.cuda.FloatTensor'>
        │     └ <module 'torch.cuda' from '/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py'>
        └ <module 'torch' from '/usr/local/lib/python3.6/dist-packages/torch/__init__.py'>

RuntimeError: Trying to create tensor with negative dimension -106: [256, 1024, -106]

**Comment by ruinmessi** [comment]
Remove `-o` in your training command

**Comment by 15162162323** [comment]
> Remove `-o` in your training command

ok，tks！

**Comment by Matthew1204** [comment]
tks for your help!
