### ISSUE TITLE
tool/eval.py推断时间有差异，开源模型的AP模型略有差异

### ISSUE THREAD

**Issue by ahong007007** [Megvii-BaseDetection/YOLOX#349]
在v100 8卡机上，执行官方demo评估代码
python tools/eval.py -n  yolox-x -c ./pth/yolox_x.pth  -b 64 -d 8 --conf 0.001 --fp16 --fuse

tui推断时间18.92ms（论文17.3ms）,AP50.5(论文51.2AP)，时间误差在允许范围内？虽然差别不是很大，但是比较好奇差异在哪里，O(∩_∩)O哈哈~
![image](https://user-images.githubusercontent.com/22077027/128110458-bf1bb701-556a-4e54-80c7-e03dad7c61bc.png)

**Comment by Joker316701882** [comment]
@ahong007007 50.5是在coco validation set上，51.2是在test set上。测速用单卡，-b 1 -d 1。
