### ISSUE TITLE
How to use YOLOX to detect polygon targets

### ISSUE THREAD

**Issue by SiChuanJay** [Megvii-BaseDetection/YOLOX#353]
Hello, professro:

Thanks for your yolox code, it's really helpful for me. I am a student, I will use yolox to detect  quadrangle targets, which means network need to output 4 coordinate points at the end. So I want to know which parts of the network I should change. Thanks for your answer.

Best regards.

**Comment by Joker316701882** [comment]
@SiChuanJay You can modify the output channel for the regression head. And change the regression targets correspondingly.
