### ISSUE TITLE
Face a problem when trying to load saved model from the drive

### ISSUE THREAD

**Issue by Md-Ferdous** [Megvii-BaseDetection/YOLOX#356]
![image](https://user-images.githubusercontent.com/55968913/128139561-c8d9bec5-0e30-40c1-b697-263ff0798360.png)
![image](https://user-images.githubusercontent.com/55968913/128139763-2cfe36b5-95fa-4c92-a6f4-47018cf8b350.png)

**Comment by zhangming8** [comment]
Google colab? 
There is a space in your weight path
