### ISSUE TITLE
error in F.one_hot()

### ISSUE THREAD

**Issue by mrljwlm** [Megvii-BaseDetection/YOLOX#357]
之前训练了一下coco数据没有报错，后来训练了一下自己的数据集发现有个错误：
在[yolo_head.py](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py)文件的get_assignments和get_losses的函数里调用了F.one_hot()：
cls_target = F.one_hot( gt_matched_classes.to(torch.int64), self.num_classes ) 
gt_cls_per_image =(F.one_hot(gt_classes.to(torch.int64), self.num_classes).float().unsqueeze(1).repeat(1, num_in_boxes_anchor, 1))

F.one_hot()的第二个参数应该是num_classes + 1 而不是num_classes，否则会报错(one_hot编码的长度应该是最大值+1)：
RuntimeError: Class values must be smaller than num_classes.

**Comment by zhangming8** [comment]
F.one_hot()第二个参数是num_classes，用你的数据集打印一下类别gt_classes是不是从0开始的？

**Comment by mrljwlm** [comment]
> F.one_hot()第二个参数是num_classes，用你的数据集打印一下类别gt_classes是不是从0开始的？

我的0是background，类别从1开始

**Comment by Joker316701882** [comment]
@mrljwlm Your class index should start from 0, not 1.

**Comment by NarutoZhao** [comment]
我看作者使用的 coco 代码，class id 是从 1 开始的啊？在 yolox/data/datasets/coco.py 
![image](https://user-images.githubusercontent.com/32025355/140049903-9c894d27-6788-4f08-bcc9-f2c8f728e050.png)

**Comment by Best-effort** [comment]
请问拟这个问题解决了吗？？
