### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox'

### ISSUE THREAD

**Issue by zhangwei-swpu** [Megvii-BaseDetection/YOLOX#358]
![1628065350(1)](https://user-images.githubusercontent.com/88427314/128147831-3c762904-75a7-49f3-8a80-89b5e55b1968.jpg)

**Comment by nicepeng** [comment]
I also have this error, how to solve, please?

**Comment by zhangwei-swpu** [comment]
@nicepeng Sorry, I didn't solve it

**Comment by Joker316701882** [comment]
@zhangwei-swpu open python in your cmd, then try:

`import yolox`

Also, try to use `python3 tools/train.py xxxxxxxx` instead of python.

**Comment by zhangwei-swpu** [comment]
> @zhangwei-swpu在你的 cmd 中打开 python，然后尝试：
> 
> `import yolox`
> 
> 另外，尝试使用`python3 tools/train.py xxxxxxxx`而不是python。
Still unresolved. 
![image](https://user-images.githubusercontent.com/88427314/128276196-fbf80588-073b-4cb6-8571-f9d0d15e85ac.png)

**Comment by ruinmessi** [comment]
Have you install yolox with:
```bash
pip install -e -v . 
```

**Comment by zhangwei-swpu** [comment]
> 您是否安装了 yolox：
> 
> ```shell
> 点安装 -e -v 。 
> ```

Thank you, The problem has been solved.

**Comment by Avnsx** [comment]
https://github.com/Megvii-BaseDetection/YOLOX/issues/154#issuecomment-971730170
