### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by qbTrible** [Megvii-BaseDetection/YOLOX#36]
Hi, thanks the opening source code! When I train my own datasets with VOC style, the process of training is nomal, but the eval process raise 'Segmentation fault (core dumped)'. It seems the val_dataloader problem.

**Comment by Joker316701882** [comment]
The answer in #34 may help you. In short, change the num_workers to 0 for your val dataloader.
And it's better to provide us your error log.

**Comment by qbTrible** [comment]
Thank! It works in epoch 1 when I set the num_workers to 0, but a 'NoneType' error like this raised when start to train epoch 2.
![微信截图_20210721112024](https://user-images.githubusercontent.com/41276778/126425442-58a43e72-43de-42c4-8bf6-181755dd33c3.png)

**Comment by qbTrible** [comment]
@Joker316701882 
It can be work when init prefetcher in 'before_epoch' function!
![image](https://user-images.githubusercontent.com/41276778/126439128-6aef5bd1-9e1c-4fa5-b282-efc3af011b6a.png)
