### ISSUE TITLE
how to use Background images in training?

### ISSUE THREAD

**Issue by Mingming008** [Megvii-BaseDetection/YOLOX#362]
哈喽, 想请问一下, 我应该怎样制作数据集进行背景图片的训练?

**Comment by ruinmessi** [comment]
Same here #367

**Comment by Mingming008** [comment]
感谢回复, 我按照coco数据格式制作训练数据, 那么背景图片的数据格式应该如何制作呢, 能否详细说明一下

**Comment by ruinmessi** [comment]
Just leave the 'annotation' as an empty list.

**Comment by Kyle-fang** [comment]
May I ask why, after I added background pictures to the training set, the accuracy did not improve but decreased by several points? @GOATmessi7
