### ISSUE TITLE
The training doesn't converge

### ISSUE THREAD

**Issue by TUDelftHao** [Megvii-BaseDetection/YOLOX#363]
I follow the instruction of training a custom dataset on coco128 by loading the pretrained model of YOLOX-S; however, it doesn't converge and the mAP keeps on 0.0. Even when I close the mix-up and shrink the scale of mosaic augmentation, the situation didn' t become better. 
This is the training log:
![image](https://user-images.githubusercontent.com/46449831/128199905-3603f381-0e06-4105-8069-7b2c38180747.png)

and the corresponding config:
![image](https://user-images.githubusercontent.com/46449831/128200020-c9b5c09c-3fb7-493a-86d1-2a27598bace4.png)

The output of model during inferring is None (no bbox predicted), even turning the conf threshold == 0.01.
Anyone knows how to solve this problem? I have already pull the latest code. @zhiqwang @ruinmessi @steinmann

**Comment by ruinmessi** [comment]
coco128 only has 128 images....it is only used for an example.

**Comment by TUDelftHao** [comment]
> coco128 only has 128 images....it is only used for an example.
I understand this is just a toy dataset used for showing the usage of code, BUT coco128 is part of the whole COCO dataset and I should get a satisfied result after a few epochs with the pretrained model instead of a super low mAP, right?
