### ISSUE TITLE
How to add negative data for training？

### ISSUE THREAD

**Issue by betterhalfwzm** [Megvii-BaseDetection/YOLOX#367]
Thanks for sharing，
I want to add some negative samples as background training, how should I do it? Could you give me a detailed introduction?
I try to add some negative data without label to the training set and then train, is that ok？
Looking forward to your reply，Thank you

**Comment by ruinmessi** [comment]
Your attempt has no problem. Just run it

**Comment by Mingming008** [comment]
感谢回复, 我按照coco数据格式制作训练数据, 那么背景图片的数据格式应该如何制作呢,  能否详细说明一下
