### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by holyYodu** [Megvii-BaseDetection/YOLOX#368]
Hi, thanks for your great work. I tried to train YOLOX-nano on a 2080ti, while I can only set the batch-size as 16 to avoid the OutOfMemoryError. I also tried yolov5 and mobilenetv2-ssdlite and i can set the batch-size as 64. So why yolox-nano consume so much memory during training,  is that becasue the data prefetch?

**Comment by ruinmessi** [comment]
I test the 64 batchsize training of yolox-nano on a 2080ti. The training is run well and the gpu mem is 8780m. You may check your gpu status and remember to add `--fp16` for training.

**Comment by holyYodu** [comment]
thanks for your quick reply, i set --fp16 and the training runs well :smile:
