### ISSUE TITLE
YOLOX VS YOLOV5，little advantage, lose in speed

### ISSUE THREAD

**Issue by Peipeilvcm** [Megvii-BaseDetection/YOLOX#369]
|     | val  | test  | Speed | Params | FLOPs |
|  ----  | ----  | ----  | ----  | ----  | ----  |
| YOLOV5-x  | 50.4/68.8 | 50.4 | 6.1 | 87.7 | 218.8 | 
| YOLOX-x | 50.5/0.690 | 51.2 | 17.3 | 99.1 | 281.9 |

**Comment by ruinmessi** [comment]
Plz check our paper **carefully** and report the speed under the same settings

**Comment by pistachio0812** [comment]
> val	test	Speed	Params	FLOPs
> YOLOV5-x	50.4/68.8	50.4	6.1	87.7	218.8
> YOLOX-x	50.5/0.690	51.2	17.3	99.1	281.9

How to test speedv100,params,FLOPs,if you not convenient to answer it, please paste your code or link or other way,thank you!
