### ISSUE TITLE
Cannot infer shapes or values for node "Resize_164"

### ISSUE THREAD

**Issue by quanh1990** [Megvii-BaseDetection/YOLOX#370]
Hello，

I've met a problem when converting onnx model to openvino IR, errors are like this

`Model Optimizer version: 	2019.3.0-375-g332562022
[ ERROR ]  Cannot infer shapes or values for node "Resize_164".
[ ERROR ]  There is no registered "infer" function for node "Resize_164" with op = "Resize". Please implement this function in the extensions. 
 For more information please refer to Model Optimizer FAQ (https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html), question #37. 
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <UNKNOWN>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  There is no registered "infer" function for node "Resize_164" with op = "Resize". Please implement this function in the extensions. `

My openvino version is 2019 and my os system is linux.

My commands are like this

`
python /opt/intel/openvino/deployment_tools/model_optimizer/mo.py \
--input_model yolox.onnx \
--data_type FP16
`

Could you help me with this problem? Thanks a lot!

**Comment by ruinmessi** [comment]
Seems you have to update to the newest openvino version.

**Comment by quanh1990** [comment]
> Seems you have to update to the newest openvino version.

Seems no other better solutions, thanks~
