### ISSUE TITLE
TypeError: 'module' object is not subscriptable

### ISSUE THREAD

**Issue by Gewaihir** [Megvii-BaseDetection/YOLOX#371]
I trained the YOLOX model with my own datasets. However, when tested with the trained weights, the following errors were consistently reported:

**Traceback (most recent call last):
  File "tools/demo.py", line 297, in <module>
    main(exp, args)
  File "tools/demo.py", line 288, in main
    image_demo(predictor, vis_folder, args.path, current_time, args.save_result)
  File "tools/demo.py", line 182, in image_demo
    result_image = predictor.visual(outputs[0], img_info, predictor.confthre)
  File "tools/demo.py", line 170, in visual
    vis_res = vis(img, bboxes, scores, cls, cls_conf, self.cls_names)
  File "/home/lee/Project/YOLOX/yolox/utils/visualize.py", line 25, in vis
    text = '{}:{:.1f}%'.format(class_names[cls_id], score * 100)
TypeError: 'module' object is not subscriptable**

This is my test code：

**python tools/demo.py image -f exps/default/yolox_s.py -c weights/best_ckpt.pth --path assets/test/ --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu**

How can we solve this problem?

**Comment by ruinmessi** [comment]
check your own "class_names"

**Comment by Gewaihir** [comment]
Thank you very much for your answer
