### ISSUE TITLE
用自己训练的模型进行测试出错，加载模型出错

### ISSUE THREAD

**Issue by fanfanyaya** [Megvii-BaseDetection/YOLOX#374]
(pytorch_17) D:\YOLOX-main>python demo.py image -n yolox-s -c YOLOX_outputs/yolox_s/best_ckpt.pth.tar --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device [CPU/GPU]
2021-08-05 13:14:25.745 | INFO     | __main__:main:240 - Args: Namespace(camid=0, ckpt='YOLOX_outputs/yolox_s/best_ckpt.pth.tar', conf=0.25, demo='image', device='[CPU/GPU]', exp_file='exps/default/yolox_s.py', experiment_name='yolox
_s', fp16=False, fuse=False, name='yolox-s', nms=0.45, path='assets/dog.jpg', save_result=True, trt=False, tsize=640)
2021-08-05 13:14:25.907 | INFO     | __main__:main:250 - Model Summary: Params: 8.97M, Gflops: 26.81
2021-08-05 13:14:25.909 | INFO     | __main__:main:261 - loading checkpoint
Traceback (most recent call last):
  File "demo.py", line 296, in <module>
    main(exp, args)
  File "demo.py", line 264, in main
    model.load_state_dict(ckpt["model"])
  File "D:\Anaconda\envs\pytorch_17\lib\site-packages\torch\nn\modules\module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([71, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([71]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([71, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([71]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([71, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([71]) from checkpoint, the shape in current model is torch.Size([80]).

**Comment by masterAllen** [comment]
请问你是怎么解决的呢？

**Comment by fanfanyaya** [comment]
> 请问你是怎么解决的呢？我当时没有指定自己训练的exp文件，应该用-f指定exp文件，而不是-n

**Comment by masterAllen** [comment]
> > 请问你是怎么解决的呢？我当时没有指定自己训练的exp文件，应该用-f指定exp文件，而不是-n

解决了，太谢谢你了！

**Comment by fanfanyaya** [comment]
> 请问你是怎么解决的呢？



> > > 说你是怎么解决的呢？我当时没有指定自己训练的exp文件，应该用-f指定exp文件，而不是-n
> 
> 解决了，太谢谢你了！

顺便问一下，你训练精度咋样，我这一直ap在0左右，，

**Comment by masterAllen** [comment]
> > 请问你是怎么解决的呢？
> 
> > > > 说你是怎么解决的呢？我当时没有指定自己训练的exp文件，应该用-f指定exp文件，而不是-n
> > 
> > 
> > 解决了，太谢谢你了！
> 
> 顺便问一下，你训练精度咋样，我这一直ap在0左右，，
YOLOX-S 是 0.6，其他的还没训练好

**Comment by fanfanyaya** [comment]
> > > 请问你是怎么解决的呢？
> > 
> > 
> > > > > 说你是怎么解决的呢？我当时没有指定自己训练的exp文件，应该用-f指定exp文件，而不是-n
> > > 
> > > 
> > > 解决了，太谢谢你了！
> > 
> > 
> > 顺便问一下，你训练精度咋样，我这一直ap在0左右，，
> > YOLOX-S 是 0.6，其他的还没训练好

用的默认的参数吗，我自己yolov5数据转的coco,用的默认的coco128那个exp,一直很低，不知道为啥，，，训练coco128也很低，，就奇怪

**Comment by masterAllen** [comment]
> > > > 请问你是怎么解决的呢？
> > > 
> > > 
> > > > > > 说你是怎么解决的呢？我当时没有指定自己训练的exp文件，应该用-f指定exp文件，而不是-n
> > > > 
> > > > 
> > > > 解决了，太谢谢你了！
> > > 
> > > 
> > > 顺便问一下，你训练精度咋样，我这一直ap在0左右，，
> > > YOLOX-S 是 0.6，其他的还没训练好
> 
> 用的默认的参数吗，我自己yolov5数据转的coco,用的默认的coco128那个exp,一直很低，不知道为啥，，，训练coco128也很低，，就奇怪

是用的默认参数，数据是VOC格式，不过我要检测的类只有一个。我看了一下YOLOX-S最高的AP是63.47。
`python tools/train.py -f my_voc_s.py -b 16 --fp16 -c yolox-s.pth.tar`

**Comment by fanfanyaya** [comment]
> > > > > 那你是怎么解决的呢？
> > > > 
> > > > 
> > > > > > > 说你是怎么解决的呢？我当时没有指定自己训练的exp文件，应该用-f指定exp文件，而不是-n
> > > > > 
> > > > > 
> > > > > 解决了，太谢谢你了！
> > > > 
> > > > 
> > > > 大问一下，你训练精确咋样，我这ap在0左右，，
> > > > YOLOX-S是0.6，其他一直没有训练好
> > 
> > 
> > 用的默认的参数吗，我yolov5数据转的coco用的默认的coco128那个exp，自己一直很小，不知道为，啥，训练coco128也很小，就不太奇怪
> 
> 是用的默认参数，数据是VOC格式，不过我要检测的类只有一个。我看YOLOX-S最高的AP是63.47。
> `python tools/train.py -f my_voc_s.py -b 16 --fp16 -c yolox-s.pth.tar`

好吧，谢谢，那我也试试转成VOC试一下

**Comment by tan90du-sx** [comment]
RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([2, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([2, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([2, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
您好，我用的就是python tools/eval.py -f exps/example/yolox_voc/yolox_voc_s.py -c YOLOX_outputs/yolox_voc_s/best_ckpt.pth -d 1 -b 4 --conf 0.001 --fp16 指定自己训练的exp文件
