### ISSUE TITLE
Get Segmentation fault when set opset=9

### ISSUE THREAD

**Issue by quanh1990** [Megvii-BaseDetection/YOLOX#375]
Is the lowest version of onnx opset 10 ?

`python3 tools/export_onnx.py \
--output-name weights/yolox_s.onnx \
-f exps/example/yolox_voc/yolox_voc_s.py \
-n yolox-s \
-c YOLOX_outputs/yolox_voc_s/best_ckpt.pth.tar \
-o 9`

Then I got Segmentation fault (core dumped)

Thanks

**Comment by ruinmessi** [comment]
Fine... If you really wanna use opset 9, you have to check out which operations this version doesn't support. I suppose the issue may come from the nearest upsample and the focus slice operator. So you may change to bilinear upsample (very little performance influence) and replace the focus with a normal conv 3x3 and fine-tune the model.

**Comment by quanh1990** [comment]
> Fine... If you really wanna use opset 9, you have to check out which operations this version doesn't support. I suppose the issue may come from the nearest upsample and the focus slice operator. So you may change to bilinear upsample (very little performance influence) and replace the focus with a normal conv 3x3 and fine-tune the model.

Thanks a lot! I'll try.

**Comment by zhanggan123456** [comment]
Have you succeeded in visualization

**Comment by quanh1990** [comment]
> Have you succeeded in visualization

Very successful, what is your problem?

**Comment by quanh1990** [comment]
> Have you succeeded in visualization

没啥问题兄弟，你遇到啥问题？

**Comment by zhanggan123456** [comment]
> > 你可视化成功了吗
> 
> 没啥问题兄弟，你遇到啥问题？

可以pull一下你的执行语句吗？参数配置

**Comment by quanh1990** [comment]
> > > 你可视化成功了吗
> > 
> > 
> > 没啥问题兄弟，你遇到啥问题？
> 
> 可以pull一下你的执行语句吗？参数配置

哪个环节？训练/eval还是推理？

**Comment by zhanggan123456** [comment]
> > > > 你可视化成功了吗
> > > 
> > > 
> > > 没啥问题兄弟，你遇到啥问题？
> > 
> > 
> > 可以pull一下你的执行语句吗？参数配置
> 
> 哪个环节？训练/eval还是推理？

网络结构可视化

**Comment by zhanggan123456** [comment]
> > > > > 你可视化成功了吗
> > > > 
> > > > 
> > > > 没啥问题兄弟，你遇到啥问题？
> > > 
> > > 
> > > 可以pull一下你的执行语句吗？参数配置
> > 
> > 
> > 哪个环节？训练/eval还是推理？
> 
> 网络结构可视化

就是将pth权重文件转化为onnx格式文件的语句

**Comment by Demonsu** [comment]
Hello, 请问你转onnx用opset=9成功了嘛，请问具体是怎么做的呢，有分支可以参考一下嘛？

**Comment by Demonsu** [comment]
[0001-Fix-onnx-export-opset-9-segmentation-fault-issue.patch.zip](https://github.com/Megvii-BaseDetection/YOLOX/files/7004960/0001-Fix-onnx-export-opset-9-segmentation-fault-issue.patch.zip)

尝试了个patch但是需要重新训练，感兴趣的可以试一下
