### ISSUE TITLE
pip3 install -v -e

### ISSUE THREAD

**Issue by ankitchandracs** [Megvii-BaseDetection/YOLOX#381]
This command in installation is giving error.
-e option requires 1 argument

Also, the command python3 setup.py develop  gives following error
 [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-10715.write-test'

**Comment by ruinmessi** [comment]
pip3 install -v -e . --user

**Comment by ankitchandracs** [comment]
Running command python setup.py egg_info
WARNING: Discarding file:///home/adc_1/scaledyolov4/YOLOX. Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status -11: python setup.py egg_info Check the logs for full command output.

i am gettng this erro when running the command
