### ISSUE TITLE
Print per-class mAP during evaluation.

### ISSUE THREAD

**Issue by liuyuan000** [Megvii-BaseDetection/YOLOX#385]
请问在测试得到的模型的时候，能不能看到每个种类的map值，就像：
![image](https://user-images.githubusercontent.com/69490927/128372155-7a639773-06c3-4138-9143-2be188cbdf07.png)

**Comment by Joker316701882** [comment]
@liuyuan000 please refer to #397

**Comment by liuyuan000** [comment]
> @liuyuan000 please refer to #397

thanks

**Comment by xialuxi** [comment]
参考：https://github.com/xialuxi/yolox-yolov5
引入了yolov5的测试方法和数据读取

**Comment by liuyuan000** [comment]
> 参考：https://github.com/xialuxi/yolox-yolov5
> 引入了yolov5的测试方法和数据读取

谢谢！

**Comment by liuyuan000** [comment]
> @liuyuan000 please refer to #397

但是我用多gpu训练的时候，每次验证之后就只剩一个gpu 0了，其余的都被kill掉了，就不再继续训练了

**Comment by FateScript** [comment]
closed in #1026
