### ISSUE TITLE
Train on own dataset in COCO format with different class names.

### ISSUE THREAD

**Issue by liminghu** [Megvii-BaseDetection/YOLOX#386]
Hi,
I am trying to train YOLOX-nano with my own dataset in COCO format.
So I just need to change:
self.data_dir = "datasets/my_coco_dataset"
self.train_ann = "instances_train.json"
self.val_ann = "instances_val.json"
self_num_classes = 2

My question is how I can change the class names to i.e. ['no_facemask', 'with_facemask']?
Thanks a lot.

**Comment by liminghu** [comment]
For COCO, the class names are predefined:
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/data/datasets/coco_classes.py

**Comment by liminghu** [comment]
or I just need to add:
self.cls_names = ("no_facemask", "with_facemask")
?

**Comment by ruinmessi** [comment]
For training and evaluation, you don't need to modify the cls_name if you follow the coco anno format. Class names are only used for visualization and demo.
