### ISSUE TITLE
'Namespace' object has no attribute 'occumpy'

### ISSUE THREAD

**Issue by yichen200** [Megvii-BaseDetection/YOLOX#389]
File "/root/YOLOX1/YOLOX-main/yolox/core/trainer.py", line 159, in before_train
    if self.args.occumpy:
       │    └ Namespace(batch_size=16, ckpt='/root/weight/weights/yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='ex...
       └ <yolox.core.trainer.Trainer object at 0x7f983e182040>

**Comment by ruinmessi** [comment]
pull the latest updates
