### ISSUE TITLE
Does YOLOX support Copy-Paste aug?

### ISSUE THREAD

**Issue by HIT-ShuWei** [Megvii-BaseDetection/YOLOX#391]
thx for your work!
Copy-Paste is mentioned in YOLOX paper, but i dont find it in this project. So does it support to use Copy-paste?

**Comment by Joker316701882** [comment]
@HIT-ShuWei Hi, copypaste is only an ablation study in our report. It is not released because it will bring some extra codes which are not related to object detection.
