### ISSUE TITLE
Could you also post the evaluation results of the standard models on COCO 2017 val?

### ISSUE THREAD

**Issue by hiyyg** [Megvii-BaseDetection/YOLOX#395]
Currently it seems the standard models only report results on COCO 2017 test. However, since the evaluation results on COCO 2017 val is easier to obtain, I think it would be better to also post those results. 

Otherwise users, who are not aware of the difference of COCO 2017 val and test, might get confused when their own evaluation results are not the same as the results reported.

**Comment by Joker316701882** [comment]
Please refer to #281. We will add results on the validation set in README in future.
