### ISSUE TITLE
每层预测的目标为什么不限定大小，分配gtbox的时候，匹配为什么不考虑尺度？

### ISSUE THREAD

**Issue by xialuxi** [Megvii-BaseDetection/YOLOX#399]

**Comment by Joker316701882** [comment]
SimOTA will take care of all these problems. Please refer to our code and tech report for more details.

**Comment by Joker316701882** [comment]
你的问题相当于Faster R-CNN出来的时候问为什么Faster R-CNN不用原始R-CNN里的selective search去生成proposal。原因很简单，目的之一就是为了干掉那个。同样SimOTA的目的之一就是干掉其他人为先验，实现fully loss/prediction aware. And please try to use English when opening issues.

**Comment by xialuxi** [comment]
了解，谢谢。
