### ISSUE TITLE
YOLOX在objects365训练，内存直线升高导致宕机

### ISSUE THREAD

**Issue by ahong007007** [Megvii-BaseDetection/YOLOX#401]
因为objects365和COCO数据格式相近，不需要改动太多代码。

用YOLOX在v100 32G 八卡机训练，内存直接从50G升到200G，导致机器宕机，无法训练。

据闻贵司也在用objects365训练模型，请问如何才不能宕机，正常训练啊？

**Comment by ruinmessi** [comment]
我们现在主要在关注其他的方向，暂时。。还没资源跑这个。 你可以降低data_num_workers试试。

**Comment by LinCoce** [comment]
可以调整下标注文件解决内存占用的问题，参考 https://mp.weixin.qq.com/s/LIca7d4qUsEENjFGSDrNCQ
