### ISSUE TITLE
Issue with transform *.pth to *.onnx

### ISSUE THREAD

**Issue by liminghu** [Megvii-BaseDetection/YOLOX#404]
![image](https://user-images.githubusercontent.com/3145211/128542411-868f82e4-d3d1-49a5-b7c6-f5cbf81fe691.png)

![image](https://user-images.githubusercontent.com/3145211/128542426-8e2dd8d8-123c-4692-844e-6acf050adfb1.png)

Thanks a lot.

**Comment by liminghu** [comment]
The issue is with onnxsim, if we add:
 --no-onnxsim

then no issue at all.

**Comment by liminghu** [comment]
One more question, if the *.param is:
7767517
310 346
Input images 0 1 images
Split splitncnn_input0 1 4 images images_splitncnn_0 images_splitncnn_1 images_splitncnn_2 images_splitncnn_3
MemoryData 1156 0 1 1156 0=1
MemoryData 1164 0 1 1164 0=1
MemoryData 1172 0 1 1172 0=1
Crop Slice_4 1 1 images_splitncnn_3 647 -23309=1,0 -23310=1,2147483647 -23311=1,1
Crop Slice_9 1 1 647 652 -23309=1,0 -23310=1,2147483647 -23311=1,2
Crop Slice_14 1 1 images_splitncnn_2 657 -23309=1,0 -23310=1,2147483647 -23311=1,1
Crop Slice_19 1 1 657 662 -23309=1,1 -23310=1,2147483647 -23311=1,2
Crop Slice_24 1 1 images_splitncnn_1 667 -23309=1,1 -23310=1,2147483647 -23311=1,1
Crop Slice_29 1 1 667 672 -23309=1,0 -23310=1,2147483647 -23311=1,2
Crop Slice_34 1 1 images_splitncnn_0 677 -23309=1,1 -23310=1,2147483647 -23311=1,1
Crop Slice_39 1 1 677 682 -23309=1,1 -23310=1,2147483647 -23311=1,2
Concat Concat_40 4 1 652 672 662 682 683 0=0
Convolution Conv_41 1 1 683 1177 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=1728
Swish Mul_43 1 1 1177 687

How to manually modify it?
Thanks a lot.

**Comment by liminghu** [comment]
> The issue is with onnxsim:
> from onnxsim import simplify
> 
> ```
>     # use onnxsimplify to reduce reduent model.
>     onnx_model = onnx.load(args.output_name)
>     model_simp, check = simplify(onnx_model)
> ```
> 
> if we add:
> --no-onnxsim
> 
> then no issue at all.

it seems that we can not turn off onnxsim. otherwise the *.onnx will have 'MemoryData '

**Comment by liminghu** [comment]
The issue is due to the ncnnruntine version:
![image](https://user-images.githubusercontent.com/3145211/128613383-e8fa1185-e8e3-4069-8853-70d72d6e148f.png)

**Comment by dsantiago** [comment]
Helped me also @liminghu , tks!
