### ISSUE TITLE
标准化问题

### ISSUE THREAD

**Issue by XautPTQ** [Megvii-BaseDetection/YOLOX#406]
` dataset = VOCDetection(
            data_dir=os.path.join(get_yolox_datadir(), "VOCdevkit"),
            image_sets=[('2007', 'trainval')],
            img_size=self.input_size,
            preproc=TrainTransform(
                rgb_means=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225),
                max_labels=50,
            ),
        )`
这里以及进行了标准化，但是在进行Mosaic数据增强时，又进行了一次数据标准化，这里是不是有问题
`dataset = MosaicDetection(
            dataset,
            mosaic=not no_aug,
            img_size=self.input_size,
            preproc=TrainTransform(
                rgb_means=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225),
                max_labels=120,
            ),
            degrees=self.degrees,
            translate=self.translate,
            scale=self.scale,
            shear=self.shear,
            perspective=self.perspective,
            enable_mixup=self.enable_mixup,
        )`

**Comment by Joker316701882** [comment]
@XautPTQ COCODataset里是在__getitem__里使用了标准化，而这个函数被MosaicDataset给覆盖了，所以第一次标准化实际上并没有被调用，标准化真正被调用是在MosaicDataset里。
