### ISSUE TITLE
Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by RTae** [Megvii-BaseDetection/YOLOX#407]
I got some error from my custom training datasets. I have **11** class, so I set **self.num_class = 11** and I got this error
`RuntimeError: Class values must be smaller than num_classes.`

so I fix this problem by change from **self.num_class from 11 to 12**. it's run fine , but I think it is't correct way to solve this problem. Do you have another solutions ?

FYI. I use COCO Datasets

**Comment by RTae** [comment]
I found the solution my coco dataset is wrong format when export

**Comment by xellDart** [comment]
Hi, can you explain how you fix this? I hace same error, thanks

**Comment by liguoyu666** [comment]
> I found the solution my coco dataset is wrong format when export

I met the same probelm, how did you solve it ?

**Comment by RTae** [comment]
@liguoyu666 I check my coco dataset and find out it have 12 classes instead of 11 classes. Carefully check it, you will find it.
