### ISSUE TITLE
建议把voc.py中读取标签名称时的名称全变成小写去掉（.lower）否则容易造成ap=0

### ISSUE THREAD

**Issue by zqjnyr** [Megvii-BaseDetection/YOLOX#408]
name = obj.find("name").text.lower().strip()

**Comment by jingruhou** [comment]
这个转小写的操作对自定义类别及名称一点都不友好

**Comment by ruinmessi** [comment]
@zqjnyr  Hi, great thx for your suggestion! Would you send us a PR for this enhancement so that we can better mark your contribution?

**Comment by Joker316701882** [comment]
Related PR #413
