### ISSUE TITLE
How to remove apex?

### ISSUE THREAD

**Issue by Watebear** [Megvii-BaseDetection/YOLOX#41]
Hello , could you please help me remove apex since i met difficulties when compile apex.
Thanks!

**Comment by thunanguyen** [comment]
If you use Window then check this link out https://github.com/kezewang/apex else you should describe more clearly what gone wrong

**Comment by FateScript** [comment]
We fix this issue now, please pull the update and try again. Thx for reporting~

**Comment by FateScript** [comment]
For training, you could comment apex and change code [here](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/core/trainer.py#L161-L163).

**Comment by FateScript** [comment]
We have already remove apex in the new version. Please update if you like.
