### ISSUE TITLE
CPU Mode for This Batch and stop

### ISSUE THREAD

**Issue by ifzhang** [Megvii-BaseDetection/YOLOX#414]
Thanks for your wonderful work! I train on my custom datasets (about 70000 images) and after 5 epochs the logger shows that '------------CPU Mode for This Batch-------------' and the running stops without doing anything! I use fewer images (3000 images) and everything is fine. Can you please help me fix this? Is there anything not normal in the label assignment strategy? Thank you very much!

The log is here:
2021-08-08 16:04:19 | INFO     | yolox.core.trainer:248 - epoch: 6/100, iter: 320/1142, mem: 26793Mb, iter_time: 0.562s, data_time: 0.002s, total_loss: 3.399, iou_loss: 1.920, l1_loss: 0.000, conf_loss: 0.966, cls_loss: 0.513, lr: 2.000e-03, size: 736, ETA: 19:56:26
2021-08-08 16:04:32 | INFO     | yolox.core.trainer:248 - epoch: 6/100, iter: 340/1142, mem: 26793Mb, iter_time: 0.647s, data_time: 0.003s, total_loss: 3.410, iou_loss: 1.907, l1_loss: 0.000, conf_loss: 0.993, cls_loss: 0.510, lr: 2.000e-03, size: 608, ETA: 19:56:06
------------CPU Mode for This Batch-------------

**Comment by ifzhang** [comment]
I also tried to reduce image size and batch size, but this issue still happened after 1-5 epochs. After printing "------------CPU Mode for This Batch-------------", it does not do anything.

**Comment by ruinmessi** [comment]
This CPU mode only occurred when your GPU mem is not enough. So you may have to continue to reduce your batchsize and img size.

**Comment by ifzhang** [comment]
Can reducing the 'max_labels' parameter help? There are more objects in my dataset than COCO, about 50 - 100 objects in one image. 

dataset = MosaicDetection(
                 dataset,
                 mosaic=not no_aug,
                 img_size=self.input_size,
                 preproc=TrainTransform(
                 rgb_means=(0.485, 0.456, 0.406),
                 std=(0.229, 0.224, 0.225),
                 max_labels=200,
            ),
            degrees=self.degrees,
            translate=self.translate,
            scale=self.scale,
            shear=self.shear,
            perspective=self.perspective,
            enable_mixup=self.enable_mixup,
        )

**Comment by ruinmessi** [comment]
Yes, reducing max_label is helpful for reducing GPU mem, but it will also decrease your performance. Your case may be complicated for handle ~100 objects in one image. I suggest you remove mosaic aug (maybe preserve the mixup?) for better performance.

**Comment by ifzhang** [comment]
Thank you very much!

**Comment by ifzhang** [comment]
This OOM issue is probably caused by a few images which contains 500+ objects (CrowdHuman dataset). I solve it by reducing 'max_labels' to 150 in MosaicDetection or filter these very crowded images. Thank you again for your answers!

**Comment by xuezu29** [comment]
In the earliest version, I set 'max_labels' to 600, this error was not reported. It works very well.
