### ISSUE TITLE
EMA Weight

### ISSUE THREAD

**Issue by developer0hye** [Megvii-BaseDetection/YOLOX#417]
Thanks for sharing your works!

Why do you set weight for EMA to 0.9998? 
YOLOv5 set it to 0.9999.

# YOLOx Implementation
https://github.com/Megvii-BaseDetection/YOLOX/blob/b861b22d3f8c78bfab129b8bbfbe2875822941e0/yolox/core/trainer.py#L168

# YOLOv5 Implementation
https://github.com/ultralytics/yolov5/blob/e96c74b5a1c4a27934c5d8ad52cde778af248ed8/train.py#L161

**Comment by Joker316701882** [comment]
I saw 0.9998 somewhere else and then tried it. According to my memory, there isn't much difference between 0.9998 and 0.9999. So I just leave it there.

**Comment by developer0hye** [comment]
@Joker316701882 
Thanks for your reply!
