### ISSUE TITLE
ncnn  output

### ISSUE THREAD

**Issue by jolt2017** [Megvii-BaseDetection/YOLOX#423]
您好：
关于 yolox.cpp 有点疑问，如下图 yolox 模型 有三个输出stride 分别是 8 16 32，为啥你在 yolox.cpp 代码里，只提取了一个 output 的节点值 ?
![企业微信截图_16284938689559](https://user-images.githubusercontent.com/45425532/128672522-459a4809-4685-456c-8d8e-33d485288484.png)

**Comment by FateScript** [comment]
[这里](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_head.py#L208-L210)的代码做了concat，所以没有多层输入了，而是直接拿一个已经输出的结果进行处理。
