### ISSUE TITLE
Can yolox handle training image without labelled bounding box

### ISSUE THREAD

**Issue by kail85** [Megvii-BaseDetection/YOLOX#427]
yolov5 suggests include 10% 'background' images. These are images without labelled bounding box. For example, an object detection task is to identify sheep from the image. There is only one class 'sheep'. 90% of the training images contain at least one sheep in each image, and 10% of the images don't contain any sheep. yolov5 handles such cases very well during training. I wonder if yolox can do the same?

**Comment by ruinmessi** [comment]
Already supported

**Comment by rkinas** [comment]
@GOATmessi7 could you elaborate more on this? It means that I can add to json coco image files without annotations?
