### ISSUE TITLE
训练问题3

### ISSUE THREAD

**Issue by liuwei3612** [Megvii-BaseDetection/YOLOX#428]
我看了训练的日志，输入图像的宽和高都是640×640，但实际图像宽和高1280×960，这个输入图像的宽和高是在哪里设置的啊，怎么默认就是640×640了？

**Comment by Joker316701882** [comment]
@liuwei3612 It is defined here. You can override image size in your own exp config.
https://github.com/Megvii-BaseDetection/YOLOX/blob/3bfac8f843791f007cb9cc7733e6e831f753e7d7/yolox/exp/yolox_base.py#L28
