### ISSUE TITLE
training of mul gpu failed on eval!

### ISSUE THREAD

**Issue by ymw123** [Megvii-BaseDetection/YOLOX#432]
File "/home/ailab/anaconda3/envs/yolox_torch1.6_py_3.6.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1786, in new_group
    timeout=timeout)
            └ datetime.timedelta(0, 1800)
  File "/home/ailab/anaconda3/envs/yolox_torch1.6_py_3.6.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 503, in _new_process_group_helper
    timeout=timeout)
            └ datetime.timedelta(0, 1800)

RuntimeError: [enforce fail at /pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: ib0

**Comment by ymw123** [comment]
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 2                          │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 2                          │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 1                          │
├──────────────────┼────────────────────────────┤
│ depth            │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ width            │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (352, 352)                 │
├──────────────────┼────────────────────────────┤
│ random_size      │ (14, 26)                   │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ scale            │ (0.1, 2)                   │
├──────────────────┼────────────────────────────┤
│ mscale           │ (0.8, 1.6)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ perspective      │ 0.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ True                       │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 2                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 3                          │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'yolox_l_custom'           │
├──────────────────┼────────────────────────────┤
│ test_size        │ (352, 352)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ is_one_class     │ True                       │
╘══════════════════╧════════════════════════════╛

**Comment by ruinmessi** [comment]
You may pull the latest updates and try again. We have already fixed the nccl configure issue
