### ISSUE TITLE
训练后的模型无法

### ISSUE THREAD

**Issue by juechenzp** [Megvii-BaseDetection/YOLOX#441]
![image](https://user-images.githubusercontent.com/38826329/128887108-cc5ea1ae-c954-42b1-8df8-e521825186c3.png)
我用yolox_tiny训练完成后，检测时会报错，这个是哪里出问题了呢

**Comment by ruinmessi** [comment]
Check your num_classes.

**Comment by juechenzp** [comment]
是num_classes的原因，已经解决了
