### ISSUE TITLE
hello！ I have some problem about the self.depth = 0.33 and  self.width = 0.50  in yolox_voc_s.py ？

### ISSUE THREAD

**Issue by yinhai86924** [Megvii-BaseDetection/YOLOX#446]
two parameters of self.depth and  self.width is used to adjust the architecture of CSPdarknet53，if I use the yolox-l or yolox-x， how to set the value of self.depth and  self.width ， I noticed that the self.depth = 0.33 and  self.width = 0.50 are corresponding to yolox-s。I do not see your code ，how to set the value to train the yolox-l or yolox-x? thank you very much

**Comment by zhangming8** [comment]
backbone_cfg = {"nano": [0.33, 0.25],
                    "tiny": [0.33, 0.375],
                    "s": [0.33, 0.5],
                    "m": [0.67, 0.75],
                    "l": [1.0, 1.0],
                    "x": [1.33, 1.25]}

**Comment by yinhai86924** [comment]
thank you!------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月11日(星期三) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] hello！ I have some problem about the self.depth = 0.33 and  self.width = 0.50  in yolox_voc_s.py ？ (#446)
