### ISSUE TITLE
How to get the precision value (array) and recall value (array) when iou=0.5?

### ISSUE THREAD

**Issue by ilem777** [Megvii-BaseDetection/YOLOX#448]
Hello developer, I would like to know how to get the precision and recall values (if it is an array is okay)? How can I add or modify the code to get the precision and recall values when iou=0.5?
I am using a custom dataset in COCO format, Windows system, CUDA 10.2, and I can run the YOLOX project without any problem at the moment.

**Comment by Joker316701882** [comment]
@ilem777 You need to modify codes in [pycocotools](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py). This is not quite YOLOX's issue, hence I close for now.
