### ISSUE TITLE
执行demo的时候报错

### ISSUE THREAD

**Issue by Healer-EugeneLi** [Megvii-BaseDetection/YOLOX#45]
resource.setrlimit(resource.RLIMIT_NOFILE, (ulimit_value, rlimit[1]))
ValueError: current limit exceeds maximum limit

这个问题请问怎么解决呀

**Comment by ruinmessi** [comment]
Please refer to #16 for the same error.

**Comment by Joker316701882** [comment]
PR #63 has fixed this issue. Hence we close it now. Reopen if necessary.
