### ISSUE TITLE
doesn't contains class named 'Exp'

### ISSUE THREAD

**Issue by YaoTaoQiHua** [Megvii-BaseDetection/YOLOX#454]
doesn't contains class named 'Exp'

**Comment by Joker316701882** [comment]
@YaoTaoQiHua Your question is quite unclear. Please provide more detail like the training log, training command, etc.

**Comment by Kangzf1996** [comment]
> @YaoTaoQiHua Your question is quite unclear. Please provide more detail like the training log, training command, etc.

I've met the same error.


python tools/demo.py image -n yolox-s -c yolox_s.pth.tar --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result
Traceback (most recent call last):
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/yolox/exp/build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yolox_s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/demo.py", line 273, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/yolox/exp/build.py", line 53, in get_exp
    return get_exp_by_name(exp_name)
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/yolox/exp/build.py", line 35, in get_exp_by_name
    return get_exp_by_file(exp_path)
  File "/home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/yolox/exp/build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: /home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/exps/default/yolox_s.py doesn't contains class named 'Exp'

**Comment by FateScript** [comment]
How do you install yolox?

**Comment by Kangzf1996** [comment]
> How do you install yolox?

I've solved that error, thanks

**Comment by axxx-xxxa** [comment]
> > > How do you install yolox?
> > 
> > 
> > I've solved that error, thanks
> 
> hi, I met the same problem with you. Can you tell me how do you solve your problem? thanks a lot!

don't install yolox by pip. Uninstall and next to import sys in demo.py  , sys.path.append(${yolo path})

**Comment by axxx-xxxa** [comment]
> > doesn't contains class named 'Exp'
> 
> Hi, do you solve your problem? really need your help,very thanks!
don't install yolox by pip. Uninstall and next to import sys in demo.py , sys.path.append(${yolo path})

**Comment by jperezmedina** [comment]
> > How do you install yolox?
> 
> I've solved that error, thanks

Hi, how you are solve it? I got the same error when try to use yolox_nano. Here my command.

python3.7 tools/demo.py video -n yolox-nano -c models/yolox_nano.pth --path test.mp4 --conf 0.25 --nms 0.45 --tsize 640 --save_result

**Comment by xzc-Eureka** [comment]
> > How do you install yolox?
> 
> I've solved that error, thanks

So, how did you solve this problem? Can you share it?

**Comment by xiaoniun** [comment]
yolox_s.py doesn't contains class named 'Exp'

**Comment by xiaoniun** [comment]
yolox_s.py doesn't contains class named 'Exp'  求解

**Comment by FateScript** [comment]
> yolox_s.py doesn't contains class named 'Exp' 求解

Did you modify any code or are you using the lastest branch?

**Comment by VV-DL-JUMP** [comment]
I solved this problem just now.  the reason of this issue  is 'Exp' class in the file of exps/default/yolox_x.py inherited base-class 'BaseExp'  in the file of ...yolox_base.py, if you weren't overwrited some functions (eg: get_model, get_optimizer, eval) in the 'Exp' class in 'yolox_base.py', the problem will be made. So, overwriting it!

**Comment by VV-DL-JUMP** [comment]
I solved this problem just now.  the reason of this issue  is 'Exp' class in the file of exps/default/yolox_x.py inherited base-class 'BaseExp'  in the file of ...yolox_base.py, if you weren't overwrited some functions (eg: get_model, get_optimizer, eval) in the 'Exp' class in 'yolox_base.py', the problem will be made. So, overwriting it!

**Comment by RabbitRunRun** [comment]
> doesn't contains class named 'Exp'

has you solved this issue? I meet this problem and don't has a clue on how to solve this. Looking forward to your reply.
