### ISSUE TITLE
训练时的图片尺度由[512 - 832]变化是否可以修改？

### ISSUE THREAD

**Issue by jingruhou** [Megvii-BaseDetection/YOLOX#459]
训练时的图片尺度由[512 - 832]变化是否可以修改？
是否可以修改为更大或更小的尺寸？
可否简述帮助一下，谢谢。。。

**Comment by zhangming8** [comment]
修改random_size就可以了
random_size=(14,26)，表示范围在14*32=448 到 26*32=832

**Comment by qingshanjiu** [comment]
我一直对这个参数不太理解，请问修改这个参数会带来什么好的影响呢？

**Comment by jingruhou** [comment]
@zhangming8 学习一下，非常感谢

**Comment by Joker316701882** [comment]
@qingshanjiu 这是常规的多尺度训练策略。范围**稍微**调大调小没有明显影响。但是**没有多尺度**就会掉点。
