### ISSUE TITLE
Window10 onnx->tensorrt yolox

### ISSUE THREAD

**Issue by ttanzhiqiang** [Megvii-BaseDetection/YOLOX#46]
![image](https://user-images.githubusercontent.com/38750855/126450492-441b55fd-acdc-41c9-9926-f8fbd317e304.png)

look https://github.com/ttanzhiqiang/onnx_tensorrt_project

**Comment by ruinmessi** [comment]
Hi, thank you for sharing. What does the last column mean? And your inference time seems too long for TensorRT. In our TRT model, YOLOX-S runs with avg 2.33 ms on a 2080ti.

**Comment by ttanzhiqiang** [comment]
this times include proprecess:8.70ms and forward:5.62ms and reprocessing:1.72ms
![image](https://user-images.githubusercontent.com/38750855/126468190-c15b823a-2151-4083-923e-32a4a8bd4cab.png)
the last column is GPU memory
