### ISSUE TITLE
开始训练 obj loss 非常大（几十~上千）且不稳定的问题

### ISSUE THREAD

**Issue by xiaochengsky** [Megvii-BaseDetection/YOLOX#460]
你好，我看论文中提到把 YOLOv5 的 backbone 部分和 YOLOX 的 head 结合起来，能提升 ∼3.0% to ∼1.0% AP。
但是我尝试后发现一个问题，就是 obj loss 异常大，逐步调试，发现经过初始化的 obj preds 输出的结果比较大（~0.02），实际上对很多负例而言，这挺大的，我跑原生的YOLOX的代码，得到的结果大约是（-4.x），请问这个问题你们之前有遇到过吗？
我单独跑 YOLOX 和 YOLOv5，obj preds 都是比较正常的（-4.x）。

**Comment by Joker316701882** [comment]
@xiaochengsky Did you initialize the bias in obj head?

https://github.com/Megvii-BaseDetection/YOLOX/blob/3bfac8f843791f007cb9cc7733e6e831f753e7d7/yolox/models/yolo_head.py#L132-L141

**Comment by xiaochengsky** [comment]
Wow, I missed it.
Now, It's getting better, THX!
BTW, In this situation,After calculating the loss, when performing the corresponding scale adjustments (such as DDP mode), should I follow the v5 or X standard?

**Comment by Joker316701882** [comment]
It depends on which codebase you are mainly based on. If you are using yolov5, and modify v5's structure to x, then you should follow v5. Otherwise, you should follow ours setting.

**Comment by xiaochengsky** [comment]
THX for you reply, I think this is an excellent contribution! 
But I still have doubts about this:

1) According to the paper, I also combine the backbone(CSPNet, PANet) from v5 and (decoupled head & loss & postprocessing) from X. How do you deal with it in the paper?

2) For me, I used the v5 as my codebase, and used your 'yolox_head.py' instead of  v5's head, loss, detect, etc. It's still runing.
For custom data, I have tried using X's loss scale, and I found the mAP is about 10% lower than v5 in the same period in the first few epochs(<10). Do you think this is normal?   And I found the paper give the training curves with ultralytics's yolov3 head and X's head in Figure 3. I can only look at ultralytics's v3 and v5 curves roughly. 

3)  Based  on your rich experience, can you give me  any suggestions  for  this  experiment?

**Comment by Joker316701882** [comment]
@xiaochengsky Some modifications in YOLOX like decoupled head, loss, label assigning strategies are not separate. So if you only change yolov5's label assign to SimOTA, it's common that you can't get any improvement. To explain more clearly, I use Chinese.

YOLOX的各项改进之间不是孤立的，每一个小改动可能都需要配合loss权重的变化、超参的调整以及其他因素的联动才能发挥作用。所以不能抱有YOLOX的改进，随便拎一个或几个出去就能涨点的期待。YOLOv5的收敛很多地方跟YOLOX差别很大，比如对loss平均时所用的norm，以及Loss权重细粒度的把控。如果非要说拉出去就可以涨点的技巧，我觉得decoupled head是一个，SImOTA在detectron2或者mmdet上直接使用也是可以涨点的，其他地方我都没有信心随便搬到一个算法上就立马涨点。这些因素之间有大量的联动，需要调参才能把效果发挥出来。所以请尽可能把YOLOX看做一个整体，而不是一堆零散tricks的堆砌。如果想在YOLOv5上尝试YOLOX的技巧并且调work，得花费大量的时间和经历，个人不是很推荐。

**Comment by xiaochengsky** [comment]
好的，谢谢。我这边基本就是这样做的，除了使用YOLOv5的backbone和PANet，其它所有的

**Comment by xiaochengsky** [comment]
好的，谢谢。
我这边基本就是按照您那边建议做的（尽量把YOLOX看成一个整体），我自己的实验上，除了使用YOLOv5的backbone（CSPNet）和PANet，后级网络和所有的处理都是使用的YOLOX（也就是您说的 decoupled head, simOTA, 也包括 iou obj 分支，anchor-free的方式等等），v5在这里其实就只是提取特征和加载数据。
主要是看到论文也上提及的这一点是 work 的，所以想尝试下这种处理，毕竟单独这样修改，在代码层面成本较小。
