### ISSUE TITLE
最后15个epoch关掉数据增强他会快速收敛 原因是？

### ISSUE THREAD

**Issue by lgf821793883** [Megvii-BaseDetection/YOLOX#465]

**Comment by Joker316701882** [comment]
@lgf821793883 参照我们在知乎上的[官方回答](https://www.zhihu.com/question/473350307/answer/2021031747)，mosaic会引入大量的不准确标注，同时mixup改变了训练数据的分布。最后15个epochs关掉可以让检测器在真实世界的数据上完成最终收敛（且没有mosaic引入的误差）。可以简单认为aug主要是为了提升分类能力，而回归是个相对简单的任务，所以前面的一堆aug让分类训的足够好了，最后15个epoch是快速的把回归也修好。

之所以能快速，我认为回归相对于分类要简单很多，所以一旦标签误差消失了，网络可以很快的学好。

**Comment by lgf821793883** [comment]
谢谢大佬

**Comment by Jiangyi-chen** [comment]
Does it mean that the sooner you turn off mosaic, the better the effect.
