### ISSUE TITLE
MAP result is always -1 while evaluating

### ISSUE THREAD

**Issue by thunder95** [Megvii-BaseDetection/YOLOX#467]
with this following command:

`
python tools/eval.py -n  yolox-x -c yolox_x.pth.tar -b 8 -d 1 --conf 0.001 --test

`

outputs looks like this:
![2021-08-12 11-26-10 的屏幕截图](https://user-images.githubusercontent.com/22673612/129134052-ea46e38d-cfb2-4fc1-ad02-a0af455c65a1.png)

**Comment by ruinmessi** [comment]
You use `--test` for your evaluation, which is evaluated in test-dev set. So you may remove the flag to get val evaluation or upload your test json file to COCO server for test-dev results.
