### ISSUE TITLE
Can't export to ONNX

### ISSUE THREAD

**Issue by YannPourcenoux** [Megvii-BaseDetection/YOLOX#476]
When running `python tools/export_onnx.py -expn=yolox-tiny` and actually, whatever the experiment name, I always get the error below, and thus I can not run the script. Would you have any idea if I am doing something wrong?
```
AssertionError: plz provide exp file or exp name.
```
![issue_yolox](https://user-images.githubusercontent.com/70574323/129194638-c6856c41-b8f0-45a6-8081-6be0221882cb.png)
Thanks in advance!

**Comment by YannPourcenoux** [comment]
changed line 56 in `export_onnx.py` to
```
exp = get_exp(args.exp_file, args.experiment_name)
```

**Comment by gyh420** [comment]
any help? l also have this question
