### ISSUE TITLE
How to further improve the detection results on crowded datasets

### ISSUE THREAD

**Issue by ifzhang** [Megvii-BaseDetection/YOLOX#484]
Thanks for your wonderful work! I train YOLOX on CrowdHuman and achieves the best detection performance I've ever seen! I want to further improve the detection results on the CrowdHuman dataset. Can you provide some suggestions like how to revise the data augmentation or other settings? By the way, where to use the 'augment_hsv' augmentation?

**Comment by ruinmessi** [comment]
Ah, good news to know!
And we will update the code with ~2x faster training and ~+1% AP for all models within several days. Stay tuned!

**Comment by Joker316701882** [comment]
@ifzhang Hi, thank you for sharing your results! Can you tell us which model you used and what performance you get? By the way, we would like to invite you to create a pull request containing your CrowdHuman customized exp config file.

To further improve the detection performance on the Crowdhuman dataset, you may increase your image size both in the training and inference phases. Current augmentation is strong enough.

Currently, 'augment_hsv' is not properly used. We are working on simplifying the whole pre-processing procedure and will add the 'augment_hsv' in our code soon.

**Comment by Joker316701882** [comment]
@ifzhang  Hi, thank you for sharing your results! Can you tell us which model you used and what performance you get? By the way, we would like to invite you to create a pull request containing your CrowdHuman customized exp config file.

To further improve the detection performance on the Crowdhuman dataset, you may increase your image size in both training and inference phases. Current augmentation is strong enough.

Currently, 'augment_hsv' is not properly used. We are working on simplifying the whole pre-processing procedure and will add the 'augment_hsv' in our code soon. As mentioned by @ruinmessi, the simplified preprocessing will greatly speed up the training procedure.

**Comment by ifzhang** [comment]
Thank you for your suggestions! I use CrowdHuman as part of my training data and do not directly test on CrowdHuman. I will clean my code and test on CrowdHuman before creating a PR. Looking forward to your new version :)

**Comment by umairjavaid** [comment]
@ifzhang  can you please share the data loader you have used for training on crowd human dataset?
