### ISSUE TITLE
How to change default epoch Size of 300 for custom Pascal VOC dataset training?

### ISSUE THREAD

**Issue by kp-algomaster** [Megvii-BaseDetection/YOLOX#485]

**Comment by Promisery** [comment]
In your exp set self.max_epoch = max_epoch

**Comment by kp-algomaster** [comment]
> In your exp set self.max_epoch = max_epoch

Thanks. 
I have added this in Exp claa in  file yolox_voc_s.py as shown below. Now its taking updatecd epoch size
class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.num_classes = 10
        self.depth = 0.33
        self.width = 0.50
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]
        self.max_epoch = 1000
