### ISSUE TITLE
yolox-s.pth 2 yolox-s.onnx question？

### ISSUE THREAD

**Issue by sunmooncode** [Megvii-BaseDetection/YOLOX#495]
yolox-s.pth weight size 71.4M
yolox-s.onnx weight size 35.7M
 Why is there so much difference？

**Comment by Joker316701882** [comment]
@sunmooncode yolox-s.pth contains not only model parameters, but also the information in the optimizer. For example, the momentum in SGD for each parameter. However, the yolox-s.onnx only contains model's parameters.

**Comment by sunmooncode** [comment]
@Joker316701882 thanks
