### ISSUE TITLE
Segmentation fault (core dumped) while trying to convert to TensorRT on Jetson Nano

### ISSUE THREAD

**Issue by yusufpraditya** [Megvii-BaseDetection/YOLOX#496]
Hi, I'm trying to export my custom model to TensorRT on Jetson Nano, but when I tried this command:

`python3 tools/trt.py -f ~/project/YOLOX/exps/default/yolox_s.py -c best_ckpt.pth.tar`

It throws an error:
`Segmentation fault (core dumped)`

**Comment by ruinmessi** [comment]
Could you provide more information about the error? like the tensorrt log

**Comment by yusufpraditya** [comment]
> 
> 
> Could you provide more information about the error? like the tensorrt log

After I ran trt.py it only shows the segmentation fault error

**Comment by yusufpraditya** [comment]
How to add tensorrt log?

**Comment by zxy-95** [comment]
> How to add tensorrt log?

in trt.py change max_workspace_size=(1 << 32) into max_workspace_size=(1 << 28), or smaller, in order to reduce memory usage.

**Comment by yusufpraditya** [comment]
> 
> 
> > How to add tensorrt log?
> 
> in trt.py change max_workspace_size=(1 << 32) into max_workspace_size=(1 << 28), or smaller, in order to reduce memory usage.

Thank you. Reduced the max workspace size and it works.

**Comment by hzlijianjun** [comment]
More matched issue is:
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
