### ISSUE TITLE
difference between YOLOV5 and YOLOX

### ISSUE THREAD

**Issue by liminghu** [Megvii-BaseDetection/YOLOX#497]
Can some one summarize the difference between YOLOV5 and YOLOX in the code base?
This is what I know:
1. removal of box anchors (improves the portability of the model to edge devices), anchor free
2. the decoupling of the YOLO detection head into separate feature channels for box classification and box regression (improves training convergence time and model accuracy)
3.  leading label assignment strategy SimOTA
4. Strong data augmentation: Mosaic, MixUp, turn off strong augmentation in later iterations.
5. train from scratch.

**Comment by zhiqwang** [comment]
Seems that the fifth trick (train from scratch) you mentioned above are used by both repos.

**Comment by Joker316701882** [comment]
@liminghu This is what I can recall:

YOLOv5: 
- Hyperparams evolution. 
- Different loss weights for different FPN layers
- CIoU (I'm not sure.)

YOLOX:
- Removal of box anchors (improves the portability of the model to edge devices), anchor free
- The decoupling of the YOLO detection head into separate feature channels for box classification and box regression (improves training convergence time and model accuracy)
- Leading label assignment strategy SimOTA
- Strong data augmentation: MixUp with large scale jittering, turn off strong augmentation in later iterations.

**Comment by FateScript** [comment]
Close this issue now, feel free to reopen it if you have any further questions.
