### ISSUE TITLE
what is the mean of argument 'max_labels' in TrainTransform

### ISSUE THREAD

**Issue by Stoneplay** [Megvii-BaseDetection/YOLOX#499]
Hi, what is the mean of argument 'max_labels' in 'TrainTransform' class ? Thx.

**Comment by Joker316701882** [comment]
@Stoneplay It means the valid maximum number of ground-truth targets in an image. If there is more than 120 gt in your image, only the former 120 will be loaded, others will be treated as backgrounds.

**Comment by Stoneplay** [comment]
Sorry, I‘m not so familiar with object detection. What's the reason for doing like this ? I notice that the maximum number of targets in an image in COCO is more 90. After the mosaic transform, the number is far more than 120.  Is this a common practice in Object detection in COCO ?

**Comment by Joker316701882** [comment]
@Stoneplay No, it's not. We want to limit the number of ground-truth to save memory occupation. In the common case, there should not exist the limitation like "max_labels".

By the way, you can modify the number of "max_labels" to fit your own situation.

**Comment by Stoneplay** [comment]
Ok, I get it. Thank you very much for your reply !
