### ISSUE TITLE
yolox安装不上

### ISSUE THREAD

**Issue by myrzx** [Megvii-BaseDetection/YOLOX#50]
你好，我使用命令pip3 install -v -e .  # or  python3 setup.py develop时，报如下错误：
![image](https://user-images.githubusercontent.com/45350198/126466274-45ad6078-b05d-4684-b479-07210e38f01d.png)

**Comment by ruinmessi** [comment]
You may have to remove "# or  python3 setup.py develop"....

**Comment by FateScript** [comment]
Is this issue fixed ? @myrzx

**Comment by myrzx** [comment]
> You may have to remove "# or python3 setup.py develop"....

> Is this issue fixed ? @myrzx

谢谢，解决了！但是又出现了新的问题，apex安装不上，显示要VC++14，但是我先后安装了15、19版本的VS都不行，可否告知一下你们的VS版本及配置
![image](https://user-images.githubusercontent.com/45350198/126653433-baf8f52d-ff67-4350-b949-c40e66b48889.png)

**Comment by FateScript** [comment]
apex
