### ISSUE TITLE
AssertionError: assert targets is not None

### ISSUE THREAD

**Issue by kingrt666666** [Megvii-BaseDetection/YOLOX#500]
请问为什么会出现如下错误呢？
2021-08-14 17:57:55 | INFO     | yolox.core.trainer:309 - Save weights to ./YOLOX_outputs\ship-yolox-s
  0%|          | 0/52 [00:06<?, ?it/s]

2021-08-14 17:58:02 | ERROR    | yolox.core.launch:68 - An error has been caught in function 'launch', process 'MainProcess' (16844), thread 'MainThread' (9948):
Traceback (most recent call last):

  File "D:/YOLOX-main/tools\train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
             │               │    └ Namespace(batch_size=4, ckpt='../yolox_s.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='../exps/example/yolox...
             │               └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
             └ 'auto'

> File "D:\YOLOX-main\yolox\core\launch.py", line 68, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000002D05023CA60>

  File "D:/YOLOX-main/tools\train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000002D0501A72F0>
    └ <yolox.core.trainer.Trainer object at 0x000002D05026FF28>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 70, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000002D0501C4B70>
    └ <yolox.core.trainer.Trainer object at 0x000002D05026FF28>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 80, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x000002D05021C268>
    └ <yolox.core.trainer.Trainer object at 0x000002D05026FF28>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 210, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x000002D05021C510>
    └ <yolox.core.trainer.Trainer object at 0x000002D05026FF28>

  File "D:\YOLOX-main\yolox\core\trainer.py", line 295, in evaluate_and_save_model
    ap50_95, ap50, summary = self.exp.eval(evalmodel, self.evaluator, self.is_distributed)
                             │    │   │    │          │    │          │    └ False
                             │    │   │    │          │    │          └ <yolox.core.trainer.Trainer object at 0x000002D05026FF28>
                             │    │   │    │          │    └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000002D056646F98>
                             │    │   │    │          └ <yolox.core.trainer.Trainer object at 0x000002D05026FF28>
                             │    │   │    └ YOLOX(
                             │    │   │        (backbone): YOLOPAFPN(
                             │    │   │          (backbone): CSPDarknet(
                             │    │   │            (stem): Focus(
                             │    │   │              (conv): BaseConv(
                             │    │   │                (conv): ...
                             │    │   └ <function Exp.eval at 0x000002D050246048>
                             │    └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
                             └ <yolox.core.trainer.Trainer object at 0x000002D05026FF28>

  File "D:\YOLOX-main\yolox\exp\yolox_base.py", line 250, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function VOCEvaluator.evaluate at 0x000002D0501CD510>
           └ <yolox.evaluators.voc_evaluator.VOCEvaluator object at 0x000002D056646F98>

  File "D:\YOLOX-main\yolox\evaluators\voc_evaluator.py", line 91, in evaluate
    outputs = model(imgs)
              │     └ tensor([[[[-0.8849, -0.8849, -0.8849,  ..., -0.8507, -0.8678, -0.8678],
              │                 [-0.9020, -0.9020, -0.9020,  ..., -0.7822, ...
              └ YOLOX(
                  (backbone): YOLOPAFPN(
                    (backbone): CSPDarknet(
                      (stem): Focus(
                        (conv): BaseConv(
                          (conv): ...

  File "C:\Python36\Lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[-0.8849, -0.8849, -0.8849,  ..., -0.8507, -0.8678, -0.8678],
             │    │                    [-0.9020, -0.9020, -0.9020,  ..., -0.7822,...
             │    └ <function _initialize.<locals>.patch_forward.<locals>.new_fwd at 0x000002D05A7CCE18>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...
  File "C:\Python36\Lib\site-packages\apex-0.1-py3.6.egg\apex\amp\_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
      │       │       └ functools.partial(<function to_type at 0x000002D04EC8C488>, torch.float32)
      │       └ {}
      └ <function applier at 0x000002D04ECBBBF8>

  File "D:\YOLOX-main\yolox\models\yolox.py", line 33, in forward
    assert targets is not None
           └ None

AssertionError: assert targets is not None

**Comment by Joker316701882** [comment]
@kingrt666666 Are there any images without any ground-truth in your dataset?

**Comment by kingrt666666** [comment]
> @kingrt666666 Are there any images without any ground-truth in your dataset?

重新配置了一下模型参数，已经解决了。
