### ISSUE TITLE
Can YOLOX detect a rotated item with a rotated bounding box?

### ISSUE THREAD

**Issue by HUI11126** [Megvii-BaseDetection/YOLOX#501]
like this: [https://github.com/cgvict/roLabelImg](url)
![image](https://user-images.githubusercontent.com/25843822/129444494-bb871206-e85b-4700-88af-108c0fe0d9e2.png)

Or can I label a a rotated item with labelme, and YOLOX detect the rotated bounding box?
like this:
![Screenshot from 2021-08-14 19-12-27](https://user-images.githubusercontent.com/25843822/129444611-c7f797fd-7456-4962-9689-61eb20ba2d05.png)

**Comment by HUI11126** [comment]
It looks better if the bounding box cover the item precisely.

**Comment by Joker316701882** [comment]
@HUI11126 Not supported now.
