### ISSUE TITLE
where is iou branch?

### ISSUE THREAD

**Issue by Bingolby** [Megvii-BaseDetection/YOLOX#503]
Great work, thanks for sharing！
I saw in the paper that YOLOX uses the IOU branch, but I didn’t see the IOU branch in the code, so actually YOLOX still uses the obj branch, right?

**Comment by Joker316701882** [comment]
Yes, YOLOX uses obj branch. For IoU branch, it is merged into cls branch. In the following code, the cls target is multiplied by preded ious.
https://github.com/Megvii-BaseDetection/YOLOX/blob/e1052df71842031413f6030723c3607b839c80ce/yolox/models/yolo_head.py#L363-L365

**Comment by Bingolby** [comment]
> Yes, YOLOX uses obj branch. For IoU branch, it is merged into cls branch. In the following code, the cls target is multiplied by preded ious.
> https://github.com/Megvii-BaseDetection/YOLOX/blob/e1052df71842031413f6030723c3607b839c80ce/yolox/models/yolo_head.py#L363-L365

Thank you for your quick reply!
