### ISSUE TITLE
推理速度的疑问

### ISSUE THREAD

**Issue by violet2422** [Megvii-BaseDetection/YOLOX#51]
### YOLOv5官方推理速度
![image](https://user-images.githubusercontent.com/73391269/126486488-9e2496fb-9fed-4649-9d4d-99a452499bdb.png)
### 论文里的YOLOv5的推理速度
![image](https://user-images.githubusercontent.com/73391269/126487450-074c1e6e-75b7-4a63-a914-322a68f99d3f.png)
都是V100为何相差这么多！！！求大佬解答

**Comment by violet2422** [comment]
![image](https://user-images.githubusercontent.com/73391269/126487596-fa0bce88-ed2f-4a3c-9fb9-968bcfcd562d.png)

**Comment by Joker316701882** [comment]
@violet2422 
They use batch inference (when inferencing, the batch size is 32). That's meaningless. 
YOLOv5测速的时候使用的batch size=32，这样可以打满GPU带宽，会快很多，但是这样测速没有意义。

**Comment by violet2422** [comment]
> @violet2422
> They use batch inference (when inferencing, the batch size is 32). That's meaningless.
> YOLOv5测速的时候使用的batch size=32，这样可以打满GPU带宽，会快很多，但是这样测速没有意义。

非常谢谢您的回答，我恍然大悟！！！
