### ISSUE TITLE
请问进行了哪些具体改进让tiny的精度从31.7提高到32.8

### ISSUE THREAD

**Issue by Watebear** [Megvii-BaseDetection/YOLOX#511]
您好，我看到您的一项commit：https://github.com/Megvii-BaseDetection/YOLOX/commit/1660f0c285eb7c914b96dff82c76e415618e5371#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

这里只说了去掉保存模型的 .tar ，并没有提到更改多的改进操作。
请问方便告知具体的改进吗 或者 提高精度的原因 ？

**Comment by liminghu** [comment]
most likely nothing changed, just a new re-run.

**Comment by FateScript** [comment]
Tiny model provided before is trained before we release, after adding some code like "allreduce_norm" and rerun, tiny model actually get better performance.

**Comment by FateScript** [comment]
Close this issue now, feel free to reopen it if you have further quesion.
