### ISSUE TITLE
difference between "self.input_size" and "self.random_size", and the meaning of "self.scale" and "self.mscale"

### ISSUE THREAD

**Issue by anonymoussss** [Megvii-BaseDetection/YOLOX#514]
Hi,
    Glad to use such an excellent work as yolox, but I still have the following problems：
    (1) What is the difference between "self.input_size" and "self.random_size".  My understanding is, if "self.random_size" is specified as (20, 30), then the size of the input training data is from 640 to 960,  no matter how parameter  "self.input_size" is set.  Am I right?
    (2) Are parameters "self.scale" and "self.mscale"  only used in Mosaic augment？

**Comment by anonymoussss** [comment]
Is anyone there?

**Comment by Joker316701882** [comment]
@anonymoussss 
(1). Yes, you are right. We will refactor this code this week to make easier to understand.
(2). self.scale is used for Mosaic. self.mscale is used for mixup.

**Comment by anonymoussss** [comment]
@Joker316701882 
Get it, thx  : )
