### ISSUE TITLE
Poor performance on custom data comparing to yolov5

### ISSUE THREAD

**Issue by kail85** [Megvii-BaseDetection/YOLOX#521]
I have a set of brain MRI images with tumor bounding box annotated. The image is grayscale, 8bit, 1024 x 1024. Previously, I trained a yolov5 (yolov5m) tumor detector. In default settings (no change from git clone), after 100 epochs I got map@0.5 = 0.7 on validation data. 

Using yolox, after 100 epochs training, I got map@0.5 = 0.3 on the same validation data. I wonder if I missed any important setting? My yolo_m.py reads below

```
import os

from yolox.exp import Exp as MyExp

class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.depth = 0.67
        self.width = 0.75
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]

        # Define yourself dataset path
        self.data_dir = "datasets/brainMRI"
        self.train_ann = "train.json"
        self.val_ann = "val.json"

        self.num_classes = 1

        self.input_size = (1024, 1024)

        self.max_epoch = 100
        self.data_num_workers = 6
        self.eval_interval = 2
```

my training command is

`python tools/train.py --exp_file exps/example/custom/yolox_m.py --devices 1 --batch-size 4 --fp16 --occupy --ckpt model/yolox_m.pth`

**Comment by jjn037** [comment]
mark

**Comment by Joker316701882** [comment]
@kail85 You may also need to add the following setting:

```
self.random_size = (32, 32)
self.test_size = (1024, 1024)
```

The first line means the training scales of your input size ranges from 1024 to 1024. You can modify the value 32 based on your own need. For example: (28, 36).

The second line means using (1024, 1024) for testing.

Let us know if you make any progress.

**Comment by Joker316701882** [comment]
According to #578, this issue has been fixed.
