### ISSUE TITLE
The fast model problem 

### ISSUE THREAD

**Issue by sunmooncode** [Megvii-BaseDetection/YOLOX#526]
1、 when I used 
           "python tools/train.py -n yolox-s -d 1 -b 32 --fp16 -o -c datasets/yolox_s.pth [--cache]" ,
      it will report an error:
       **"Traceback (most recent call last):
  File "tools/train.py", line 116, in <module>
    exp.merge(args.opts)
  File "/home//YOLOX/yolox/exp/base_exp.py", line 64, in merge
    assert len(cfg_list) % 2 == 0
AssertionError"**
     but when i change  "[--cache]" to "--cache" , it will work. 
2、 This mean I have insufficient memory?
      RuntimeError: Trying to create tensor with negative dimension -1096: [256, 1024, -1096]

**Comment by ruinmessi** [comment]
1. [] means optional... so the exact way to work is `--cache`
2.  remove `-o` can fix this error.

**Comment by sunmooncode** [comment]
@ruinmessi Thank you for your answer
