### ISSUE TITLE
Openvino C++ inference issue

### ISSUE THREAD

**Issue by Dereck-Ting** [Megvii-BaseDetection/YOLOX#531]
![result](https://user-images.githubusercontent.com/75430702/130052130-42ba8ec7-59ea-4c4d-8d8e-07d8e2401ba4.PNG)
I trained my own data with 6 classes and convert it to openvino xml file. I tested this xml and bin file under openvino python script and works good , but I got the weird results when tested in Openvino C++. Do I need to change something in c++ file besides class number?

**Comment by ruinmessi** [comment]
check the img input size in cpp file to be consistent with your converted model

**Comment by Dereck-Ting** [comment]
> check the img input size in cpp file to be consistent with your converted model, and the num_class should also be changeI 

The input size in cpp file is consistent with the model, I used yolox_tiny and set the size to be both 416, but the result in cpp is still werid.
