### ISSUE TITLE
pr:fix bug in yolox_openvino.cpp

### ISSUE THREAD

**Issue by amazingzby** [Megvii-BaseDetection/YOLOX#532]
使用openvino C++代码部署时，当INPUT_H和INPUT_W相同时结果正确，不同时不能输出结果。尝试能运行正确运行的修改如下：
cv::Mat out( INPUT_W, INPUT_H,CV_8UC3, cv::Scalar(114, 114, 114));
修改为：
cv::Mat out(INPUT_H, INPUT_W, CV_8UC3, cv::Scalar(114, 114, 114));
修改generate_grids_and_stride函数：
static void generate_grids_and_stride(const int target_h,int target_w, std::vector<int>& strides, std::vector<GridAndStride>& grid_strides) 
{
    for (auto stride : strides)
    {
        int num_grid_h = target_h / stride;
        int num_grid_w = target_w / stride;
        for (int g1 = 0; g1 < num_grid_w; g1++)
        {
            for (int g0 = 0; g0 < num_grid_h; g0++)
            {
                grid_strides.push_back((GridAndStride){g0, g1, stride});
            }
        }
    }
}
修改调用方式，
generate_grids_and_stride(INPUT_W, strides, grid_strides);
改为：
generate_grids_and_stride(INPUT_W,INPUT_H, strides, grid_strides);

**Comment by ruinmessi** [comment]
Thx. Could you send us a PR for this enhancement so we can better remark your contribution?

**Comment by amazingzby** [comment]
@ruinmessi  https://github.com/Megvii-BaseDetection/YOLOX/pull/546
