### ISSUE TITLE
Unable to overfit coco128

### ISSUE THREAD

**Issue by kail85** [Megvii-BaseDetection/YOLOX#534]
I downloaded coco128 from [here](https://drive.google.com/file/d/16N3u36ycNd70m23IM7vMuRQXejAJY9Fs/view?usp=sharing). In a 100 epoch training, the most map metrics stayed at 0. I just changed yolox_m.py and did not touch any other codes. My yolox_m.py reads below and I used yolox_m model

```
import os
from yolox.exp import Exp as MyExp

class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.depth = 0.67
        self.width = 0.75
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]

        # Define yourself dataset path
        self.data_dir = "datasets/coco128"
        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"

        self.num_classes = 71

        self.input_size = (640, 640)

        self.max_epoch = 100
        self.data_num_workers = 6
        self.eval_interval = 2
```

I wonder if anyone could kindly share a config file to overfit coco128? Thanks in advance.

**Comment by kail85** [comment]
solved. turned out something not right about the annotation json.

**Comment by sudharsan2000** [comment]
> solved. turned out something not right about the annotation json.

Can you please share details on what was wrong and how you fixed it
