### ISSUE TITLE
The input is no longer normalized, right?

### ISSUE THREAD

**Issue by xuezu29** [Megvii-BaseDetection/YOLOX#536]
Thanks very much for your works, In the latest version there is no normalization before the network forward, and not even divided by 255. right?

**Comment by ruinmessi** [comment]
Yes. Since we don't use ImageNet pre-trained weights, these preprocess are redundant.

**Comment by xuezu29** [comment]
@ruinmessi  Thank you very much.

**Comment by jinfagang** [comment]
@ruinmessi  Seems not /255 as well, directly using raw input? Does this helps boost performance?

**Comment by Joker316701882** [comment]
@jinfagang It's only used for simplifying the preprocessing pipeline. Due to the existence of BN, we no more need to normalize the training image.
