### ISSUE TITLE
TypeError: get_data_loader() got an unexpected keyword argument 'cache_img'

### ISSUE THREAD

**Issue by PhoenyHan** [Megvii-BaseDetection/YOLOX#540]
![2021-08-20 14-39-18屏幕截图](https://user-images.githubusercontent.com/87840463/130191295-2b03b3a5-b8e6-4df1-a787-e7971659b281.png)

**Comment by PhoenyHan** [comment]
is this the bug of new version or something wrong on my side?

**Comment by ruinmessi** [comment]
Have you pulled the new updates? And if you use your own exp file, you may also have to modify the get_data_loader() function in your own exp file.

**Comment by gyy0592** [comment]
change [--cache] into --cache

**Comment by PhoenyHan** [comment]
> change [--cache] into --cache

this error occurs with and without --cache

**Comment by PhoenyHan** [comment]
> Have you pulled the new updates? And if you use your own exp file, you may also have to modify the get_data_loader() function in your own exp file.

yes, I'm not sure how to modify it, could you provide tutorial on this?

**Comment by FateScript** [comment]
Are you using your custom dataset?

**Comment by PhoenyHan** [comment]
@FateScript  yes, in VOC format

**Comment by Gabrieluol** [comment]
I'm facing the same problem, don't know how to solve yet

**Comment by PhoenyHan** [comment]
@Gabrieluol   pull the latest code, it solved

**Comment by Gabrieluol** [comment]
> @Gabrieluol pull the latest code, it solved

Could you be a bit more specific about which part of the code needs to be updated? Many thanks

**Comment by PhoenyHan** [comment]
@Gabrieluol  I'm not sure, guess voc.py,  for safety just clone the whole project XD

**Comment by Gabrieluol** [comment]
haha, thanks!

**Comment by ZainZhao** [comment]
Have you solved the problem? I have the same problem， many thanks for replying
