### ISSUE TITLE
Characters in README cause install problem on Windows

### ISSUE THREAD

**Issue by emillundh** [Megvii-BaseDetection/YOLOX#542]
Doing `pip install .` on Windows 10 (python 3.9), I receive 
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 435: character maps to <undefined>`
The stack trace gave few clues to where the error was, but after googling, I found out that the README file was the culprit and i simply had to remove the lines containing thick braces [] under "Updates!!". Then I could install.
So I'd like to propose a nicer (Windows-friendly?) kind of character set for the README.

**Comment by ruinmessi** [comment]
Did this pr #274  fix this issue already?

**Comment by emillundh** [comment]
Yes, thanks!
