### ISSUE TITLE
where does the 1 AP boost comes from in new model?

### ISSUE THREAD

**Issue by jinfagang** [Megvii-BaseDetection/YOLOX#547]
where does the 1 AP boost comes from in new model?

**Comment by Joker316701882** [comment]
@jinfagang We add all_reduce_norm in the training phase

https://github.com/Megvii-BaseDetection/YOLOX/blob/c9fe0aae2db90adccc90f7e5a16f044bf110c816/yolox/core/trainer.py#L206

and fix a tiny bug in the annotation parser #324 .
