### ISSUE TITLE
ncnn 推理没有结果

### ISSUE THREAD

**Issue by panghongwei17** [Megvii-BaseDetection/YOLOX#552]

**Comment by panghongwei17** [comment]
ncnn官网给出的yolox.cpp有问题，换成原作者的yolox.cpp就可以正常推理了。。。
![image](https://user-images.githubusercontent.com/51523667/130341292-62babdfc-d441-440b-874d-126ac7432662.png)

**Comment by Joker316701882** [comment]
@panghongwei17 Thank you for your information! Maybe you can open another issue in ncnn : p
