### ISSUE TITLE
what meanings for legacy models ? difference legacy and standard models

### ISSUE THREAD

**Issue by zgsxwsdxg** [Megvii-BaseDetection/YOLOX#558]
您好！我想问下legacy 和 standard models 是什么关系？谢谢！

**Comment by Joker316701882** [comment]
@zgsxwsdxg In #523, we greatly simplified the preprocessing pipeline for YOLOX and re-trained them, getting the current standard models. The pre-trained models before #523 update are now renamed as legacy models.

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg In #523, we greatly simplified the preprocessing pipeline for YOLOX and re-trained them, getting the current standard models. The pre-trained models before #523 update are now renamed as legacy models.

谢谢，理解了
