### ISSUE TITLE
Cannot download benchmark model

### ISSUE THREAD

**Issue by jasonkhadka** [Megvii-BaseDetection/YOLOX#56]
The benchmark models are not accessible and are not downloadable.

**Comment by steinmann** [comment]
It seems like the models are on a Chinese server. Maybe an issue with the great firewall?

**Comment by yonomitt** [comment]
If you have a VPN provider with servers in Hong Kong, you can use those to download the weights.

**Comment by FateScript** [comment]
Hello @jasonkhadka , We provide github link now, you could click and download now.

**Comment by jasonkhadka** [comment]
Thank you! i can access it now!
