### ISSUE TITLE
nms 后处理对于检测效果的影响

### ISSUE THREAD

**Issue by zgsxwsdxg** [Megvii-BaseDetection/YOLOX#560]
您好！问下，我发现yolox自带的模型推理时一个目标有时会检测出两个目标框，然后这两个框是属于不同的类别且iou还很大，nms处理是否合理？你们用的是那种nms，基于什么nms算法实现的？谢谢

**Comment by Joker316701882** [comment]
我们用了multiclass nms，是否合理暂时不清楚。如果觉得检测效果多了一个框，可以使用一个class agnostic 的NMS并且设置较高的阈值过滤一下最终的结果。

**Comment by zgsxwsdxg** [comment]
> 我们用了multiclass nms，是否合理暂时不清楚。如果觉得�检测效果多了一个框，可以使用一个class agnostic 的NMS并且设置较高的阈值过滤一下最终的结果。

谢谢

**Comment by Kyle-fang** [comment]
Why is the detection frame with different categories but large IOU suppressed？

**Comment by Kyle-fang** [comment]
多类别NMS不是应该只在单类中对冗余框进行抑制吗？
