### ISSUE TITLE
After I followed the installation process,I got an error with Demo

### ISSUE THREAD

**Issue by LVkunfeng** [Megvii-BaseDetection/YOLOX#57]
![2021-07-21 22-30-38屏幕截图](https://user-images.githubusercontent.com/72434148/126506284-8ba89bc4-7346-4f18-8660-35e935bc47f1.png)

**Comment by FateScript** [comment]
Hello @LVkunfeng , we fix this in the newest [commit](https://github.com/Megvii-BaseDetection/YOLOX/commit/a026133849b724b64fc4794224ee2a2b1c3b8600), you could pull them and retry again.
