### ISSUE TITLE
Tensorrt-7.1.3.4 trt Engine infer result is much worse than using pytorch for own trained model

### ISSUE THREAD

**Issue by lantudou** [Megvii-BaseDetection/YOLOX#570]
cuda_version = 11.1
tensorrt_version = 7.1.3.4

the command to use demo.py for normal pytorch interference：
`python3 tools/demo.py image -f exps/yolol_chang.py -c ./best_ckpt.pth --save_result --path test.jpg --device gpu`

the command to use demo.py for tensorrt：
`python3 tools/demo.py image -f exps/yolol_chang.py -c ./best_ckpt.pth --save_result --path test.jpg --device gpu --trt`

My exp file is given as below : (yolol_chang.py)

```
import os

from yolox.exp import Exp as MyExp


class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.depth = 1
        self.width = 1
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0] + "chang1"

        # Define yourself dataset path
        #self.data_dir = "/share_data/YuhaoSun/yoloxtest2/"
        #self.train_ann = "/share_data/YuhaoSun/VOCcancer10_normal_train_argument/train.json"
        #self.val_ann = "/share_data/YuhaoSun/VOCcancer10_test/train.json"
        #self.num_classes = 9

        self.data_dir = "/share_data/YuhaoSun/yoloxtest/image"
        self.train_ann = "/share_data/YuhaoSun/VOCJC4.2_normal_train_argument/train.json"
        self.val_ann = "/share_data/YuhaoSun/VOCJC_test_8.11_crop/train.json" 
        self.num_classes = 1

        self.max_epoch = 100
        self.data_num_workers = 4
        self.eval_interval = 1
```

And got two different results: 

For normal gpu:
![HZ05A0151W5022](https://user-images.githubusercontent.com/34973475/130551926-33de4a7a-33db-49e3-ab26-e1ed257c8713.jpg)

For tensorrt:
![HZ05A0151W5022](https://user-images.githubusercontent.com/34973475/130551861-75fcc332-5da4-4502-aa94-dd166c80a975.jpg)

This just is a demo to show you the performance reduction about using tensorrt and torch2trt

**Comment by lantudou** [comment]
I observed the same thing for converting onnx model to tensorrt engine. I wonder whether this issue is because of the tensorrt version

**Comment by ruinmessi** [comment]
Have you checked the input shape for all these models?  I have no idea about the differences between tensorrt versions. You may manually convert the coco model to verify it. 
I also suggest you to use `max(abs(out_from_pytorch - out_from_trt))` to check the output of trt models.

**Comment by lantudou** [comment]
I have noticed that the trt infer need an extra decoder process before the postprocess in demo.py:
https://github.com/Megvii-BaseDetection/YOLOX/blob/3c07916abbaa05eea0295cd48c26623f05acb1ac/tools/demo.py#L155

So, I tried to print the output tensor directly before the postprocess and got the following results:

```
import torch
trt_output = torch.load('test1.pt')
pytorch_output = torch.load('test2.pt')

print(torch.max(abs(trt_output - pytorch_output)))

```

> tensor(5.1458, device='cuda:0')

**Comment by lantudou** [comment]
By the way, I don't understand what is your said about "manually convert the coco model to verify it." You means using tensorrt layer API directly to build the engine file?

**Comment by lantudou** [comment]
I don't think the input size will cause this issue because all files I used is your code and the exp file I used is given above. maybe I can send my pth weight file to you and could you help me to check the output difference using tensorrt 7.2 or above version?

**Comment by lantudou** [comment]
Hey, I use the trt.py to test the torch2trt output :
After this line
https://github.com/Megvii-BaseDetection/YOLOX/blob/3c07916abbaa05eea0295cd48c26623f05acb1ac/tools/trt.py#L57

I added

y = model(x)
y_trt = model_trt(x)
print(torch.max(torch.abs(y-y_trt)))

The result shows the difference is only 0.01. so maybe there is a bug in this line to obtain the wrong result?

https://github.com/Megvii-BaseDetection/YOLOX/blob/3c07916abbaa05eea0295cd48c26623f05acb1ac/tools/demo.py#L155

**Comment by lantudou** [comment]
@ruinmessi @steinmann @xxr3376 @nihui 
Now I can make sure that is your code bug!

When I tried to use the demo_postprocess function:

```
from yolox.utils import demo_postprocess
outputs = demo_postprocess(outputs.cpu(),(640,640))
```

 to replace the work of decoder in demo.py:
https://github.com/Megvii-BaseDetection/YOLOX/blob/3c07916abbaa05eea0295cd48c26623f05acb1ac/tools/demo.py#L155



, I got the correct answer which is like the tensorrt correct output!:
![HZ05A0151W5022](https://user-images.githubusercontent.com/34973475/130589319-d9f79291-d372-4004-89bf-fc09f7c1cbbd.jpg)

**Comment by ruinmessi** [comment]
See #342

**Comment by lantudou** [comment]
So what? your demo.py will got the wrong result for own trained model in torch2trt and please fix it because of the demo_postprocess function working in cpu.

**Comment by lantudou** [comment]
@ruinmessi 
the torch2trt model can not initial the "self.hw" like pytorch, that is the reason for the wrong answer

**Comment by Taikangsheng** [comment]
> @ruinmessi
> the torch2trt model can not initial the "self.hw" like pytorch, that is the reason for the wrong answer

hi， i have the same question, how do you solve this?
