### ISSUE TITLE
How was the speed in the benchmark tables calculated?

### ISSUE THREAD

**Issue by mikel-brostrom** [Megvii-BaseDetection/YOLOX#581]
Could you clarify how you obtained the values under the `Speed V100 (ms)` column here: https://github.com/Megvii-BaseDetection/YOLOX#standard-models?

Does it take into consideration image preprocessing, postprocessing and NMS? Are you using F16 precision?
What was the chosen batch size?

It would be nice if you could add those details under the table.

Thank you for your time!

**Comment by violet2422** [comment]
+1
