### ISSUE TITLE
Cannot download the weight 

### ISSUE THREAD

**Issue by chenyd0763** [Megvii-BaseDetection/YOLOX#59]

**Comment by chenyd0763** [comment]
When I click the download button, it just shows "can't reach to te site"

**Comment by YanChenkai** [comment]
onedrive is not accessible in some place.（狗头保命）

maybe you should try something like a proxy service

**Comment by ruinmessi** [comment]
Hi, we have noticed this issue and are trying to give a better alternative.

**Comment by yonomitt** [comment]
If you have a VPN provider with servers in Hong Kong, you can use those to download the weights.
