### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'YOLOXHead' object has no attribute 'hw'

### ISSUE THREAD

**Issue by anonymoussss** [Megvii-BaseDetection/YOLOX#598]
Hi, 
I have a code problem in tools/demo.py,  I want to know the meaning of lines 117 and 118 ?  In fact, when I commented out these two lines of the code, there was a running error  "torch.nn.modules.module.ModuleAttributeError: 'YOLOXHead' object has no attribute 'hw'"，I want to know the role of the forward calculation of "self.model(x)". 

Thanks for anyone's answer.

Puzzled codes in tools/demo.py as follows:

111       if trt_file is not None:
112           from torch2trt import TRTModule
113
114           model_trt = TRTModule()
115           model_trt.load_state_dict(torch.load(trt_file))
116
117           x = torch.ones(1, 3, exp.test_size[0], exp.test_size[1]).cuda()
118           self.model(x)
119           self.model = model_trt

**Comment by ruinmessi** [comment]
See #342
