### ISSUE TITLE
trainning AP is 0.0 after 10 epochs

### ISSUE THREAD

**Issue by deep-practice** [Megvii-BaseDetection/YOLOX#60]
2021-07-21 17:32:55.097 | INFO     | yolox.core.trainer:after_iter:245 - epoch: 10/300, iter: 970/973, mem: 8646Mb, iter_time: 1.567s, data_time: 0.027s, total_loss: 3.7, iou_loss: 1.9, l1_loss: 0.0, conf_loss: 1.2, cls_loss: 0.7, lr: 9.993e-03, size: 512, ETA: 4 days, 23:01:45
2021-07-21 17:32:59.200 | INFO     | yolox.core.trainer:save_ckpt:307 - Save weights to ./YOLOX_outputs/yolox_voc_s
2021-07-21 17:32:59.893 | INFO     | yolox.core.trainer:after_train:184 - Training of experiment is done and the best AP is 0.00

**Comment by Mindisblown** [comment]
I meet the same error, but  I found a problem when I checked the data loading.

![2021-07-22 11-00-18 的屏幕截图](https://user-images.githubusercontent.com/34301002/126584570-393aec91-a09a-47a8-bcd7-33c1e889d201.png)

Left: correct labels Right: paddle labels

In `data_augmrnt.py` TrainTransform `return paddle_labels`, I'm not sure  if it is correct !

**Comment by ruinmessi** [comment]
Seems your evaluation is not correctly executed.  For VOC, if your evaluation is running well, you will get the following outputs even with zero APs:
2021-07-20 22:19:55 | INFO     | yolox.evaluators.voc_evaluator:142 - Evaluate in main process...                                                                     [9413/63738]
Writing aeroplane VOC results file                                                                                                                                                
Writing bicycle VOC results file                                                                                                                                                  
Writing bird VOC results file                                                                                                                                                     
Writing boat VOC results file                                                                                                                                                     
Writing bottle VOC results file                                                                                                                                                   
Writing bus VOC results file                                                                                                                                                      
Writing car VOC results file                                                                                                                                                      
Writing cat VOC results file                                                                                                                                                      
Writing chair VOC results file                                                                                                                                                    
Writing cow VOC results file                                                                                                                                                      
Writing diningtable VOC results file                                                                                                                                              
Writing dog VOC results file                                                                                                                                                      
Writing horse VOC results file                                                                                                                                                    
Writing motorbike VOC results file                                                                                                                                                
Writing person VOC results file                                                                                                                                                   
Writing pottedplant VOC results file                                                                                                                                              
Writing sheep VOC results file                                                                                                                                                    
Writing sofa VOC results file                                                                                                                                                     
Writing train VOC results file                                                                                                                                                    
Writing tvmonitor VOC results file                                                                                                                                                
Eval IoU : 0.50                                                                                                                                                                   
AP for aeroplane = 0.8896                                                                                                                                                         
AP for bicycle = 0.8918                                                                                                                                                           
AP for bird = 0.8364                                                                                                                                                              
AP for boat = 0.7808                                                                                                                                                              
AP for bottle = 0.7451                                                                                                                                                            AP for bus = 0.8844                                                                                                                                                               
AP for car = 0.8965                                                                                                                                                               AP for cat = 0.8728                                                                                                                                                               
AP for chair = 0.7193                                                                                                                                                             AP for cow = 0.8860                                                                                                                                                               
AP for diningtable = 0.7891                                                                                                                                                       AP for dog = 0.8668                                                                                                                                                               
AP for horse = 0.9037                                                                                                                                                             AP for motorbike = 0.8927                                                                                                                                                         
AP for person = 0.8703                                                                                                                                                            AP for pottedplant = 0.6309                                                                                                                                                       
AP for sheep = 0.8535                                                                                                                                                             AP for sofa = 0.8287                                                                                                                                                              
AP for train = 0.8674                                                                                                                                                             AP for tvmonitor = 0.8397                                                                                                                                                         
Mean AP = 0.8373
......

**Comment by deep-practice** [comment]
l1_loss is always 0,is it normal?

**Comment by xuezu29** [comment]
my l1_loss is also 0 , normal?

**Comment by TerryYiDa** [comment]
me too?

**Comment by ruinmessi** [comment]
Yes, we only adopt l1 loss in the last 15 epoch when mosaic and mixup are closed

**Comment by maichm** [comment]
me too?

**Comment by xuezu29** [comment]
> Yes, we only adopt l1 loss in the last 15 epoch when mosaic and mixup are closed

3thx a lot.

**Comment by deep-practice** [comment]
@ruinmessi  Why the eval process not print the outputs?

2021-07-22 17:13:19.695 | INFO     | yolox.core.trainer:save_ckpt:307 - Save weights to ./YOLOX_outputs/yolox_voc_s
2021-07-22 17:14:35.553 | INFO     | yolox.evaluators.voc_evaluator:evaluate_prediction:142 - Evaluate in main process...
2021-07-22 17:16:39.495 | INFO     | yolox.core.trainer:evaluate_and_save_model:298 - 
Average forward time: 2.04 ms, Average NMS time: 1.29 ms, Average inference time: 3.33 ms

2021-07-22 17:16:39.497 | INFO     | yolox.core.trainer:save_ckpt:307 - Save weights to ./YOLOX_outputs/yolox_voc_s
2021-07-22 17:16:39.710 | INFO     | yolox.core.trainer:before_epoch:188 - ---> start train epoch11

**Comment by DataXujing** [comment]
我的`l1_loss`也一直是0！！！！

**Comment by Joker316701882** [comment]
@DataXujing L1_loss只有最后15个epochs才会打开
