### ISSUE TITLE
Please, update your android example

### ISSUE THREAD

**Issue by RTae** [Megvii-BaseDetection/YOLOX#602]
Hi, I test your ncnn android example with my custom model with legacy weight and it's working fine. Now I train model with new weight and convert to ncnn for deploy on android . The result is app always force quit from app.

**Comment by RTae** [comment]
Hey, @FateScript I upload my android project for you, I think it may help you. (link)[https://github.com/RTae/YOLOX-android]

**Comment by FateScript** [comment]
> Hey, @FateScript I upload my android project for you, I think it may help you. [link](https://github.com/RTae/YOLOX-android)

Many thx~ I will update later.

**Comment by RTae** [comment]
@FateScript I found the solution, your code is working fine, but you need to update your document about how to convert from onnx to ncnn. I get this solution from this [issue](https://github.com/FeiGeChuanShu/ncnn-android-yolox/issues/8#issuecomment-907988585)
