### ISSUE TITLE
Do I need to re-generate ground truth json files for different input image size?

### ISSUE THREAD

**Issue by kail85** [Megvii-BaseDetection/YOLOX#605]
The coco format json records bounding box locations in absolute coordinates, while yolov5 txt file records them in relative coordinates. By examining coco.py, seems the codes re-scale the absolute coordinates to fit the given image size. 

For example, let's say in the json file the top left corner of a bounding box is (x0, y0) for a 100 x 100 image. By specifying the input image size as 500 x 500, I guess the original coordinate will become (x0, y0) * 5? Just want to double check my understanding, thanks.

**Comment by Joker316701882** [comment]
@kail85 Of course.
