### ISSUE TITLE
运行Demo出错

### ISSUE THREAD

**Issue by liuwei3612** [Megvii-BaseDetection/YOLOX#61]
(base) lw@lw-System:~/work/YOLOX$ python3 tools/demo.py image -n yolox-s -c path/to/yolox_s.pth.tar --path assets/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result
2021-07-22 12:13:29 | INFO     | __main__:219 - Args: Namespace(camid=0, ckpt='path/to/yolox_s.pth.tar', conf=0.3, demo='image', exp_file=None, experiment_name='yolox_s', fp16=False, fuse=False, name='yolox-s', nms=0.65, path='assets/dog.jpg', save_result=True, trt=False, tsize=640)
/home/lw/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-07-22 12:13:29 | INFO     | __main__:229 - Model Summary: Params: 8.97M, Gflops: 26.81

**Comment by YanChenkai** [comment]
请把`-c path/to/yolox_s.pth.tar`换成自己电脑权重文件的所在地...

**Comment by liuwei3612** [comment]
![图片](https://user-images.githubusercontent.com/12774651/126594166-950f11f1-ec58-45c7-a65c-7a0b785e9605.png)

**Comment by liuwei3612** [comment]
> 请把`-c path/to/yolox_s.pth.tar`换成自己电脑权重文件的所在地...

![图片](https://user-images.githubusercontent.com/12774651/126594229-6897e81f-9b89-4a9b-8259-dcdbf25ec240.png)
我改成相应的路径后，还是报这样的错误

**Comment by YanChenkai** [comment]
请大佬来解决吧，剩下的我不懂

如果正常的话，下一步应该是load模型参数，终端输出应该是
`| INFO     | __main__:240 - loading checkpoint`

所以可以调试一下，查看一下demo.py中第229行到第240行之间哪里有问题？

还有我是在NVIDIA的docker里运行的，没有问题，如果实在没法解决要不要试一试？

**Comment by liuwei3612** [comment]
> @liuwei3612 请大佬来解决吧，剩下的我不懂
> 
> 如果正常的话，下一步应该是load模型参数，终端输出应该是
> `| INFO | __main__:240 - loading checkpoint`
> 
> 所以可以调试一下，查看一下demo.py中第229行到第240行之间哪里有问题？
> 
> 还有我是在NVIDIA的docker里运行的，没有问题，如果实在没法解决要不要试一试？

谢谢

**Comment by Joker316701882** [comment]
@liuwei3612 Hi, does your machine have GPU?

**Comment by liuwei3612** [comment]
> @liuwei3612 Hi, does your machine have GPU?

有的，只有一个

**Comment by Joker316701882** [comment]
Hi @liuwei3612 and all, we have updated demo.py in #77.
Many bugs are fixed. Now you can use --device cpu/gpu when running demo.py to specify the device (default CPU).

**Comment by liuwei3612** [comment]
> Hi @liuwei3612 and all, we have updated demo.py. Many bugs are fixed. Please pull our latest branch!!
> Now you can use --device cpu/gpu when running demo.py to specify the device (default CPU).

谢谢你的回复，目前同步到最新baranch，默认的device是CPU，可以运行成功。但改成成GPU，就出错了，错误信息如下：
![图片](https://user-images.githubusercontent.com/12774651/126626273-101973b7-992b-4c5e-a434-b36cad269baf.png)

目前我这边CUDA Version 10.1.243
工程运行的pytorch是什么版本啊，需要匹配的CUDA的版本是多少？

**Comment by Joker316701882** [comment]
pytorch==1.9.0, but I think as long as >=1.7.0, it should be fine.
cuda==10.2
