### ISSUE TITLE
 Model evaluation？

### ISSUE THREAD

**Issue by allenchertk** [Megvii-BaseDetection/YOLOX#612]
想请问一下模型评估只有mAP50吗？
如果要评估出IOU或GIOU
输入什么代码？

Would you like to ask if the model evaluation is only mAP50?
If you want to evaluate IOU or GIOU
What code to enter?

**Comment by Joker316701882** [comment]
评估出IoU和GIoU是什么意思？

**Comment by allenchertk** [comment]
[https://zhuanlan.zhihu.com/p/57992040](https://zhuanlan.zhihu.com/p/57992040)
[https://blog.csdn.net/qq_33869371/article/details/104753299](https://blog.csdn.net/qq_33869371/article/details/104753299)

@Joker316701882  您好 我想跟之前我训练好的模型进行比较
之前我训练好的模型(Yolov3)有GIOU值评估，我想知道我训练好的模型有没有Giou值可以参考

**Comment by Joker316701882** [comment]
@allenchertk 这是个loss，不是评估指标
