### ISSUE TITLE
what the meaning of center_radius=2.5 in yolo_head 

### ISSUE THREAD

**Issue by PyNancy** [Megvii-BaseDetection/YOLOX#618]
https://github.com/Megvii-BaseDetection/YOLOX/blob/d17bef824966bf3f0209fd58c70d07f93265c9c7/yolox/models/yolo_head.py#L581

**Comment by Joker316701882** [comment]
@PyNancy Center sampling radius. The anchor points out of these regions won't be assigned as positive.

**Comment by zhangjinsong3** [comment]
> @PyNancy Center sampling radius. The anchor points out of these regions won't be assigned as positive.

why not `center_radius=1.5`  as the paper said  `We simply assigns the center 3×3 area as positives, also named “center sampling” in FCOS`
