### ISSUE TITLE
comments on configs

### ISSUE THREAD

**Issue by dongdongyee** [Megvii-BaseDetection/YOLOX#62]
Hi，

thank you for sharing such a wonderful work. I would appreciate it if you could add some comments on some params in config files / hyperparams in model structure. Those are really helpful for us beginners.

Best

**Comment by FateScript** [comment]
Thanks for advice, we will update it later

**Comment by awandzel** [comment]
+1 for this

**Comment by FateScript** [comment]
Solved. I will close this issue.
