### ISSUE TITLE
关于论文中的3*3区域为正样本

### ISSUE THREAD

**Issue by kingrt666666** [Megvii-BaseDetection/YOLOX#621]
论文中提到assign the center 3*3 area as positives，在代码中实现的时候是落在中心点半径为2.5的区域内为正样本，这两者是不是存在冲突呢？

**Comment by Joker316701882** [comment]
@kingrt666666 3x3是fcos风格的multi positive，仅仅是为了说明一个目标多个正样本，它只是一个中间试验。最终版本的multi positive和label assign是整体(SimOTA)。
