### ISSUE TITLE
self.multiscale_range is missing in the source code

### ISSUE THREAD

**Issue by gorkemkrdmn** [Megvii-BaseDetection/YOLOX#628]
In the [Manipulating Your Training Image Size](https://github.com/Megvii-BaseDetection/YOLOX/blob/69f1173a569f1e0cc41025146a32b5d5fa06dd26/docs/manipulate_training_image_size.md) file, it is mentioned that multiscale_range can be set to modify the input size. But there is no multiscale_range in the source code. Is this documentation outdated? If so, what happened to the multiscale range?

**Comment by Joker316701882** [comment]
@gorkemkrdmn Please check
https://github.com/Megvii-BaseDetection/YOLOX/blob/69f1173a569f1e0cc41025146a32b5d5fa06dd26/yolox/exp/yolox_base.py#L31

If you want to change this default value, you can override it in your own exp file.
