### ISSUE TITLE
关于加快训练速度2x的一些问题

### ISSUE THREAD

**Issue by Joker-co** [Megvii-BaseDetection/YOLOX#629]
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/docs/updates_note.md
您好，我阅读了关于加快训练速度的更新note，貌似都是关于预处理代码的优化，但预处理时间貌似在整个迭代过程中的占比较小，对这部分的优化能够提高两倍的训练速度吗？哪部分是速度提升最快的优化呢？

**Comment by Joker316701882** [comment]
@Joker-co 在预处理是bottlenect的设备上，比如v100，可以实现2倍左右的加速，其他设备上的加速会小于2
