### ISSUE TITLE
the "from yolox.exp import get_exp" yield error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hzlijianjun** [Megvii-BaseDetection/YOLOX#642]
On Jetson Nano 4g with 6g swap
Install and run torch2trt demo successfully followed the guide
Install YOLOX successfully followed the guide

then, I try a convert but failed as following:
$ python tools/trt.py -n yolox-s -c model/yolox_s.pth
I checked found follwing line in the tools/trt.py
from yolox.exp import get_exp
yielded the error:
Segmentation fault (core dumped)

Thanks for help!

**Comment by hzlijianjun** [comment]
I solved with:
export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

**Comment by mehul-rigyn** [comment]
@hzlijianjun How much FPS are you getting for yolox on Jetson Nano ?
