### ISSUE TITLE
Is it bug in augmentation?

### ISSUE THREAD

**Issue by GodOfSmallThings** [Megvii-BaseDetection/YOLOX#647]
![image](https://user-images.githubusercontent.com/20166060/132034519-e0ee2274-d9a7-4dd5-80c2-19d9feb1508e.png)
![image](https://user-images.githubusercontent.com/20166060/132034563-9a2f5ca6-6e7a-4843-a091-8b98d6e08b76.png)
![image](https://user-images.githubusercontent.com/20166060/132034639-24a8e1dc-eeb9-4450-a593-1c1a4f08f30e.png)
![image](https://user-images.githubusercontent.com/20166060/132034739-8f9aa1f4-1198-48a3-b1d0-dfd34d6f4d6b.png)

My training result with my custom dataset was weird, and I tried to see how labels are feed into the model with VOC dataset.
However some of them were fine, but it seems some of labels were missing. I got this image at the end of the augmentation code. 

My question is
1. Is this a bug or intended feature? I also tried to run without mixup, but the result was same.
2. Some of boxes don't look like its fitting to the object. Are enlarged boxes are some type of label augmentation?

**Comment by ruinmessi** [comment]
Have you used `--cache`? Delete your cache or remove `--cache` can fix this issue

**Comment by GodOfSmallThings** [comment]
@ruinmessi  Thank you, It was due to my mistake. I solved the problem.
