### ISSUE TITLE
IoU-aware branch

### ISSUE THREAD

**Issue by van-hub** [Megvii-BaseDetection/YOLOX#651]
您好，请问IoU-aware branch指的是在推理阶段加权分类置信度和iou预测值得到anchor最终的分数吗，代码具体在哪个文件有体现，想学习一下代码。谢谢

**Comment by Joker316701882** [comment]
@van-hub The IoU target is merged into the classification branch.

https://github.com/Megvii-BaseDetection/YOLOX/blob/a0cef7336316275d3f2cb2471d7d459778f7b38a/yolox/models/yolo_head.py#L363-L365
