### ISSUE TITLE
trt error: 'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by zhennronnnhui** [Megvii-BaseDetection/YOLOX#653]
cuda:11.1
tensorrt:7.2.3.4

When I did: 
python3 deepsort_yolox/YOLOX/tools/trt.py -n yolox-m -c deepsort_yolox/YOLOX/yolox_m.pth

----------------------------------------------------------------------
File "deepsort_yolox/YOLOX/tools/trt.py", line 77, in <module>
    main()
    └ <function main at 0x7ff9b1930940>

  File "deepsort_yolox/YOLOX/tools/trt.py", line 64, in main
    torch.save(model_trt.state_dict(), os.path.join(file_name, "model_trt.pth"))
    │     │    │         │             │  │    │    └ './YOLOX_outputs/yolox_m'
    │     │    │         │             │  │    └ <function join at 0x7ffb30776af0>
    │     │    │         │             │  └ <module 'posixpath' from '/home/ronnnhui/anaconda3/envs/yolox/lib/python3.8/posixpath.py'>
    │     │    │         │             └ <module 'os' from '/home/ronnnhui/anaconda3/envs/yolox/lib/python3.8/os.py'>
    │     │    │         └ <function Module.state_dict at 0x7ff9bce14310>
    │     │    └ TRTModule()
    │     └ <function save at 0x7ff9dd5b9ee0>
    └ <module 'torch' from '/home/ronnnhui/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/__init__.py'>

  File "/home/ronnnhui/anaconda3/envs/yolox/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1261, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
                  │    │     │            │       └ {'version': 1}
                  │    │     │            └ ''
                  │    │     └ OrderedDict()
                  │    └ TRTModule()
                  └ <function TRTModule._on_state_dict at 0x7ff9bc4fa3a0>
  File "/home/ronnnhui/anaconda3/envs/yolox/lib/python3.8/site-packages/torch2trt-0.3.0-py3.8.egg/torch2trt/torch2trt.py", line 436, in _on_state_dict
    state_dict[prefix + "engine"] = bytearray(self.engine.serialize())
    │          │                              │    └ None
    │          │                              └ TRTModule()
    │          └ ''
    └ OrderedDict()

AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by umairjavaid** [comment]
How did u solve this?
