### ISSUE TITLE
value of mosaic_pro needed to be 1.0 or returns bugs!!! 

### ISSUE THREAD

**Issue by DavidQiuChao** [Megvii-BaseDetection/YOLOX#658]
When using the "exps/example/custom/nano.py" as the configuration file and sets the mosaic_pro=0.5 will get a bug of un-matched shapes.
![image](https://user-images.githubusercontent.com/15049009/132294783-563a652a-a9d7-4292-8c1e-351b37807d5c.png)
The code is the latest version!!!

**Comment by Joker316701882** [comment]
@DavidQiuChao For now, you can modify this line
https://github.com/Megvii-BaseDetection/YOLOX/blob/a0cef7336316275d3f2cb2471d7d459778f7b38a/yolox/data/datasets/mosaicdetection.py#L159
into

`return img, label, img_info, idx `

**Comment by Joker316701882** [comment]
Fixed. #660

**Comment by DavidQiuChao** [comment]
> @DavidQiuChao For now, you can modify this line
> https://github.com/Megvii-BaseDetection/YOLOX/blob/a0cef7336316275d3f2cb2471d7d459778f7b38a/yolox/data/datasets/mosaicdetection.py#L159
> 
> 
> into
> `return img, label, img_info, idx `

Many thanks
