### ISSUE TITLE
When training for 100 - 200 epoch, the following errors are reported:

### ISSUE THREAD

**Issue by ZhenxinYUAN** [Megvii-BaseDetection/YOLOX#659]
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102:operator():block:[117,0,0], thread:[32,0,0] Assertion 'input_val' >= zero && input_val <= one' failed
 File "/var/software/code/YOLOX-main/yolox/models/yolo_head.py", line 327, in get_losses
    imgs,
    └ <unprintable Tensor object>

  File "/home/sprite/anaconda3/envs/yolox/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function YOLOXHead.get_assignments at 0x7fe5d4259830>

  File "/var/software/code/YOLOX-main/yolox/models/yolo_head.py", line 510, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ <unprintable Tensor object>
        │    │                  │     │               │           └ 8
        │    │                  │     │               └ <unprintable Tensor object>
        │    │                  │     └ <unprintable Tensor object>
        │    │                  └ <unprintable Tensor object>
        │    └ <function YOLOXHead.dynamic_k_matching at 0x7fe5d42599e0>
        └ YOLOXHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(128, 128, kernel_size=...

  File "/var/software/code/YOLOX-main/yolox/models/yolo_head.py", line 623, in dynamic_k_matching
    cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False
    │    │          │          └ 0
    │    │          └ <unprintable Tensor object>
    │    └ 0
    └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered

During handling of the above exception, another exception occurred:

Why is this problem？

**Comment by zcy5417** [comment]
这个bug你解决了吗?我用自己数据,cost.shape有时会出现[3,0]这种

**Comment by ZhenxinYUAN** [comment]
@zcy5417 May be due to the number of categories, you can try to set  num_classes +1.

**Comment by ZhenxinYUAN** [comment]
> 这个bug你解决了吗?我用自己数据,cost.shape有时会出现[3,0]这种

Have you solved this problem?

**Comment by upsx** [comment]
> 

你好，请问解决了没有？我一直都有这种问题，没有解决。
