### ISSUE TITLE
mini-coco128 数据集 建议增加国内网盘

### ISSUE THREAD

**Issue by monkeycc** [Megvii-BaseDetection/YOLOX#663]
https://yolox.readthedocs.io/en/latest/train_custom_data.html

For example:

If you download the mini-coco128 and unzip it to the datasets, you can direct run the following training code.

mini-coco128 数据集 应该放  国内网盘
google网盘不能访问！

**Comment by Keiku** [comment]
Is this link accessible? https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip

**Comment by hopesala** [comment]
I download it recently, upload it to baidu netdisk, wish it is helpful
链接: https://pan.baidu.com/s/1fcaBAUgJxhKYP774KJwjqQ  密码: 9hst

**Comment by Keiku** [comment]
@monkeycc I think it has been resolved, so please close it.

**Comment by Shua-Kang** [comment]
> Is this link accessible? https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip

coco128 from Yolov5 is yolo format but coco format is needed. Baidu netdisk version from @hopesala is right (coco format).
