### ISSUE TITLE
EVAL: AP is error

### ISSUE THREAD

**Issue by LJ-lijian** [Megvii-BaseDetection/YOLOX#670]
python tools/eval.py -n  yolox-s -c yolox_s.pth -b 1 -d 1 --conf 0.001 --fp16 --fuse

Average forward time: 9.12 ms, Average NMS time: 0.91 ms, Average inference time: 10.03 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.110
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.164
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.116
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.045
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.126
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.168
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.117
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.170
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.176
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.061
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.195
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.269

**Comment by Joker316701882** [comment]
@LJ-lijian We have updated our preprocessing method as well as the pretrained models. Please make sure:
1. you have pull the latest code
2. you have download the latest yolox_s.pth
Otherwise, the preprocessing method doesn't match between the code and the model.

**Comment by LJ-lijian** [comment]
Thank you. It's OK after I change the preprocessing method, and I get 40.5 AP of yolox-s.
