### ISSUE TITLE
how to train with cpu?

### ISSUE THREAD

**Issue by futureflsl** [Megvii-BaseDetection/YOLOX#673]
I try to set -d -1 or set -d 0,it always use my display drvier.

**Comment by Joker316701882** [comment]
@futureflsl Not supported yet.

**Comment by futureflsl** [comment]
I hope this project can supprt train with cpu.in some condition,some one need.

**Comment by nTnZone** [comment]
> @futureflsl Not supported yet.

sometimes I need cpu mode to debug, hope it support cpu mode in the future

**Comment by YongboLiang** [comment]
> @futureflsl Not supported yet.

Thanks for your job, and I also hope it support cpu mode in the future
