### ISSUE TITLE
每次迭代最大的labels数目是多少

### ISSUE THREAD

**Issue by Donaghys** [Megvii-BaseDetection/YOLOX#678]
每次迭代labels的最大数目是多少？这个参数设置在哪里呢？

**Comment by Joker316701882** [comment]
@Donaghys 120

https://github.com/Megvii-BaseDetection/YOLOX/blob/69f1173a569f1e0cc41025146a32b5d5fa06dd26/yolox/exp/yolox_base.py#L127

你需要在exp里override这个MosaicDataloader并修改这个数字。
