### ISSUE TITLE
各位大佬！如何将检测结果的包围框的线条变粗？图片太大看不清。如何修改代码？

### ISSUE THREAD

**Issue by zhangmingjiang1114** [Megvii-BaseDetection/YOLOX#683]
我将yolox\utils\visualize.py的第30行cv2.rectangle(img, (x0, y0), (x1, y1), color,2) 中的最后的2改大为20后还是没反应。请问怎么修改？谢谢

**Comment by ChinaRush** [comment]
改大下面一行代码中的thickness值 
`cv2.putText(img, text, (x0, y0 + txt_size[1]), font, 0.4, txt_color, thickness=1)`

**Comment by zhangmingjiang1114** [comment]
> 改大下面一行代码中的thickness值
> `cv2.putText(img, text, (x0, y0 + txt_size[1]), font, 0.4, txt_color, thickness=1)`

谢谢！
