### ISSUE TITLE
Changing total loss when resume training

### ISSUE THREAD

**Issue by hoangkhoiLE** [Megvii-BaseDetection/YOLOX#684]
Hello,

I try to resume my training at epoch 408. This is my old result with total loss 3.0
![image](https://user-images.githubusercontent.com/57557628/132961675-03fc55a6-a7cf-4ab6-b5db-73711356a6cb.png)
But when i resume the total augment at 3.6
![image](https://user-images.githubusercontent.com/57557628/132961703-872fc4c6-5d90-4625-b04d-e896c979abf8.png)

This is the code that i used
!python tools/train.py -f yolox_s.py -d 1 -b 64 --fp16 -o -c  last_epoch_ckpt.pth --start_epoch 408 --resume

Please help me to understand this ! 

Best regard

**Comment by Joker316701882** [comment]
@haolongzhangm When training, there are two models in YOLOX: the original model and the EMA model. We only save the EMA model when checkpointing. So when resuming, the ema model will be used as the initialization of the original model, leading to the change of the total loss. This is not a bug and will not bring too much difference in our experiments, please let it finish the training and check the final result.

**Comment by hoangkhoiLE** [comment]
@Joker316701882 Thank you for your help !
