### ISSUE TITLE
What is good value of total loss or  another loss ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [Megvii-BaseDetection/YOLOX#685]
Hello, 

I want to know some of recommendation for value in loss to stop training. For example, in your case with dataset what is the loss final of best ckpt. Thank you !

Best regard

**Comment by Joker316701882** [comment]
@hoangkhoiLE For yolox-l, it should be 2 or 3 on COCO. For yolox-nano, it should be 6~7.

**Comment by hoangkhoiLE** [comment]
@Joker316701882 Thank you for your help
