### ISSUE TITLE
如何使用YOLOX-m模型？作者帮看看我下面的方式正确吗？谢谢

### ISSUE THREAD

**Issue by Wanghe1997** [Megvii-BaseDetection/YOLOX#686]
你好，我想请问问一下，如果模型想选用YOLOX-m，是不是只需要把yolox_voc_s.py里的depth和width参数改成和yolox_m.py里的一样就行了呢？然后训练时指令仍然选择-f exps/example/yolox_voc/yolox_voc_s.py，是不是这样呢？谢谢
![1](https://user-images.githubusercontent.com/45507837/132971595-1d0764e8-59fe-4faf-92d5-12458cd79a8f.png)
![2](https://user-images.githubusercontent.com/45507837/132971611-bed27d4a-98af-42e4-8312-b9290cdd63af.jpg)

**Comment by we0091234** [comment]
试了吗，这样可以吗

**Comment by Wanghe1997** [comment]
> 试了吗，这样可以吗

可以

**Comment by FateScript** [comment]
Feel free to reopen.
