### ISSUE TITLE
Training with cache affect the total loss ? 

### ISSUE THREAD

**Issue by hoangkhoiLE** [Megvii-BaseDetection/YOLOX#703]
Hello,

I tried to resume training with cache but if seems like my total loss with cache is not compatible with result before (before I had trained with cache too).  The result with no cache is very compatible.
Stop training
![image](https://user-images.githubusercontent.com/57557628/133402415-fa25db3e-d911-4cb0-b8f0-06a084bd2e70.png)
Resume with cache
![image](https://user-images.githubusercontent.com/57557628/133402568-404cb7ff-9d0d-4214-92f2-f7c2e7fa7281.png)
Resume with no cache
![image](https://user-images.githubusercontent.com/57557628/133402670-c8b4576e-abad-4ade-acc1-cc5ed0936c68.png)

Please help me in this case !

Best regard !

**Comment by hoangkhoiLE** [comment]
I have resumed the training with this command:
python tools/train.py -f yolox_s.py -d 1 -b 64 --fp16 -o -c  last_epoch_ckpt.pth --start_epoch 332 --resume

**Comment by ruinmessi** [comment]
The cache may be inconsistent with your current data. So you have to delete the cache file in your dataset dir and try again.

**Comment by hoangkhoiLE** [comment]
@ruinmessi It's possible. Thank for your help!
