### ISSUE TITLE
请问同样的数据集为什么训练的Loss比YOLOV4高，并且预测的置信度也就相应偏低了

### ISSUE THREAD

**Issue by 244668226** [Megvii-BaseDetection/YOLOX#705]
如题，我用YOLOV4的最后Loss大概0.3, 但是用YOLOX的话很快下降到2.5左右就基本保持了，最后预测同样的一批图片V4的置信度在95%左右，但是X的置信度才70-80%，导致我不太敢用YOLOX，还是用的V4，请问这是什么原因，可以解决吗

**Comment by Joker316701882** [comment]
@244668226 Loss不重要，看mAP。我们特意对reg loss乘以了5去帮助回归分支收敛，所以最后loss看起来比较高。你说的分数低的问题应该是没训好。

**Comment by 244668226** [comment]
> @244668226 Loss不重要，�看mAP。我们特意对reg loss乘以了5去帮助回归分支收敛，所以最后loss看起来比较高。你说的分数低的问题应该是没训好。

用mAP评估谢谢您的指导， 但是我还是有置信度的疑问，现在我的conf的loss比之前的V4总loss高所以导致最后的置信度比较低听起来也挺合理的，您说是训练的问题， 首先我数据没变，其次学习率调整多次了也没效果，那么您觉得是哪里出现了问题导致的呢

**Comment by Joker316701882** [comment]
@244668226 不好说，如果非常在意分数的话，可以对输出的分数开个平方根，可以把整体值放大。数值相对于tp、fp的顺序来说其实也没那么重要

**Comment by 244668226** [comment]
好的，谢谢
