### ISSUE TITLE
GIOU计算问题

### ISSUE THREAD

**Issue by liu-b-s** [Megvii-BaseDetection/YOLOX#712]
计算GIOU时，是不是写错了？giou = iou - (area_c - area_i) / area_c.clamp(1e-16)，应该减并集面积吧。。。是故意减的交面积吗？

**Comment by Joker316701882** [comment]
@liu-b-s You are right! But GIoU is not used in our current experiments. So the results reported in our paper and this repo should be fine. We will fix it soon!
