### ISSUE TITLE
如何计算YOLOX网络架构各个部分的推断时间？

### ISSUE THREAD

**Issue by ahong007007** [Megvii-BaseDetection/YOLOX#715]
例如backbone, neck, head三个部分的推断时间？ 我想在不同的dataset使用不同的头部，所以想评估一下各个part的效率。

谢谢。

**Comment by Joker316701882** [comment]
@ahong007007 Check the forward part and put your time logger here.

https://github.com/Megvii-BaseDetection/YOLOX/blob/426523d3b528bb7be5059672e46f39acc3e3745c/yolox/models/yolox.py#L28-L48

**Comment by ahong007007** [comment]
Thank you very much!
