### ISSUE TITLE
long time to training

### ISSUE THREAD

**Issue by Hiwyl** [Megvii-BaseDetection/YOLOX#72]
![image](https://user-images.githubusercontent.com/44716550/126612982-ee55c125-5d40-45d5-b896-56dea8e56f55.png)
Hi,this is a good project! 
I just have 20000 imgs  with yolox-tiny to train,why need 20days??? I fuesd

**Comment by ruinmessi** [comment]
Your data time is toooooo long.   Please check your I/O or pre-process

**Comment by Hiwyl** [comment]
TKS! beacuse multiprocess  error
