### ISSUE TITLE
Training error：AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by hccv** [Megvii-BaseDetection/YOLOX#73]
In training, when epoch=1, it's successed;
when epoch=2, it's error!
File "/YOLOX-main/yolox/core/trainer.py", line 93, in train_one_iter
    inps = inps.to(self.data_type)
           │       │    └ torch.float16
           │       └ <yolox.core.trainer.Trainer object at 0x7f48fdb85630>
           └ None

AttributeError: 'NoneType' object has no attribute 'to'

**Comment by ruinmessi** [comment]
Make sure you have pulled our lastes updates. See #22 for more details. If the error happened again, plz let me know.

**Comment by hccv** [comment]
> Make sure you have pulled our lastes updates. See #22 for more details. If the error happened again, plz let me know.
