### ISSUE TITLE
Why add L1 loss after close mosaic?

### ISSUE THREAD

**Issue by captainfffsama** [Megvii-BaseDetection/YOLOX#74]
Thanks for you excellent work ...
I notice that yolox add L1 loss after shut down mosaic,but It seems that no mention in paper...
How to explain this trick?  Is there any theoretical basis for this? Or  it just experience?

**Comment by ruinmessi** [comment]
An experienced trick for only 0.1~0.2 AP actually, so we didn't mention it.
