### ISSUE TITLE
YOLOX-OpenVINO in C++ Windows, none objects

### ISSUE THREAD

**Issue by zhongwenkun886** [Megvii-BaseDetection/YOLOX#740]
when I run the YOLOX-OpenVINO in C++(win10, openvino_2021.4.689), It outputs none object.
I tryed the model yolox_s and yolox_m.

**Comment by toddlt** [comment]
> when I run the YOLOX-OpenVINO in C++(win10, openvino_2021.4.689), It outputs none object.
> I tryed the model yolox_s and yolox_m.

If you use yolo_s and yolo_m, you should modify INPUT_W and INPUT_H from 416 to 608 in yolox_openvino.cpp

**Comment by zhongwenkun886** [comment]
OK ，thanks
