### ISSUE TITLE
warning occurs when train model with pretrained .pt

### ISSUE THREAD

**Issue by nTnZone** [Megvii-BaseDetection/YOLOX#747]
I use customed data and yolox_l. Following the guide you provide I download yolox_l.pt and I want to train my data with your pretrained ckpt file. And warnings happen as following:
 WARNING  | yolox.utils.checkpoint:16 - backbone.backbone.dark2.0.dconv.conv.weight is not in the ckpt. Please double check and see if this is desired.
| WARNING  | yolox.utils.checkpoint:16 - backbone.backbone.dark2.0.dconv.conv.weight is not in the ckpt. Please double check and see if this is desired.
| WARNING  | yolox.utils.checkpoint:16 - backbone.backbone.dark2.0.dconv.bn.bias is not in the ckpt. Please double check and see if this is desired.
....
My question is " **Does this affect performance** "? If so what should I do?

**Comment by L1onKing** [comment]
Same problem here. One observation - when I train using nano pretrained model, I have only a warning regarding last layer, which is expected - my model is meant to detect one object, not 80, as pretrained model. But when I do the same training, but using tiny or small model, with respective changes in the .py configs, I have huge pile of warnings that this and that block is not in the checkpoint. Is there a place where I can download pretrained models that are in tact with current state of the code?

**Comment by L1onKing** [comment]
NVM, just figured out an issue. When I created config for tiny, I used nano example, and get_model function is clearly irrelevant for that. Sorry!
