### ISSUE TITLE
demo/TensorRT/cpp Compile Error

### ISSUE THREAD

**Issue by tensorturtle** [Megvii-BaseDetection/YOLOX#768]
I'm on Pop OS 20.04 and I followed all installation instructions on [the README](https://github.com/Megvii-BaseDetection/YOLOX/tree/52c878e3039fd68a0796c038346b347c48138f50/demo/TensorRT/cpp). I get this message during `make`:

![Screenshot from 2021-10-05 02-55-33](https://user-images.githubusercontent.com/75611662/135900466-f5e224a0-93cf-43bc-9a7c-64ff15a13696.png)

error: looser throw specifier for 'virtual void Logger::log(nvinfer1:ILogger::Severity, const char*)'

Please help

**Comment by ujsyehao** [comment]
modify it to 
`void Logger::log(Severity severity, const char* msg) noexcept`
