### ISSUE TITLE
  assert num_gpu <= get_num_devices() AssertionError运行下载的小数据集，报错

### ISSUE THREAD

**Issue by dtde** [Megvii-BaseDetection/YOLOX#785]
再云服务器上运行!python train.py -n yolox-s -d 8 -b 64 --fp16 -o --cache，报错Traceback (most recent call last):
  File "train.py", line 123, in <module>
    assert num_gpu <= get_num_devices()
AssertionError，每一步都是按照官方命令输入的，只是把数据集换了一下，不知道是什么问题，求解答！

**Comment by rahuja23** [comment]
When removing the -d flag I am getting the following error: AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
