### ISSUE TITLE
demo.py:   Reasoning part can't show the picture result, video can't, how to solve?

### ISSUE THREAD

**Issue by KangChou** [Megvii-BaseDetection/YOLOX#79]
Reasoning part can't show the picture result, video can't, how to solve?
In addition, the output video result cannot be decoded, that is, it cannot be played.
env:
ubuntu16.04
pytorch1.7
cuda11.0
cudnn8
python3.6

![image](https://user-images.githubusercontent.com/36963108/126622831-f5d23243-d735-489a-a4e1-01e0b2b6e055.png)

**Comment by Joker316701882** [comment]
@KangChou 
We have just updated the demo.py. Can you pull the latest branch and try it again?

**Comment by KangChou** [comment]
In addition, the output video result cannot be decoded, that is, it cannot be played.

**Comment by KangChou** [comment]
> @KangChou
> We have just updated the demo.py. Can you pull the latest branch and try it again?

Thank you. I'll try it now

**Comment by KangChou** [comment]
> @KangChou
> We have just updated the demo.py. Can you pull the latest branch and try it again?

Thank you. I'll try it now @Joker316701882

**Comment by KangChou** [comment]
> @KangChou
> We have just updated the demo.py. Can you pull the latest branch and try it again?

Thank you. The problem has been solved. Try to train coco tomorrow. Thank you for your generous answer. @Joker316701882

**Comment by Joker316701882** [comment]
You are welcome. This issue is closed for now. Reopen it if necessary.
