### ISSUE TITLE
Use l1_loss from scratch

### ISSUE THREAD

**Issue by shl1993** [Megvii-BaseDetection/YOLOX#806]
Why doesn't use l1_loss from scratch, but the last eta(=15) epoch?
If use l1_loss from scratch, model performance will drop?

**Comment by Joker316701882** [comment]
@shl1993 Under strong augmentation, there are many inaccurate bounding boxes. Hence strong regression loss is not necessary. But the mAP difference is around 0.1~0.2 mAP between these two settings.

**Comment by shl1993** [comment]
> @shl1993 Under strong augmentation, there are many inaccurate bounding boxes. Hence strong regression loss is not necessary. But the mAP difference is around 0.1~0.2 mAP between these two settings.

Thx!
