### ISSUE TITLE
Torch1.6不支持SiLU，请问可以支持torch1.6吗？

### ISSUE THREAD

**Issue by zhishao** [Megvii-BaseDetection/YOLOX#81]

**Comment by iamhaoyuwu** [comment]
SiLU报错位置的上方有SiLU的实现，删掉SiLU报错位置的“nn.”和括号内的“inplace=True”

**Comment by Joker316701882** [comment]
@zhishao 
Simply replace nn.SiLU() in this line:
https://github.com/Megvii-BaseDetection/YOLOX/blob/f281865af2f0cdf5ff113304f804bf430c4485ca/yolox/models/network_blocks.py#L19

with a customized SiLU() defined here:
https://github.com/Megvii-BaseDetection/YOLOX/blob/f281865af2f0cdf5ff113304f804bf430c4485ca/yolox/models/network_blocks.py#L9

**Comment by zhishao** [comment]
非常感谢！@Joker316701882@iamhaoyuwu

**Comment by zhishao** [comment]
@Joker316701882 @iamhaoyuwu 您好，我修改silu后，model_utils.py中的get_model_info函数 中
flops, params = profile(deepcopy(model), inputs=(img,), verbose=False)
这一句无法执行，请您帮助，谢谢。

**Comment by zhiqwang** [comment]
如果是训练使用 `nn.SiLU` 的话，最好还是升级到pytorch1.7+，速度会快一些应该。

**Comment by zhishao** [comment]
decode_outputs中 torch.full([*shape, 1], stride) 不执行， 版本为torch1.6。没有任何报错信息，只是forward执行到这里走不下去。

**Comment by Yaoxingtian** [comment]
> @zhishao You can replace nn.SiLU() in this line:
> 
> https://github.com/Megvii-BaseDetection/YOLOX/blob/f281865af2f0cdf5ff113304f804bf430c4485ca/yolox/models/network_blocks.py#L19
> 
> with a customized SiLU() defined here:
> 
> https://github.com/Megvii-BaseDetection/YOLOX/blob/f281865af2f0cdf5ff113304f804bf430c4485ca/yolox/models/network_blocks.py#L9

Hi, I wonder why not train the model by Class SILU directly ?
