### ISSUE TITLE
multi label training?

### ISSUE THREAD

**Issue by ahmedanis03** [Megvii-BaseDetection/YOLOX#814]
How can I use YOLOX in multi label scenario?

**Comment by FateScript** [comment]
Waht do you mean by saying `multi label`? If your dataset contains multiple classes in COCO format, just modify the anno file could train your own dataset.

**Comment by FateScript** [comment]
I think your should write your own adaptor logic. If you treat them as seprate label(which is strange in my opinion), you could train them but your loss and inference logic should change. If you first detect a box then give the box multi labels, you should write your own classification logic.

**Comment by abhigoku10** [comment]
@ahmedanis03  if i understand correctly single bounding box with multi label is the intent right ? @FateScript  to do this should we add additional head into the architecture which performs the classification like gender , age , accessories

**Comment by ahmedanis03** [comment]
@abhigoku10 Yes exactly!

**Comment by FateScript** [comment]
@abhigoku10 Yes.

I will close this issue. Feel free to reopen it.

**Comment by abhigoku10** [comment]
@FateScript  generally wider attribute dataset with is available with single box multilabels so can we train with yolox or  should we add additional head into the architecture which performs the classification like gender , age , accessories
