### ISSUE TITLE
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT

### ISSUE THREAD

**Issue by starsky68** [Megvii-BaseDetection/YOLOX#816]
训练几个epoch后出现torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT

**Comment by NarutoZhao** [comment]
我也是这个bug，使用 一个卡就可以，两个卡就会报错

**Comment by starsky68** [comment]
似乎好像是需要batch和卡数还有个什么东西，，做好匹配，有点迷，我现在两张卡就木事，但是4张就不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/YOLOX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT (Issue #816)





 
我也是这个bug，使用 一个卡就可以，两个卡就会报错
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NarutoZhao** [comment]
昨天两张还可以，今天就不行了...

**Comment by starsky68** [comment]
我也遇到过，有点迷，摸不到头脑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/YOLOX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT (Issue #816)





 
昨天两张还可以，今天就不行了...
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NarutoZhao** [comment]
我试了下 coco128 数据是可以跑通的，使用 coco2017 这个问题，是不是数据太大了，读取时在进程等待时出现问题？

**Comment by starsky68** [comment]
对对，我想起来了，我当时用的就是coco出现的问题，我把batch调小了，works关于进程的，我用的4，然后两张卡就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/YOLOX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT (Issue #816)





 
我试了下 coco128 数据是可以跑通的，使用 coco2017 这个问题，是不是数据太大了，读取时在进程等待时出现问题？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NarutoZhao** [comment]
我的batch 已经很小了，我的两张卡 是 titanx 12G，现在一张卡可以跑通，两张不行。@FateScript 大佬可否看下啥问题？

**Comment by LeBron-Jian** [comment]
> 我的batch 已经很小了，我的两张卡 是 titanx 12G，现在一张卡可以跑通，两张不行。@FateScript 大佬可否看下啥问题？

hi，你修改了什么东西？

**Comment by starsky68** [comment]
看看你的works num，线程数？很久的问题了，当时印象是，线程数，显卡数，batch数都调整合适了，我的现在4卡就不行，但是2卡就可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/YOLOX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT (Issue #816)





  
我的batch 已经很小了，我的两张卡 是 titanx ***@***.*** 大佬可否看下啥问题？
  
hi，你修改了什么东西？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LeBron-Jian** [comment]
> 看看你的works num，线程数？很久的问题了，当时印象是，线程数，显卡数，batch数都调整合适了，我的现在4卡就不行，但是2卡就可以
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Megvii-BaseDetection/YOLOX" ***@***.***&gt;; 发送时间:&nbsp;2021年12月13日(星期一) 下午5:31 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Megvii-BaseDetection/YOLOX] torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT (Issue #816) 我的batch 已经很小了，我的两张卡 是 titanx ***@***.*** 大佬可否看下啥问题？ hi，你修改了什么东西？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我发现我的问题了，谢谢！  我的问题与卡没关系，是loss的问题。

**Comment by zura-false** [comment]
> > 看看你的works num，线程数？很久的问题了，当时印象是，线程数，显卡数，batch数都调整合适了，我的现在4卡就不行，但是2卡就可以
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Megvii-BaseDetection/YOLOX" _**@**_._**>; 发送时间: 2021年12月13日(星期一) 下午5:31 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [Megvii-BaseDetection/YOLOX] torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT (Issue #816) 我的batch 已经很小了，我的两张卡 是 titanx _**@**_.*** 大佬可否看下啥问题？ hi，你修改了什么东西？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 我发现我的问题了，谢谢！ 我的问题与卡没关系，是loss的问题。

请问你的loss是哪里的问题，我也是改了loss出现了类似错误

**Comment by bstech-gpu** [comment]
有结论了吗？我也遇到类似的问题了
