### ISSUE TITLE
jetson nano tensorrt yolox error

### ISSUE THREAD

**Issue by Czhazha** [Megvii-BaseDetection/YOLOX#820]
Hello, i have got an model_trt.engine on my jetson nano.
Next, i run the command
`./yolox model_trt.engine -i image.jpg`
it return an error with this log:
`[10/22/2021-13:09:15] [E] [TRT] Parameter check failed at: engine.cpp::getBindingDimensions::2069, condition: bindIndex >= 0 && bindIndex < getNbBindings()
out_dims = 0
blob image
yolox: /home/nano/Development/YOLOX/demo/TensorRT/cpp/yolox.cpp:417: void doInference(nvinfer1::IExecutionContext&, float*, float*, int, cv::Size): Assertion `engine.getNbBindings() == 2' failed.
Aborted (core dumped)`

Is there any reason for this? How can I fix it?

**Comment by Chitti21** [comment]
@Czhazha Hi, Can you share your inferred fps on Jetson Nano ?  with YOLOX-tiny and YOLOX-nano

**Comment by Czhazha** [comment]
> @Czhazha Hi, Can you share your inferred fps on Jetson Nano ? with YOLOX-tiny and YOLOX-nano

YOLOX 7fps
YOLOX-nano 25fps

**Comment by Chitti21** [comment]
Thanks for sharing.
