### ISSUE TITLE
首次用yolox，用预训练模型做推理，demo图片识别类别出现错误

### ISSUE THREAD

**Issue by Gold-ML** [Megvii-BaseDetection/YOLOX#821]
第一次用yolox，运行demo，下载预训练模型yolox_s.pth，检测assets\dog.jpg，类别识别有错误
![dog](https://user-images.githubusercontent.com/11494692/138433479-d7305494-ba8c-47bb-a7ec-9b4291bed5c4.jpg)

**Comment by Gold-ML** [comment]
> Please provide your commit message. I tried on latest commit of main branch, it works.

![0](https://user-images.githubusercontent.com/11494692/138619829-b59deaa8-9dac-4189-bd60-ed4fdb93f1ea.png)
![dog](https://user-images.githubusercontent.com/11494692/138619840-15174c0c-0438-49a9-9ae2-2a5c03a48bef.jpg)

**Comment by zwk1277023870** [comment]
您好请问下新版的预训练模型在哪下载

**Comment by Gold-ML** [comment]
> 您好请问下新版的预训练模型在哪下载

官网就是最新的
