### ISSUE TITLE
IoU pred从reg brach改到cls branch导致模型掉点严重

### ISSUE THREAD

**Issue by YuHengsss** [Megvii-BaseDetection/YOLOX#824]
作者您好！
        首先感谢您的杰出的工作，最近我尝试使用ImageNet中的VID作为数据集训练YOLOX，但是将IoU pred从reg brach改到cls branch，导致模型掉点严重（接近10%ap50），请问IoU prediction为什么只改变了在最后的预测分支中的位置就会导致这么严重的掉点呢？

**Comment by FateScript** [comment]
classification branch might learn contradict target with regression related task.
