### ISSUE TITLE
yolox_nano.pth transforms yolox_nano.onnx file reporting an error ：Missing key(s) & Unexpected key(s) in state_dict... (Models trained by my own data sets)

### ISSUE THREAD

**Issue by Elsa-zlt** [Megvii-BaseDetection/YOLOX#829]
I recently trained the yolox_nano. pth model using my own dataset (only class 1) 
The way I trained went like this:
https://blog.csdn.net/ELSA001/article/details/120918082?spm=1001.2014.3001.5501
And I am trying to convert this yolox_nano. pth to yolox_nano.onnx,but many errors were reported:
Convert command (in YOLOX directory) :
`python tools/export_onnx.py -n yolox-nano -c weights/yolox_nano.pth --output-name weights/yolox_nano.onnx`
Error message:
```
RuntimeError: Error(s) in loading state_dict for DataParallel:
 Missing key(s) in state_dict: ....
Unexpected key(s) in state_dict...
```
The error picture is as follows:
![image](https://user-images.githubusercontent.com/88954773/138624020-cb92d1af-bcc0-44f9-a7db-27d89fac9e7f.png)
![image](https://user-images.githubusercontent.com/88954773/138624034-93412ab2-2f53-4294-8c4f-d26dd8033139.png)
I think the reason for the error is that I am converting my own data set, but when I convert coco data set, there is no error and it can be converted normally:
![image](https://user-images.githubusercontent.com/88954773/138624080-4d4da78a-98a3-4070-a712-b14023ea0903.png)
![image](https://user-images.githubusercontent.com/88954773/138624093-4d500f98-1b87-4ce1-83e8-5601eed5a071.png)
But I've changed num_classes, depth, width, and input_size in yolox_base.py:
![image](https://user-images.githubusercontent.com/88954773/138624159-5b7a2cfb-387e-4546-8240-83414a0f8435.png)
Let's report this error
The complete error message is as follows:
```
(torch_G) E:\YOLOX>python tools/export_onnx.py -n yolox-nano -c weights/yolox_nano.pth --output-name weights/yolox_nano.onnx
2021-10-24 17:15:37.712 | INFO     | __main__:main:59 - args value: Namespace(batch_size=1, ckpt='weights/yolox_nano.pth', dynamic=False, exp_file=None, experiment_name=None, input='images', name='yolox-nano', no_onnxsim=False, opset=11, opts=[], output='output', output_name='weights/yolox_nano.onnx')
2021-10-24 17:15:40.278 | ERROR    | __main__:<module>:119 - An error has been caught in function '<module>', process 'MainProcess' (66764), thread 'MainThread' (59796):
Traceback (most recent call last):
> File "tools\export_onnx.py", line 119, in <module>
    main()
    └ <function main at 0x00000276616C75E0>
  File "tools\export_onnx.py", line 81, in main
    model.load_state_dict(ckpt)
    │     │               └ OrderedDict([('backbone.backbone.stem.conv.conv.weight', tensor([[[[ 1.2789e-02,  1.7050e-02,  2.4743e-02],
    │     │                           [ 6.535...
    │     └ <function Module.load_state_dict at 0x00000276609BEAF0>
    └ DataParallel(
        (module): YOLOX(
          (backbone): YOLOPAFPN(
            (backbone): CSPDarknet(
              (stem): Focus(
                (c...
  File "E:\Anaconda3\envs\torch_G\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.backbone.backbone.stem.conv.conv.weight", "module.backbone.backbone.stem.conv.bn.weight", "module.backbone.backbone.stem.conv.bn.bias"......
        Unexpected key(s) in state_dict: "backbone.backbone.stem.conv.conv.weight", "backbone.backbone.stem.conv.bn.weight", "backbone.backbone.stem.conv.bn.bias"....
 
```
I think it's a network problem, some extra or missing parameter, causing the mismatch.
My trained yolox_nano. pth is fine and can be predicted normally (reasoning) :
![image](https://user-images.githubusercontent.com/88954773/138624284-3e0bc607-dceb-45ba-97b8-7ab4a05d5b54.png)
![image](https://user-images.githubusercontent.com/88954773/138624333-8f76bd13-7729-47d3-bf6a-8f51eb6e1fe0.png)
That feels very strange, I hope there can have this experience of the students can help me answer, thank you.
Original problem address:
https://ask.csdn.net/questions/7543357?spm=1001.2014.3001.5501

**Comment by reclusezz** [comment]
Have you solve this problem? I have met a similar one but don't konw how to deal with it.

RuntimeError: Error(s) in loading state_dict for YOLOX:
        Missing key(s) in state_dict: "backbone.backbone.stem.conv.conv.weight", "backbone.backbone.stem.conv.bn.weight", "backbone.backbone.stem.conv.bn.bias", "backbone.backbone.stem.conv.bn.running_mean", "backbone.backbone.stem.conv.bn.running_var".
        Unexpected key(s) in state_dict: "backbone.backbone.stem.dconv.conv.weight", "backbone.backbone.stem.dconv.bn.weight", "backbone.backbone.stem.dconv.bn.bias", "backbone.backbone.stem.dconv.bn.running_mean", "backbone.backbone.stem.dconv.bn.running_var", "backbone.backbone.stem.dconv.bn.num_batches_tracked", "backbone.backbone.stem.pconv.conv.weight", "backbone.backbone.stem.pconv.bn.weight", "backbone.backbone.stem.pconv.bn.bias", "backbone.backbone.stem.pconv.bn.running_mean", "backbone.backbone.stem.pconv.bn.running_var", "backbone.backbone.stem.pconv.bn.num_batches_tracked".

**Comment by Elsa-zlt** [comment]
https://blog.csdn.net/ELSA001/article/details/121032193?spm=1001.2014.3001.5502

**Comment by Elsa-zlt** [comment]
https://blog.csdn.net/ELSA001/article/details/121032193?spm=1001.2014.3001.5502
You can look this blog,following the training steps,maybe can solve the problem.

**Comment by Elsa-zlt** [comment]
> Have you solve this problem? I have met a similar one but don't konw how to deal with it.
> 
> RuntimeError: Error(s) in loading state_dict for YOLOX: Missing key(s) in state_dict: "backbone.backbone.stem.conv.conv.weight", "backbone.backbone.stem.conv.bn.weight", "backbone.backbone.stem.conv.bn.bias", "backbone.backbone.stem.conv.bn.running_mean", "backbone.backbone.stem.conv.bn.running_var". Unexpected key(s) in state_dict: "backbone.backbone.stem.dconv.conv.weight", "backbone.backbone.stem.dconv.bn.weight", "backbone.backbone.stem.dconv.bn.bias", "backbone.backbone.stem.dconv.bn.running_mean", "backbone.backbone.stem.dconv.bn.running_var", "backbone.backbone.stem.dconv.bn.num_batches_tracked", "backbone.backbone.stem.pconv.conv.weight", "backbone.backbone.stem.pconv.bn.weight", "backbone.backbone.stem.pconv.bn.bias", "backbone.backbone.stem.pconv.bn.running_mean", "backbone.backbone.stem.pconv.bn.running_var", "backbone.backbone.stem.pconv.bn.num_batches_tracked".

https://blog.csdn.net/ELSA001/article/details/121032193?spm=1001.2014.3001.5502
You can look this blog,following the training steps,maybe can solve the problem.
