### ISSUE TITLE
请教一个问题，yolox输出解码过程，对应的编码步骤在哪个位置

### ISSUE THREAD

**Issue by Dandelion111** [Megvii-BaseDetection/YOLOX#846]
请教一个问题，yolox输出解码过程如下图，对应的编码步骤在哪个位置
解码过程在yolo_head.py中的249-250行
![image](https://user-images.githubusercontent.com/48303408/139409582-ff8875c8-f9ce-4008-8a23-4f515f4be2a6.png)

**Comment by Dandelion111** [comment]
> Are you asking data encode process or decode process?

是的，

**Comment by FateScript** [comment]
Well... decode process is posted on the code above. And Exp is just a encoding method, don't care too much, you could also try remove exp.

**Comment by Dandelion111** [comment]
> Well... decode process is posted on the code above. And Exp is just a encoding method, don't care too much, you could also try remove exp.

谢谢大佬回复，还想请教一下：yolox也是直接预测偏移量吗？这个偏移量的计算方式是和faster rcnn一样的吗？是通过解码方式决定这个偏移量的计算方法吗？

**Comment by kache1995** [comment]
outputs[..., :2] = (outputs[..., :2] + grids) * strides
这里为什么不对中心偏移量预测做sigmoid呢，不做sigmoid的话，岂不是值的范围很大

**Comment by FateScript** [comment]
> > Well... decode process is posted on the code above. And Exp is just a encoding method, don't care too much, you could also try remove exp.
> 
> 谢谢大佬回复，还想请教一下：yolox也是直接预测偏移量吗？这个偏移量的计算方式是和faster rcnn一样的吗？是通过解码方式决定这个偏移量的计算方法吗？

Yeah
