### ISSUE TITLE
why logure module error when i train with nano model? 

### ISSUE THREAD

**Issue by Liyang0520** [Megvii-BaseDetection/YOLOX#849]
(yoloxnew) liyang@victoria:~/Yolo/YOLOX$ python tools/train.py -f exps/example/yolox_voc/voc_nano.py -d 1 -b 16 --fp16
2021-10-30 21:18:47 | INFO     | yolox.core.trainer:126 - args: Namespace(batch_size=16, cache=False, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_voc/voc_nano.py', experiment_name='voc_nano', fp16=True, machine_rank=0, name=None, num_machines=1, occupy=False, opts=[], resume=False, start_epoch=None)
2021-10-30 21:18:47 | INFO     | yolox.core.trainer:127 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 10                         │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 10                         │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 20                         │
├──────────────────┼────────────────────────────┤
│ depth            │ 0.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 0.25                       │
├──────────────────┼────────────────────────────┤
│ act              │ 'silu'                     │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ multiscale_range │ 5                          │
├──────────────────┼────────────────────────────┤
│ data_dir         │ None                       │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ mosaic_prob      │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ mixup_prob       │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ hsv_prob         │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ flip_prob        │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ mosaic_scale     │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ False                      │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 1                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 300                        │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'voc_nano'                 │
├──────────────────┼────────────────────────────┤
│ test_size        │ (416, 416)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │
├──────────────────┼────────────────────────────┤
│ input_scale      │ (416, 416)                 │
├──────────────────┼────────────────────────────┤
│ random_size      │ (10, 20)                   │
╘══════════════════╧════════════════════════════╛
/home/liyang/anaconda3/envs/yoloxnew/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2021-10-30 21:18:47 | INFO     | yolox.core.trainer:132 - Model Summary: Params: 0.90M, Gflops: 1.05
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=626559), 'exception': (type=<class 'AttributeError'>, value=AttributeError("'Exp' object has no attribute 'perspective'"), traceback=<traceback object at 0x7f178a4be740>), 'extra': {}, 'file': (name='launch.py', path='/home/liyang/Yolo/YOLOX/yolox/core/launch.py'), 'function': 'launch', 'level': (name='ERROR', no=40, icon='❌'), 'line': 98, 'message': "An error has been caught in function 'launch', process 'MainProcess' (40184), thread 'MainThread' (139741768365888):", 'module': 'launch', 'name': 'yolox.core.launch', 'process': (id=40184, name='MainProcess'), 'thread': (id=139741768365888, name='MainThread'), 'time': datetime(2021, 10, 30, 21, 18, 53, 471458, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'HKT'))}

分割线---------------------------------------------
it is normal when i try to train with yolo_voc_s.py？

**Comment by FateScript** [comment]
Only happend in VOC  yolox-s? Is this exception raised also in default model ?

**Comment by tigerdhl** [comment]
@Liyang0520 I also get the same error when train with the yolox-s

dell@dell-Precision-7820-Tower:~/DLproject/YOLOX$ python3 tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 0 -b 32 -c weights/yolox_s.pth
2022-01-26 14:18:48 | INFO     | yolox.core.trainer:126 - args: Namespace(batch_size=32, cache=False, ckpt='weights/yolox_s.pth', devices=0, dist_backend='nccl', dist_url=None, exp_file='exps/example/yolox_voc/yolox_voc_s.py', experiment_name='yolox_voc_s', fp16=False, machine_rank=0, name=None, num_machines=1, occupy=False, opts=[], resume=False, start_epoch=None)
2022-01-26 14:18:48 | INFO     | yolox.core.trainer:127 - exp value:
╒══════════════════╤════════════════════════════╕
│ keys             │ values                     │
╞══════════════════╪════════════════════════════╡
│ seed             │ None                       │
├──────────────────┼────────────────────────────┤
│ output_dir       │ './YOLOX_outputs'          │
├──────────────────┼────────────────────────────┤
│ print_interval   │ 10                         │
├──────────────────┼────────────────────────────┤
│ eval_interval    │ 10                         │
├──────────────────┼────────────────────────────┤
│ num_classes      │ 9                          │
├──────────────────┼────────────────────────────┤
│ depth            │ 0.33                       │
├──────────────────┼────────────────────────────┤
│ width            │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ act              │ 'silu'                     │
├──────────────────┼────────────────────────────┤
│ data_num_workers │ 4                          │
├──────────────────┼────────────────────────────┤
│ input_size       │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ multiscale_range │ 5                          │
├──────────────────┼────────────────────────────┤
│ random_size      │ (14, 26)                   │
├──────────────────┼────────────────────────────┤
│ data_dir         │ None                       │
├──────────────────┼────────────────────────────┤
│ train_ann        │ 'instances_train2017.json' │
├──────────────────┼────────────────────────────┤
│ val_ann          │ 'instances_val2017.json'   │
├──────────────────┼────────────────────────────┤
│ test_ann         │ 'instances_test2017.json'  │
├──────────────────┼────────────────────────────┤
│ mosaic_prob      │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ mixup_prob       │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ hsv_prob         │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ flip_prob        │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ mosaic_scale     │ (0.1, 2)                   │
├──────────────────┼────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ True                       │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 1                          │
├──────────────────┼────────────────────────────┤
│ max_epoch        │ 300                        │
├──────────────────┼────────────────────────────┤
│ warmup_lr        │ 0                          │
├──────────────────┼────────────────────────────┤
│ basic_lr_per_img │ 0.00015625                 │
├──────────────────┼────────────────────────────┤
│ scheduler        │ 'yoloxwarmcos'             │
├──────────────────┼────────────────────────────┤
│ no_aug_epochs    │ 15                         │
├──────────────────┼────────────────────────────┤
│ min_lr_ratio     │ 0.05                       │
├──────────────────┼────────────────────────────┤
│ ema              │ True                       │
├──────────────────┼────────────────────────────┤
│ weight_decay     │ 0.0005                     │
├──────────────────┼────────────────────────────┤
│ momentum         │ 0.9                        │
├──────────────────┼────────────────────────────┤
│ exp_name         │ 'yolox_voc_s'              │
├──────────────────┼────────────────────────────┤
│ test_size        │ (640, 640)                 │
├──────────────────┼────────────────────────────┤
│ test_conf        │ 0.01                       │
├──────────────────┼────────────────────────────┤
│ nmsthre          │ 0.65                       │
╘══════════════════╧════════════════════════════╛
/home/dell/anaconda3/envs/tcstorch/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-01-26 14:18:49 | INFO     | yolox.core.trainer:132 - Model Summary: Params: 8.94M, Gflops: 26.65
2022-01-26 14:18:51 | INFO     | yolox.core.trainer:286 - loading checkpoint for fine tuning
2022-01-26 14:18:51 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([9, 128, 1, 1]).
2022-01-26 14:18:51 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([9]).
2022-01-26 14:18:51 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([9, 128, 1, 1]).
2022-01-26 14:18:51 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([9]).
2022-01-26 14:18:51 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 128, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([9, 128, 1, 1]).
2022-01-26 14:18:51 | WARNING  | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([9]).
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=846932), 'exception': (type=<class 'xml.etree.ElementTree.ParseError'>, value=ParseError('no element found: line 1, column 0'), traceback=<traceback object at 0x7fc68ebe9180>), 'extra': {}, 'file': (name='launch.py', path='/home/dell/DLproject/YOLOX/yolox/core/launch.py'), 'function': 'launch', 'level': (name='ERROR', no=40, icon='❌'), 'line': 98, 'message': "An error has been caught in function 'launch', process 'MainProcess' (13798), thread 'MainThread' (140495071781696):", 'module': 'launch', 'name': 'yolox.core.launch', 'process': (id=13798, name='MainProcess'), 'thread': (id=140495071781696, name='MainThread'), 'time': datetime(2022, 1, 26, 14, 18, 52, 870773, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST'))}

**Comment by FateScript** [comment]
Your  shape mismatched. Just look at the following log:
```
2022-01-26 14:18:51 | WARNING | yolox.utils.checkpoint:24 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([9]).
```

**Comment by loyclay** [comment]
This is a problem, I changed the Expfile to three classes and used pre-trained weights. 
**(Don't worry for the different shape of detection head between the pretrained weights and your own model, we will handle it)**

I wonder how this is handled?

`RuntimeError: Error(s) in loading state_dict for YOLOX:
        size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([3, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([80]).`

**Comment by FateScript** [comment]
It's only caused by `load_state_dict` and you could use `strict=False` to start your training with pre-trained model.

**Comment by loyclay** [comment]
This doesn't solve the issue, I can confirm the new version of Yolox has this problem
