### ISSUE TITLE
output decode problem

### ISSUE THREAD

**Issue by kache1995** [Megvii-BaseDetection/YOLOX#853]
outputs[..., :2] = (outputs[..., :2] + grids) * strides
这里为什么不对中心偏移预测做sigmoid呢，不做sigmoid的话，岂不是值的范围很大

**Comment by FateScript** [comment]
Output value of sigmoid function is limited and you might consider box scale.

**Comment by kache1995** [comment]
觉得本来就应该限制啊，grid是特征图上网格左上角的坐标，比如我特征图是80*80，stride=8，以前yolo的输出就是相对于网格左上角的偏移，因为网格大小是1*1（在特征图上），所以偏移也应该是0-1范围内的，所以做sigmoid，可能你这样做也是有道理的吧，但是总感觉应该限制在网格内部
