### ISSUE TITLE
android推理问题

### ISSUE THREAD

**Issue by zhang0225** [Megvii-BaseDetection/YOLOX#855]
作者您好，我用的您demo/android的工程项目，按照您的指引，首先克隆了项目，然后下载了ncnn预编译库，修改了ncnn_DIR，然后下载param和bin文件并放在对应的位置，但是我选择图片并运行后出现了很多杂乱框，是什么原因呢，不知道您那边能不能复现这个问题。除了按照您的指引导入项目外其他的任何修改我都没做

![result](https://user-images.githubusercontent.com/46886284/139649012-c1d5a37f-c74e-47b3-9d9f-3d0ead19e6b1.jpg)

**Comment by FateScript** [comment]
YOLOX is updated by removing normalization (minus mean and div by std), did you check this ? For latest veriosn, bin and param files are brand new..

**Comment by zhang0225** [comment]
I used the latest version of your project, and this problem has been solved, thank you for your reply
