### ISSUE TITLE
请问OTA和simOTA的区别？

### ISSUE THREAD

**Issue by kuazhangxiaoai** [Megvii-BaseDetection/YOLOX#859]
好像OTA也有选择top-k这样的操作，那OTA和simOTA的区别是什么呢？

**Comment by Joker316701882** [comment]
@kuazhangxiaoai OTA的topk用来筛选candidates，是用来求dynamic k过程中使用的，最终的正样本划分有sinkhorn-knopp iter求解得到。SimOTA拿到dynamic k之后，最终正负样本划分依然是greedy的topk

**Comment by kuazhangxiaoai** [comment]
> 到dynamic k之后
区别主要是simOTA没有用到sinkhorn-knopp-iter，还有就是如下的top-k的筛选
![image](https://user-images.githubusercontent.com/54108453/140076710-e434d5d5-7eda-4ffe-9116-6022ca61916d.png)
