### ISSUE TITLE
请问下在验证环境是否安装成功时，推理图片输出原图，没有预测框是什么原因

### ISSUE THREAD

**Issue by zwk1277023870** [Megvii-BaseDetection/YOLOX#860]

**Comment by zwk1277023870** [comment]
![Uploading 1.jpg…]()

**Comment by zwk1277023870** [comment]
![1](https://user-images.githubusercontent.com/72496860/139818444-eef975e6-53f8-4799-a24f-a6128d2b6695.jpg)

**Comment by FateScript** [comment]
Are you using latest model?

**Comment by zwk1277023870** [comment]
yes,我是在Standard Models那张表上下载的模型，用yolox_x预测时只能识别出car和bicycle，dog则不能识别，用yolox_s则直接输出原图没有预测框，不知道是什么原因，下图是yolox_x的预测结果，求解答，谢谢
![2021-11-02 18-10-35屏幕截图](https://user-images.githubusercontent.com/72496860/139827818-dc97f4fb-9060-4127-b945-f7365211d863.jpg)

**Comment by zwk1277023870** [comment]
thanks you,问题已解决
