### ISSUE TITLE
运行demo，出现No module named 'yolox'

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#864]
![image](https://user-images.githubusercontent.com/78945582/140001626-2585829e-9b72-46a0-8697-1afd795b366d.png)

**Comment by leetesua** [comment]
你安装成功了吗

**Comment by lixiangMindSpore** [comment]
> 你安装成功了吗

requirement.txt安装没问题，是demo里面需要适配一些代码，当前问题解决了，谢谢您

**Comment by Avnsx** [comment]
https://github.com/Megvii-BaseDetection/YOLOX/issues/154#issuecomment-971730170
