### ISSUE TITLE
I have released a YOLOX repository for using the BDD100K as a custom dataset.

### ISSUE THREAD

**Issue by Keiku** [Megvii-BaseDetection/YOLOX#903]
I think many users find it a little confusing how to use custom data with YOLOX. I hope it will be a tutorial on how to use custom data through the BDD100K dataset. I'm glad if you can use it as a reference.

I'm going to refactor it a bit to make it a little easier to use.

Keiku/YOLOX-BDD100K: YOLOX repository for using BDD100K as a custom dataset. https://github.com/Keiku/YOLOX-BDD100K

**Comment by FateScript** [comment]
Thanks for your work. Here are my questions about your repo:
(1)You remove all the history, does this means that you abandon all the new features in the future?
(2) Could you tell us what makes you feel it's difficult to use in our repo? Maybe we could try to fix such code.

**Comment by Keiku** [comment]
Excuse me. I couldn't understand the meaning of (1). The YOLOX-BDD100K repo has been released as an example of applying a custom dataset. It may be ideal for YOLOX to support various datasets. I think it is unavoidable that the YOLOX-BDD100K repository will throw away the changes that apply to YOLOX. YOLOX-BDD100K repository will eventually become obsolete.

Regarding (2), it may just be my lack of understanding. In my opinion, YOLOX supports official Pascal VOC and COCO datasets, but even Pascal VOC format and COCO format datasets are not easy to apply. In fact, the BDD100K has various changes. I hope this repo helps refactor the Megvii team. If it's simple, I'd love to contribute too.

**Comment by FateScript** [comment]
For (1),  you could not merge or cherry-pick any new commit of YOLOx in your repo

**Comment by Keiku** [comment]
> For (1), you could not merge or cherry-pick any new commit of YOLOx in your repo

That's true. I am in conflict and cannot merge new features of YOLOX. This needs to be refactored, but it's unclear.

**Comment by Keiku** [comment]
It seems that there are still many parts that lack understanding about YOLOX. I will continue to study. Thank you very much.
