### ISSUE TITLE
验证yolox_nano.pth的时候出现IndexError: list index out of range

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#905]
![image](https://user-images.githubusercontent.com/78945582/141733673-125f7a55-ba6a-4bf9-b327-6b5490251c91.png)

**Comment by PH-Cheng** [comment]
看一下你的标签里image_id是不是int.

**Comment by dtde** [comment]
请问解决了吗

**Comment by lixiangMindSpore** [comment]
> 请问解决了吗

已解决，多谢

**Comment by Msunshineboy** [comment]
请问你是怎么解决的
