### ISSUE TITLE
SimOTA 和OTA的对比实验

### ISSUE THREAD

**Issue by BooKing-hub** [Megvii-BaseDetection/YOLOX#906]
您好，请问一下你们做SimOTA和OTA的对比实验了吗？在同一个baseline下哪一个效果要好一点，效果相差的多不多。感谢

**Comment by FateScript** [comment]
PTAL @Joker316701882

**Comment by BooKing-hub** [comment]
@FateScript 感谢您的回答，我想知道在相同baseline，比如在yolox中使用OTA/simOTA的效果是哪一个要好一点，有没有相关的消融实验。再次感谢您的耐心回答

**Comment by FateScript** [comment]
I remember that there are no difference between OTA and SimOTA on performance of model trained on COCO.  FYI @Joker316701882

**Comment by BooKing-hub** [comment]
Thank you for your reply and enjoy your work

**Comment by Joker316701882** [comment]
@BooKing-hub The results between SimOTA and OTA are almost comparable, but as I remember, the hyper-paramters need to be carefully tuned for OTA to get the comparable performance.

**Comment by BooKing-hub** [comment]
@Joker316701882 Ok, I see. Thank you for your answer. Have a nice day!
