### ISSUE TITLE
训练的时候为什么有的total_loss和其余的loss和不相等？

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#909]
![image](https://user-images.githubusercontent.com/78945582/141927369-070ccafc-efae-40f7-b7b8-60ed79a15c85.png)
1.8 < 1.2 + 0.3 + 0.4

**Comment by wallds** [comment]
因为只保留一位小数

**Comment by FateScript** [comment]
It's rounding.
