### ISSUE TITLE
YOLOX-nano slower than YOLOX-tiny on Jetson using tensorrt

### ISSUE THREAD

**Issue by RGring** [Megvii-BaseDetection/YOLOX#911]
After comparing the inference speed of YOLOX-nano and YOLOX-tiny on the Jetson NX using tensorrt, I realized that YOLOX-tiny is faster (tiny: 60 ms, nano: 100ms).

Is there an explanation for that?

**Comment by JiaPai12138** [comment]
some more details and screenshots might help

**Comment by Chitti21** [comment]
@RGring  Only 60ms and 100ms !?! what was your image size that you considered ? 

So which model is best suitable for Jetson Devices ? **YOLOX-tiny or YOLOv4-tiny** ? 

The [paper](https://arxiv.org/pdf/2107.08430.pdf) also report the speed only on V100 where as YOLOv4-tiny is[ reported to ru](https://alexeyab84.medium.com/yolov4-the-most-accurate-real-time-neural-network-on-ms-coco-dataset-73adfd3602fe)n at 32 fps on Jetson Xavier AGX

**Comment by RGring** [comment]
I don't know, what leaded to these results. After averaging on a larger amount of images (640 x 640), I need to correct my reported values.
YOLOX-tiny: 21.4 ms
YOLOX-nano: 18.9 ms
So no huge speed-up, but both quite fast. Closing the issue and sorry about the misleading post!

**Comment by Chitti21** [comment]
@RGring Wow, then its nearly 50 frames per second. Great n Thanks for sharing.

**Comment by zzzfo** [comment]
hi，May I ask which version of yolox_nano weights you are using? I use the 0.1.0 version of yolox_nano. The result of tensorrt C++ inference is problematic. What is going on? @RGring

**Comment by RGring** [comment]
I used these weights(and re-trained on my data). https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_nano.pth. Why is inference problematic? I used the python with the torch2trt-package.

**Comment by zzzfo** [comment]
I have no problem using python reasoning, but the result of using c++ reasoning is wrong. There may be a problem with the preprocessing logic.
