### ISSUE TITLE
训练问题请教

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#913]
前93轮相对比较平稳，loss在2左右，到了第94轮，loss反弹较大，如下图所示，这属于正常现象吗？
![image](https://user-images.githubusercontent.com/78945582/142134442-96c8eeee-f872-4d46-9e9a-569d3484bb6f.png)

**Comment by lixiangMindSpore** [comment]
第94个Epoch后期在2-3之间

**Comment by LeBron-Jian** [comment]
想请教一下，你后面训练出来的模型效果如何，是否会受这个波动影响。
我查看了自己训练的loss，没出现你这种情况

**Comment by lixiangMindSpore** [comment]
> 想请教一下，你后面训练出来的模型效果如何，是否会受这个波动影响。 我查看了自己训练的loss，没出现你这种情况

现在挺好的了，也在稳步提升
