### ISSUE TITLE
Decoupled Head

### ISSUE THREAD

**Issue by fushh** [Megvii-BaseDetection/YOLOX#917]
In the following paper, 

> Wu, Yue, et al. "Rethinking classification and localization for object detection." Proceedings of the IEEE/CVF conference on computer vision and pattern recognition. 2020.

the authors find that Single-Conv performs better than Double-Conv. They believe that the regression task helps the classification task when sharing a single convolution head. However, in YOLOX, Double-Conv performs better. What causes these inconsistent results?

**Comment by BowieHsu** [comment]
Did we read the same paper? the conclusion doesn't show single conv performs better than double-conv, it shows "fc-head has more capability to distinguish a complete object from part of an object,but is not robust to regress the whole object. Based upon these findings, we propose a Double-Head method, which has a fully connected head focusing on classification and a convolution head for bounding box regression" maybe I am wrong

**Comment by fushh** [comment]
你好，你的邮件付盛豪已经收到啦，会尽快处理哒~
