### ISSUE TITLE
2分钟前运行demo.py程序没有问题，同一个conda环境，现在却提示 No module named 'megengine'

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#919]
![image](https://user-images.githubusercontent.com/78945582/142560673-a9ecc6f5-55e6-4c14-b0c2-ceb09bc22f14.png)

**Comment by lixiangMindSpore** [comment]
两分钟前
![image](https://user-images.githubusercontent.com/78945582/142561447-7bba4466-7c5d-4a3a-bed1-176d08fcd2d1.png)

**Comment by FateScript** [comment]
Are you using the same file?
