### ISSUE TITLE
How to disable/customize augmentation?

### ISSUE THREAD

**Issue by Chitti21** [Megvii-BaseDetection/YOLOX#928]
This is my customized Exp file. How can I enable/disable augmentations? 

```
import os

from yolox.exp import Exp as MyExp


class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()

        self.num_classes = 5
        self.depth = 0.33
        self.width = 0.375
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]

        self.input_size = (416, 416)
        self.max_epoch = 200

        self.data_dir = "datasets/coco_form_images/wbc7"
        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"

        self.test_size = (416, 416)
        
        self.enable_mixup = False
```
Although, I have not set augmentation in my Exp file , it automatically takes all default  augmentation values.

Command for training: 
`python tools/train.py --exp_file my_configs/yolox_tiny_wbc7.py --devices 1 --batch-size 16 --cache --fp16 --ckpt model_chk/yolox_tiny.pth`

This is what I get : 

mosaic_prob      │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ mixup_prob       │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ hsv_prob         │ 1.0                        │
├──────────────────┼────────────────────────────┤
│ flip_prob        │ 0.5                        │
├──────────────────┼────────────────────────────┤
│ degrees          │ 10.0                       │
├──────────────────┼────────────────────────────┤
│ translate        │ 0.1                        │
├──────────────────┼────────────────────────────┤
│ mosaic_scale     │ (0.1, 2)                   │
├──────────────────┼────────────────────────────┤
│ mixup_scale      │ (0.5, 1.5)                 │
├──────────────────┼────────────────────────────┤
│ shear            │ 2.0                        │
├──────────────────┼────────────────────────────┤
│ enable_mixup     │ False                      │
├──────────────────┼────────────────────────────┤
│ warmup_epochs    │ 5      

Where can I control /disable the augmentation ? 

Are there any[ hyperparameter](https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch.yaml) files as that in yolov5 ?

**Comment by Chitti21** [comment]
@FateScript @Joker316701882 Can you pls help me out with this ? 

Does making the below changes in _YOLOX/yolox/core/trainer.py_ disable all augmentations? 

`        #self.no_aug = self.start_epoch >= self.max_epoch - self.exp.no_aug_epochs

        self.no_aug = True`

**Comment by FateScript** [comment]
`no_aug` is related to mosaic. What do you mean by saying disable aug? Remove all aug of dataloader?

**Comment by Chitti21** [comment]
@FateScript Yes, I want to remove all augmentations as my datasets are already augmented.

**Comment by Chitti21** [comment]
@FateScript Any suggestions?

**Comment by FateScript** [comment]
@Chitti21 
The logic is here: 
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/data/datasets/coco.py#L190-L214

You could try to comment `@Dataset.mosaic_getitem` and return the value that `pull_item` returns.

**Comment by Chitti21** [comment]
@FateScript Thank you. But does this disable all augmentations or only Mosaic augmentation ?

**Comment by lofyol** [comment]
你这打印出来的没啥问题呀

**Comment by Chitti21** [comment]
@FateScript Is this right ?

```
    #@Dataset.mosaic_getitem                <-- commented here
    def __getitem__(self, index):
        img, target, img_info, img_id = self.pull_item(index)
        '''                                                 
        if self.preproc is not None:                        <--- Commented the if loop
            img, target = self.preproc(img, target, self.input_dim)
        '''
        return img, target, img_info, img_id         <------ returns the values that pull item returns
```
**However, when I ran this I got the below error after the 10  epoch**

loss: 1.3, lr: 3.123e-04, size: 352, ETA: 1:10:38
2021-11-30 18:33:06 | INFO     | yolox.core.trainer:247 - epoch: 10/300, iter: 130/137, mem: 2683Mb, iter_time: 0.101s, data_time: 0.001s, total_loss: 5.7, iou_loss: 2.8, l1_loss: 0.0, conf_loss: 2.1, cls_loss: 0.9, lr: 3.123e-04, size: 512, ETA: 1:10:35
2021-11-30 18:33:06 | INFO     | yolox.core.trainer:319 - Save weights to ./YOLOX_outputs/yolox_tiny_wbc7_DEL
  0%|          | 0/54 [00:00<?, ?it/s]
2021-11-30 18:33:07 | INFO     | yolox.core.trainer:185 - Training of experiment is done and the best AP is 0.00
2021-11-30 18:33:07 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (514), thread 'MainThread' (140362453468992):
Traceback (most recent call last):

  File "tools/train.py", line 132, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=2, cache=False, ckpt='model_chk/yolox_tiny.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fa7c00f6d90>

  File "tools/train.py", line 110, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fa7e0de68c8>
    └ <yolox.core.trainer.Trainer object at 0x7fa7c010c0b8>

  File "/YOLOX/yolox/core/trainer.py", line 72, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7fa7c017c158>
    └ <yolox.core.trainer.Trainer object at 0x7fa7c010c0b8>

  File "/YOLOX/yolox/core/trainer.py", line 82, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x7fa7c00d86a8>
    └ <yolox.core.trainer.Trainer object at 0x7fa7c010c0b8>

  File "/YOLOX/yolox/core/trainer.py", line 208, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x7fa7c00d8950>
    └ <yolox.core.trainer.Trainer object at 0x7fa7c010c0b8>

  File "/YOLOX/yolox/core/trainer.py", line 304, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x7fa7c010c0b8>
    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fa7b4451c88>
    │          └ <yolox.core.trainer.Trainer object at 0x7fa7c010c0b8>
    └ YOLOX(
        (backbone): YOLOPAFPN(
          (backbone): CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): ...

  File "/YOLOX/yolox/exp/yolox_base.py", line 284, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function COCOEvaluator.evaluate at 0x7fa7c017c400>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x7fa7b4451c88>

  File "/YOLOX/yolox/evaluators/coco_evaluator.py", line 108, in evaluate
    outputs = model(imgs)
              │     └ tensor([[[[166., 157., 198.],
              │                 [164., 159., 200.],
              │                 [164., 162., 202.],
              │                 ...,
              │                 [204., 225...
              └ YOLOX(
                  (backbone): YOLOPAFPN(
                    (backbone): CSPDarknet(
                      (stem): Focus(
                        (conv): BaseConv(
                          (conv): ...

  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[166., 157., 198.],
             │    │                    [164., 159., 200.],
             │    │                    [164., 162., 202.],
             │    │                    ...,
             │    │                    [204., 22...
             │    └ <function YOLOX.forward at 0x7fa7c00c8840>
             └ YOLOX(
                 (backbone): YOLOPAFPN(
                   (backbone): CSPDarknet(
                     (stem): Focus(
                       (conv): BaseConv(
                         (conv): ...

  File "/YOLOX/yolox/models/yolox.py", line 30, in forward
    fpn_outs = self.backbone(x)
               │             └ tensor([[[[166., 157., 198.],
               │                         [164., 159., 200.],
               │                         [164., 162., 202.],
               │                         ...,
               │                         [204., 225...
               └ YOLOX(
                   (backbone): YOLOPAFPN(
                     (backbone): CSPDarknet(
                       (stem): Focus(
                         (conv): BaseConv(
                           (conv): ...

  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[166., 157., 198.],
             │    │                    [164., 159., 200.],
             │    │                    [164., 162., 202.],
             │    │                    ...,
             │    │                    [204., 22...
             │    └ <function YOLOPAFPN.forward at 0x7fa7c00c8730>
             └ YOLOPAFPN(
                 (backbone): CSPDarknet(
                   (stem): Focus(
                     (conv): BaseConv(
                       (conv): Conv2d(12, 24, kernel_size=(3...

  File "/YOLOX/yolox/models/yolo_pafpn.py", line 93, in forward
    out_features = self.backbone(input)
                   │             └ tensor([[[[166., 157., 198.],
                   │                         [164., 159., 200.],
                   │                         [164., 162., 202.],
                   │                         ...,
                   │                         [204., 225...
                   └ YOLOPAFPN(
                       (backbone): CSPDarknet(
                         (stem): Focus(
                           (conv): BaseConv(
                             (conv): Conv2d(12, 24, kernel_size=(3...

  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[166., 157., 198.],
             │    │                    [164., 159., 200.],
             │    │                    [164., 162., 202.],
             │    │                    ...,
             │    │                    [204., 22...
             │    └ <function CSPDarknet.forward at 0x7fa7c00c1950>
             └ CSPDarknet(
                 (stem): Focus(
                   (conv): BaseConv(
                     (conv): Conv2d(12, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1...

  File "/YOLOX/yolox/models/darknet.py", line 169, in forward
    x = self.stem(x)
        │         └ tensor([[[[166., 157., 198.],
        │                     [164., 159., 200.],
        │                     [164., 162., 202.],
        │                     ...,
        │                     [204., 225...
        └ CSPDarknet(
            (stem): Focus(
              (conv): BaseConv(
                (conv): Conv2d(12, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1...

  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
             │    │        │        └ {}
             │    │        └ (tensor([[[[166., 157., 198.],
             │    │                    [164., 159., 200.],
             │    │                    [164., 162., 202.],
             │    │                    ...,
             │    │                    [204., 22...
             │    └ <function Focus.forward at 0x7fa7c00c16a8>
             └ Focus(
                 (conv): BaseConv(
                   (conv): Conv2d(12, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                   (bn)...

  File "/YOLOX/yolox/models/network_blocks.py", line 208, in forward
    dim=1,

RuntimeError: Sizes of tensors must match except in dimension 3. Got 1 and 2 (The offending index is 0)

**Comment by FateScript** [comment]
Just look at your exception trace, it says your input tensor missmatch. Could you set a breakpoint and take a look at your input.

**Comment by Chitti21** [comment]
@FateScript 
I don't think the problem is with my input. For the same input, the training happens if don't comment these items.

> @Chitti21 The logic is here: https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/data/datasets/coco.py#L190-L214
> 
> You could try to comment `@Dataset.mosaic_getitem` and return the value that `pull_item` returns.

Can you tell,  what is happening after 10th epoch?

**Comment by Chitti21** [comment]
@FateScript  Thank you. It is Solved.

**Comment by kef-bassam** [comment]
I ran into this problem as well. I was not converting my image tensors in the PyTorch format [batch, channel, width, height]. My original input was in [batch, width, height, channel] which was causing the error.
