### ISSUE TITLE
coco格式数据训练ap为0的问题

### ISSUE THREAD

**Issue by wolfVbx** [Megvii-BaseDetection/YOLOX#935]
Average forward time: 0.00 ms, Average NMS time: 0.00 ms, Average inference time: 0.00 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = **0.000**
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = **0.000**
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = **0.000**
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = **-1.000**
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = **0.000**
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = **0.000**
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = **0.000**
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = **0.000**
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = **0.000**
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = **-1.000**
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = **0.000**
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = **0.000**

2021-11-22 20:49:08 | INFO     | yolox.core.trainer:318 - Save weights to ./YOLOX_outputs/test-coco128
2021-11-22 20:49:11 | INFO     | yolox.core.trainer:184 - Training of experiment is done and the best AP is 6.92

这个是训练的命令行
CUDA_VISIBLE_DEVICES=0 python tools/train.py -f exps/example/custom/coco107.py -expn test-coco128 -d 1 -b 8 --fp16 -o -c YOLOX_outputs/coco107-voc/best_ckpt.pth

coco格式训练的时候，一些epoch的ap值为0(上面加粗的部分)(如上log)，coco128数据集也存在这个问题，自己的数据集可视化后可以确定没有问题，学习率也调小了，但是还是有问题。使用代码里面提供的c++版的pycocotools或者原版的pycocotools都存在这个问题，测试了多张卡和单张卡，不是多张gpu的原因。请问下，问题可能在哪里？

**Comment by wolfVbx** [comment]
测试了多张卡和单张卡，也不是这个原因，不是多张gpu的原因

**Comment by hwy98** [comment]
请问您解决了吗，我也遇到了同样的问题

**Comment by lyf6** [comment]
请问您解决了吗，同样遇到这样的问题

**Comment by 0-ing** [comment]
请问您解决了吗，同样遇到这样的问题

**Comment by lyf6** [comment]
解决了，是我的数据格式有问题。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 0-ing ***@***.***&gt;
发送时间: 2022年3月24日 10:43
收件人: Megvii-BaseDetection/YOLOX ***@***.***&gt;
抄送: lyf6 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Megvii-BaseDetection/YOLOX] coco格式数据训练ap为0的问题 (Issue #935)





 
请问您解决了吗，同样遇到这样的问题

**Comment by 7EDG77** [comment]
训练数据格式不是标准coco格式会导致这种问题

**Comment by 2339749019** [comment]
> 训练数据格式不是标准coco格式会导致这种问题

细说，哥
