### ISSUE TITLE
我想在demo.py里实时检测摄像头，修改cv2.VideoCapture(args.path if args.demo == "video" else args.camid)为cv2.VideoCapture(0, cv2.CAP_DSHOW)，却不兼容，有什么方法实时检测摄像头吗？具体需要怎么修改？

### ISSUE THREAD

**Issue by lixiangMindSpore** [Megvii-BaseDetection/YOLOX#939]
我想在demo.py里实时检测摄像头，修改cv2.VideoCapture(args.path if args.demo == "video" else args.camid)为cv2.VideoCapture(0, cv2.CAP_DSHOW)，却不兼容，有什么方法实时检测摄像头吗？具体需要怎么修改？

**Comment by tyj1225** [comment]
您好，你的问题解决了吗

**Comment by lixiangMindSpore** [comment]
> 您好，你的问题解决了吗

解决

**Comment by tyj1225** [comment]
怎么解决的呀 我运行demo调用摄像头的时候并没有显示检测的窗口，只有推理时间
