### ISSUE TITLE
No module named yolox.exp

### ISSUE THREAD

**Issue by quaid281** [Megvii-BaseDetection/YOLOX#940]
I'm attempting to convert my yolox pytorch model to a tensorRT in python

When i apply the code given: 
python tools/trt.py -f <YOLOX_EXP_FILE> -c <YOLOX_CHECKPOINT>

I get the following error:
from yolox.exp import get_exp
ModuleNotFoundError: No module named yolox.exp

Has anyone ever experienced this?  is there a work around or any ideas on how to resolve.

**Comment by FateScript** [comment]
Did you install YOLOX as README suggested?

**Comment by quaid281** [comment]
Yes, I figured out the issue.
I recently reformatted my hard drive.
A few of the YOLOX dependencies call on python files that had long path's.  I had to enable long paths in my windows registry.
