### ISSUE TITLE
Custom anchor boxes

### ISSUE THREAD

**Issue by loucif01** [Megvii-BaseDetection/YOLOX#946]
i just have one question about anchor boxes in yolox : i have a set of regions of interests witch i got theme with some ML methods, now i want to feed theme to yolox,  can i modify the anchor boxes in yolox and replace theme with the regions of interests that i have? If yes, can i use the pretrained weights or i have to train yolox from scratch again?

Thank you for your help :)

**Comment by FateScript** [comment]
YOLOX is an anchor-free algorithm.  Just use your RoI as GT boxes and make your annoation like COCO format might help you.

**Comment by loucif01** [comment]
@FateScript thank you for your response. In fact i want to use my model yolox witch is already trained on the same dataset where i extracted the RoI, i just want to enhance my model by specifying the RoI to it, so i want to know if there's a flexible way to inject these RoI into my trained model in order to help it to more detect objects?

Thanks.

**Comment by FateScript** [comment]
So you want to use YOLOX to learn a regression from your pre-defined boxes?

**Comment by loucif01** [comment]
Yes exactly. Because my pretrained model is a little bit weak in terms of recall, so i want to enhance it by learning from specific regions.

**Comment by FateScript** [comment]
The total YOLOX is not design for a simple box regreession. Use a detector head  might solve your issue in a easier way.

**Comment by loucif01** [comment]
@FateScript  Ok, but how to feed the RoI to the detector head?

**Comment by Joker316701882** [comment]
@loucif01 You **cannot** use any learned anchor boxes for YOLOX. One purpose of YOLOX is to eliminate the effect of anchor boxes design. Using pre-defined anchors in YOLOX is not easy. But if you manage it and find the anchor boxes are useful, your results are welcomed.
