### ISSUE TITLE
cls_target

### ISSUE THREAD

**Issue by BugOOM** [Megvii-BaseDetection/YOLOX#949]
why the cls_target is multiplied by pred_ious_this_matching?

**Comment by Joker316701882** [comment]
@BugOOM 
We would like to encode the iou information into the target, to relieve the misalignment between the classification and regression prediction. You may refer to https://arxiv.org/abs/1912.05992. Our implementation is a variant.

**Comment by BugOOM** [comment]
> @BugOOM We would like to encode the iou information into the target, to relieve the misalignment between the classification and regression prediction. You may refer to https://arxiv.org/abs/1912.05992. Our implementation is a variant.

Thank you for your quick reply!!!
