### ISSUE TITLE
您好，训练COCO格式数据集出现了问题

### ISSUE THREAD

**Issue by lxzatwowone1** [Megvii-BaseDetection/YOLOX#95]
训练了大概10轮左右，出现了下图的报错
![image](https://user-images.githubusercontent.com/57927067/126734299-42e94887-ccdc-4e04-9c51-788914007c94.png)
请教下您这个是啥问题啊

**Comment by ruinmessi** [comment]
这个看起来是你跨卡通讯出了问题...
你可以先把这一行用[all_reduce_norm](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/core/trainer.py#L209)的注释掉，这个不会影响性能，只是你训练时候的测试结果会比实际 offline 测的结果低一点点

**Comment by lxzatwowone1** [comment]
感谢，我尝试一下

**Comment by Xiang99** [comment]
> 感谢，我尝试一下

我注释了还是不行，你的可以了吗

**Comment by lxzatwowone1** [comment]
> > 感谢，我尝试一下
> 
> 我注释了还是不行，你的可以了吗

一样，也是不行的，感觉是gloo库的问题

**Comment by lxzatwowone1** [comment]
因为数据量不多，关闭了分布式训练，可以正常运行啦
