### ISSUE TITLE
YOLOX训练时报错

### ISSUE THREAD

**Issue by YL-laughtale** [Megvii-BaseDetection/YOLOX#952]
在开始训练自己的数据集时报错如下，训练使用命令为：python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 16 --fp16 -o -c weights/yolox_s.pth，请问有人知道是什么原因吗
`2021-11-29 22:12:18 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (6368), thread 'MainThread' (1312):
Traceback (most recent call last):
 
  File "tools\train.py", line 128, in <module>
    launch(
    └ <function launch at 0x000002D04D513040>
 
> File "e:\yolox\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000002D04E1C0F70>
 
  File "tools\train.py", line 113, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000002D04CCF6040>
    └ <yolox.core.trainer.Trainer object at 0x000002D04E1CC490>
 
  File "e:\yolox\yolox\core\trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000002D04E19D820>
    └ <yolox.core.trainer.Trainer object at 0x000002D04E1CC490>
 
  File "e:\yolox\yolox\core\trainer.py", line 160, in before_train
    occupy_mem(self.local_rank)
                    │          │    └ 0
                    │          └ <yolox.core.trainer.Trainer object at 0x000002D04E1CC490>
                    └ <function occupy_mem at 0x000002D04DA58B80>
 
  File "e:\yolox\yolox\utils\metric.py", line 35, in occupy_mem
    total, used = get_total_and_free_memory_in_Mb(cuda_device)
                                                    │                               └ 0
                                                    └ <function get_total_and_free_memory_in_Mb at 0x000002D04DA58AF0>
 
  File "e:\yolox\yolox\utils\metric.py", line 27, in get_total_and_free_memory_in_Mb
    total, used = devices_info[int(cuda_device)].split(",")
                            │                                   └ 0
                            └ ['']
 
ValueError: not enough values to unpack (expected 2, got 1)`

**Comment by FateScript** [comment]
Did your gpu available? Seems your total gpu mem is 0? Or you could try `get_total_and_free_memory_in_Mb ` to check your device.

**Comment by YL-laughtale** [comment]
> 

> Did your gpu available? Seems your total gpu mem is 0? Or you could try `get_total_and_free_memory_in_Mb ` to check your device.

Thank you for your answer, I re-installed CUDA can be normal operation.
