### ISSUE TITLE
ctrl+c stopped, gpu memory still using one 

### ISSUE THREAD

**Issue by aidemHJC** [Megvii-BaseDetection/YOLOX#958]
Dear sir,
I have two GPU memory, normally, everything works well, as bellow, 
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     52573      C   ...a3/envs/yolovx/bin/python    29347MiB |
|    1   N/A  N/A     52574      C   ...a3/envs/yolovx/bin/python    29347MiB |
+-----------------------------------------------------------------------------+
BUT when I use "Ctrl+C" to stop training, one gpu memory still using,as bellow,
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A     52574      C   ...a3/envs/yolovx/bin/python    29347MiB |
+-----------------------------------------------------------------------------+

my code downloaded at 2021/10/28

**Comment by FateScript** [comment]
killing the left process could solve your issue.

**Comment by aidemHJC** [comment]
ok, thanks, you can close this issue
