### ISSUE TITLE
RuntimeError: Trying to create tensor with negative dimension -1460: [256, 1024, -1460]

### ISSUE THREAD

**Issue by likyoo** [Megvii-BaseDetection/YOLOX#96]
I try:
`python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 16 --fp16 -o -c yolox_s.pth.tar`
but I get this error:
![image](https://user-images.githubusercontent.com/44317497/126734876-c863312a-78b9-473e-a1ae-67b46454d413.png)

**Comment by ruinmessi** [comment]
You can remove `-o` in the command and try it again.
