### ISSUE TITLE
YOLOX Demo!: error: the following arguments are required: demo

### ISSUE THREAD

**Issue by HuYo-OS** [Megvii-BaseDetection/YOLOX#964]
本来想偷懒用demo.py来测试一下自己训练出来的权重文件，没想到经过一通修改之后直接报错了
![image](https://user-images.githubusercontent.com/94115384/144649307-9d83dea6-ff10-45d7-9060-9aacd4e7cea4.png)
心情复杂

**Comment by xxxjjjx** [comment]
请问这个问题你解决了吗

**Comment by HuYo-OS** [comment]
> 

还没有

**Comment by HuYo-OS** [comment]
@xxxjjjx 还没有

**Comment by FateScript** [comment]
... Please read the note of using demo.

**Comment by vaerdu** [comment]
> 本来想偷懒用demo.py来测试一下自己训练出来的权重文件，没想到经过一通修改之后直接报错了 ![image](https://user-images.githubusercontent.com/94115384/144649307-9d83dea6-ff10-45d7-9060-9aacd4e7cea4.png) 心情复杂
![image](https://user-images.githubusercontent.com/78519509/147647020-8c251d38-9ac0-4d36-af06-7aaf40c9a633.png)
demo字符前要有两个 -

**Comment by xiejiekai** [comment]
问题解决了吗？
