### ISSUE TITLE
WandB Integration

### ISSUE THREAD

**Issue by opassos** [Megvii-BaseDetection/YOLOX#973]
I read [here](https://wandb.ai/diganta/YOLOX/reports/A-complete-YOLOX-experiment-and-model-tracking-pipeline--VmlldzoxMDkwMTk5) that YoloX has integration with wandb to log the training process. However, the command `-﻿-wandb [﻿-﻿-cache]` fails. The probable reason why it fails is that I can't find the file `YOLOX/yolox/utils/wandb/wandb_utils.py`. I am probably missing something very obvious but I would love any assistance! Thanks

**Comment by opassos** [comment]
NVM, just realized the guy was using a custom [fork](https://github.com/digantamisra98/YOLOX)

**Comment by ONNONS** [comment]
> 



> NVM, 그 사람이 방금 user-정의 [포크를](https://github.com/digantamisra98/YOLOX) 사용하고 있다는 것을 깨달았습니다 . 공식 리포지에서 WandB를 지원하세요.

I also want to use wandb . Please explain in detail how you solved it

**Comment by opassos** [comment]
I downloaded YoloX from a different repo: using the command `git clone https://github.com/digantamisra98/YOLOX -q`.

**Comment by ynhuhu** [comment]
The following error occurred during the training：

File "/kaggle/working/YOLOX/yolox/utils/wandb/wandb_utils.py", line 153, in _handle_pred
    if isinstance(image, Union[str, Path]):
......
File "/opt/conda/lib/python3.7/typing.py", line 716, in __instancecheck__
    return self.__subclasscheck__(type(obj))
           │    │                      └ array([[[ 92., 180., 156.],
           │    │                                [ 99., 178., 156.],
           │    │                                [108., 170., 157.],
           │    │                                ...,
           │    │                                [  0.,  87., 176.],
           │    │                        ...
           │    └ <function _GenericAlias.__subclasscheck__ at 0x7fb1192eca70>
           └ typing.Union[str, pathlib.Path]
  File "/opt/conda/lib/python3.7/typing.py", line 724, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
