### ISSUE TITLE
卷积层权重初始化

### ISSUE THREAD

**Issue by simochen** [Megvii-BaseDetection/YOLOX#976]
想请问一下，在代码里好像没看到卷积层权重初始化部分的代码，为什么YOLOX不需要进行卷积层参数初始化？

**Comment by Joker316701882** [comment]
@simochen They are initialized here:
https://github.com/Megvii-BaseDetection/YOLOX/blob/f0d1ce892e9fbe0bd982abf00de979db63e4887f/yolox/exp/yolox_base.py#L87-L88

**Comment by simochen** [comment]
@Joker316701882 这里看起来只初始化了BN层，以及head的conv bias，没有看到初始化conv weight的部分？

**Comment by FateScript** [comment]
PyTorch will help to init conv and bias itself. Howerver, init of conv doesn't matter much in YOLOX. @simochen

**Comment by simochen** [comment]
@FateScript Thanks for reply.
