### ISSUE TITLE
使用官方权重，检测结果不对

### ISSUE THREAD

**Issue by xiaoyc003** [Megvii-BaseDetection/YOLOX#977]
下载了官方的权重，执行命令：

```
python tools/demo.py image -n yolox-m -c models/yolox_m.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640
```
发现结果不对

![demo_screenshot_08 12 2021](https://user-images.githubusercontent.com/33978041/145130826-f9f5aa62-96a5-4270-8f86-e0e7f8b02881.png)

各位大佬，请问这是什么情况？

**Comment by FateScript** [comment]
Plz compare your preprcess logic with the latest commit.

**Comment by xiaoyc003** [comment]
I used the newest code all ready, and I just download the weights and run the demo

![Uploading Screenshot from 2021-12-08 11-50-08.png…]()

**Comment by xiaoyc003** [comment]
ok, just add `--legacy` :

```
python tools/demo.py image -n yolox-m -c models/yolox_m.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --legacy
```

![demo_screenshot_08 12 2021](https://user-images.githubusercontent.com/33978041/145157892-51157831-6beb-4311-9412-30bff03f733e.png)

**why not set it to true by default ?**

**Comment by FateScript** [comment]
Yes, it's a break change. However, we recommand all users to use new model but not legacy model with complex preprocess func.

**Comment by lix19937** [comment]
bad result !

**Comment by lix19937** [comment]
```
    parser.add_argument(
        "--legacy",
        dest="legacy",
        default=False,
        action="store_true",
        help="To be compatible with older versions",
    )
```

the readme.md not mention it.

**Comment by lix19937** [comment]
```
python tools/demo.py image -n yolox-s -c ckpt/yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu --legacy


python tools/demo.py image -f exps/default/yolox_s.py -c ckpt/yolox_s.pth --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 640 --save_result --device gpu  --legacy

```
