### ISSUE TITLE
 use ciou training

### ISSUE THREAD

**Issue by aidemHJC** [Megvii-BaseDetection/YOLOX#986]
Dear sir
could pls help me, 
I add Diou and Ciou in losses.py, and Diou works well, the total loss decrease with epoch increase,
BUT Ciou, the total loss decease at beginning epochs, then increase, especially the conf_loss
attach file is losses.py and training log,
my code downloaded at 2021/10/2
thanks, BR
[code and log.zip](https://github.com/Megvii-BaseDetection/YOLOX/files/7690493/code.and.log.zip)
8

**Comment by aidemHJC** [comment]
my code downloaded at 2021/10/28

**Comment by scsolaris** [comment]
@aidemHJC using yolov5 version of mosaic augmentation could increase the training stability

**Comment by aidemHJC** [comment]
@scsolaris do you mean that using ciou with my code and yolov5 version of mosaic augmentation the same time can increase the training stability?

**Comment by scsolaris** [comment]
> @scsolaris do you mean that using ciou with my code and yolov5 version of mosaic augmentation the same time can increase the training stability?

@aidemHJC yes. yolov5 version of mosaic augmentation filters out some low quality boxes.

**Comment by vaerdu** [comment]
> > @scsolaris do you mean that using ciou with my code and yolov5 version of mosaic augmentation the same time can increase the training stability?
> 
> @aidemHJC yes. yolov5 version of mosaic augmentation filters out some low quality boxes.

interesting! do you have open source code?

**Comment by scsolaris** [comment]
@vaerdu the old version of yolox use the yolov5 version of mosaic augmentation. please refer to #765

**Comment by aidemHJC** [comment]
@scsolaris 
thanks for your reply
