### ISSUE TITLE
Follow the README to run the MegEngine implementation, but report an error

### ISSUE THREAD

**Issue by milezhao** [Megvii-BaseDetection/YOLOX#988]
When I followed the [README](https://github.com/Megvii-BaseDetection/YOLOX/tree/main/demo/MegEngine/python) to run the MegEngine implementation, I got an error like below.

**14 07:38:02 WRN try setting the submodule `<class 'megengine.tensor.Tensor'>` to `<class 'models.yolo_head.YOLOXHead'>`'s new attribute `grids.1`, its name `grids.0` will remain unchanged
14 07:38:02 WRN try setting the submodule `<class 'megengine.tensor.Tensor'>` to `<class 'models.yolo_head.YOLOXHead'>`'s new attribute `grids.2`, its name `grids.0` will remain unchanged**

**Comment by FateScript** [comment]
Don't worry, it's just a warning.
