### ISSUE TITLE
yolox-s with default config cannnot converge in mini-coco128

### ISSUE THREAD

**Issue by LLsmile** [Megvii-BaseDetection/YOLOX#995]
yolox-s with default config cannnot converge in mini-coco128 provided in [https://github.com/Megvii-BaseDetection/YOLOX/blob/main/docs/train_custom_data.md](url)

**Comment by LLsmile** [comment]
Training code is _python tools/train.py -f ./exps/default/yolox_s.py -d 1 -b 4 --fp16 -o -c ./models/yolox_s.pth_
Nothing else is changed.

**Comment by Joker316701882** [comment]
@LLsmile Training on mini-coco128 will probably produce unexpected behavior. Please try on standard COCO.

**Comment by LLsmile** [comment]
ok, thanks.
