### ISSUE TITLE
爆显存以及磁盘挂载失败

### ISSUE THREAD

**Issue by Gong-Wenming** [Megvii-BaseDetection/YOLOX#997]
我在复现yolox过程时，服务器上是3张1080ti，显存11个G，命令行运行：python tool/train.py -n yolox-x -d 3 -b 64时，直接显示显存不够，最后直到batch-size降低到8才能加载成功，请问这是我显卡显存不够，还是哪里参数设置出了问题吗？还有一个问题就是，运行起来后，总是在第一个epoch运行，将我的home磁盘给unmount掉，试了好几次都是，还有一次服务器直接重启了，请问有遇到过同样问题的人吗？

**Comment by FateScript** [comment]
3 device with batch_size 64?

**Comment by Gong-Wenming** [comment]
> 

换到batch-size=8了，

**Comment by FateScript** [comment]
1. 8 is still not the multiples of 3
2. Did your issue solved by reduce batch size?

**Comment by Gong-Wenming** [comment]
batch-size = 8可以解决显存不够的问题，但是后面训练过程中还是出问题，我把batch-size降到了4，后面的问题还是会出现，是否仍然继续降低batch-size呢？

**Comment by FateScript** [comment]
You could check your training by using batch_size 4 with 1 device, which means 12 batchsize with 3 devices.

**Comment by Gong-Wenming** [comment]
> 
好的，我去尝试用单卡训练一次，十分感谢您！
